tikv/pd

server/cluster_worker.go
server/cluster_worker_test.go
server/command.go
server/conn.go

server: add split support.

---

pd-client/leader_change_test.go

Old test fails occasionally when the second pd server doesn't become leader in time.

client: update test

---

server/cluster_worker.go
server/cluster_worker_test.go

server: fix epoch compile.

---

server/cluster.go
server/cluster_worker.go
server/conn.go
server/leader.go
server/node_conn.go
server/node_conn_test.go
server/server.go

add keep alive connection support for sending command to raft server

---

pd-client/client.go
pd-client/client_test.go

aims to make library user easier to write mock testing

client: extract Client to an interface

---

server/cluster.go
server/cluster_worker_test.go

server: add get first region meta support by using empty search key.

---

pd-client/client.go
pd-client/client_test.go
pd-client/leader_change_test.go
pd-server/main.go
server/cluster.go
server/cluster_test.go
server/cluster_worker_test.go
server/command.go
server/config.go
server/conn.go
server/id.go
server/id_test.go
server/leader.go
server/server.go
server/server_test.go
server/tso.go
server/tso_test.go

For #68 
@ngaut @qiuyesuifeng @disksing

*: simplify raft cluster.

---

server/tso.go

server: add tso retry number log info.

---

server/cluster_worker.go

server: minor changes for add/remove peer.

---

server/cluster_worker.go
server/cluster_worker_test.go

It happens when 1) A region splits. 2) Not enough store to add peer. If addPeer returns an error, the (splitted) Region in request will not be saved, which is a bug.
@siddontang @qiuyesuifeng

server: fix not enough store issue

---

server/conn.go
server/leader.go
server/server.go
server/tso.go
server/util.go

I move `IsLeader` check into `newConn` function, then connsLock can make sure that only leader can create new connection, so that we can remove some redundant `enableLeader` function calls.
@siddontang  PTAL

server: add IsLeader check when create new client conn and cleanup.

---

LICENSE
README.md

@ngaut @qiuyesuifeng @disksing

Add goreport and license.

---

server/cache.go
server/cluster_worker_test.go

server: use start key and clear search ranges.

---

server/balancer.go
server/balancer_worker.go
server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_worker.go
server/id.go

Now  Balancer can only depend on ClusterInfo, we can test whole
balancer mechanism independently.

server: use IDAllocator to let balancer easy test.

---

server/balancer.go
server/cache.go

server: tiny update

---

server/cluster.go

If we start cluster, but after a while, we cannot connect to etcd,  we will campaign leader and restart inner cluster.
But there is a bug in start function, that is we have not set `c.running` correctly,  a `close of closed channel`  panic may occur.
This PR has fixed it.

server: fix panic bug when start cluster failed.

---

conf/config.toml
server/balancer.go
server/balancer_test.go
server/balancer_worker.go
server/balancer_worker_test.go
server/cache.go
server/cluster_worker.go
server/config.go
server/score.go
server/util.go

In #195 , we have mentioned that the refactor balance including following steps:
1）separate leader count and capacity balancer.
2）find a new algorithm to decide the priority of balance strategy dynamically.
This PR is for 2) step, the balance strategy is dynamical.
In this implement, we will calculate the capacity and leader score of stores first, then try to find the  best balance candidate. 
Now we only consider the diff score of `from store` and `to store` and the threshold score conditions.
The balance refactor framework is finished, later we should add more balance rules to make the strategy better.
/cc @siddontang @huachaohuang @zhangjinpeng1987 @shenli @disksing

Balance refactor step two. 

---

cmd/pd-server/main.go
conf/config.toml
server/balancer.go
server/balancer_test.go
server/cache.go
server/config.go
server/filter.go
server/util.go

Filter out unknown and down stores from balance.

Health check for stores

---

cmd/pd-server/main.go
server/api/config.go
server/cluster.go
server/cluster_worker.go
server/config.go
server/server.go

See #210 
Reduce some flags and refactor config parser.
/cc @siddontang  @huachaohuang  @overvenus

*: tiny refactor config.

---

server/config.go

Fix some bugs here.
PTAL @qiuyesuifeng @siddontang @shenli

config: fix config parsing.

---

server/api/member.go
server/api/member_test.go
server/api/router.go

server: add api member delete

---

server/config.go
server/join.go
server/join_test.go

#248 #247 #246 
Etcd automatically re-join cluster if there is data dir.
Join cases:
1. join cluster
- 1.1. with data-dir: return ""
- 1.2. without data-dir: MemberAdd, MemberList, gen initial-cluster
2. join self
- 2.1. with data-dir: return ""
- 2.2. without data-dir: return ""
3. re-join after fail
- 3.1. with data-dir: return ""
- 3.2. without data-dir: return error(etcd reports: raft log corrupted, truncated, or lost?)
4. join after delete
- 4.1. with data-dir: return "" (cluster will reject it, however itself will keep runing.)
- 4.2. without data-dir: treat as case 1.2
PTAL @siddontang @qiuyesuifeng @huachaohuang 
cc @v01dstar @iamxy

server: refine join flag

---

.travis.yml
pd-client/rpc_worker.go
server/api/member_test.go
server/config.go
server/server.go
server/util.go

*: use unix socket in test

---

server/join_test.go

The restarted joinself PD should not initalize successfully, because it lost data.

server: fix join test

---

server/api/member_test.go
server/leader.go
server/leader_test.go
server/server.go

PD will panic if it try to `GetLeader()` before `s.client` is ready in startup.

leader: check client in GetLeader().

---

pd-client/client_test.go
server/api/balancer.go
server/api/cluster.go
server/api/config.go
server/api/event.go
server/api/member.go
server/api/region.go
server/api/server.go
server/api/store.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/cluster_worker_test.go
server/command.go

1. `GetRaftCluster()` actually never return error.
2. Errors should not be rendered into JSON directly, that will output nothing...

Cleanup GetRaftCluster() and fix API errors.

---

server/api/member_test.go
server/tso.go
server/tso_test.go

If the previous leader has used the millisecond of the last saved
timestamp, the new leader may use that millisecond too.
So we wait one more millisecond, make sure that the previous and
the new leader will never use the same millisecond.

server/tso: prevent the same millisecond

---

Makefile
pd-client/client.go
pd-client/client_test.go
pd-client/conn.go
pd-client/leader_change_test.go
pd-client/rpc_worker.go
pkg/apiutil/apiutil.go
pkg/apiutil/client.go
pkg/rpcutil/connect.go
pkg/rpcutil/rpcutil.go
pkg/testutil/testutil.go
server/tso_test.go

Since PD server can proxy requests to the leader,
PD client don't need to watch the leader any more.
Now PD client first try to connect to the leader,
if it fails, it will connect to any other PD servers temporarily,
and retry to connect to the leader later.
**Update**:
When we can't connect to the leader, we will connect to any
other servers temporarily. Meanwhile, we delegate a
goroutine to keep trying to connect to the leader. Once the
delegated goroutine connected to the leader, it sends the
connection to the channel, and we can use the leader
connection to replace the old one.
Reference Issues: #293

pd-client: no need to watch leader

---

server/balancer_worker.go
server/cluster_worker_test.go

When an operator is in progress, we should not replace it.
For example, we have a region with 3 peers (A,B,C).  The balancer add
an operator to add a peer D and replace peer A.  Then, the region adds
the peer D and reports to PD that it has 4 peers (A,B,C,D). Now the
replica balancer will take over to remove a peer, and it may remove
peer D, which is not reasonable.
Reference Issues: [TiKV #1084](https://github.com/pingcap/tikv/issues/1084)

server/balancer_worker: check in progress operator

---

server/cache.go
server/cache_test.go
server/cluster_worker_test.go
server/region.go
server/region_test.go

My intent is to optimize the cache, but it's messed up, and may break a lot of code.
So I will do some pull requests to cleanup the code first.
This PR separates region search related code to the `regionTree`.

server: add regionTree

---

pkg/timeutil/duration.go
pkg/timeutil/duration_test.go
pkg/timeutil/timeutil_test.go
server/api/store.go
server/balancer.go
server/balancer_test.go
server/cache.go
server/cluster.go
server/cluster_worker_test.go
server/config.go
server/filter.go
server/store.go

This PR separates the `storeInfo` from the cache to cleanup code of the cache.
A `StartTS` is added to the `StoreStatus` to indicate when the store is started and how long the store has been up.
Close Issue: #339

server: separate store info and add uptime

---

server/api/redirector.go
server/api/redirector_test.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/cluster_worker_test.go
server/command.go
server/conn_test.go
server/id.go
server/id_test.go
server/join_test.go
server/leader.go
server/lessor.go
server/lessor_test.go
server/server.go
server/server_test.go
server/tso.go
server/tso_test.go
server/txn.go
server/util.go

Here's a brief introduction about how etcd session and election work.
When a session is created, it requests a lease with a ttl, and keeps
alive it automatically.
Then we use the session to create an election under a prefix. When we
campaign with a leader value, the election will save the leader value
under the prefix with the session id. For example, if the prefix is
`/pd/1/leader`, and the session id is 123, then the leader value will be
saved at `/pd/1/leader/123`.  Notice that, multiple elections may save
values under the same prefix concurrently. After the leader value has
been saved, the election will wait until any values created before it
have been deleted. That is, the first created value under the same
prefix is the current leader.
We need to pay attention to one thing. No …

server: use etcd election for PD leader election

---

.travis.yml
Makefile

* ignore pd-server in tests and coveralls
* ignore a generated go-bindata file in coveralls
* prevent stall jobs in travis tests by extending testing timeout
close #347

Makefile, travis: miscellaneous fix

---

server/balancer.go
server/balancer_test.go
server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/store.go

Embed `metapb.Store` into `storeInfo` to make the code more clean.

server/store: embed metapb.Store into storeInfo

---

server/api/member.go
server/join.go

Derive Context from `client.Ctx()` instead of `Background`.

api/member, server/join: use client.Ctx()

---

server/balancer.go
server/balancer_test.go
server/balancer_worker.go
server/balancer_worker_test.go
server/cache.go
server/cluster.go
server/cluster_test.go
server/cluster_worker.go
server/cluster_worker_test.go
server/command.go
server/operator.go
server/region.go
server/region_test.go

Wrap region information into regionInfo. regionInfo will be cached after
optimizing the cache, so that we can access different information
about a region more easily.
This commit is tedious and breaks a lot of trivial code.

server: add regionInfo

---

server/leader.go

Log pd leader ready to serve.
Only when a pd becomes a leader does it prints `PD cluster leader is ready to serve`. 
PTAL @siddontang @huachaohuang 
Close #363

server/leader: log pd leader ready to serve

---

server/balancer_test.go
server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/cluster_worker_test.go
server/command.go

This commit is separated from https://github.com/pingcap/pd/pull/359, it
remove some unnecessary code and wrap some code in clusterInfo.

server/cache: wrap some methods in clusterInfo

---

server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/region_test.go

regionsInfo will be rewrote later, we should not access it directly.
Base on https://github.com/pingcap/pd/pull/366.

server/cache: hide regions in clusterInfo

---

conf/config.toml
pd-client/client_test.go
pd-client/leader_change_test.go
server/api/balancer_test.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/cluster_worker_test.go
server/config.go
server/conn.go
server/conn_test.go
server/id_test.go
server/server.go
server/server_test.go
server/tso_test.go
server/util.go

If the cluster is bootstrapped, use the saved cluster ID.
Else if the cluster ID is specified in the command line flags, use the specified cluster ID.
Else use a random cluster ID.
Closes https://github.com/pingcap/pd/issues/362

server/config: use random cluster id for new cluster

---

server/api/redirector.go
server/conn.go
server/leader.go
server/leader_test.go

The get leader API does not check nil leader, it may panic when no
leader.
I think is more reasonable to return an error when no leader in
`GetLeader()`, so we don't need to check nil leader everywhere.
Ref: https://s3.amazonaws.com/archive.travis-ci.org/jobs/172596650/log.txt

server/leader: return error when no leader

---

pd-client/conn.go
pd-client/leader_change_test.go

The leader connection may not be closed if it is not used before the
conn has been closed.

pd-client: close leader connection if not used

---

server/balancer_test.go
server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_worker.go
server/cluster_worker_test.go
server/command.go
server/region.go
server/region_test.go

First, stores and regions are reorganized so that we can easily access
the information we need.
Second, the algorithm to handle region heartbeat is modified
accordingly, to handle Split and Merge.
It's hard to handle Split and Merge perfectly to keep the cache always
reflecting the newest information about which region is serving which
range. But we can keep the cache always updating according to the region
heartbeat.
Here's how we handle region heartbeat. First, if the region does not
exist, it is added to the cache directly. Second, if the region exists
but the heartbeat is stale, an error will be returned. Finally, if the
region exists and the heartbeat is not stale, it is updated to the
cache. Additionaly, every time a region is added or updated, all range
overlap regions will be …

server/cache: reorganize the cache

---

server/balancer_worker.go
server/cluster_worker_test.go
server/operator.go

When the index is 0, the first operator may has started by not finished,
so we need to add a flag to check whether the balancer has started.
Closes https://github.com/pingcap/pd/issues/343.

server/balancer: check started operator

---

server/cache.go
server/cache_test.go
server/cluster.go
server/kv.go
server/kv_test.go
server/server.go
server/server_test.go
server/util.go

Add kv to wrap etcd operations.
Add limit when loading stores and regions, or it may failed when we have a lot of regions.
Load stores and regions inside `clusterInfo` to avoid locks and copies.

server: add kv

---

server/balancer_test.go
server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_test.go
server/command.go

We update cache and kv separately in different places, which may not be safe and hard to maintain.
This PR updates both cache and kv consistently inside `clusterInfo`.

server/cache: add kv to cluster

---

server/balancer.go
server/cache.go
server/cache_test.go
server/scheduler.go
server/selector.go

We can use selector to abstract different strategies to select the
source and target stores.

server/selector: add selector interface and balance selector

---

server/balancer.go
server/cluster.go
server/filter.go
server/scheduler.go

We will replace balancer with scheduler in the future, but we should
extract some common code from balancer first.

server: use selector to schedule region peer

---

server/config.go
server/join_test.go
server/server.go

Adjust Config immediately after parsing. Also fix a bug caused by #411 :
```
metricutil.go:83: [error] could not push metrics to Prometheus Pushgateway: unexpected status code 400 while pushing to http://10.9.113.105:9091/metrics/job//instance/10-9-84-63: job name is required
```

server: adjust Config immediately after parsing

---

server/server.go

Data race occurred between [server.go#L193](https://github.com/pingcap/pd/blob/master/server/server.go#L193) and [conn.go#L173](https://github.com/pingcap/pd/blob/master/server/conn.go#L173).
PTAL @huachaohuang @siddontang 
Detailed log: 
```
==================
WARNING: DATA RACE
Write at 0x00c42209bb38 by 2016/12/06 06:11:45 conn.go:96: [error] proxy request cmd_type:AllocId alloc_id:<>  err /home/travis/gopath/src/github.com/pingcap/pd/server/leader.go:111: server is closed
/home/travis/gopath/src/github.com/pingcap/pd/server/conn.go:232: 
goroutine 120:
github.com/pingcap/pd/server.(*Server).initClusterID()
/home/travis/gopath/src/github.com/pingcap/pd/server/server.go:176 +0x1e0
github.com/pingcap/pd/server.(*Server).StartEtcd() …
```

server: fix data race on initClusterID()

---

cmd/pd-server/main.go

For SIGTERM, exit with 0, others, exit with 1.
PTAL @huachaohuang @siddontang 
close #392

cmd: tweak signal handler

---

pkg/testutil/testutil.go

This PR addresses issues reported by [Go report card](https://goreportcard.com/report/github.com/pingcap/pd).
Note that gocyclo reports [`handleRequest()`](https://github.com/pingcap/pd/blob/8c16b74224edc3ce913772fff4e480b8d014beba/server/conn.go#L179) is too complex, which I think it is a [false alarm](https://goreportcard.com/report/github.com/pingcap/pd#gocyclo), so I did not make any changes to it.
If we really wants **100%**, we can use a `map[CommandType]func(*pdpb.Request) (*pdpb.Response, error)` later.

pkg/testutil: add some comments

---

server/cluster.go

PTAL @huachaohuang @siddontang 
Close #401

server: clean up tombstone status

---

server/conn.go
server/conn_test.go

EOF means the remote peer closes the connection actively, seems not a server error, we don't need to log it as error to confuse users.

server/conn: remove EOF log

---

conf/config.toml
server/config.go

The original default configs seems too conservative for most cases.

conf: update default configs to speed up schedule

---

server/balancer.go
server/balancer_test.go
server/coordinator.go
server/coordinator_test.go
server/event.go
server/operator.go
server/region.go
server/scheduler.go
server/scheduler_test.go

Cleanup the operator interface and implementation, fix some pitfalls:
- associate ResourceKind with operator;
- don't resend add peer response when the added peer is pending.

cleanup operator and fix some pitfalls

---

conf/config.toml
server/balancer.go
server/balancer_test.go
server/config.go
server/coordinator.go
server/filter.go
server/region.go
server/region_cache.go
server/region_test.go
server/replication.go
server/replication_test.go
server/scheduler.go
server/store.go

Schedule replicas according to the location of stores.
For example, we can replicate data to different zones, racks and hosts.
Closes #454

server: add location awareness replication

---

server/coordinator.go

According to golang package initialization, we may meet some
mysterious bugs if we do not use the same context package.
That is:
```
context.Canceled != context.Canceled
```
Because the first `Canceled` may comes from `"context"` and the
later one comes from `"golang.org/x/net/context"`.

server/coordinator: fix context pitfall

---

server/leader.go

We should keep alive before initialization (`createRaftCluster` and
`syncTimestamp`), otherwise, if the initialization takes too long (longer than
the leader lease), we will lose the leader lease.

server/leader: keep alive leader before initialization

---

conf/config.toml
server/balancer.go
server/balancer_test.go
server/cluster.go
server/config.go
server/filter.go
server/replication.go
server/replication_test.go
server/selector.go
server/store.go

We can not do balance safely if we have only 3 data centers, because of https://github.com/pingcap/tikv/issues/1468.
So, the current implementation guarantee safety if we have more than 3 data centers, but we will still balance if we have only 3 data cetners.

server/balancer: guarantee replicas are safe if possible

---

server/api/scheduler.go
server/balancer.go
server/balancer_test.go
server/coordinator.go
server/coordinator_test.go
server/handler.go

Rename `LeaderBalancer` to `BalanceLeaderScheduler`,
Rename `StorageBalancer` to `BalanceStorageScheduler`.
Close https://github.com/pingcap/pd/issues/467.

server: remove balancer concept

---

server/balancer.go
server/balancer_test.go

If a region has not enough replicas, we just add replicas to any available stores.

server/balancer: don't care score if not enough replicas

---

conf/config.toml
server/balancer.go
server/balancer_test.go
server/cluster_worker_test.go
server/config.go
server/coordinator.go
server/coordinator_test.go
server/event.go
server/handler.go
server/operator.go
server/scheduler.go
server/scheduler_test.go
server/store.go

Different schedulers may use different limits in the future, so we should let
the scheduler control its resource limit.

server: let scheduler control the resource limit

---

server/coordinator.go
server/coordinator_test.go

If the limit is 0, just return the original interval.

server/coordinator: fix "divided by zero" error

---

cmd/pd-ctl/main.go
pdctl/command/global.go
pdctl/ctl.go

close https://github.com/pingcap/pd/issues/507
PTAL @siddontang @overvenus @huachaohuang

pdctl: verify pd address

---

pdctl/command/global.go
pdctl/command/scheduler.go
pdctl/ctl.go

Add command to show, add and remove schedulers.
Close #492 
```
» help scheduler
show schedulers
Usage:
pdctl scheduler
scheduler [command]
Available Commands:
add         add a scheduler
remove      remove a scheduler
» help scheduler add
add a scheduler
Usage:
add [command]
Available Commands:
evict-leader-scheduler   add a scheduler to evict leader from a store
grant-leader-scheduler   add a scheduler to grant leader to a store
shuffle-leader-scheduler add a scheduler to shuffle leaders between stores
shuffle-region-scheduler add a scheduler to shuffle regions between stores
» help scheduler remove
remove a scheduler
Usage:
pdctl scheduler remove <scheduler>
```

pdctl/command: add scheduler command

---

server/config.go

PTAL @siddontang @disksing 
close https://github.com/pingcap/pd/issues/561

server/config: add etcd config

---

cmd/pd-server/main.go
server/config.go
server/join.go
server/join_test.go
server/util.go

prepareJoin will add a member firstly, if before startNode meet an error and return. It will add an empty name member. result in the inability to successfully join new members
PTAL @siddontang @overvenus @disksing 
close https://github.com/pingcap/pd/issues/557

server: fix join a member with the empty name

---

cmd/pd-ctl/main.go

fix Ctrl+D to exit
PTAL @siddontang @disksing @overvenus

pd-ctl: fix Ctrl+D

---

server/cluster_worker_test.go

In the suite, some test need replica 1. There is a chance that an AddNode is already scheduled before change the config value in test case. See: https://travis-ci.org/pingcap/pd/jobs/213261398#L1968
The fix is to set replica as 1 in `SetUpTest()` then adjust it in test cases.
cc @nolouch @siddontang

server: make testClusterWorkerSuite stable.

---

server/api/store.go
server/balancer_test.go
server/cache.go
server/cache_test.go
server/cluster_worker_test.go
server/store.go

cc @nolouch 
This PR aims to optimize balance speed by always using region cache to calculate a store's leaderCount and regionCount, which will be more up to date compared to reading it from StoreHeartbeat.
The main modify is whenever we get a `storeInfo` from `clusterInfo`, we setup its leaderCount and regionCount by calculating them from region cache.
However, some tests rely on manually setting leaderCount/regionCount, so `setFakeLeaderCount` and `setFakeRegionCont` are introduced to keep them working properly.

clusterInfo: calculate leaderCount/regionCount from cache.

---

server/balancer_test.go
server/cluster_worker_test.go
server/coordinator_test.go
server/operator.go
server/region.go
server/scheduler.go

Fix #579 
Avoid removing a peer when it is the leader:
When move a leader peer, [add B, remove A] becomes [add  B, transfer A to B, remove A].
When remove a leader peer, [remove A] becomes [transfer A to B, remove A].

server: transfer leader when move leader peer.

---

server/coordinator.go
server/coordinator_test.go

As we have observed, the schedule interval increases too fast.
We should not increase interval after each retry failure (it seems to be a bug). Also the increase factor is changed from 2 to 1.3.
/cc @nolouch @siddontang @andelf

balance: slow down interval increase speed.

---

circle.yml

For that we use sub packages.
Change repo path to pingcap/proj. or golang may use master branch from github.com/pingcap, which is wrong.
@shenli the same applies to pingcap/tidb .

circleci: fix bad gopath under forked project

---

conf/config.toml
pkg/logutil/log.go

- log.format: text, json, console
- log rotate options
- log entry timestamp options

pkg/logutil: add json log format

---

pkg/testutil/testutil.go

the test will block in some situation because unix schema will convert to http schema and the port seems not work when etcd server start. now use port number exclude system ports.
PTAL @andelf @disksing @siddontang

pkg: no use system ports

---

README.md

remove `cluster-id` as it has been removed and will cause pd-server fail to start,
and add `data-dir` & `log-file` which will be helpful

docs(README): update pd-server startup option

---

server/balancer.go
server/balancer_test.go
server/operator.go

when we offline one store,  the scheduler will do the operator {add peer in another health store, remove peer in the offline store}. if operator timeout and just finish add peer, we will remove this operator and new an operator {add peer, remove peer}.Which cause the loop add a peer. we need to check the number of the peers and remove directly extra peer in the offline store.

server: offline checker directly remove extra peer

---

pkg/typeutil/size.go

use iec size, will marshal to "B", "KiB", "MiB", "GiB", "TiB", "PiB", "EiB".
PTAL @disksing @siddontang

pkg: use iec size for ByteSize

---

pkg/typeutil/size.go
server/coordinator.go
server/coordinator_test.go
server/event.go
server/metrics.go
server/operator.go
server/operator_test.go

server/operator: add operator state

---

Makefile
cmd/pd-recover/main.go

cmd: add recover command tool

---

server/balancer.go
server/balancer_test.go
server/cache.go
server/coordinator.go
server/handler.go

We just consider the leader when do "hot regions" balance,  this will lead to a bad situation that a store contains many hot regions’ peer, and TiKV nodes load various from each other.
@nolouch @disksing @siddontang PTAL

balance hot regions by peer && by leader

---

server/balancer.go
server/balancer_test.go

we may access nil store when recovering cluster. this PR fix it.
PTAL @disksing @siddontang

balance: prevent access nil store when recovering cluster

---

server/cluster_worker.go
server/event.go

PTAL @disksing @siddontang @zhangjinpeng1987

*: record split

---

pd-client/client.go

This API can avoid creating a lot of goroutines in TiDB.
PTAL @disksing @siddontang @nolouch

pd-client: provide GetTSAsync API

---

pd-client/client.go
pd-client/client_test.go

In the defer statement, `req.start` is visted after the `req` object put back to pool.
This may cause data race when another goroutine get the `req` from pool and reset its `req.start`.

pd-client: fix a data race in pd client

---

server/util_test.go

`t` and `nt` represent the same time instant, yet are not deep equal. `nt` don't have monotonic clock imformation.
Fix #665 
@siddontang PTAL
Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

test: fix flakey TestParseTimestamp

---

server/api/router.go
server/api/status.go
server/api/status_test.go

See https://github.com/pingcap/pd/issues/551
PTAL @siddontang @nolouch 
Signed-off-by: Cholerae Hu <choleraehyq@gmail.com>

httpapi: support /status to show PD version

---

server/balancer.go
server/cache.go

Only alloc peer id if found a better replacement.
/cc @nolouch @huachaohuang

replica checker: compare score then alloc peer.

---

pd-client/client_test.go
server/cache.go
server/cluster_test.go
server/cluster_worker.go
server/cluster_worker_test.go
server/coordinator.go
server/coordinator_test.go
server/grpc_service.go
server/metrics.go
server/operator_test.go

Another approach of #661.
Now `dispatch()` does not return responses, all responses transfers through `heartbeatStream`.

server push schedule commands.

---

server/cache.go
server/cluster_worker_test.go

The main purpose is to avoid holding mutex to write kv.

server: reduce lock scope for region heartbeat.

---

server/tso.go
server/util.go
server/util_test.go

Other usages of `Sub` seem to be cost measurements, in which case the new behaviour of `Sub` have not affection.
Test passed on both go 1.8.3 and go 1.9 beta 2.
@disksing @siddontang PTAL 
Signed-off-by: Cholerae Hu <huyingqian@pingcap.com>

tso: fix for Sub behaviour for go1.9

---

Makefile

Our internal CI fails with error:
```
+ make test
rm: cannot remove '_vendor/src/github.com/pingcap/pd': Is a directory
```
cc @choleraehyq @nolouch @tiancaiamao

*: fix CI.

---

Makefile
pd-client/client.go
pd-client/client_test.go
pkg/apiutil/apiutil.go
pkg/etcdutil/etcdutil.go
pkg/etcdutil/etcdutil_test.go
pkg/testutil/testutil.go
server/api/cluster_test.go
server/api/config_test.go
server/api/history_test.go
server/api/label_test.go
server/api/member_test.go
server/api/redirector.go
server/api/redirector_test.go
server/api/region_test.go
server/api/server_test.go
server/api/status_test.go
server/api/store_test.go
server/api/util.go
server/cluster_test.go
server/config.go
server/server_test.go
server/util.go

As etcd does not support unix socket, using unix socket in tests improves nothing and introduces complexity.
cc @nolouch @siddontang @huachaohuang

*: remove unix socket.

---

pkg/testutil/testutil.go
server/replication.go
server/replication_test.go
server/store.go

The main argument is that if 2 stores are located in different zones, whether their host names are the same is meaningless.

replication: update distinct score.

---

conf/config.toml
pkg/etcdutil/etcdutil.go
server/config.go

Now tikv send a heartbeat after finish transfer leader. So normally the transfer process should be fast, don't need to use the large value, which may cause over balance.

conf: set default value of leader-schedule-limit to 64.

---

server/cluster.go
server/coordinator.go
server/coordinator_test.go
server/grpc_service.go
server/heartbeat_streams.go
server/operator_test.go
server/server.go

The bug:
We create _heartbeatStreams_ in _coordinator_ to manage async region heartbeats. If pd-server loses leadership then quickly becomes leader again, a new _coordinator_ will be created, but grpc steams are still bind to the old one, then scheduler commands will not be able to send to tikv.
The fix:
Create _heartbeatStreams_ along with _Server_, _coordinator_ only keeps a reference.

server: fix heartbeat stream bug.

---

server/operator.go
server/util.go

Operators may be accessed concurrently, should be mutex guarded.

*: fix a data race.

---

pd-client/client.go
server/cluster_worker_test.go

To make pd client recover faster from network isolation.

client: add timeout for rpc calls.

---

pd-client/client.go

We should not use `WithTimeout` for streaming calls, which will close the stream after timeout.

client: remove timeout for streaming call.

---

server/api/label.go
server/api/store.go
server/api/store_test.go
server/balancer.go
server/balancer_test.go
server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_worker_test.go
server/filter.go
server/grpc_service.go
server/replication.go
server/replication_test.go
server/selector.go
server/store.go

Fix #634.
Now the outputs are:
- Normal
```
{
"store": {
"id": 1,
"address": "127.0.0.1:20160",
"state": 0,
"state_name": "Up"
},
"status": {
"capacity": "229 GiB",
"available": "80 GiB",
"leader_count": 1,
"region_count": 1,
"start_ts": "2017-08-24T10:22:55+08:00",
"last_heartbeat_ts": "2017-08-24T10:25:06.133247517+08:00",
"uptime": "2m11.133247517s"
}
}
```
- Down
```
{
"store": {
"id": 1,
"address": "127.0.0.1:20160",
"state": 0,
"state_name": "Down"
},
"status": {
"capacity": "229 GiB",
"available": "80 GiB",
"region_count": 1,
"start_ts": "2017-08-24T10:22:55+08:00",
"last_heartbeat_ts": "2017-08-24T10:25:16.133257177+08:00",
"uptime": "2m21.133257177s"
}
}
```
- Offline
```
{
"store": {
"id": 1,
"address": "127.0.0.1:20160",
"state": 1,
"state_name": "Offline"
},
"status": { …
```

*: refactor storeInfo.

---

server/api/redirector.go
server/util.go

Optimize merging array elements

Optimize merging array elements

---

server/cache.go
server/coordinator_test.go

if we lose some region stored in etcd, and restart PD. we will receive amount heartbeat to insert region, but we don't see it as an active region. then the scheduler will not run.

*: fix active region statistic

---

server/config.go
server/testutil.go

Make raft tick and election configurable. 
In some test like jepsen, we need to use a small raft tick and election.
PTAL @disksing @huachaohuang

server: make raft tick configurable

---

server/balancer_test.go
server/cluster.go
server/coordinator.go
server/coordinator_test.go
server/namespace/classifer.go
server/namespace_cluster.go
server/namespace_test.go
server/schedule/filters.go
server/schedule/replica_checker.go
server/schedulers/balance_region.go

server: balance by namespace.

---

.gitignore
server/schedulers/balance_region.go

when run make dev, vet will fail:
```
make dev
server/schedulers/balance_region.go:43: declaration of "cache" shadows declaration at server/schedulers/balance_region.go:20
Makefile:41: recipe for target 'check' failed
```
caused by a variable naming problem

server/schedulers/balance_region.go: fix a error in make dev

---

server/cluster.go

I reproduce the problem in the following steps:
1. start 1pd+1tikv, wait for bootstrap.
2. stop tikv and restart pd.
3. use pd-ctl to remove store1.
4. wait 1 minute, the store is tombstone state.

server: fix a bug that may set not empty store to tombstone state.

---

pdctl/command/store_command.go
server/api/router.go
server/api/store.go
server/api/store_test.go
server/cluster.go

Sometime we want to recover store from wrong state. Sometime we want to cancel removing a store.

api: support set store state.

---

server/api/router.go
server/api/store.go
server/api/store_test.go
server/cluster.go

server: fix a bug that may set not empty store to tombstone.

---

server/core/tablecodec.go
server/tableNamespaceClassifier.go

Add table namespace classifier

Add table namespace classifier

---

server/cache.go
server/cache_test.go
server/cluster.go
server/cluster_worker_test.go
server/core/region.go
server/core/region_test.go
server/core/region_tree.go
server/core/region_tree_test.go
server/core/store.go
server/core/test_util.go
server/handler.go
server/kv.go
server/kv_test.go
server/util.go

This pr is a preparation for MockCluster.
1 move storesInfo, regionsInfo and regionTree into core package,  and export their methods as public so that other modules like MockCluster can also use them.
2 move region_tree_test.go into core, and split some util test functions from this file into core/test_util.go, so that test suite like cache_test.go in server can use them.
3 move RegionMapTestSuite from cache_test.go into core/region_test.go for specific test of regionsMap.

scheduler: clusterInfo refactor

---

server/grpc_service.go

1. make Send() supports timeout using the technique suggested by https://github.com/grpc/grpc-go/issues/1229
2. when the stream has error or been half closed, close both endpoints.

grpc: fix block send problem.

---

conf/config.toml
server/balancer_test.go
server/config.go
server/coordinator_test.go
server/handler.go
server/scheduler_test.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/evict_leader.go
server/schedulers/grant_leader.go
server/schedulers/hot_region.go
server/schedulers/shuffle_leader.go
server/schedulers/shuffle_region.go

schedules, config: change all name to kebab-case

---

.gitignore
server/core/kv_base.go
server/kv.go
server/kv_test.go
server/server.go

Extract kv to an interface. The benefits include a) plugin schedulers or namespace classifiers can save data without depend on server package, b) some tests can use in-memory storage without starting etcd server.

server: refactor kv.

---

server/cluster.go
server/config.go
server/core/tablecodec.go

Enable namespace classifier as well

fix tablecodec

---

server/api/label.go
server/api/store.go
server/api/store_test.go
server/cluster.go
server/core/store.go
server/schedule/filters.go

Introduce the `Disconnected` state to identify stores that lost heartbeats for a short period of time, the `LowSpace` state to be shown in metrics as warning for potential disk space shortage risk.

*: add some store states.

---

conf/config.toml
server/cluster.go
server/config.go
server/coordinator.go
server/coordinator_test.go
server/handler.go
server/kv.go
server/leader.go
server/schedule/scheduler.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/evict_leader.go
server/schedulers/grant_leader.go
server/schedulers/hot_region.go
server/schedulers/shuffle_leader.go
server/schedulers/shuffle_region.go
server/server_test.go

This reverts commit 16e898c2fd2e7463c32179ed3c0f5bf3bbd91a35.

Revert "schedule, server: persist scheduler list to etcd (#769)"

---

pdctl/command/health_command.go
pdctl/ctl.go

pdctl: support health check

---

server/api/label.go
server/api/label_test.go
server/api/store_test.go
server/core/store.go

case-insensitive when comparing StoreLabel.key, the string store in StoreLabel is still case-sensitive

core, api: store labels case-insensitive

---

conf/config.toml
server/cache.go
server/cache_test.go
server/config.go
server/core/region.go
server/core/store.go
server/schedule/filters.go
server/schedule/opts.go
server/schedulers/balance_region.go
server/schedulers/mockcluster.go

we need filter the store with lots of pending peers when scheduling regions.

*: filter store with lots of pending peers

---

server/cluster.go
server/coordinator.go
server/coordinator_test.go
server/handler.go

we can get kv from clusterInfo in coordinator, so coordinator doesn't need kv field.

coordinator: remove verbose kv

---

table/namespace_classifier.go
table/namespace_classifier_test.go

In order to allow tikv to support region merge easily, now only split at the begining of a region. 
ref https://github.com/pingcap/tidb/pull/4926

table: adjust table id calculation.

---

server/coordinator_test.go
server/schedule/replica_checker.go

Consider we have 3 peers (A, B, C), we set the store that contains C to offline while C is pending. If we generate an operator that adds a replica D then removes C, D will not be successfully added util C is normal again.
So it's better to remove C directly.

schedule: remove pending peer before add new peer.

---

pdctl/command/table_namespace_command.go
table/namespace_classifier.go
table/namespace_classifier_test.go
table/namespace_handler.go

namespace: support set namespace for meta

---

pd-client/client.go

There is a bug in last commit: I've thought **all requests** to be with or without span information in context, and **check the first one to determine that**.
```
if len(requests) > 0 && opentracing.SpanFromContext(requests[0].ctx) != nil {
opts := make([]opentracing.StartSpanOption, 0, len(requests))
for _, req := range requests {
span := opentracing.SpanFromContext(req.ctx)  // SPAN MAYBE NIL !!!
opts = append(opts, opentracing.ChildOf(span.Context()))
}
span := opentracing.StartSpan("pdclient.processTSORequests", opts...)
defer span.Finish()
}
```
but actually I meet cases where some context have span and some not, then TiDB panic on nil pointer dereference:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 …
```

pd-client: fix a nil pointer dereference

---

conf/config.toml
server/cache.go
server/config.go
server/core/store.go
server/schedule/basic_cluster.go
server/schedule/opts.go
server/schedule/scheduler.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/balance_test.go
server/schedulers/mockcluster.go
server/schedulers/test_util.go
server/schedulers/utils.go

When calculate region/leader score, use size instead of count, in order to balance store size in final.
new shouldBalance logic:
1. introduce avgScore to make sure moving is not unnecessary. Cause in some case:
note that: avgScore is not equal to totalScore / count, since weight is not same for every store, move will cause the change of score for two involved store is not equal. So it should be totalSize / totalWeight.
- sourceScore > targetScore > avgScore, if move, targetScore is still higher than avgScore, and then target store will be scheduled to move some region or leader to other stores with smaller score. But is is better to move some region or leader from source store to store with score lower than avgScore, so it is unnecessary
- avgScore > sourceScore > targetScore, if move, …

core, schedule: use size as a factor of score

---

server/api/router.go
server/api/stats.go
server/api/stats_test.go
server/cache.go
server/cluster.go
server/core/region.go
server/core/region_tree.go
server/grpc_service.go

api: add region stats.

---

Makefile

alter makefile go env 
Change ENABLE_CGO=1  to CGO_ENABLED=1 ，add CGO_ENABLED=0
use CGO_ENABLED=1 ：
```
ldd pd-server 
linux-vdso.so.1 =>  (0x00007ffd1e8e9000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7d41369000)
libc.so.6 => /lib64/libc.so.6 (0x00007f7d40fa6000)
/lib64/ld-linux-x86-64.so.2 (0x00007f7d41591000)
```
use CGO_ENABLED=0
```
ldd pd-server 
not a dynamic executable
```

alter_Makefile_go_env

---

server/coordinator.go
server/coordinator_test.go
server/schedule/scheduler.go

Recalculate `limiter.counts` using all pending operators so that we do not have to worry about limit and operators are not synchronized.

server: update limit using all operators

---

server/config.go
server/config_test.go

pd-server fails with throwing error log 'authentication handshake failed' when the `Join` is set to a 'host:port' style address instead of URL, such as "127.0.0.1:2379". The problem actually contains 2 bugs:
1. For integrity, we should only allow join a URL format as "http(s)://host:port".
2. If TLS is not configured, we should not pass a `tls.Config` to etcd.
The second issue was not revealed before because `tls.Config` did not take effect when scheme is explicitly specified as http.

config: fix join without scheme.

---

server/schedulers/hot_region.go

Fix some misuses of read/write flow. 
1. [Here](https://github.com/pingcap/pd/compare/master...disksing:hot?expand=1#diff-334c6fcc0476a142177d16a4f1f875feL329) uses `srcRegion.ReadBytes` but the method will also be called by hot-write schedule.
2. Use [`rs.FlowBytes`](https://github.com/pingcap/pd/compare/master...disksing:hot?expand=1#diff-334c6fcc0476a142177d16a4f1f875feR260) instead of `region.ReadBytes`/`region.WrittenBytes` to participate in calculations.
3. Some variable renames and function extractions.

scheduler: fix hot region scheduler select store problem.

---

server/core/store.go
server/schedulers/balance_test.go

when region size is zero, the score will be zero accordingly. When scheduler move this kind of regions, the score of store isn't affected, leading to maldistribution of region count for stores.

fix score when region size is zero

---

server/cluster_worker_test.go
server/grpc_service.go

Suppress errors when a newer version of tikv (probably v1.1) connects to pd v1.0.x.
Related issue: https://github.com/pingcap/tikv/issues/2681

proto: compatible with proto3.

---

server/config.go
server/grpc_service.go
server/heartbeat_stream_test.go

Circumvent potential problems that may be occurred by reconnecting.

heartbeat: rebind stream.

---

server/config.go
server/grpc_service.go
server/heartbeat_stream_test.go

heartbeat: rebind stream. (#918)

---

cmd/pd-server/main.go
pkg/logutil/log.go
server/join.go

if log directory is subdirectory of data directory, a new pd to join cluster will fail cause log directory will create before checking data directory whether exists and pd will regard the new join pd as a already existing pd.
this pr does: 
don't allow log directory to be the subdirectory of data directory

main: fix join failed when log dir is same as data dir

---

server/cache.go
server/schedule/basic_cluster.go
server/schedulers/mockcluster.go

When the number of regions is large, the lock is  expensive when processing the heartbeat.now does not need to get the lock if cache not needs to update.

 server: reduce the lock overhead

---

server/schedulers/balance_test.go
server/schedulers/hot_region.go

we need use the source store rather than the leader store.

schedulers: fix hot region distinct score filter

---

server/balancer_test.go
server/schedulers/hot_region.go

cherry-pick 934 to release 1.0

schedulers: fix hot region distinct score filter (#934) 

---

conf/config.toml
pdctl/command/config_command.go
server/api/config.go
server/api/config_test.go
server/api/router.go
server/api/scheduler.go
server/cache.go
server/config.go
server/handler.go
server/option.go
server/schedule/filters.go
server/schedule/operator.go
server/schedule/opts.go
server/schedulers/label.go
server/schedulers/mockcluster.go
server/schedulers/scheduler_test.go
server/server.go

Usage: 
```
> config show label-property
{
"reject-leader": [
{
"key": "zone",
"value": "cn1"
},
{
"key": "disk",
"value": "hdd"
}
]
}
> config delete label-property reject-leader zone cn1
> config set label-property reject-leader zone cn2 
```

api, pdctl, server: support config label scheduler and label property.

---

server/schedule/replica_checker.go

increase the priority of replica checker's operator produce by down peer or offline peer.

server: increase priority of replica checker's operator

---

cmd/pd-server/main.go
server/schedulers/balance_test.go
server/schedulers/hot_region.go

When region merge is enabled, `GetRegion()` may return nil, so we need to check it.

*: fix panic caused by region not found.

---

server/config.go
server/schedulers/mockcluster.go

Increase replica scheduler limiter to speed up failover.

server: increase replica scheduler limit default value

---

server/core/store.go

Tombstone stores are incorrectly counted in the LowSpace list.

*: fix lowspace metrics.

---

pd-client/leader_change_test.go
server/coordinator_test.go
server/namespace_test.go
server/schedule/operator.go
server/schedulers/balance_test.go
server/schedulers/scheduler_test.go
server/schedulers/test_util.go

The fix is here: https://github.com/pingcap/pd/compare/master...disksing:operator-kind?expand=1#diff-0d8836a3f85c65317b42262724f5bda7

schedule: fix operator kind bug.

---

server/schedule/operator.go

The default timeout (5 minutes) is kind short as the operators tend to have more steps than before (for instance the region merge operator).

schedule: increase operator timeout.

---

pdctl/command/global.go

Fix pdctl error message:
```
Additional help topics:template: top:15:47: executing "top" at <.IsHelpCommand>: can't evaluate field IsHelpCommand in type *cobra.Command
```

pdctl: fix usage template.

---

server/region_statistics.go
server/region_statistics_test.go

region statistics count offline peer.

server: count the number of  offline region

---

pdctl/ctl.go

Take `config show ` command as an example:
when first call `config show --help`, it will save help flag in config-show command struct . And we reuse the rootCmd, thus when call `config show`, it still get the command struct which has saved help flag and print help info. So initialing rootCmd every time we call pd-ctl.Start()

pd-ctl: fix always show help info after using --help once

---

server/core/region.go
server/core/store.go

1. Make sure region's size won't be 0. Balance a region with 0 size will make no effect on the store's score.
2. The store's score does not need to be non-zero.

core: fix region size calculation.

---

server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/balance_test.go
server/schedulers/utils.go

In some scenarios, the leader scores or region scores cannot eventually converge on the average. We have to give up using average score to determine whether to schedule.

schedule: balance scheduler do not depend on average score.

---

server/schedulers/scheduler_test.go
server/schedulers/shuffle_leader.go

Make it no longer dependent on `scheduleTransferLeader()`, which involves too much logic about balance.

shedulers: simplify shuffle leader scheduler.

---

server/schedule/region_scatterer.go

TiKV will refuse to remove a peer if that peer is a leader. So in order to remove old peers when scattering regions, we can simply transfer leader to the new peer after it has been added.
Without transfer leader:
With transfer leader:

Transfer leader to new peer when scattering regions

---

server/cache/ttl.go
server/schedulers/balance_leader.go
server/schedulers/balance_test.go
server/schedulers/base_scheduler.go
server/schedulers/metrics.go
server/schedulers/utils.go

This PR introduces a new procedure to improve leader balance when a) there are many stores need to balance, b) the stores with the highest/lowest leader score cannot generate feasible operator.
1. select stores with the highest/lowest leader score.
2. try to transfer leader out of the store with the highest score; try to transfer leader in to the store with lowest score.
3. if step 2 not able to create an operator, add the 2 stores to a TTL cache, the scheduler will ignore them for the next 5 minutes.

schedulers: improve balance-leader scheduler.

---

server/cache.go
server/cache_test.go
server/core/region.go
server/namespace_cluster.go
server/schedule/basic_cluster.go
server/schedule/scheduler.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/evict_leader.go
server/schedulers/grant_leader.go
server/schedulers/label.go
server/schedulers/random_merge.go
server/schedulers/shuffle_leader.go
server/schedulers/utils.go

*: add region option for random pick region

---

server/cache/cache.go

Make cache.Get use write lock because Get method will rearrange cache's entry.

ThreadSafeCache Get method lock bug

---

server/schedule/replica_checker.go
server/schedulers/balance_region.go

the balance region may alloc peer but do not produce operator.

server: fix frequent alloc id

---

server/schedulers/balance_test.go
server/schedulers/hot_region.go

`balanceByPeer` may spend a long time, it will block` balanceByLeader`.

scheduler: hot write scheduler randomly select the balance strategy

---

conf/config.toml
server/core/store.go
server/store_statistics.go

if tikv uses whole storage capacity as capacity, it is probably available ratio is too small cause there are  so many other irrelative files in the storage, namely, `capacity == available + used + irrelative `. So pd need take it into consideration.

core: adjust capacity to fit for more cases

---

server/api/member_test.go
server/leader.go
server/server.go

When leader priority is updated on the fly, etcd leader is transferred to the one has the highest priority, while PD leader is not changed. This PR makes sure PD leader switches the same instance.

server: resign pd leader when it is not same as etcd leader.

---

server/coordinator.go
server/coordinator_test.go

if disable a default scheduler and restart PD, it will delete the scheduler whether it is valid or not. and then restart PD, it will create the default scheduler again because of it think that is a newly added default scheduler.

server: fix the valid scheduler was deleted when start coordinator

---

conf/config.toml
server/cache.go
server/cluster_worker.go
server/config.go
server/option.go
server/schedule/merge_checker.go
server/schedule/mockcluster.go
server/schedule/opts.go
server/schedulers/balance_test.go

Another approach of https://github.com/pingcap/pd/pull/1048. The difference is it does not need to update region meta.
Close #1048

schedule: merge checker skips recently split regions.

---

server/schedule/filters.go
server/schedule/mockcluster.go
server/schedulers/balance_leader.go
server/schedulers/balance_test.go
server/schedulers/evict_leader.go
server/schedulers/hot_region.go
server/schedulers/label.go
server/schedulers/scheduler_test.go
server/schedulers/shuffle_leader.go

When a store's state is _disconnected_, it is likely to be either down, isolated, or busy, so we better not transfer leader to it.

schedule: filter disconnected stores for leader transfer.

---

server/schedule/operator.go
server/schedule/operator_test.go

If _TransferLeader_ can't be executed quickly, it usually means that it cannot be successfully executed for some reason (such as the target store down). So we can use a shorter timeout in order to release schedule limit earlier.

schedule: adjust timeout for operator contains only leader transfer.

---

server/schedulers/label.go
server/schedulers/scheduler_test.go

Currently unhealthy regions are ignored by label scheduler.
Consider we have IDC1, IDC2, IDC3. IDC3 is configured as 'reject leader'. If IDC1 and IDC3 have network problem or one of IDC1's tikv is down, regions whose leader in IDC3 will be unhealthy, so they will not be able to transfer leader to IDC2.

scheduleres: label scheduler takes care of unhealthy regions.

---

server/schedulers/evict_leader.go
server/schedulers/scheduler_test.go

To prevent evict-leader-scheduler from breaking reject-leader property.

scheduler: evict-leader-scheduler checks reject-leader property.

---

server/cache.go
server/cache_test.go
server/cluster_worker_test.go
server/coordinator_test.go

It's easy to forget to use Lock and then visit the anonymous field. This is not very safe.

*: Do not use anonymous field in clusterInfo

---

server/coordinator.go
server/coordinator_test.go
server/handler.go
server/schedule/operator.go
server/schedule/operator_test.go
server/schedule/region_scatterer.go
server/schedule/replica_checker.go
server/schedulers/adjacent_region.go
server/schedulers/balance_leader.go
server/schedulers/evict_leader.go
server/schedulers/grant_leader.go
server/schedulers/hot_region.go
server/schedulers/label.go
server/schedulers/shuffle_leader.go

The _Schedulers_/_Checkers_ are run by selecting a Region from the _Cluster_, generating operator by some sort of calculation and adding it to the coordinator.
There is a flaw in this process: if the region is changed after being selected out, wrong operator may be added and executed.
This PR fixes the problem by checking the region's epoch is unchanged before adding the operator.

server, schedule: check region epoch before adding operators.

---

server/config.go

Like TiKV, Make the config log more readable.
New output:
```
2018/06/11 17:00:15.915 server.go:99: [info] PD config - {
"client-urls": "http://127.0.0.1:2379",
"peer-urls": "http://127.0.0.1:2380",
"advertise-client-urls": "http://127.0.0.1:2379",
"advertise-peer-urls": "http://127.0.0.1:2380",
"name": "pd",
"data-dir": "default.pd",
"initial-cluster": "pd=http://127.0.0.1:2380",
"initial-cluster-state": "new",
"join": "",
"lease": 3,
"log": {
"level": "",
"format": "text",
"disable-timestamp": false,
"file": {
"filename": "",
"log-rotate": true,
"max-size": 0,
"max-days": 0,
"max-backups": 0
}
},
"log-file": "",
"log-level": "",
"tso-save-interval": "3s",
"metric": {
"job": "pd",
"address": "",
"interval": "0s"
},
"schedule": {
"max-snapshot-count": 3,
"max-pending-peer-count": 16, …
```

server/config: use json output to make the config log more readable

---

.travis.yml

The script of travis Ci was not correctly updated by https://github.com/pingcap/pd/pull/1102.

ci: skip integration tests in CI environment

---

server/cluster_info.go
server/cluster_info_test.go

After TiKV unsafe recover some regions, the region epoch not changed but the peers number have changed, we should update it.
- Bug fix 
- Unit tests

server: handle heartbeat of the region with peers change

---

server/schedule/replica_checker.go
server/schedulers/balance_test.go

When the store is distributed in multiple different zones, the PD tries to distribute the regions in different zones. The `replicaChecker` schedule does not properly check the store space, resulting in the out of space due to scheduling when there is less space in a zone.
make dev

schedule: fix store out of space due to moving replica

---

pkg/apiutil/apiutil.go
server/api/admin.go
server/api/config.go
server/api/log.go
server/api/member.go
server/api/operator.go
server/api/region.go
server/api/scheduler.go
server/api/store.go
server/api/util.go
server/api/util_test.go
server/util_test.go
table/namespace_handler.go

pd server
We often send a 500 error where it should be 400 or 404.
It is important to get these right.
A client will assume it did nothing wrong when a 500 is received
and perhaps automatically retry the request.
This is a conservative change in that
there are many more places that should be changed from 500 to 400 or 404.
Mostly this is due to not investing more time to understand the entire code base.
In some cases, functions are called which don't differentiate error types properly.
A forthcoming PR will provide some help in this case.
A helper function `jsonRespondError` is added.
- Breaking change
I can only assume that most client code is not differentiating between 400 and 500 error codes. In that case there will not be any breakage.
There is a new test suite for the …

send back HTTP 400 where there is a client error

---

server/schedulers/adjacent_region.go
server/schedulers/scheduler_test.go

The scheduler may return `[]*Operator{nil}` in some time, that will cause panic in `addOperator` function.
Bug fix (non-breaking change which fixes an issue)
Unit tests

schedulers: fix the panic issue when no operator produce by adjacent region

---

server/schedulers/adjacent_region.go
server/schedulers/scheduler_test.go

cherry-pick #1136
make dev
#1136

schedulers: fix the panic issue when no operator produce by adjacent region scheduler (#1136)

---

server/schedulers/balance_test.go
server/schedulers/hot_region.go

Currently, the HotRegionScheduler adjusts schedule limit by itself. See https://github.com/pingcap/pd/blob/1e8e857d365585af6841a54473a5aca071ede509/server/schedulers/hot_region.go#L393-L405
A problem was found in the test: when there are many hot regions, when some tikv-servers are added, the limit will be updated to a large value, causing in a large number of operators in a short period of time, resulting in a QPS drop.
Unit test

schedulers: make hot region scheduler respect schedule limit

---

server/schedulers/adjacent_region.go
server/schedulers/scheduler_test.go

This PR fixes two errors in `balanceAdjacentRegionScheduler`. 
- Unit tests

schedulers: fix bugs in balanceAdjacentRegionScheduler

---

server/util.go
server/util_test.go

TiDB-Operator uses the hostname as a label value, so adjust the regular expression. same as kubernetes: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set
unit test

server/api: adjust the regular expression of the validation label

---

server/cluster.go

Fix the wrong log message when an operator timeout.
None

server: fix wrong log

---

server/leader.go
server/metrics.go
server/server.go

- add metrics to show etcd raft states
- rename 'leaderLoopXxx' to 'serverLoopXxx'
Test in a cluster with grafana installed
https://github.com/pingcap/tidb-ansible/pull/480

server: add etcd raft state metrics

---

server/schedule/operator.go
server/schedule/operator_kind.go
server/schedulers/balance_test.go

In `CreateMergeRegionOperator()` bind the kind `OpMerge` to generated operators.
Before this, the operator created by `RandomMergeScheduler` and HTTP API was not correctly set, resulting in a large number of operators.
- add test case
- make test

schedulers: fix the issue that the operator kind is not set correctly

---

server/cluster_info_test.go
server/core/region_tree.go
server/core/store.go

Now PD will calculate the total bytes flow once region heartbeat coming, this is an extra cost. After this change, only calculate the bytes flow when store heartbeat coming. 
unit test

server: reduce the overhead of calculating bytes flow

---

Makefile
docs/development.md
hack/retool-install.sh

This move unecessary tooling tasks out of the Makefile and matches the setup in the tidb repo.
Development tooling
`make check && ./hack/retool-install.sh`

move tool installs to a hack script

---

pkg/integration_test/member_test.go

Fix `TestMemberDelete` by allowing temporary HTTP request failure.
`go test -check.f="TestMemberDelete"` for 100 times
https://github.com/pingcap/pd/pull/1175
PTAL @liukun4515

integration: fix delete member test

---

server/cluster_info.go
server/core/region.go

With bench the heartbeat. log costs a lot of CPU.
```
flat  flat%   sum%        cum   cum%
4420ms  8.02%  8.02%     4420ms  8.02%  runtime.cmpbody
2660ms  4.82% 12.84%     2660ms  4.82%  github.com/pingcap/pd/vendor/github.com/pingcap/kvproto/pkg/metapb.(*Region).GetStartKey
2370ms  4.30% 17.14%     2420ms  4.39%  runtime.heapBitsForObject
2180ms  3.95% 21.09%    17310ms 31.39%  fmt.(*pp).doPrintf
0.52s  0.94% 53.84%     14.81s 26.86%  github.com/pingcap/pd/vendor/github.com/golang/protobuf/proto.writeString
```
mainly due to the proto MashalText and io.write. This PR:
- Do not log the new region insert. the report split handler will log it.
- Do not log the leader change when startup the PD.
- log the all key when the `conf` changed
- Improvement (non-breaking change which is an …

server: adjust the log when receiving heartbeat

---

server/coordinator.go

When adding a big table into namespace, the checker creates too many operators, which causes io/leader_change disasters.
this pr fix this.
make namespace checker follows scheduler limits.
- `make dev` is passed.
- Manual tested.
no

coordinator: make namespace checker honor the leader&region&replica limit

---

server/cluster.go
server/namespace/classifier.go
server/namespace_test.go
server/region_statistics_test.go
table/namespace_classifier.go
table/namespace_classifier_test.go

When using table namespace classifier, the ns info should be reload from storage.
related issue: #1178
Reload namespace info of table classifier after becoming leader.
The PR add a `ReloadNamespaces() error`  function into `Classifier` interface,
and table classifier rescans data from kv, default implementation does nothing.
- Fix #1178 
Reload function is tested, and `make dev` is passed.
no

classifier: reload ns info after leader change

---

cmd/simulator/main.go

This PR makes the simulator run again. There is one case that the etcd's leader has been elected but the server' leader has not. If we start PD server from the simulator itself, the bootstrap will fail under the circumstance. 
- Manual tests

simulator: wait PD leader election before simulator start

---

server/cluster_info.go
server/config.go
server/namespace_test.go
server/option.go
server/schedule/mockcluster.go
server/schedule/namespace_checker.go
server/schedule/opts.go

This PR add an option to disable namespace checker's region relocation scheduling.
- disable-namespace-relocation
The implementation uses https://github.com/pingcap/pd/pull/1140 for reference.
- New feature (non-breaking change which adds functionality)
`make dev` and manual test.
TODO: add later
#1199

schedule: add option to disable namespace checker

---

server/schedule/selector.go
server/schedulers/adjacent_region.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/evict_leader.go
server/schedulers/label.go
server/schedulers/random_merge.go
server/schedulers/shuffle_leader.go
server/schedulers/shuffle_region.go
server/schedulers/utils.go

- Remove the `Selector` interface, use concrete Selector types instead
- Remove the redundant filters parameter in `SelectSource()` and `SelectTarget()`.
- Move `scheduleRemovePeer` and `scheduleAddPeer` out of `utils.go` since they are used only by `shuffleRegionScheduler`
make dev

schedule: refactor Selector

---

Gopkg.lock
Gopkg.toml
vendor/github.com/BurntSushi/toml/COPYING
vendor/github.com/BurntSushi/toml/cmd/toml-test-decoder/COPYING
vendor/github.com/BurntSushi/toml/cmd/toml-test-encoder/COPYING
vendor/github.com/BurntSushi/toml/cmd/tomlv/COPYING
vendor/github.com/BurntSushi/toml/lex.go

The existing commit has the WTFPL license, which is not an OSCI license.
The latest commit has been licensed as MIT.
update toml to the latest version.
The existing commit has the WTFPL license, which is not an OSCI license.
The latest commit has been licensed as MIT.
I didn't test this other than to run `make`. Are there any toml-related tests we can do?
However, its clear from the changes to vendor that the only difference is support for UTC offset from this PR: https://github.com/BurntSushi/toml/pull/182

update toml to the latest version

---

hack/clean_vendor.sh
vendor/github.com/coreos/etcd/NOTICE
vendor/github.com/coreos/go-systemd/NOTICE
vendor/github.com/coreos/pkg/NOTICE
vendor/github.com/etcd-io/gofail/LICENSE
vendor/github.com/etcd-io/gofail/NOTICE
vendor/github.com/grpc-ecosystem/grpc-gateway/LICENSE.txt
vendor/github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/LICENSE
vendor/github.com/matttproud/golang_protobuf_extensions/NOTICE
vendor/github.com/prometheus/client_golang/NOTICE
vendor/github.com/prometheus/client_model/NOTICE
vendor/github.com/prometheus/common/NOTICE
vendor/github.com/prometheus/procfs/NOTICE
vendor/github.com/spf13/cobra/LICENSE.txt
vendor/github.com/spf13/cobra/cobra/cmd/testdata/LICENSE.golden
vendor/go.uber.org/atomic/LICENSE.txt
vendor/go.uber.org/multierr/LICENSE.txt
vendor/go.uber.org/zap/LICENSE.txt
vendor/gopkg.in/yaml.v2/LICENSE.libyaml
vendor/gopkg.in/yaml.v2/NOTICE

Add missing legal files by fixing ./hack/clean_vendor.sh
NOTICE and LICENSE are added.
I did not add files for TOML because there is another PR to update toml.
That PR includes license files.
This file is being kept in sync with the tidb project.
There are additional pruning commands that remove exteraneous files in
tidb, but currently have no effect in pd.
no additional testing

Add missing legal files

---

server/core/region.go
server/core/region_test.go

No use of escape characters will print strange logs. this PR fix it.
unit test.

server/core: fix DiffRegionKeyInfo no use escaped key

---

revive.toml

revive linter: exit 1 on failure.
I didn't realize it was defaulting to exit with code 0.
Warning still exits with code 0.

revive linter: exit 1 on failure

---

server/schedulers/balance_leader.go
server/schedulers/balance_region.go

This PR is going to make the debug log look better.
before:
```
2018/08/30 10:11:03.437 balance_leader.go:156: [debug] [balance-leader-scheduler] skip balance region 2968, source 4 to target 2, source size: 19296, source score: 19296, so
urce influence: 0,
target size: 18912, target score: 18912, target influence: 0, average region size: 96
```
after:
```
2018/08/30 10:12:43.080 balance_leader.go:156: [debug] [balance-leader-scheduler] skip balance region 1896, source 6 to target 1, source size: 11808, source score: 11808, so
urce influence: 0, target size: 11712, target score: 11712, target influence: 0, average region size: 96
```

server: make debug log look better

---

pd-client/client.go
pd-client/client_test.go

Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
Now we want invoke RPC calls to each TiKV in TiDB, so TiDB should know all TiKVs before doing this. PD already has this functionality but it didn't show up in the PDClient interface. Add it so that TiDB can call it conveniently.
This PR added GetAllStores function to PdClient interface so that TiDB can use it conveniently to get all TiKVs.
Tests
- Unit test
- Need to cherry-pick to the release branch (Maybe)

client: Add GetAllStores function to PdClient interface

---

cmd/simulator/main.go
pkg/faketikv/cases/add_nodes.go
pkg/faketikv/cases/add_nodes_dynamic.go
pkg/faketikv/cases/delete_nodes.go
pkg/faketikv/drive.go
pkg/faketikv/raft.go
pkg/faketikv/statistics.go
pkg/faketikv/task.go

This PR add some statistics for simulator, such as task statistics and snapshot statistics.
- Manual tests

simulator: add statistics for simulator

---

pdctl/command/region_command.go
server/api/api.raml
server/api/region.go
server/api/region_test.go
server/api/router.go
server/cluster.go
server/cluster_info.go
server/core/region.go

Closes #511.
This PR adds API to list all regions in a specified store. After this PR is merged, we can use `region store <id>` to print all regions in a specified store by using `pd-ctl`.
Tests 
- Unit test

pd-ctl: list all regions in a specified store 

---

pkg/faketikv/cases/cases.go
pkg/faketikv/cases/makeup_down_replica.go
server/coordinator_test.go
server/schedule/replica_checker.go
server/schedulers/balance_test.go

At present, if a store is down, it will remove peers in the store directly, and then make up replicas. It usually needs some time because it will traverse all the regions. 
This PR tries to move the peers to another store if the original store is down.
Besides, this PR adds a case in the simulator to simulate this kind of situation. It will print an error log without these changes: `making up replicas don't start immediately`.
Tests 
- Unit test
- Manual test

server: try to replace the down replicas instead of removing directly

---

server/cluster_info.go
server/coordinator.go
server/coordinator_test.go
server/core/region.go

…n of regions activated on each store
If we have many stores, like 10 stores, and restart the cluster. 9 stores already reported a heartbeat and the last not finished. the schedulers will begin to schedule and do some unnecessary balance.
This PR startup schedulers with considering the proportion of regions activated on each store.
Tests 
- Unit test

server/coordinator: startup schedulers with considering the proportion of regions

---

pdctl/command/region_command.go
server/api/api.raml
server/api/region.go
server/api/region_test.go
server/api/router.go
server/core/region_option.go

Related to #1092.
This PR provides a way to list top regions whose conf version or version is the largest. After this PR, we can use `region topconfver <limit>` or  `region topversion <limit>` in `pd-ctl` to find what we want.
Tests 
- Unit test
- Manual test

pd-ctl: support topconfver and topversion

---

server/cluster.go

This PR closes #1221.
When setting a store to `Offline`, it won't turn into `Tombstone`, if there are no extra space or nodes to accommodate the extra replicas. This PR will show warning message to let user know about it.
Tests 

server: store cannot turn into tombstone due to limited resources

---

server/cluster_info.go
server/coordinator_test.go
server/region_statistics.go

After the RegionInfo refactor PR https://github.com/pingcap/pd/pull/1207, we are able to avoid region clone in non-test files.
Search and cleanup region clone from non-test files. There is still a place that is currently inconvenient to remove. 
https://github.com/pingcap/pd/blob/21d425857acf52e8ddf9c913d1f7a70c4ec79654/server/schedule/replica_checker.go#L101 
It does have a good reason to clone here. But we may consider handle it later.
Tests 
- Unit test

server: cleanup residual region clone

---

Gopkg.toml

Other projects are now depending directly on PD.
In the long term we need to separate out client/library functionality
from the server. But that will still require this change.
This came up in https://github.com/pingcap/tidb/pull/7151

pkg/errors: use a lower bound

---

pdctl/command/tso_command.go

More precise tso time decoding
Calculate the millisecond portion
Tests 
- Manual test
```
>> tso 402826222697185283
system:  2018-09-11 18:01:30.245 +0800 CST
logic:  3
```

pdctl: more precise tso time decoding

---

server/schedulers/adjacent_region.go

If `adjacent-region` scheduler is enabled, after pd transfers leader and the new leader is prepared, 
there is a gap that heartbeats of some regions are not received, and leaders are not updated.
store id of a nil peer  is `0`, see https://github.com/pingcap/pd/blob/fa5f08c252a4c5025cdef5bf0f2bdab78d7c0a36/vendor/github.com/pingcap/kvproto/pkg/metapb/metapb.pb.go#L256, so this line https://github.com/pingcap/pd/blob/fa5f08c252a4c5025cdef5bf0f2bdab78d7c0a36/server/schedulers/adjacent_region.go#L223 return a `nil` store, which causes panic.
This change makes sure that region's leader is not nil, and leader's store is not nil, and also fix metric value of adjacent-count.
Another solution is  skip holes of not heartbeat-ed regions when calculating adjacent-regions, which prevents the issue at …

Fix panic of adjacent-region-scheduler after pd transfer leader

---

server/config.go

Fix `DisableNamespaceRelocation` option when cloning SchedulerConfig.
As it is.
Tests 
make test

config: fix DisableNamespaceRelocation option clone behaviour

---

server/api/region.go
server/api/region_test.go

- return full region information not only the region meta.
close #1223 
Tests 
- Unit test
- Manual test
Side effects
no

pd-ctl: return full region information for /region api

---

server/coordinator.go

Currently, after removing scheduler by using `pd-ctl`, the scheduler which is deleted still remains in the Grafana.
This PR sets the metrics of the scheduler which is deleted to 0 after removing it.
Tests 
- Manual test

server: fix scheduler metrics

---

server/placement/constraint.go
server/placement/parser.go
server/placement/placement_test.go

Part of the placement constraint implementation.
Add config structure and the parser to parse user-defined config.
Tests 
- Unit test

server/placement: add placement constraint config parser

---

Makefile

When we run `make test`, it could be failed sometimes. And it will make the temporary files which is generated by the test remain in the system temporary directory. We need to delete them manually in order to free up the space which is not friendly enough.
This PR adds a target for `make` to remove those temporary files. 
Tests 
- Manual test

*: clean up the test temporary files

---

server/cluster.go
server/coordinator.go
server/coordinator_test.go

At present, `coordinator` uses `WaitGroup` to synchronize. We call `Add()` in `(c *coordinator) run()` and `Wait()` in `(c *coordinator) stop()` which are in different goroutines. So the data race could happen when the leader drops. This PRs closes #1268. 
Tests 

server: fix WaitGroup data race

---

server/cluster_test.go
server/heartbeat_stream_test.go

CI fails occasionally because the tests in `cluster_test.go` uses a shared server, which might make `getRegion` failed. 
This PR starts a new server to run each test and does some clean up since `testClusterBaseSuite` looks like a gocheck suite but actually it is not. 
Tests 
Side effects
- Need a little bit more time to run this test suite

*: fix cluster test

---

server/cluster.go

Currently, the store in both up and offline state will be considered as `offlineStore`, which will call `BuryStore`, but this bug doesn't affect correctness.
If the store is up, the `upStoreCount` should add one and continue the next loop.
Tests 

*: fix a tiny bug in checkStore

---

Dockerfile

* Small, consistent executable image.
* Use the latest golang version which supports go modules.
Use separate build and deploy images.
- Manually tested only by verifying that pd starts up.

use a separate builder image and deploy in Alpine

---

server/cluster.go
server/coordinator.go
server/coordinator_test.go

cherry-pick #1273 
This PR puts `Add()` and `Wait()` of `WaitGroup` into the same goroutine.
Tests 

server: fix WaitGroup data race (#1273)

---

server/api/scheduler.go
server/schedulers/adjacent_region.go
server/schedulers/random_merge.go
tools/pd-ctl/pdctl/command/scheduler.go

Currently, we only support adding some of schedulers by using `pd-ctl`. And some schedulers, such as `balance-leader-scheduler` and `balance-region-scheduler`, can not be added once they has been removed. The only way we can add them back is by using `curl`.
Closes #1286.
This PR is going to support adding all schedulers of PD by using `pd-ctl`.
Tests 
- Manual test

pd-ctl: support adding more schedulers

---

server/cluster.go
server/cluster_worker.go
server/coordinator.go
server/coordinator_test.go
server/grpc_service.go
server/handler.go
server/heartbeat_streams.go
server/metrics.go
server/schedule/merge_checker.go
server/schedule/metrics.go
server/schedule/operator.go
server/schedule/operator_controller.go
server/schedule/sched_limiter.go
server/schedule/scheduler.go
server/schedulers/balance_test.go
server/schedulers/random_merge.go

Currently, the logic of schedule limit is mainly in `coordinator.go` which is not clear enough.
This PR moves the schedule limit related logic from `coordinator.go` and `scheduler.go` to `sched_limiter.go` and does some tiny cleanup.
Tests 

schedule: schedule limiter refactor

---

client/client.go
server/cluster.go
server/cluster_test.go
server/cluster_worker.go
server/grpc_service.go
server/handler.go

When the leader drops which could be caused by some reasons (e.g. cannot read from disk), it will elect a new leader which will call `createRaftCluster` to reassign `cachedCluster`, `coordinator` and `running` in `RaftCluster`. At that time, if we read `RaftCluster` without lock, the data race may happens. This PR closes #1270.
This PR adds some locks when reading from `cachedCluster` and `coordinator` in order to prevent reading and writing `RaftCluster` at the same time. 
Tests 
- Unit test

server: fix data race in RaftCluster

---

server/api/region_test.go
tools/pd-ctl/pdctl/command/region_command.go

We should escape the key otherwise will not get the corresponding region.
escape the key in query URL.
Tests 
- Unit test

pdctl: escape the key before query the corresponding region

---

tools/pd-simulator/simulator/cases/add_nodes.go
tools/pd-simulator/simulator/cases/add_nodes_dynamic.go
tools/pd-simulator/simulator/cases/balance_leader.go
tools/pd-simulator/simulator/cases/cases.go
tools/pd-simulator/simulator/cases/delete_nodes.go
tools/pd-simulator/simulator/cases/event_inner.go
tools/pd-simulator/simulator/cases/hot_read.go
tools/pd-simulator/simulator/cases/hot_write.go
tools/pd-simulator/simulator/cases/makeup_down_replica.go
tools/pd-simulator/simulator/cases/region_merge.go
tools/pd-simulator/simulator/cases/region_split.go
tools/pd-simulator/simulator/drive.go
tools/pd-simulator/simulator/event.go

Currently, we have an interface named `EventInner` and it is public, which is wired.
This PR renames `EventInner` to `EventDescriptor` and use a global id allocator. 
Tests 
- Manual test

simulator: rename EventInner to EventDescriptor

---

tools/pd-ctl/pdctl/command/region_command.go

The command `region key` does not support all escaped keys generated by golang "%q".
Support all runes listed in https://golang.org/ref/spec#Rune_literals
Tests 

pdctl: fix decode key

---

server/cluster.go
server/coordinator.go

When we call `run()` in `coordinator`, it will write `scheduleCfg`. However, some functions such as `GetMaxStoreDownTime()` may read this variable at the same time which will lead to a data race.
This PR fixes this problem by cloning the `scheduleCfg`.
Tests 
- Manual test (make test)

*: fix ScheduleConfig data race

---

server/api/region.go
server/cluster_info.go
server/cluster_worker.go
server/core/region.go
server/core/region_test.go
server/core/region_tree.go
server/schedule/merge_checker.go
tools/pd-ctl/pdctl/command/region_command.go
tools/pd-ctl/pdctl/command/scheduler.go

Fix the variety of key formats used in different Ti projects. We finally decided to use the hex format everywhere.
- Use hex format as the output of region key related APIs.
- Support hex format in pdctl and make it the default format.
- Use hex format keys in logs.
Tests 
Code changes
- Has HTTP API interfaces change: The output of region key is changed.
Side effects
- It breaks backward compatibility for tools that rely on the key format we were using for the region info related APIs.

pdctl, api: support hex format keys

---

server/tso.go
server/tso_test.go

If client forgets to set the `count` field of tso request. pd-server will respond timestamp without increasing logical counter.
Check count before allcating tso.
Tests 
- Unit test

tso: add sanity check for the count field of request

---

pkg/integration_test/cluster.go
pkg/integration_test/leader_watch_test.go
server/leader.go
server/tso_test.go
server/util.go

the watcher maybe loses some event without specified revision. In our election, there is a gap between `got leader key` and `watch the leader key`, if some event happens in this gap, like delete the leader key and write a new leader key, the watcher will lose those events, and cause the PD still think the leader is the old one.
get the last modify revision and use it to watch.
Tests 
- Unit test

server/leader: use the last modify revision to watch leader

---

CHANGELOG.md

Prepare release.
Add changelog.
Tests 
- Unit test

Release v2.1.0-rc.5

---

pkg/integration_test/cluster.go
pkg/integration_test/pdctl_test.go

This PR is part of #1328 and based on #1327.
Add tests for scheduler and tso subcommands in pd-ctl.
Tests 
- Unit test

pdctl: add tests for scheduler and tso subcommands

---

server/config.go
server/config_test.go

this patch will not cause the name conflict when user doesn't provide a name.
Tests 
- Unit test
Code changes

Config: change default name to pd-{hostname}

---

server/api/redirector.go
server/api/redirector_test.go

If we send a request to a follower, it will be redirected to the leader and we use the `Add` function to copy the header. In this situation, the redundant informations could be appended. 
Before appending the informations to the header, we firstly check if it already has the same message.
Fixes pingcap/tikv#3894.
Tests 
- Manual test

api: fix redundant header

---

server/config.go
server/config_test.go
server/coordinator.go

[Cherry-pick] config: check undefined config item (#1362)

---

server/cluster.go
server/cluster_test.go

the `RaftCluster` probability can't stop cause by deadlock.
fix the mutex usage.
Tests 
- Unit test

server: Fix the issue about RaftCluster cannot be stopped

---

tools/pd-ctl/pdctl/command/config_command.go

When we use `config delete namespace` in `pd-ctl`, if we only provide the namespace name, it will panic.
```
» config delete namespace ts1
panic: runtime error: index out of range
goroutine 1 [running]:
github.com/pingcap/pd/tools/pd-ctl/pdctl/command.deleteNamespaceConfigCommandFunc(0xc00045b680, 0xc000131ce0, 0x1, 0x3)
/.../PingCAP/go/src/github.com/pingcap/pd/tools/pd-ctl/pdctl/command/config_command.go:304 +0x642
github.com/spf13/cobra.(*Command).execute(0xc00045b680, 0xc000131bf0, 0x3, 0x3, 0xc00045b680, 0xc000131bf0)
/.../PingCAP/go/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:760 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042d400, 0x10, 0xe, 0xc000467b80)
/.../PingCAP/go/pkg/mod/github.com/spf13/cobra@v0.0.2/command.go:846 +0x2fd …
```

pd-ctl: fix delete namespace command

---

Makefile

It's better to run `go mod tidy` before sending a PR. 
This PR adds `go mod tidy` into `make check`
Tests 
- Manual test

*: add go mod tidy into Makefile

---

server/cluster.go

Currently, when there is tombstone store, it will print the log `[info] buried store id:x address:"xxx" state:Tombstone` every minute, which is kind of disturbing.
This PR removes this unused log and makes some cleanup.
Tests 

server: remove the disturbing log when store is tombstone

---

pkg/integration_test/pdctl_test.go
server/cluster.go
server/cluster_info.go
server/cluster_worker_test.go
server/namespace/classifier.go
server/namespace_test.go
server/region_statistics_test.go
server/schedule/hot_cache.go
server/schedulers/scheduler_test.go
server/server.go
table/namespace_classifier.go
table/namespace_classifier_test.go

There is some code which is not covered by tests.
This PR adds more tests and comments.
Tests 
- Unit test

*: add more tests and comments

---

pkg/integration_test/pdctl_test.go

Part of #1328.
This PR adds some tests for `operator` subcommand in `pd-ctl`.
Tests 
- Unit test

pdctl: add operator subcommand tests for pd-ctl

---

server/leader.go

Currently, when we stop PD, it will print the error stack which is confused even if there is only one PD.
```
2018/12/26 05:10:45.332 leader.go:116: [error] campaign leader err server closed
github.com/pingcap/pd/server.(*Server).campaignLeader
/.../pd/server/leader.go:287
github.com/pingcap/pd/server.(*Server).leaderLoop
/.../pd/server/leader.go:115
runtime.goexit
/usr/local/go1.11.1/src/runtime/asm_amd64.s:1333
```
This PR fixes this problem. It will returns nil rather than an error when the server is closed in `campaignLeader`'s loop.
Tests 
- Manual test

server: return nil when server is closed

---

Makefile
server/cluster.go
server/leader.go
server/server.go
tests/client/client_test.go
tests/cluster.go
tests/cmd/pdctl_test.go
tests/compatibility/version_upgrade_test.go
tests/config.go
tests/server/api_test.go
tests/server/join_test.go
tests/server/leader_watch_test.go
tests/server/member_test.go
tests/server/region_syncer_test.go
tests/server/server_test.go

Currently, the tests in `pkg/integration_test` often fail since the port has been used. The more test cases we have, the easier the test is to fail.
This PR divides these tests into different packages in order to utilize our `jenkins` CI to speed up the tests and avoid port conflicts.
Tests 
- Unit test
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/pd/1391)

test: split integration tests into different packages

---

go.mod
go.sum

The tests failed which is caused by `replace` in `go.mod`.
This PR fixes CI after splitting tests into multi-container to run.
Tests 
- Unit test

*: update gofail to fix CI

---

server/metrics.go
server/store_statistics.go

For now, we can only find the parameters of the configuration through the log, which is not friendly.
This PR adds some important configurations into metrics.

*: add the scheduling configuration metrics

---

pkg/integration_test/leader_watch_test.go
server/leader.go

* server/leader: use the compact revision to watch leader
Cherry pick #1396  to 2.1 branch.

server/leader: use the compact revision to watch leader (#1396)

---

tools/pd-ctl/pdctl/command/region_command.go

make some region_command, such as `region topwrite` support `--jq`.
Tests 
- Manual test 
Side effects
> bin/pd-ctl -u http://10.136.133.23:2379 -d region topwrite 1 --jq=".regions[] | {start_key: .start_key, end_key: .end_key, peer_stores: [.peers[].store_id], leader:.leader.store_id, id: .id, written_bytes: .written_bytes}"
unknown flag: --jq
{"start_key":"fm_bench_mark_user:-1254349631","end_key":"fm_bench_mark_user:-1256054961","peer_stores":[17,8,1],"leader":17,"id":86367,"written_bytes":28664496}
See above, it ouputs unexpected message "unknown flag: --jq".

make some region_command support jq

---

server/api/member.go
server/api/redirector.go
server/api/util.go
server/region_syncer/client.go
server/region_syncer/history_buffer.go
server/region_syncer/server.go
server/schedule/filters.go
server/schedule/merge_checker.go
server/schedule/mockcluster.go
server/schedule/namespace_checker.go
server/schedule/operator.go
server/schedule/operator_controller.go
server/schedule/replica_checker.go
server/schedule/scheduler.go
server/schedulers/adjacent_region.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/base_scheduler.go
server/schedulers/hot_region.go
server/schedulers/label.go
server/schedulers/scheduler_test.go
server/schedulers/shuffle_hot_region.go
server/schedulers/shuffle_region.go

Format the log according to our RFC.
This PR is going to do the log format for `schedule`, `scheduler`, `syncer`, and `api` packages.
Tests 
- Unit test

*: log format for schedule, scheduler, syncer, api

---

client/client.go
pkg/etcdutil/etcdutil.go
pkg/metricutil/metricutil.go
pkg/tempurl/tempurl.go
table/namespace_classifier.go
tools/pd-simulator/main.go
tools/pd-simulator/simulator/cases/add_nodes.go
tools/pd-simulator/simulator/cases/add_nodes_dynamic.go
tools/pd-simulator/simulator/cases/balance_leader.go
tools/pd-simulator/simulator/cases/delete_nodes.go
tools/pd-simulator/simulator/cases/hot_read.go
tools/pd-simulator/simulator/cases/hot_write.go
tools/pd-simulator/simulator/cases/import_data.go
tools/pd-simulator/simulator/cases/makeup_down_replica.go
tools/pd-simulator/simulator/cases/region_merge.go
tools/pd-simulator/simulator/cases/region_split.go
tools/pd-simulator/simulator/client.go
tools/pd-simulator/simulator/drive.go
tools/pd-simulator/simulator/event.go
tools/pd-simulator/simulator/node.go
tools/pd-simulator/simulator/raft.go
tools/pd-simulator/simulator/simutil/logger.go
tools/pd-simulator/simulator/task.go
tools/pd-tso-bench/main.go

Format the log according to our RFC.
This PR is going to do the log format for tools, client, pkg, and table packages.
And it still works in progress. Do not review it now.
Tests 
- Unit test

*: log format for tools, client, pkg, table

---

server/coordinator.go
server/coordinator_test.go
server/grpc_service.go
server/heartbeat_stream_test.go
server/heartbeat_streams.go
server/metrics.go
server/schedule/filters.go
server/schedule/metrics.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/metrics.go
server/server.go
server/store_statistics.go

Closes #1427.
This PR is going to use TiKV address instead of `storeID` for the metrics.
Tests 
- Unit test

*: use address instead of storeID for metrics

---

server/config.go
server/config_test.go
server/coordinator.go
server/schedule/scheduler.go
server/testutil.go

Check scheduler's name from configFile to prevent misspelled cases.
Related issue: https://github.com/pingcap/pd/issues/1443
Checking happens in scheduleConfigs validation stage.
Tests 
- Unit test

config: check scheduler's name from config file

---

server/handler.go
server/schedule/namespace_checker.go
server/schedule/operator.go
server/schedule/region_scatterer.go
server/schedule/replica_checker.go
server/schedulers/adjacent_region.go
server/schedulers/balance_region.go
server/schedulers/balance_test.go
server/schedulers/hot_region.go
server/schedulers/shuffle_region.go

Normally, PD avoids removing leader directly when scheduling. When the leader needs to be removed, the PD inserts a transfer leader step. However, when the number of replica is set to 1, this scheme does not attempt to transfer the leader to the peer that will be created, resulting in the direct remove of the leader.
Constructs a list based on the current peers and the peer to be added, then looks for the target of the transferLeader in the list. If target is not found, it returns an error to cancel the schedule process.
Tests 
- Unit test

schedule: fix scheduler removes region leader

---

CONTRIBUTING.md
docs/development-workflow.md

The document can help contributor how to do development workflow.
I just added a document and update the document CONTRIBUTING.md.

added the doc 'development-workflow.md'

---

server/handler.go
server/schedule/namespace_checker.go
server/schedule/operator.go
server/schedule/region_scatterer.go
server/schedule/replica_checker.go
server/schedulers/adjacent_region.go
server/schedulers/balance_region.go
server/schedulers/balance_test.go
server/schedulers/hot_region.go
server/schedulers/shuffle_region.go

Normally, PD avoids removing leader directly when scheduling. When the leader needs to be removed, the PD inserts a transfer leader step. However, when the number of replica is set to 1, this scheme does not attempt to transfer the leader to the peer that will be created, resulting in the direct remove of the leader.
Constructs a list based on the current peers and the peer to be added, then looks for the target of the transferLeader in the list. If target is not found, it returns an error to cancel the schedule process.
Tests 
- Unit test

schedule: fix scheduler removes region leader (#1462)

---

Makefile
server/coordinator.go
tools.json

Currently, our CI is not stable. And also `gometalinter` and `megacheck` are deprecated.
This PR fixes CI by adding `export GO111MODULE=on` and switches to `golangci-lint`.
Tests 
- Unit test

*: fix CI and switch to golangci-lint

---

server/api/router.go
server/api/store.go
server/cluster.go
server/cluster_info.go
server/core/kv.go
server/core/store.go
server/schedule/basic_cluster.go
tests/cmd/pdctl_test.go
tools/pd-ctl/pdctl/command/store_command.go
tools/pd-ctl/pdctl/ctl.go

#1468 
Tests 
- Unit test
- No code
Code changes
Side effects

*: add a API to clear tombstone store 

---

CHANGELOG.md

Bump to v2.1.7

---

server/api/hot_status.go
server/schedule/mockcluster.go
tests/cmd/pdctl_test.go

Currently, `GetHotStores` will return the same value for `KeysRead` and `KeysWritten`.
This PR fixes this problem and improves the test.
Tests 
- Unit test

api: fix GetHotStores

---

server/config.go

Force to create a new one-member cluster. It commits configuration changes forcing to remove all existing members in the cluster and add itself
add flag
Tests 

*: supports force to create a new one-member cluster

---

server/core/store.go
table/codec.go
table/namespace_classifier.go
table/namespace_classifier_test.go

For now, both `GetBytesReadRate` and `GetBytesWriteRate` use a read lock, and `GetRegionNamespace` decodes the same key twice.
This PR replaces `GetBytesReadRate` and `GetBytesWriteRate` with `GetBytesRate` to reduce lock contention and replace `IsMeta` with `MetaOrTable` to reduce one decoding.
Tests 
- Unit test

server: improve region heartbeat

---

server/schedule/operator_controller.go

Cannot understand the log, like:
```
[2019/04/02 15:29:20.333 +08:00] [INFO] [operator_test.go:206] [testing] [step="{\"ToStore\":1,\"PeerID\":1}"]
[2019/04/02 15:29:20.333 +08:00] [INFO] [operator_test.go:206] [testing] [step="{\"FromStore\":3,\"ToStore\":1}"]
[2019/04/02 15:29:20.333 +08:00] [INFO] [operator_test.go:206] [testing] [step="{\"FromStore\":3}"]
```
use the `String` function to format output. 
Tests 
- Manual test
before:
```
[2019/04/02 15:29:20.333 +08:00] [INFO] [operator_test.go:206] [testing] [step="{\"ToStore\":1,\"PeerID\":1}"]
[2019/04/02 15:29:20.333 +08:00] [INFO] [operator_test.go:206] [testing] [step="{\"FromStore\":3,\"ToStore\":1}"]
[2019/04/02 15:29:20.333 +08:00] [INFO] [operator_test.go:206] [testing] …
```

schedule: fix the operator step print

---

server/api/hot_status.go
server/grpc_service.go
server/handler.go
server/schedule/mockcluster.go
server/schedule/operator.go
server/schedule/region_scatterer.go
server/schedulers/scheduler_test.go

some fixes to release 2.1
cherry pick
Tests 
- Unit test

*: cherry pick some fixes to release 2.1

---

server/coordinator.go
server/handler.go
server/schedule/namespace_checker.go
server/schedule/operator_controller_test.go
server/schedule/operator_test.go
server/schedule/replica_checker.go
server/schedulers/hot_region.go
server/schedulers/shuffle_hot_region.go
server/schedulers/shuffle_leader.go

At present, we have different styles of operator's descriptions, such as `promoteLearner` and `balance-leader`.
This PR unifies the format of these descriptions.
Tests 
- Unit test

server: unify the format of operators' descriptions

---

server/grpc_service.go
server/metrics.go

When pd-client reports slow tso, we don't know if it takes too much time for server to handle the request.
Add metrics.
Tests 

server: add tso handle time metrics

---

server/grpc_service.go
server/metrics.go

When pd-client reports slow tso, we don't know if it takes too much time for server to handle the request.
Add metrics. Cherry-pick #1502 
Tests 

server: add tso handle time metrics (#1502)

---

client/client.go
client/client_test.go

Add the scatter region and get operator interface to PD Client.
Tests 
- Unit test

client: supports scatter region and get operator status

---

Makefile

When `make test` and there are some unstaged changes, the `tidy` check will fail.
`tidy` checkes only module files (go.mod and go.sum)
Tests 

makefile: tidy checks only module files

---

server/util.go
tools/pd-ctl/pdctl/command/global.go

To avoid the potential hanging, it's better to add a timeout for HTTP clients.
This PR adds a timeout for these clients.
Tests 
- Unit test

util: add a timeout for HTTP client

---

Dockerfile

+ Add pd-ctl in Docker
+ Add jq support for pd-ctl in Docker
+ Cache dependencies to avoid build them every time
Tests 
- No code
Code changes
No
Side effects
No
No need

docker: add jq and cache dependencies

---

server/cluster_test.go
server/grpc_service.go
server/heartbeat_stream_test.go
server/heartbeat_streams.go

Because of cannot get the target peer, we cannot send the error to tikv.
check the target peer.
Tests 
- Unit test

server: fix cannot send error in heartbeat stream

---

server/config.go
server/coordinator.go
server/leader.go
server/schedule/hot_cache.go
server/schedule/merge_checker.go
server/schedule/operator.go
server/schedule/opts.go
server/schedule/replica_checker.go
server/schedule/scheduler.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/util.go

Clean up some code.
Just clean up the code
Tests 
- Unit test

*: tiny clean up code

---

server/config.go
tests/cluster.go
tests/cmd/pdctl_test.go
tests/server/api_test.go

For 3.0, we default enable it.
change config.
Tests 
- Manual test

config:  enable use region storage by default

---

server/cluster.go
server/coordinator.go
server/leader.go

cherry-pick log improvement in #1516 and #1526.
Tests 
- Unit test

*: improve some logs

---

server/schedulers/balance_test.go
server/schedulers/hot_region.go

In some situation, the balance region has preempted the limiter, and the hot region balance has no chance to schedule.
change the `AllowSchedule` condition.
Tests 
- Unit test

schedulers: let hot region balance not affect by balance-region-scheduler-limit

---

server/config.go
server/region_syncer/history_buffer.go

close https://github.com/pingcap/pd/issues/1523
```
[2019/04/29 04:25:37.846 +00:00] [ERROR] [leader.go:80] ["no etcd leader, check leader later"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20190214045112-b37da76f67a7/global.go:42\ngithub.com/pingcap/pd/server.(*Server).leaderLoop\n\t/go/src/github.com/pingcap/pd/server/leader.go:80"][2019/04/29 04:25:38.046 +00:00] [ERROR] [leader.go:80] ["no etcd leader, check leader later"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20190214045112-b37da76f67a7/global.go:42\ngithub.com/pingcap/pd/server.(*Server).leaderLoop\n\t/go/src/github.com/pingcap/pd/server/leader.go:80"]
```
The  stack trace of error level is not required, we can add a field if we need it.
change the …

log: do not add stack to error log

---

server/leader.go

When multiple PDs calls `MoveLeader`, one will succeed and others will block in `MoveLeader` function.
Add timeout when calling `MoveLeader`.
Cherry-pick #1533 
Tests 

server: set timeout for MoveLeader

---

README.md

Closes #1542.
This PR updates some dead links of PD README.
Tests 
- No code

*: update some dead links

---

server/cluster.go
server/schedule/operator.go
server/schedule/operator_controller.go

Currently, the metrics of the timeout operator is updated in `IsTimeout`, which will be calculated multiple times since there are many functions call it.
Add a new function `RemoveTimeoutOperator` to update this metrics.
Tests 
- Unit test

metrics: fix operator timeout metrics

---

server/schedulers/balance_test.go
server/schedulers/hot_region.go

The auto adjust limit may become 0.
use 1 as min value.
Tests 
- Unit test

schedulers: fix the issue about the limit of the hot region

---

Makefile
hack/retool-install.sh
server/schedulers/balance_test.go
tools.json

The CI of `release-2.1` branch has been broken since `megacheck` is deprecated.
This PR fixes this problem by using `staticcheck` and also fixes a lint problem.
Tests 
- Unit test

*: use staticcheck instead of megacheck

---

tests/pdctl/store/store_test.go
tools/pd-ctl/pdctl/command/store_command.go

closes #1517
https://github.com/pingcap/pd/issues/1517
Support removing a TiKV store by its address.
Extend the `delete` command
```
store delete addr <address>
```
There are two HTTP requests issued in this command, first to fetch all the stores, finding the ID by its address and second to delete the store by the ID.
Tests 
- Manual test (add detailed scripts or steps below) 

pdctl: support to delete a store by its address

---

server/coordinator.go
server/handler.go
server/schedule/merge_checker.go
server/schedule/operator.go
server/schedule/region_scatterer.go
server/schedule/replica_checker.go
server/schedulers/adjacent_region.go
server/schedulers/balance_leader.go
server/schedulers/evict_leader.go
server/schedulers/grant_leader.go
server/schedulers/hot_region.go
server/schedulers/label.go
server/schedulers/random_merge.go
server/schedulers/shuffle_hot_region.go
server/schedulers/shuffle_leader.go

We have a lot of operators right now, and these operators are created through API, schedulers and checkers. We use `NewOperator` everywhere and each of them needs `steps` as the parameters, which is complex.
Since we already have some functions like `CreateMovePeerOperator`. This PR abstracts more functions to create corresponding operators and makes the code unified.
Tests 
- Unit test

schedule: move all NewOperator into operator

---

server/schedule/mockcluster.go
server/schedule/operator.go
server/schedule/operator_controller.go
server/schedule/operator_controller_test.go
server/schedule/region_scatterer.go
server/schedulers/scheduler_test.go

cherry-pick #1554
This PR introduces two more steps named AddLightLearner and AddLightPeer respectively to solve this problem.
Tests 
- Unit test

schedule: add light peer without considering the influence (#1554)

---

tools/pd-ctl/README.md
tools/pd-ctl/main.go
tools/pd-ctl/pdctl/ctl.go

solve issue [1518](https://github.com/pingcap/pd/issues/1518)
`./pd-ctl` to use detached mode by default
`./pd-ctl -i` to use interactive mode
modify the flag parameter
Tests 
- No code
Code changes
Side effects

set detached as default mode for pd-ctl

---

Makefile

Improve the `Makefile` to build binaries separately. The most time we want to build is the `pd-server` when in a modify-test-modify workflow.
* `make` keeps the original behavior
* `make pd-server` builds the pd-server only
* `make pd-ctl` builds the pd-ctl only
* `make pd-tso-bench` builds the pd-tso-bench only
* `make pd-recover` builds the pd-recover only
Tests 

makefile: add the capability to build binarys separately

---

server/api/redirector.go
server/api/util.go
server/server.go
server/util.go
tools/pd-ctl/pdctl/command/global.go

To solve the problem like #1569, we add a timeout for the HTTP client in #1515, but it still needs to spend a long time to wait for the goroutine to exit.
This PR uses clients with a different timeout respectively for `server`, `api` and `pd-ctl`. And it changes the timeout of the client in `server` to 3 seconds.
Tests 
- Unit test

server: use a different timeout for http clients

---

server/api/redirector.go
server/api/util.go
server/server.go
server/util.go
tools/pd-ctl/pdctl/command/global.go

cherry-pick #1574.
This PR uses clients with a different timeout respectively for `server`, `api` and `pd-ctl`. And it changes the timeout of the client in `server` to 3 seconds.
Tests 
- Unit test

server: use a different timeout for http clients (#1574)

---

conf/config.toml
server/config.go
server/config_test.go

Now, the undefined config item will let PD exit. This makes the new configuration item incompatible with the old configuration template.
Only log it with `warn` level.
Tests 

config: warn undefined config item

---

conf/config.toml
server/api/label_test.go
server/api/server_test.go
server/api/store_test.go
server/cluster.go
server/cluster_info.go
server/config.go
server/config_test.go
server/option.go
server/schedule/mockcluster.go
server/schedule/opts.go

cherry pick some PRs to 3.0.
cherry pick
Tests 
- Unit test

*: some picks to 3.0

---

tests/pdctl/config/config_test.go
tools/pd-ctl/README.md
tools/pd-ctl/pdctl/command/config_command.go

[#1580](https://github.com/pingcap/pd/issues/1580)  `pd-ctl config show` command add replication config
get data from api `pd/api/v1/config` to get schedule and replicate config
Tests 
- Unit test

pdctl: config show command add replication config

---

server/cluster_info.go
server/coordinator_test.go
server/core/basic_cluster.go
server/core/store.go
server/core/store_option.go
server/schedule/operator_controller.go
server/schedule/scheduler.go

There are some cases which will cause the PD cannot generate operator since the store could be always overloaded and be filtered in the end.
This PR fixes this problem by removing reset logic.
Tests 
- Unit test

schedule: fix store maybe always overloaded

---

conf/config.toml
pkg/mock/mockoption/mockoption.go
server/api/store.go
server/api/trend_test.go
server/config.go
server/coordinator_test.go
server/schedule/operator_controller.go
tests/pdctl/operator/operator_test.go

The previous `store-balance-rate` is a little bit hard to understand.
This PR changes the meaning of `store-balance-rate` which means the max number of balance operators related to `AddPeer` and `AddLearner` per minute.
Tests 
- Unit test
Code changes

schedule: adjust store balance rate meaning

---

server/util.go
server/util_test.go

Closes #1588
tolerate backslash in the label name.
relax the rules to check the validation of a label.
Tests 
- Unit test

feature(label): tolerate backslash in the label name

---

server/config.go

./bin/pd-ctl config set enable-two-way-merge true
Failed to set config: [500] "json: cannot unmarshal string into Go struct field ScheduleConfig.enable-two-way-merge of type bool"
support it
Tests 
- Unit test
- Manual test 
I do manual test and set sucess.

config: fix cannot set `two-way-merge` via pdctl

---

server/api/etcd_api_test.go
server/api/util.go
server/config.go

After upgrade the `etcd`, the [gRPC gateway](https://github.com/etcd-io/etcd/blob/master/Documentation/dev-guide/api_grpc_gateway.md) does not enable in default(https://github.com/etcd-io/etcd/pull/10392). Our `tidb-ctl` use it. Now, add a config to enable it.
add a configurable item.
Tests 
- Unit test

config: add a option about gRPC gateway

---

server/statistics/store_collection.go

Fix the metrics.
add the missing items.
Tests 
- Unit test

statistics: add the missing schedule config items

---

Makefile

add `gcflags` support
support to specify the go compile flags (see `go tool compile --help`)
```
make GCFLAGS='your flags here'
```
For example: build the pd-server without the optimization and inline
```
make GCFLAGS='-N -l'
```
This is useful when you want to debug pd-server with `dlv`.
Tests 

feat(Makefile): support gcflags

---

CHANGELOG.md
server/api/etcd_api_test.go
server/api/util.go
server/config.go
server/schedulers/balance_test.go
server/schedulers/hot_region.go
server/statistics/store_collection.go

cherry pick some fixes.
+ Fix the issue about the limit of the hot region [#1552](https://github.com/pingcap/pd/pull/1552)
+ Add a option about grpc gateway [#1596](https://github.com/pingcap/pd/pull/1596)
+ Add the missing schedule config items [#1601](https://github.com/pingcap/pd/pull/1601)
Tests 
- Unit test

some fixes to release 3.0

---

server/schedule/selector.go

The comment is wrong, so fix it.
Fix the comment.

schedule: keep the comment consistent with codes

---

server/checker/merge_checker_test.go
server/cluster.go
server/schedule/operator.go
server/schedule/operator_test.go
server/statistics/store.go

Currently, the store limit may influence the speed of merge. And some users hope to merge the region very fast.
This PR eases this restriction by replacing `AddLearner` and `AddPeer` with `AddLightLearner` and `AddLightPeer` respectively. The behavior is just like before we introduce store limit.
**Update:**
**We still use `AddLearner` and `AddPeer`, but set the influence according to the region size.**
Tests 
- Unit test

schedule: set influence according to region size

---

server/schedulers/hot_region.go
server/schedulers/scheduler_test.go
server/schedulers/utils.go
server/schedulers/utils_test.go

We don't check the number of replicas when scheduling the hot region.
This PR improves it by checking if it is lack of replicas or has learner peer, just like the balance region does.
Tests 
- Unit test

scheduler: check replica for hot region 

---

server/cluster_info.go
server/core/basic_cluster.go
server/core/region.go
server/core/region_option.go
server/schedule/filters.go
server/schedule/scheduler.go
server/schedulers/balance_region.go
server/schedulers/balance_test.go

`balance region` not select a source store with many pending peers is unreasonable：
- `pending peers` means the log may not catch up with the leader, the most case is the disk busy than another store. move the peer to idle another store more reasonable.
- If not select the store as a source store, the pending peers may be more and more.
- Do not filter the source store
- Priority to select a pending peer to balance.
Tests 
- Unit test

schedulers: balance region consider pending peer

---

client/client.go
client/metrics.go

The "PD TSO WAIT DURATION" here is very confusing:
I'd like to change this to a real **wait** duration, that is, we wait on the channel to return the result.
The meaning of this metric is that we **wait** for a tso future, maybe that time is quite small if the **wait** doesn't really happen.
Tests 
Side effects
PTAL @disksing @jackysp

client: modify the tso_wait_duration metric

---

CHANGELOG.md
conf/config.toml
pkg/mock/mockoption/mockoption.go
server/cluster.go
server/cluster_info.go
server/config.go
server/core/basic_cluster.go
server/core/region.go
server/core/region_option.go
server/schedule/filters.go
server/schedule/merge_checker_test.go
server/schedule/operator.go
server/schedule/operator_test.go
server/schedule/scheduler.go
server/schedulers/balance_region.go
server/schedulers/balance_test.go
server/schedulers/hot_region.go
server/schedulers/scheduler_test.go
server/schedulers/utils.go
server/schedulers/utils_test.go
server/statistics/store.go

cherry-pick
Tests 
- Unit test

*: some fixes for release 3.0

---

server/api/redirector_test.go

There is a certain probability that the redirector test may be failed because there is a gap between two requests.
This PR removes the `Date` comparison between two requests. It will make our CI more stable.
Tests 
- Unit test

api: stabilize redirector test

---

server/schedule/waiting_operator.go
server/schedule/waiting_operator_test.go

Currently, we only take `merge-region` into consideration. But `random-merge` and `admin-merge-region` also need to be considered.
This PR uses `Kind()` instead of `Desc()` to decide if we need to get another operator.
Tests 
- Unit test

schedule: fix merge related operators in waiting operators

---

server/checker/merge_checker.go
server/cluster_info.go
server/cluster_worker.go
server/core/region.go
server/core/region_test.go
server/core/region_tree.go
tools/regions-dump/main.go

When printing the log, the region meta key is not in hex format in many places. e.g.
```
[2019/07/10 08:36:24.581 +00:00] [INFO] [cluster_worker.go:207] ["region batch split, generate new regions"] [region-id=48898216] [origin="[{\"id\":48904284,\"start_key\":\"NzQ4MDAwMDAwMDAwMDAwNUZGMTc1RjcyODAwMDAwMDAwMEZGNDZDOUE1MDAwMDAwMDAwMEZB\",\"end_key\":\"NzQ4MDAwMDAwMDAwMDAwNUZGMTc1RjcyODAwMDAwMDAwMEZGNDhFQUE4MDAwMDAwMDAwMEZB\",\"region_epoch\":{\"conf_ver\":74,\"version\":1332},\"peers\":[{\"id\":48904285,\"store_id\":1723600},{\"id\":48904286,\"store_id\":14},{\"id\":48904287,\"store_id\":12}]}]"] [total=1]
```
After this PR:
```
[2019/07/10 12:03:30.051 +00:00] [INFO] [cluster_worker.go:205] ["region batch split, generate new regions"] [region-id=179169] [origin="id:179249 …
```

core: use hex format for region meta key

---

CHANGELOG.md
server/cluster_info.go
server/cluster_worker.go
server/core/region.go
server/core/region_test.go
server/core/region_tree.go
server/schedule/merge_checker.go

cherry-pick #1627.
Tests 
- Unit test

core: use hex format for region meta key (#1627)

---

server/schedule/range_cluster.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/metrics.go
server/schedulers/scatter_range.go

There are some mistakes created by the previous PR which causes the scatter range scheduler cannot work.
This PR fixes it to make it work like before.
Tests 
- Unit test

schedule: fix scatter range

---

circle.yml
server/checker/replica_checker.go

The pending peer state should have the same logic as the snapshot. 
This PR creates `PendingPeerCountFilter` when calling `NewReplicaChecker`.
Tests 
- Unit test

checker: fix replica checker filter

---

cmd/pd-server/main.go
server/join/join.go
server/join/join_test.go
tests/cluster.go
tests/server/join/join_fail/join_fail_test.go
tests/server/join/join_test.go

Part of modularizing PD. It should be reviewed after #1657 is merged.
This PR uses an individual package for `join`.
Tests 
- Unit test

server: use an individual package for join

---

Makefile
tools/pd-simulator/main.go
tools/pd-simulator/simulator/raft.go
tools/pd-simulator/simulator/simutil/key.go
tools/pd-simulator/simulator/simutil/key_test.go

We have some unrelated code, like `generateTableKeys ` in `raft.go`.
This PR moves the generator key into `simutil`, which can be more clear and improve the coverage.
Tests 
- Unit test

simulator: move generate key to simutil

---

server/schedule/operator/operator.go
server/schedule/operator/operator_test.go

Currently, the priority of the operator whose kind is `opAdmin` is normal. But the high priority is much suitable for this kind of operators.
This PR changes the priority of this kind of operators to high.
Tests 
- Unit test
- Need to cherry-pick to the release branch (Maybe)

operator: use high priority for admin operators

---

tools/pd-ctl/pdctl/command/global.go

Some pd-ctl commands do not have any output.
Show "Success!" like other commands.
Tests 
- Unit test

pdctl: add success response (#1600)

---

server/grpc_service.go
tests/server/api_test.go
tests/server/region_syncer/region_syncer_test.go

`TestReconnect` and `TestRegionSync` cannot pass.
When the server is not started, serving tso request returns 'cluster id not match', which is incorrect:
```
[error="rpc error: code = FailedPrecondition desc = mismatch cluster id, need 0 but got 6727122697637626582"]
```
- enlarge sleep time, Fix #1693
- fix wrong status code in `TestReconnect`
- check if server is started when handling tso 
Tests 
- Unit test

test: fix tests

---

cmd/pd-server/main.go
server/config/config.go
server/util.go

add `config-check` for pd-server, we can use it to check the config file before to start pd . 
tidb-ansible plans to use this to check config before upgrading cluster. 
related issue:  https://github.com/pingcap/tidb-ansible/issues/903
If we set `--config-check=true`, pd will exit after parsing config. 
```
./bin/pd-server --config=./conf/config.toml  --config-check
```

add config-check flag for pd-server

---

server/cluster_worker.go
server/coordinator.go
server/coordinator_test.go
server/operator_queue.go

cherry pick actively push operator
=

 schedule: actively push operator (#1536)

---

client/client.go
client/client_test.go
go.mod
go.sum
pkg/mock/mockcluster/mockcluster.go
server/api/region.go
server/api/router.go
server/cluster.go
server/coordinator.go
server/core/basic_cluster.go
server/core/region.go
server/grpc_service.go
server/schedule/range_cluster.go
server/schedulers/adjacent_region.go
server/statistics/region.go
tools/pd-ctl/pdctl/command/global.go

Fix #1699
~~Wait for https://github.com/pingcap/kvproto/pull/447~~
- grpc API support setting endKey
- merge scan by limit and scan by endkey implementations
Backward compatibility is reserved.
Tests 
- Unit test

*: support setting endKey for ScanRange

---

server/core/store.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go

It does tiny clean up for the code.
This PR reduces some unnecessary parameters.
Tests 
- Unit test

*: reduce some unnecessary parameters

---

server/cluster.go
server/grpc_service.go

When using scatter region, there is a probability that the PD will hang due to the dead lock problem.
This PR fixes this problem by removing defer and also clean up locks in grpc_service.go
Fix https://github.com/pingcap/pd/issues/1707
Tests 
- Unit test

server: fix the dead lock in scatter region

---

server/api/api.raml
server/api/router.go
server/api/store.go
server/cluster.go
server/cluster_info.go
server/core/kv.go
server/core/store.go
server/schedule/basic_cluster.go
tools/pd-ctl/pdctl/command/store_command.go
tools/pd-ctl/pdctl/ctl.go

cherry-pick #1472.
Tests 
- Unit test
Code changes

*: add a API to clear tombstone store  (#1472)

---

tests/pdctl/config/config_test.go
tools/pd-ctl/pdctl/command/config_command.go
tools/pd-ctl/pdctl/command/global.go

When the status of the response is not OK, it should return an error. Closes #1681. 
After this PR:
```
$ ./pd-ctl -u http://127.0.0.1:2379 -i
>> config set namespace ts1 leader-schedule-limit 10
Failed to set namespace: ts1 error: [404] "invalid namespace Name ts1, not found"
```
Tests 
- Unit test

tools: fix set namespace in pd-ctl

---

tests/pdctl/cluster/cluster_test.go
tools/pd-ctl/pdctl/command/global.go

After #1629, we cannot use the address like `127.0.0.1:2379` in `pd-ctl`.
This PR fixes this problem by checking if it has `//` in the address. It should be merged after #1701 is merged.
Tests 
- Unit test

tools: fix parse url without http prefix

---

.gitignore
Makefile
pkg/cache/cache.go
scripts/retool-install.sh
tools.json

We have a lot of lock-related problems, such as #1340, #1370, #1678.
This PR uses `go-deadlock` to replace the `sync` package when running our tests in order to find some potential deadlock problems.
Tests 
- Unit test

tests: support deadlock detection in make test

---

server/checker/merge_checker.go
server/checker/merge_checker_test.go

The `target` argument passed to `checkTarget` is always `nil`, so `next` and `prev` are never compared.
Make it right and clear and add test.
Tests 
- Unit test

checker: fix the issue that a region does not merge to the sibling with smaller size 

---

server/schedule/operator/operator.go
server/schedule/operator_controller.go
server/schedule/operator_controller_test.go

There is a bug introduced by #1652, in some case, like adding peers or adding learners, the step is left unfinished if the peer is in pending state, although the conf version has changed, in these cases, the  operator will be removed because the controller thought someone has  changed the conf version(in fact, it self did). We fix that by checking if the conf version has actually changed by current step, if it is, the operator is not regarded as stale.
Only check conf version changes when a new step to be executed.
Tests 
- Unit test

scheduler: do not remove the operator when the step does not finish

---

server/schedule/operator/operator.go
server/schedule/operator_controller_test.go

Fix a bug, `AddLearner` should be always config changed in the check. 
adjust the check logic.
Tests 
- Unit test

operator: fix the AddLearner config version judgment

---

tests/pdctl/cluster/cluster_test.go
tools/pd-ctl/pdctl/ctl.go

For now, pd-ctl cannot work when enable the TLS option.
This PR fixes this problem by adding `ParseFlags` back.
Tests 
- Unit test

tools: fix TLS in pd control

---

client/client.go
pkg/grpcutil/grpcutil.go
server/region_syncer/client.go
server/region_syncer/server.go

Currently, the region syncer establish the connection by using `WithInsecure()` which doesn't use TLS. Closes #1682.
This PR adds TLS support for the region syncer.
Tests 
- Manual test

syncer: support TLS for region syncer

---

server/checker/merge_checker_test.go
server/cluster.go
server/coordinator_test.go
server/handler.go
server/schedule/operator_controller.go
server/schedule/operator_controller_test.go

1. There is a thread-safe bug which may remove operators unexpectedly, see issue #1716.
2. There is a suspicious code in `pollNeedDispathOperator`: when the region of an operator is disappeared, it is ignored. The code to handle this problem is in `RaftCluster.checkOperator`, which is far away from the problem.
1. This PR use the second possible solution mentioned in the issue: check operator is the same before `delete`.
2. Moved the logic in `RaftCluster.checkOperator` to `pollNeedDispathOperator`, and removed some useless functions.
Tests 
- Unit test

schedule: fix a thread-safe bug and improve code

---

pkg/mock/mockcluster/mockcluster.go
server/core/region.go
server/core/region_option.go
server/schedulers/balance_test.go
server/schedulers/scheduler_test.go
server/statistics/hot_cache.go

Region flow statistics would be inaccurate when transfer leader occurs.
Use time interval reported from region heartbeat to calculate flow.
Tests 
- Manual test

statistics: fix region flow calculation

---

Makefile
tools/pd-analysis/analysis/transfer_region_counter_test.go
tools/pd-simulator/simulator/cases/redundant_balance_region.go

`deadlock-enable` and `deadlock-disable` in Makefile is too slow.
The reason is that `goimports` is slow, and the origin script do this on every `*.go` files. The new script did three changes:
* replace `Mutex` and `RWMutex` in one command
* filter out unchanged files before calling `goimports` (the main improve)
* call `goimports` once with all changed files
Tests 
- No code

makefile: improve deadlock-enable/disable

---

server/api/region.go
server/api/region_test.go
server/core/region_option.go

Fix https://github.com/pingcap/pd/issues/1737.
written keys and read keys is missing.
fix api
Tests 
- Unit test

api: fix missing keys statistic in region information

---

client/client_test.go
pkg/etcdutil/etcdutil_test.go
server/cluster_test.go
server/cluster_worker_test.go
server/coordinator_test.go
server/join/join_test.go
server/server_test.go
tests/server/id/id_test.go
tests/server/join/join_fail/join_fail_test.go
tests/server/join/join_test.go
tests/server/member/member_test.go
tests/server/region_syncer/region_syncer_test.go
tests/server/server_test.go
tests/server/tso/tso_test.go
tests/server/watch/leader_watch_test.go

Currently, after running the test, it will leave a lot of testing directories in temp directories according to the different OS. If there are some people running the tests in the same machine with different users. It may encounter privileges problems.
No matter the test is failed or not, this PR tries to clean up these testing directories after the tests have existed.
Tests 
- Unit test

*: clean temp dir after testing

---

server/cluster.go
server/cluster_test.go
server/metrics.go

For https://github.com/pingcap/pd/issues/1721,  the flow changed but do not update the cache now. Sometimes we need the information to analyze the cluster workload, change the behavior for that. 
Tests 
- Unit test

cluster: update the region cache when flow changed

---

server/checker/metrics.go
server/checker/replica_checker.go
server/cluster.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/random_merge.go
server/schedulers/shuffle_region.go
server/statistics/store_collection.go

At present, it's hard to know the process status of making replicas for offline or down stores. We might not know why the operator is failed to be created.
This PR adds a new metrics named `processStatusCounter` to record the failure reason when creating the operator for the offline or down store. Also, this PR renames some labels to make them more clear.
Pros and cons:
Pros: 
1. We can know why the operator cannot be created and the kind of failure reasons.
2. After #1746, once we encounter "no-store", we can directly find some information from filter metrics.
Cons:
1. It records some duplicated information with `checkerCounter`.
**UPDATE:
According to the comments, reuse `checkerCounter`.**
Tests 
- Unit test

*: improve more metrics

---

tests/pdctl/cluster/cluster_test.go
tests/pdctl/helper.go
tests/pdctl/operator/operator_test.go
tests/pdctl/region/region_test.go
tests/pdctl/scheduler/scheduler_test.go
tools/pd-ctl/pdctl/command/operator.go
tools/pd-ctl/pdctl/command/scheduler.go

Repair echo .
Before:
```
» schedule add label-scheduler
Success!
» schedule remove label-scheduler
» 
```
After:
```
» schedule add label-scheduler
Success!
» schedule remove label-scheduler
Success!
» 
```
Tests 
- Unit test

Fix pd-ctl echo output 

---

go.sum
server/api/version_test.go
server/cluster_test.go
server/server.go

Before executing `startEtcd`, if we send an HTTP request, e.g. `curl http://127.0.0.1:2379/pd/api/v1/version`. It will panic due to the nil pointer problem. See #1764.
This PR fixes this problem by using an empty struct.
Tests 
- Unit test

server: fix panic caused by GetLeader

---

pkg/mock/mockoption/mockoption.go
server/checker/merge_checker.go
server/cluster.go
server/config/config.go
server/config/option.go
server/schedule/opt/opts.go
server/schedulers/random_merge.go
tools/pd-ctl/README.md

Region merge left into right in https://github.com/pingcap/pd/pull/1564.
But [the description](https://github.com/pingcap/pd/tree/master/tools/pd-ctl) in this document is the opposite 
>  "This means a Region can only be merged into left."
Fix document and add more comment.
Otherwise, replace `GetEnableOneWayMerge` with `IsOneWayMergeEnabled` and refactor to make it easier to understanding.
Tests 
- Unit test

Fix merge region doc and refactor

---

go.mod
go.sum
pkg/typeutil/size.go
pkg/typeutil/size_test.go
server/api/store_test.go

user report the storage used about `80GB` data but available do not change, like:
improve the precision, default `.4f`.
Tests 
- Unit test

util: imporve the precision of human size

---

pkg/btree/btree.go
revive.toml

Closes #1769.
This PR keeps the original btree implementation and omits the warnings by adding two rules.
Tests 
- No code

pkg: omit the btree warnings

---

tests/pdctl/cluster/cluster_test.go
tests/pdctl/helper.go
tests/pdctl/operator/operator_test.go
tests/pdctl/region/region_test.go
tests/pdctl/scheduler/scheduler_test.go
tools/pd-ctl/main.go
tools/pd-ctl/pdctl/command/global.go
tools/pd-ctl/pdctl/command/operator.go
tools/pd-ctl/pdctl/command/scheduler.go

cherry-pick #1765 #1763 
Tests 
- Unit test

pd-ctl: fix output (#1765) (#1763) (cherry pick to release-3.1)

---

server/coordinator.go
server/schedulers/hot_region.go
server/schedulers/utils.go
server/schedulers/utils_test.go

Improves current store-load-based scheduler
* Selects src/dest store by each store's overall score
* Limits the rate of scheduling transfer leader operation by associating each operation to its region
* Enables scheduling transfer leader for hot region (write hotspot) to avoid high CPU overhead when there are too many leaders of hot region in some stores
* Uses stddev/average to measure the difference of store load

[new-hotspot-scheduler] schedulers: improve store-load-based scheduler

---

.gitignore
server/api/redirector.go

cherry-pick #1740 
Tests 
- Unit test

api: fix TLS when redirecting the request (#1740)

---

server/coordinator_test.go

repair test failed in TestStoreOverloaded and TestStoreOverloadedWithReplace with deadlock-enable.
Tests 
- Unit test

test: repair test

---

server/cluster.go
server/core/basic_cluster.go
server/core/store.go
server/core/store_option.go
server/schedule/checker/replica_checker.go
server/schedule/filter/filters.go
server/schedule/operator_controller.go

The `overloadFilter` checks if a store has exceeded the store limitation, the word `overload` is too general to describe the feature, so I use `storeLimitFilter` instead.
* Rename `overloadFilter` to `storeLimitFilter`
* Change method `IsOverloaded` to `IsAvailable`
Tests 
- Unit test

Rename overloadFilter to storeLimitFilter

---

server/cluster.go
server/schedule/operator_controller.go
tests/pdctl/store/store_test.go

If we firstly use `stores remove-tombstone` and then calling `stores show limit` in `pd-ctl`. It will panic due to the nil pointer.
This PR fixes it by removing the store limit when removing a tombstone store.
Tests 
- Unit test

tools: fix panic when using stores show limit

---

server/cluster.go
server/cluster_test.go
server/core/basic_cluster.go
server/core/region.go
server/core/region_storage.go
server/core/region_test.go
server/core/region_tree.go
server/core/region_tree_test.go
server/core/storage.go
server/core/test_util.go
tests/server/region_syncer/region_syncer_test.go
tools/pd-simulator/simulator/cases/import_data.go
tools/pd-simulator/simulator/raft.go

This PR is mainly for supporting range for schedulers.
This PR changes the region map to region tree and supports random selection according to a given range.
Tests 
- Unit test
Side effects

core: support range for random selection

---

server/schedule/checker/replica_checker.go
server/schedule/checker/replica_checker_test.go
server/schedule/operator/operator.go

See #1720.
This PR adds `CreateOfflinePeerOperator` to accelerate the offline speed.
Tests 
- Unit test

checker: transfer leader first when offline a store

---

server/core/region_tree_test.go

The current random region related tests are not stable enough. We have met some failures due to the `checkRandomRegion`
This PR enlarges the loop count to reduce the possibility of failure.
Tests 
- Unit test (manually run 1000 times)

*: make random region tests more stable

---

server/core/region.go
server/core/region_test.go

As `regionTree` supports random method now. We don't need the ids to support random selection.
Remove `regionMap.ids`.
Tests 
- Unit test

core: cleanup regionMap

---

client/client.go

when some endpoint passing into the client is unavailable
in calling NewClient() will log the error log, but the service is
supported to be still available if one of the endpoints can work.
error level log will be too serious and confuse the user.
client.go: Degrade log level when passing unavailable endpoint to client
Tests 
log after this pr:
```
[2019/10/28 18:51:04.975 +08:00] [INFO] [client.go:144] ["[pd] create pd client with endpoints"] [pd-address="[localhost:9999,localhost:2379]"]
[2019/10/28 18:51:04.987 +08:00] [WARN] [client.go:200] ["[pd] failed to get cluster id"] [url=http://localhost:9999] [error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = …
```

client.go: Degrade log level when passing unavailable endpoint to client

---

server/grpc_service.go

To make clear about whether the server is slow or the network is slow when getting timestamps.
This PR will print a log when the cost time of getting timestamps is more than one second.
Tests 
- Unit test

*: add a log when getting timestamps are too slow

---

go.mod
go.sum
server/cluster.go
server/core/store_option.go

The TiKV uses `status_address` to provide HTTP service for external components. But the original store metadata does not contain the `status_address` and `git_hash` information, so the TiDB cannot get the `status_address` from PD via `GetAllStores` gRPC interface. Furthermore, TiDB cannot use the HTTP service provided by TiKV.
This PR adds the support that reports the status_address and git_hash to PD on TiKV startup to make subsequent work easier.
Related change: 
- https://github.com/pingcap/kvproto/pull/481
- https://github.com/tikv/tikv/pull/5760

server: merge status_address/git_hash fields of store meta

---

server/cluster.go
server/cluster_test.go
server/core/basic_cluster.go
server/core/region.go
server/core/region_test.go
server/schedule/range_cluster.go
tools/pd-simulator/simulator/drive.go
tools/pd-simulator/simulator/raft.go

In the `placement rules` implementation, the `RegionOption` which passed to `RandXxxRegion` needs to call `cluster.GetStores()`. It meets deadlock problem because it first needs lock `BasicCluster` before get into `regions.RandXxxRegion`.
Check `RegionOption` in `BasicCluster`. The procedure is:
1. Lock `BasicCluster`
2. Get 10 random regions without check `RegionOption`.
3. Release Lock.
4. Check `RegionOption` (during the check it may require Lock again)
Tests 
- Unit test

core: refactor random region

---

server/cluster.go

If cluster is not deployed with grafana, user cannot know there are stores have not enough space.
Add warning log.
/cc @solotzg 
Tests 
set capacity to a small value then insert some data. Check PD's log:
```
[2019/11/01 13:14:51.041 +08:00] [WARN] [cluster.go:321] ["store does not have enough disk space"] [store-id=1] [capacity=104857600] [available=0]
```

server: add low space warning

---

server/api/redirector.go
server/api/redirector_test.go

Some requests should be handled locally instead of redirecting to the leader (e.g: retrieve hardware information from the PD node)
Add HTTP header to allow the follower handle requests locally.
Tests 
- Unit test
Code changes
Side effects

server/api: add HTTP header to allow follower handle requests

---

server/statistics/hot_peer_cache.go

The previous refactor PR #1750 accidentally removed the change of calculating region flow in PR #1688.
Fix it and made some upgrade:
PR #1688 only use the report interval to improve the flow rates.
This PR also use report interval to denoise.
Tests 
- Unit test

statistics: fix refactor

---

server/core/region.go
server/core/region_tree.go
server/core/region_tree_test.go

Fixes #1889.
When the region is not in the tree, we don't need to change the region size and keys.
Tests 
- Unit test

core: fix remove region

---

server/coordinator_test.go

After #1823 is merged, `TestPeerState` is not stable anymore.
This PR prohibits to select other stores as a source store, only store 4 will meet the requirement and create an operator.
edit: This PR makes another test `TestDispatch` more stable by changing the leader count of the store 3.
Tests 
- Unit test

*: make some tests stable

---

client/client.go

cherry-pick #1895 to release-3.1
current pdTimeout(3s) is too small for backup & restore Scenario
so need set timeout outside 
add timeout argument in scanRegions function
Tests 
- Unit test
- No code
Code changes
Side effects

client: add timeout for scanRegions (#1895)

---

server/schedule/operator/operator.go
server/schedule/operator_controller.go
server/schedule/operator_controller_test.go
server/statistics/hot_peer_cache.go

Problem produce:
```
create table x(a int);
split table x between (0) and (1000000) regions 1000;
```
And found many stale operators:
```
[2019/11/04 23:43:33.176 +08:00] [INFO] [operator_controller.go:122] ["stale operator"] [region-id=9422] [takes=24.486979339s] [operator="\"scatter-region {scatter region: stores [1 6 7] to [4 6 7]} (kind:leader,region, region:9422(2019,8), createAt:2019-11-04 23:43:08.689465805 +0800 CST m=+242.334032834, startAt:2019-11-04 23:43:08.689582143 +0800 CST m=+242.334149184, currentStep:2, steps:[add learner peer 10733 on store 4, promote learner peer 10733 on store 4 to voter, transfer leader from store 6 to store 4, remove peer on store 1])\""] [diff=2] [latest="{\"id\":9422,\"start_key\":\"dIAAAAAAAAD/K19ygAAAAAD …
```

schedule: fix the issue that stale operator when scatting regions

---

server/schedule/filters.go
server/schedule/filters_test.go
server/schedule/metrics.go
server/schedule/namespace_checker.go
server/schedule/region_scatterer.go
server/schedule/replica_checker.go
server/schedulers/adjacent_region.go
server/schedulers/balance_leader.go
server/schedulers/balance_region.go
server/schedulers/evict_leader.go
server/schedulers/hot_region.go
server/schedulers/label.go
server/schedulers/metrics.go
server/schedulers/random_merge.go
server/schedulers/shuffle_hot_region.go
server/schedulers/shuffle_leader.go
server/schedulers/shuffle_region.go

cherry-pick #1746 to release-3.0
This PR adds a new dimension named `ActOn` for each filter to indicate that each scheduler or checker is affected by the kind of the filter.
Also this PR removes two unused filters: `disconnectFilter` and `rejectLeaderFilter `
Tests 
- Unit test

schedule: add more dimension for filter metrics (#1746)

---

server/schedulers/hot_region.go
server/schedulers/hot_test.go

Fix https://github.com/pingcap/pd/issues/1901
- Consider limits when deciding `byPeer` or `byLeader`
- Disable leader limit in test 
Tests 
- Unit test

schedulers: make testHotWriteRegionSchedulerSuite stable

---

server/api/version_test.go

`TestGetVersion` fails a lot in CI environment.
temporary disable it.

testing: temporary skip TestGetVersion

---

client/client.go
client/client_test.go

If timestamp decrease, the transaction consistency can break
Detects timestamp decreases and returns an error when it happens.
Tests 
- Unit test

client: check timestamp decrease and return error

---

tests/pdctl/operator/operator_test.go
tools/pd-ctl/pdctl/command/global.go
tools/pd-ctl/pdctl/command/region_command.go

#1943 
fix echo and some typo
Tests 
- Unit test

pd-ctl: fix echo when TiKV cluster not bootstrapped

---

server/schedule/checker/replica_checker.go
server/schedule/checker/replica_checker_test.go

Closes #1923.
This PR fixes it by checking if the max replica is 1 before transferring the leader.
Tests 
- Unit test

checker: fix offline when only having one replica

---

pkg/grpcutil/grpcutil.go
server/region_syncer/client.go

PR #1739 accidentally removes the max gRPC receive message size constraint for the client.
This PR fixes it by adding it back.
Tests 
- Unit test

*: fix the max recv message size for the client

---

server/api/router.go

This PR adds profile CPU/memory/mutex/allocs/block/goroutine HTTP API and make profile cluster component via SQL possible. (Part of https://github.com/pingcap/tidb/issues/13567)
Add HTTP API for PD.
Tests 
- No code
Code changes
- Has HTTP API interfaces change (Don't forget to [update API document]

add profile CPU/memory/mutex/allocs/block/goroutine HTTP API

---

pkg/grpcutil/grpcutil.go
server/region_syncer/client.go

cherry-pick #1952 
The previous PR accidentally removes the max gRPC receive message size constraint for the client. This PR fixes it by adding it back.
Tests 
- Unit test

*: fix the max recv message size for the client (#1952)

---

server/api/health.go
server/cluster/cluster.go
tests/cluster.go
tests/pdctl/health/health_test.go

After #1906 is merged. The health API cannot work due to the accidentally check.
This PR fixes it by removing the bootstrap check.
Tests 
- Unit test

cluster: fix the health API problem

---

Makefile
server/api/region.go
server/api/region_test.go
server/api/router.go
server/core/region.go

cherry-pick #1970 to release-3.0
Optimize `convertToAPIRegions` and `h.rd.JSON`
Tests 
- Unit test

Improve the performance of the HTTP API for getting all regions (#1970)

---

client/client.go
client/client_test.go

Fix https://github.com/pingcap/pd/issues/1983
add `NewClientWithContext`
Tests 
- Unit test

client: support create with context

---

.travis.yml
Makefile
server/api/region.go
server/api/region_test.go
server/api/router.go
server/core/region.go

cherry-pick #1970 to release-3.1
Optimize `convertToAPIRegions` and `h.rd.JSON`
Tests 
- Unit test

Improve the performance of the HTTP API for getting all regions (#1970) 

---

client/client.go

Some tools need to access PD's HTTP API but cannot know which PD is current leader.
export `GetLeaderAddr`.
Tests 
- only export exsisted function.

client: export GetLeaderAddr

---

tools/pd-ctl/pdctl/ctl.go

In step c below.
```
bin/pd-ctl -i
config show -h
```
Tips are as follows
```
show replication and schedule config of PD
Usage:
...
```
But enter the following command
```
config show
```
Tips are still as follows
```
show replication and schedule config of PD
Usage:
```
In fact, it should show specific content：
```
{
"replication": {
"EnablePlacementRules": false,
"location-labels": "",
"max-replicas": 3,
"strictly-match-label": "false"
},
...
```
The reason is that in interactive mode the value of --help -h is passed down from the previous command.so I used 'PersistentFlags' to avoid it.
Tests 
Code changes
Side effects

fix bug of args -h in pd-ctl interactive mode

---

server/core/region_tree.go

Fix #1976 
Fix #1913 
log when the keys are really wrong. (startIndex==endIndex can happen when there is simply no region in the range)
Tests 
```
(in server/schedulers) $ go test
```

core: fix misleading wrong keys log

---

server/cache.go
server/cache_test.go

Fix #1980
Update cache and kv when peer list changed.
Tests 
- Unit test

server: update region cache when peer list changed

---

server/statistics/hot_peer.go
server/statistics/hot_peer_cache.go

Close issue #1997 .
Replace `TwoQueueCache` with `TopN`.
Tests 
- Unit test

statistics: use TopN

---

.travis.yml

go mod tidy failed.
lazy install  `goveralls`.
Tests 
- Unit test

test: fix travis ci

---

server/schedule/operator_controller_test.go

There is a probability that the data race may occur after #2015 is merged. It's because the `mock Cluster` doesn't have a lock to prevent the concurrency. Fixes #2030.
This PR fixes it by adding an explicit lock to prevent `RemoveStoreLimit` and `Check` from running at the same time.
Tests 
- Unit test

test: fix the race of TestRemoveTombstone

---

server/schedule/operator_controller.go
server/schedule/operator_controller_test.go

cherry-pick #2015 to release-3.1 branch
This PR fixes the panic problem by resetting the attached function when removing the store limit.
Tests 
- Unit test

schedule: fix panic caused by removing tombstone (#2015)

---

server/cluster_info.go
server/cluster_info_test.go
server/core/basic_cluster.go
server/core/errors.go
server/core/kv.go
server/core/kv_test.go
server/core/region.go
server/core/region_kv.go
server/handler.go
tests/server/region_syncer/region_syncer_test.go

cherry-pick #2022 
cherry-pick.
Tests 
- Unit test

*: fix the issue that loadcluster does not remove overlap regions(#2022)

---

client/client.go
client/client_test.go

we test 
After all 3 instances of PD are killed in AWS(k8s environment), it takes a long time (15 minutes) for TiDB server instances to reconnect to new PD instances. and we found the stale TCP connection after all pod IP is changed. 
```
we see the connection is still establish, and that ip does not exist after kill.
10.0.48.116 is not exist, but the tcp is establisted.
Tue Dec 17 12:54:36 UTC 2019
tcp        0      1 10.0.38.181:53424       172.20.62.78:2379       SYN_SENT    1/tidb-server
tcp        0      0 10.0.38.181:53302       10.0.22.167:2379        ESTABLISHED 1/tidb-server
tcp        0      0 10.0.38.181:53304       10.0.22.167:2379        ESTABLISHED 1/tidb-server
tcp        0      0 10.0.38.181:53300       10.0.22.167:2379 …
```

client: supports to add gRPC dial options

---

client/client.go
client/client_test.go

cherry-pick #2035 
add an option.
Tests 
- Unit test

client: supports to add gRPC dial options (#2035)

---

server/cluster/cluster.go
server/cluster/cluster_test.go
server/core/basic_cluster.go
server/core/storage.go
server/core/storage_test.go
server/region_syncer/client.go
server/region_syncer/server.go
server/server.go
tests/cluster.go
tests/server/cluster/cluster_test.go
tests/server/region_syncer/region_syncer_test.go

PCP #1830 
new feature : PCP: Accelerate the speed of the load region
- add a method of storage.go : LoadRegionsOnce
- in the cluster.go : the calling method changes to when load regions
- in the region_syncer/client.go: When the follower synchronizes the regions, it will first determine whether it has been loaded from storage and will update the cache synchronously for the changed regions
Tests 
- Unit test

PCP: Accelerate the speed of the load region

---

server/cluster/cluster.go
server/handler.go
tests/pdctl/operator/operator_test.go

Some feature cannot work as expected when enable placement rules.
disable them.
Tests 
- Unit test

*: disable transferRegion and offline warning when enable placement rules

---

server/config/config.go
tools/pd-ctl/README.md

when using pd-ctl config show:
before:
```
...
"leader-schedule-strategy": "\"count\"",
...
```
After:
```
...
"leader-schedule-strategy": "count",
...
```
This PR removes the "string" tag for `LeaderScheduleStrategy`.
Tests 
- Manual test

config: tiny fix config item

---

server/server.go

Signed-off-by: disksing <i@disksing.com
Fix https://github.com/pingcap/pd/issues/2069
Check if bootstrapped.
Tests 
when not bootstrapped:
```bash
./bin/pd-ctl config set enable-placement-rules true
Failed to set config: [500] "TiKV cluster not bootstrapped, please start TiKV first"
```

server: fix placement rules panic

---

pkg/mock/mockcluster/mockcluster.go
server/cluster/cluster.go
server/cluster/coordinator_test.go
server/handler.go
server/schedule/checker/replica_checker.go
server/schedule/operator/builder.go
server/schedule/operator/operator.go
server/schedule/opt/opts.go
server/schedule/region_scatterer.go
server/schedulers/adjacent_region.go
server/schedulers/hot_region.go
server/schedulers/shuffle_hot_region.go
server/schedulers/shuffle_region.go

IDs may be wasted because `AllocPeer` is called too early. See https://github.com/pingcap/pd/issues/1924
Now we use `operator.Builder` to create operators. Since it supports [allocating ID automatically](https://github.com/pingcap/pd/blob/ea974c9488b8d304a72916d8cc50962f5ab99c5d/server/schedule/operator/builder.go#L233-L239), we can defer ID allocation to Builder.
- allocate IDs in builder
- change cluster.AllocPeer to cluster.AllocID. (some tests keeps using AllocPeer)
Tests 
- Unit test

server/*: refactor AllocPeer

---

server/schedule/placement/label_constraint.go

[online restore](https://github.com/pingcap/br/pull/114) use label `exclusive` to mark some stores used to import data only.
add exclusive labels
Tests 
- Manual test with online restore

placement: add exclusive label

---

client/base_client.go
client/client.go
client/client_test.go
client/config_client.go
client/metrics.go
server/config_manager/config_manager.go
server/core/storage.go
tests/client/client_test.go
tests/client/config_client_test.go

Part of #1977. It should be reviewed after #2033 is merged.
This PR adds a client for config manager service.
Tests 
- Unit test

*: add config client

---

server/api/operator_test.go
server/api/scheduler.go
server/api/scheduler_test.go
server/api/util.go
server/cluster/cluster_worker.go
server/cluster/coordinator.go

Fixes pingcap/tidb-ansible#1052.
This PR makes the output of removing a nonexistent scheduler be consistent with the original API.
Tests 
- Manual test
before:
```
>> curl -X DELETE http://127.0.0.1:2379/pd/api/v1/schedulers/evict-leader-scheduler-1
null
```
after:
```
>> curl -X DELETE http://127.0.0.1:2379/pd/api/v1/schedulers/evict-leader-scheduler-1
"scheduler not found"
```

api: fix remove scheduler output

---

server/config/config.go

tiflash use v2 API.
enable v2 API.
Tests 
- Unit test

config: enable etcd api v2

---

server/api/config.go
tests/pdctl/config/config_test.go

run `pd-ctl config set enable-placement-rules true` twice, it reports `config item not found`
My previous fix (https://github.com/pingcap/pd/pull/1960) has a bug: it use json tag to check if the config item exists, while the json tag can be declared as `foobar,string`, we need trim tailing `,string`.
Tests 
- Unit test

api: fix the problem that enable-placement-rules cannot be set twice

---

server/api/region.go
server/api/region_test.go
server/cluster_info.go
server/cluster_info_test.go
server/core/region.go
server/core/region_option.go
server/metrics.go

Signed-off-by: hundundm <hundundm@gmail.com>
cherry-pick #1759 #1741 and part of #1641 
Tests 
- Unit test

cluster: update the region cache when flow changed (#1759) (#1741) (#1641)

---

Makefile
pkg/dashboard/uiserver/empty_assets_handler_windows.go

Signed-off-by: hundundm <hundundm@gmail.com>
Cannot compile pd-server in Windows.
Determine the OS in the Makefile. If it is Windows, skip the process of building Dashboard-UI and use empty_assets_handler.go instead.
Tests 
- Just `make` in Windows

dashboard: do not build dashboard-ui on windows

---

tests/server/join/join_test.go

Before #1948 we manually call cancel function to exit `startEtcd`. #1948 changes it by using a timeout. But 5 seconds maybe short for starting etcd which will make the test failed sometimes. Closes #2059. 
This PR enlarges `EtcdStartTimeout` to 10 seconds in order to make test more stable.
Tests 
- Unit test

test: make TestFailedAndDeletedPDJoinsPreviousCluster stable

---

metrics/grafana/pd.json

Added the comparison of region size, store used size, and move peer directions. It will be convenient for experiments on balance region.
Since #2087 has been merged, so the [pr](https://github.com/pingcap/tidb-ansible/pull/1097) in tidb-ansible is closed.
Tests 
- Unit test

Add metrics for balance region schedulers

---

Dockerfile

Docker build failed:
```
...
Step 11/17 : RUN make
---> Running in 355e290172b1
./scripts/embed-dashboard-ui.sh
env: can't execute 'bash': No such file or directory
make: *** [Makefile:68: pd-server] Error 127
The command '/bin/sh -c make' returned a non-zero code: 2
```
Add bash in Dockerfile.
Tests 
- Manual test (add detailed scripts or steps below): `docker build -t pd:test .`

build: fix ci build

---

go.mod
go.sum
server/api/router.go
server/api/status.go
server/cluster/cluster.go
server/core/store_option.go
server/server.go

This PR is used to partial implement the https://github.com/pingcap/tidb/issues/14707, which aim to show cluster components `START_TIME` and `UPTIME`
Add a `start_timestamp` for PD `/status` HTTP API and save the `start_timestamp` of TiKV.
Tests 
- Unit test
```
mysql> select * from cluster_info;
+------+-----------------+-----------------+----------------------------------------------+------------------------------------------+---------------------------+-----------------+
| TYPE | INSTANCE        | STATUS_ADDRESS  | VERSION                                      | GIT_HASH                                 | START_TIME                | UPTIME          | …
```

server: add start_timestamp for cluster components

---

server/api/config.go
server/api/config_test.go
server/api/label_test.go
server/api/log.go
server/api/store_test.go
server/config/config.go
server/grpc_service.go
server/server.go
tests/client/config_client_test.go
tests/server/cluster/cluster_test.go

To keep consistent with other components' naming style.
This PR rename `EnableConfigManager` to `EnableDynamicConfig`
Tests 
- Unit test

config: rename EnableConfigManager to EnableDynamicConfig

---

server/grpc_service.go
server/leader.go
server/lease.go
server/server.go
server/tso.go
tests/server/region_syncer/region_syncer_test.go

pick #1676 
cherry-pick
Tests 

server: use leader lease to determine tso service validity #1676

---

go.mod
go.sum
server/api/member.go
server/member/leader.go
server/server.go

We need to know the deploy path of pd binary for tidb dashboard.
This PR adds binary deploy path for member API
Tests 
- Manual test
Details:
```
➜  ~ curl http://127.0.0.1:2379/pd/api/v1/members
{
"header": {
"cluster_id": 6793225628982604172
},
"members": [
{
"name": "pd2",
"member_id": 5454843464880847909,
"peer_urls": [
"http://127.0.0.1:3380"
],
"client_urls": [
"http://127.0.0.1:3379"
],
"deploy_path": "/path/to/bin"
},
{
"name": "pd1",
"member_id": 13195394291058371180,
"peer_urls": [
"http://127.0.0.1:2380"
],
"client_urls": [
"http://127.0.0.1:2379"
],
"deploy_path": "/path/to/bin"
}
],
"leader": {
"name": "pd1",
"member_id": 13195394291058371180,
"peer_urls": [
"http://127.0.0.1:2380"
],
"client_urls": [
"http://127.0.0.1:2379"
]
},
"etcd_leader": {
"name": "pd1",
"member_id": …
```

api: add deploy path and binary version in member

---

server/schedule/checker/rule_checker.go
server/schedule/checker/rule_checker_test.go

when no more store to replace, it panics:
```
[2020/02/26 11:46:45.244 +08:00] [FATAL] [log.go:294] [panic] [recover="\"invalid memory address or nil pointer dereference\""] [stack="github.com/pingcap/log.Fatal\n\t/home/birdstorm/go/pkg/mod/github.com/pingcap/log@v0.0.0-2020011      7041106-d28c14d3b1cd/global.go:59\ngithub.com/pingcap/pd/v3/pkg/logutil.LogPanic\n\t/home/birdstorm/go/src/github.com/pingcap/pd/pkg/logutil/log.go:294\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:679\nruntime.panicmem\n\t      /usr/local/go/src/runtime/panic.go:199\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:394\ngithub.com/pingcap/kvproto/pkg/metapb.(*Store).GetId\n\t/home/birdstorm/go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-202002130 …
```

checker: fix rule checker panic

---

server/api/status.go
server/api/status_test.go
server/api/version.go

Fix problem
```
curl http://pd-ip:2379/api/v1/version
got:  1.0.0
```
consistent with the release version.
Tests 
- Unit test

api: make  api/version and release version consistent

---

tools/pd-ctl/main.go

Introduced by #2187, which will cause `unknown shorthand flag: 'd' in -d` error when using pipeline.
Since the default mode is `detach`, we don't need to set the `detach` flag.
Tests 
- Manual test 
1. start pd server
2. run `echo "--pd 127.0.0.1:2379 config set region-schedule-limit 1" | /path/to/pd-ctl`

tools: fix pipeline of pd-ctl

---

.gitignore
.golangci.yml
Makefile
scripts/retool-install.sh
tools.json

UCP #2181
Signed-off-by: Poytr1 <pooytr1@gmail.com>
Resolve: https://github.com/pingcap/pd/issues/2181
Currently, golangci-lint is installed in retool, which is not an officially recommended installation method. We need to change to the officially recommended way and add the .golangci.yml configuration file.
- Delete `golangci-lint` in the `retool-install.sh` as well as `tool.json`
- Add a new task in Makefile called `golangci-lint-setup` to download `golangci-lint` binary into *$GOPATH/bin/golangci-lint* as https://github.com/golangci/golangci-lint#install suggests.
- Add a `.golangci.yml` file which has same config with the command line option.
- Update the command to call `golangci-lint` using the new config file.
Tests 
Run `make …

tools: use golangci-lint in the officially recommended way

---

.gitignore
Makefile
server/cluster.go
server/cluster_info.go
server/coordinator.go
server/coordinator_test.go
server/region_statistics.go
server/schedule/hot_cache.go
server/store_statistics.go

cherry-pick #1790 to release-2.1
This PR resets the metrics when the leader steps down.
Tests 
- Manual test

*: reset metrics after the leader steps down (#1790)

---

tests/pdctl/scheduler/scheduler_test.go
tools/pd-ctl/pdctl/command/scheduler.go

Currently, on server side, schedulers can define their own http handlers to read/write configuration. However, pd-ctl side does not reflect the same logical structure. Specifically, it uses fixed `show`, `update`, `delete` sub commands to manipulate configurations.
It seems the better way is to allow schedulers to define their own sub commands
old:
```
scheduler config show evict-leader-scheduler
scheduler config update evict-leader-scheduler 1
scheduler config delete grant-leader-scheduler 2
```
new:
```
scheduler config evict-leader-scheduler
scheduler config evict-leader-scheduler add-store 1
scheduler config grant-leader-scheduler delete-store 2
```
- change command/subcommand structure
- some refactor to eliminate command Use resets
Tests 
- …

pdctl: improve scheduler config commands

---

pkg/dashboard/apiserver/apiserver.go
pkg/dashboard/uiserver/uiserver.go
server/api/server.go
server/server.go
server/server_test.go

Currently, there are different solutions in PD to solve etcd race problem. One of the solutions has the following problem:
After #2204. we enable dynamic config by default. When we use HTTP API, the `lazyHandler` will be called. The handler will call `RegisterConfigHandlerFromEndpoint` which creates a goroutine to handle the stop logic. In this case, once we call API multiple times, goroutines will be leaked.
Removed `lazyHandler` and used a unified solution to solve etcd race problem.
Tests 
- Manual test 
1. start a cluster
2. call API multiple times
3. check `http://127.0.0.1:2379/debug/pprof/goroutine?debug=1` for the number of goroutines

server: unify the solutions to etcd race problem

---

server/core/storage.go
server/schedule/placement/rule.go
server/schedule/placement/rule_manager.go
server/schedule/placement/rule_manager_test.go

cherry-pick #2205 to resolve #2203
- startKey and endKey can be duplicated, use groupID+ID instead
- check data consistency and recover when load rules
Tests 
- Unit test
- insert some rules with same key, make sure it won't be over written
- use old pd to write some rules, then start new pd, the wrong key are recovered
Code changes

placement: use id as store key (#2205)

---

pkg/mock/mockcluster/mockcluster.go
server/schedule/checker/merge_checker.go
server/schedule/checker/merge_checker_test.go
server/schedule/checker_controller.go
server/schedule/operator_controller_test.go
server/schedulers/balance_test.go
server/schedulers/random_merge.go

cherry-pick #2212 to resolve #2210
- port merge checks from mergeChecker to random-merge-scheduler
- minor refactor: remove `mergeChecker.ruleManager` and get it from `cluster`
Tests 
- Unit test

schedulers: add sanity check for random-merge (#2212)

---

server/api/status.go
server/api/status_test.go
server/api/version.go

Fix problem
```
curl http://pd-ip:2379/api/v1/version
got:  1.0.0
```
cherry-pick #2191 
Tests 
- Unit test

api: make  api/version and release version consistent (#2191)

---

server/api/middleware.go
tests/config.go
tests/pdbackup/backup_test.go
tests/pdctl/cluster/cluster_test.go
tests/pdctl/component/component_test.go
tests/pdctl/config/config_test.go
tests/pdctl/health/health_test.go
tests/pdctl/helper.go
tests/pdctl/hot/hot_test.go
tests/pdctl/label/label_test.go
tests/pdctl/log/log_test.go
tests/pdctl/member/member_test.go
tests/pdctl/operator/operator_test.go
tests/pdctl/region/region_test.go
tests/pdctl/scheduler/scheduler_test.go
tests/pdctl/store/store_test.go
tools/pd-ctl/pdctl/command/component_command.go
tools/pd-ctl/pdctl/command/global.go
tools/pd-ctl/pdctl/ctl.go

When using `curl http://127.0.0.1:2379/pd/api/v1/component/127.0.0.1:2379`, it will print results both in `json` and `toml` format.
This PR fixes it. Besides, this PR adds some basic tests for component command of `pd-ctl`
Tests 
- Unit test
- Manual test
1. start a server 
2. run `curl http://127.0.0.1:2379/pd/api/v1/component/127.0.0.1:2379`

config: fix output of GET method of component API

---

pkg/testutil/operator_check.go
server/schedule/selector/selector.go
server/schedulers/scheduler_test.go
server/schedulers/shuffle_region.go
server/schedulers/shuffle_region_config.go
tests/pdctl/scheduler/scheduler_test.go
tools/pd-ctl/pdctl/command/scheduler.go

cherry-pick #2219 to fix https://github.com/pingcap/pd/issues/2177
Add role configuration to shuffle-region-scheduler.
Use it to balance learners:
**1. add shuffle-region-scheduler**
```
pd-ctl scheduler add shuffle-region-scheduler
```
or
```
curl -XPOST -d '{"name": "shuffle-region-scheduler"}' http://pd:2379/pd/api/v1/schedulers
```
**2. config roles**
```
pd-ctl scheduler config shuffle-region-scheduler set-roles learner
```
or
```
curl -XPOST -d '["learner"]'  http://pd:2379/pd/api/v1/scheduler-config/shuffle-region-scheduler/roles
```
Tests 
- Unit test
- Manual test
Code changes
- Need to cherry-pick to …

schedulers: add role config to shuffleRegionScheduler (#2219)

---

server/grpc_service.go
server/server.go
server/util.go
tests/server/cluster/cluster_test.go

Fix #2237
- When placement rules not enabled, don't allow add tiflash node.
- When the cluster has tiFlash nodes, don't allow disable placement rules.
Tests 
- Unit test

server: prevent misoperation when there are tiflash nodes

---

client/config_client.go
client/metrics.go
go.mod
go.sum
server/config_manager/config_manager.go
server/config_manager/config_manager_test.go
server/config_manager/grpc_service.go

Wait for https://github.com/pingcap/kvproto/pull/579.
Add a new method `GetAll` to the config manager to let the `TiDB` get all configs from `PD`.
Tests 
- Unit test

*: add a new method `GetAll` to the config manager

---

server/region_syncer/client.go

When we upgrade the cluster, the leader may be in a low version, which doesn't sync the statistics. In this case, the follower in the high version will panic.
This PR adds if statement to avoid this case.
Tests 
- Unit test

syncer: fix panic problem when upgrading

---

server/config/config.go
server/server.go
tests/pdctl/config/config_test.go
tools/pd-ctl/pdctl/command/config_command.go

after the https://github.com/pingcap/pd/pull/2188
the position of the `scheduler-payload` is changed, which causes the `tidb-operator`  failed to upgrade the cluster. the operator needs to know which store is being offline.
move to the back.
Tests 
- Manual Test

api: fix the compatibility about schedulers item in config

---

conf/config.toml
pkg/grpcutil/grpcutil.go
server/config/config.go

TiDB, TiKV Supports multiple CNs, but we depend on etcd, let the config be consisted firstly.
changed config items.
Tests 
- Manual test

config: let the cert-allowed-cn same with other components

---

server/api/server.go
server/config/config.go
server/config_manager/config_manager.go
server/config_manager/grpc_service.go
server/server.go

We have three switches on tikv, tidb, pd repos to control dynamic config which is noisy.
This PR tries to control the dynamic config only using pd.
Tests 
- Unit test

config: let PD to control the dynamic config

---

tools/pd-ctl/pdctl/ctl.go

UCP: #2259 
Signed-off-by: wq1019 <2013855675@qq.com>
It solves the problem of printing useless global flags when we input wrong arguments in interactive mode.
Some useless global flags messages are hidden in interactive mode.
```
func getInteractCmd(args []string) *cobra.Command {
rootCmd := getBasicCmd()
rootCmd.SetArgs(args)
rootCmd.ParseFlags(args)
rootCmd.SetOutput(os.Stdout)
hiddenFlag(rootCmd)
return rootCmd
}
func hiddenFlag(cmd *cobra.Command) {
err := cmd.Flags().MarkHidden("pd")
if err != nil {
cmd.Printf("Failed to hidden flags: %s\n", err)
}
}
```
```
» region key
Usage:
pd-ctl region key [--format=raw|encode|hex] <key> [flags]
Flags:
--format string   the key format (default "hex")
Global Flags:
-h, --help   Help message.
»  
```
Tests 
- Unit test

remove incorrect help message

---

server/api/router.go
server/config_manager/config_manager.go
tests/pdctl/component/component_test.go
tools/pd-ctl/pdctl/command/component_command.go

UCP: #2229
Signed-off-by: wq1019 <2013855675@qq.com>
@rleungx 
If IDs parameter is empty, all component IDs will be returned.
1. When the IDs parameter is ignored, CTL will automatically assemble the URL into`/component/ids/all`and continue to request.
2. Updated `/component/ids/{component}` API, When the parameter passed in is`all`, all component IDS will be returned.
Tests 
- Unit test

show all component ID when using ids

---

server/statistics/avg_over_time.go
server/statistics/avg_over_time_test.go
server/statistics/store.go
tests/pdctl/hot/hot_test.go

It will denoise and make statistics more stable. Below is a contrast between before and after.
We use average overtime to solve the problem that interval is different.
And add another moving average to filter out high-frequency noise.
Add moving average to make flow statistics more stable.
Tests 
- Unit test

statistic: add moving average for stable hot 

---

server/cluster/cluster.go
server/cluster/coordinator.go
server/schedulers/hot_region.go
server/schedulers/metrics.go
server/schedulers/utils.go
server/statistics/hot_regions_stat.go
server/statistics/store.go
tests/pdctl/hot/hot_test.go

- add some metrics and log to observe hot region scheduling.
- Reduce the frequency of hotspot scheduling.
add metrics.
Tests 
- Unit test
- No code
Code changes
Side effects

schedulers: add some metrics for hotreigon

---

pkg/mock/mockcluster/mockcluster.go
server/schedulers/hot_region.go
server/schedulers/hot_region_config.go
server/schedulers/hot_test.go
server/schedulers/metrics.go
server/schedulers/utils.go

To prevent excessive redundant scheduling
add the avg load as an expectation.
Tests 
- Unit test
- Manual test
the scheduler operator is reduced and QPS is stable.

scheduelrs: add load expectations for hot scheudler

---

server/schedulers/hot_region.go
server/schedulers/hot_test.go

…lanced
In this scenario: 9 tikv, running with a workload  `oltp_insert` (6 tables)
- the count is not suitable for calculating limit because there are many hot regions (index) and only 6 very hot regions (row data)
- there are too many hot regions, so the hot leader may have no chance to be scheduled.
- remove the auto limit
- randomly schedule peer or leader.
Tests 
- Unit test
- Manual test

schedulers/hot: let leader can be schedule even if the peer is not balanced

---

server/server.go

When we start a new cluster, it will update config twice due to the change of `SchedulersPayload`. Besides, since `SetXXXConfig` will call validate inside of the function. We don't need to call it outside.
This PR removes these extra checks. Besides, this PR doesn't persist the value of `SchedulersPayload` which may cause two extra updates when starting a new cluster.
Fix the extra config update when starting a new cluster
Tests 
- Unit test

config: fix the extra config update when starting a new cluster

---

server/config/config.go
server/core/store.go
server/core/store_test.go
server/schedulers/balance_test.go
server/schedulers/scheduler_test.go

We use `low-space-ratio` and `high-space-ratio` to control the calculation of score. But in some cases which the capacity of the store is large enough. These ratios may not reasonable.
This PR adds a fixed size for low and high space threshold to help choose a better value compared with the original way.
Use fixed size and space ratio to decide the space threshold.
Tests 
- Unit test

store: use fixed size and space ratio to decide space threshold

---

tests/pdctl/config/config_test.go
tools/pd-ctl/pdctl/command/config_command.go

Fix https://github.com/pingcap/pd/issues/2285
add commands:
- `pd-ctl config placement-rules enable`, same as `config set enable placement-rules true`
- `pd-ctl config placement-rules disable`, same as `config set enable placement-rules false`
- `pd-ctl config placement-rules show`, show all rules
- `pd-ctl config placement-rules show --group=g1`, show rules in a group
- `pd-ctl config placement-rules show --group=g1 --id=id2`, show a rule
- `pd-ctl config placement-rules show --region=1`, show rules match a region
- `pd-ctl config placement-rules load -out=rules.json`, load all rules to a file
- `pd-ctl config placement-rules save -in=rules.json`, save rules in a file to PD
Tests 
- Unit test
- PR to update `pingcap/docs`/`pingcap/docs-cn`: TBD

pdctl: add placement rules commands

---

server/api/middleware.go
tests/pdctl/component/component_test.go
tools/pd-ctl/pdctl/command/component_command.go

Sometimes, we need to change multi configs at a time, especially for the configs of TiKV.
This PR changes the component subcommand to support accepting multi arguments.
Support changing multi config at a time
Tests 
- Unit test

support change multi config at a time

---

pkg/dashboard/manager.go
server/cluster/cluster.go
server/config/config.go
server/config/option.go
server/server.go
tests/server/cluster/cluster_test.go
tools/pd-ctl/pdctl/command/component_command.go

Since there are some problems in dynamic config, we will disable it by default.
Just as above says.
Disable dynamic configuration change by default
Tests 
- Unit test
Code changes

config: disable dynamic config by default

---

server/schedulers/hot_region.go
server/schedulers/hot_region_config.go
server/schedulers/hot_test.go

After #2297, we introduce hot tolerance. After some tests, we found there need to be more accurate config
This PR split tolerance to two configs, src and dst.
Tests 
- Unit test

schedulers: add src and dst tolerance ratio for hot scheduler

---

server/api/config.go
server/api/middleware.go
server/api/util.go
server/config_manager/config_manager.go
server/server.go

Fixes #2309.
This PR adds some `*Locked` functions to avoid using lock outside of the config manager.
Fix a data race when getting the version from the config manager.
Tests 
- Unit test

config: fix data race in config manager

---

server/schedulers/hot_region.go
server/schedulers/hot_test.go
server/statistics/store.go
tests/pdctl/hot/hot_test.go

Fix the problem that read hotspot scheduling cannot converge well.
- adjust the method of calculate rank process.  (SrcStore consider the peer) 
- adjust the size of the window of reading statistic
Fix the problem that read hotspot scheduling cannot converge well.
Tests 
- Unit test

schedulers: adjust calculate rank process

---

server/cluster/coordinator_test.go

Fix https://github.com/pingcap/pd/issues/1925
we were expecting transfer leader 4->2, but sometimes it got 4->3, the reason is that balance leader scheduler and test code run concurrently. Possible execution sequence:
1. test: `tc.updateLeaderCount(4, 50)` (leader count 1:0, 2:0, 3:0, 4:50)
2. scheduler: sort stores by leader count (order 4, 1, 2, 3)
3. test: continue update leader counts (leader count 1:10, 2:20, 3:50, 4:50)
4. test: put region (leader:4, follower: 2, 3)
5. scheduler: select the region and create balance leader 4->3
how to fix: run coordinator after done all setups
Tests 
- Unit test
add some time.Sleep and test 20000 times.

cluster: fix TestDispatch

---

server/cluster/cluster.go
server/replicate/replicate.go
server/replicate/replicate_test.go

Fix https://github.com/pingcap/pd/issues/2271
- add a background job to check store down and switch states
- add test
Tests 
- Unit test
Code changes

replicate: add state switch

---

go.sum
tests/pdctl/scheduler/scheduler_test.go
tools/pd-ctl/pdctl/command/scheduler.go

Fixes #2320.
This PR changes the path of list command and adds tests for the hot region scheduler.
Fix scheduler config balance-hot-region-scheduler list command in pd-ctl
Tests 
- Unit test

pd-ctl: fix scheduler config balance-hot-region-scheduler list

---

pkg/dashboard/manager.go
server/server.go
tests/server/cluster/cluster_test.go

Due to TestSetScheduleOpt uses `SetStorage` to change the storage, it may cause a race problem. This is because we may call `GetStorage` in other places at the same time. The problem only affects the testing. Fixes #2316 
This PR prevents calling `GetStorage` manually by disabling dynamic config and increasing the check interval of the dashboard.
Tests 
- Unit test

tests: fix data race in TestSetScheduleOpt

---

server/api/scheduler.go
server/api/scheduler_test.go
server/cluster/cluster_worker.go
server/cluster/coordinator.go
server/schedulers/evict_leader.go
server/schedulers/grant_leader.go
server/schedulers/utils.go

Fixes #2319.
This PR returns 404 when the scheduler/scheduler config is not found.
Fix the problem that returns 500 when the scheduler is not found
Tests 
- Unit test
Code changes

api: return 404 when scheduler is not found

---

go.mod
go.sum

update go.mod for https://github.com/pingcap/sysutil/pull/15.
Before
```sql
select * from `CLUSTER_LOAD` where device_type='cpu'
+------+-------------------+-------------+-------------+------------+-------------+
| TYPE | INSTANCE          | DEVICE_TYPE | DEVICE_NAME | NAME       | VALUE       |
+------+-------------------+-------------+-------------+------------+-------------+
| pd   | 127.0.0.1:2379  | cpu         | cpu         | load1      | 2.83          |
| pd   | 127.0.0.1:2379  | cpu         | cpu         | load5      | 2.61          |
| pd   | 127.0.0.1:2379  | cpu         | cpu         | load15     | 2.36          |
| pd   | 127.0.0.1:2379  | cpu         | cpu0        | user       | …
```

go.mod: update sysutil

---

server/api/region.go

Fix #2338
```
./bin/pd-ctl region
{"count":1,"regions":[{"id":2,"start_key":"","end_key":"","epoch":{"conf_ver":1,"version":1},"peers":[{"id":3,"store_id":1}],"leader":{"id":3,"store_id":1},"written_bytes":41,"read_bytes":0,"written_keys":1,"read_keys":0,"approximate_size":1,"approximate_keys":0,"replication_status":{"state":"INTEGRITY_OVER_LABEL","state_id":4}}]}
```
Tests 
- start cluster with replication mode and query region
Code changes

api: add replication status to region

---

server/replication/replication_mode.go

As when we use 2dc replication, we may need more metrics to monitor replication progress.
add `total` and `current` metric through httpstatus api.
Tests 
- No code
Code changes

replication_mod: add total and current metrics

---

go.mod
go.sum
server/api/member.go
server/member/leader.go
server/server.go

TiDB-Dashboard require git-hash for components, and previous pd don't have logic about git-hash. So This pr change it and add git hash. 
This pr: https://github.com/pingcap/kvproto/pull/599 modify kvproto and add `git_hash` field. This pr add the logic in pd api.
Please put it in 4.0.
Tests 
- No code
Code changes
Side effects

API: add git_hash in pd-member's api

---

go.mod
go.sum

Dependency: Update kvproto to [kvproto#605](https://github.com/pingcap/kvproto/pull/605), which change binary path to deploy path.
Previous we change tidb cluster's component path from `binary_path` to `deploy_path`. But pd's kvproto didn't changed. This pr update it and change pd's kvproto version to [kvproto#605](https://github.com/pingcap/kvproto/pull/605), which will fit this change.
Update kvproto to [kvproto#605](https://github.com/pingcap/kvproto/pull/605), which change binary path to deploy path.
Tests 
- No code
Code changes
Side effects

Dependency: Update kvproto to #605, which change binary path to deploy path.

---

pkg/component/manager.go
pkg/component/manager_test.go
server/api/component.go
server/api/component_test.go
server/api/router.go
server/cluster/cluster.go
server/core/storage.go
server/server.go

Previously, the component addresses are only kept in memory.
This PR persists the component addresses to etcd.
Tests 
- Unit test

*: persist the component address

---

server/core/store.go
server/core/store_test.go

When the store clone,add a method called ShallowClone,it won't clone the meta
Improve the  heartbeat processing 
https://github.com/pingcap/pd/issues/2391
When the store clone,add a method called ShallowClone,it won't clone the meta.
The test conditions are: 1 million region 20store 0.1 region-update-ratio, 10heartbeat-rounds. The average heartbeat is the average of the last 9 times.
the improve percent like this:
no.|improve content |related code |average heartbeat/s | improve percent
---|---|---|---|---
1|   master branch |     |   101652 | 0%    
2|use ShallowClone when UpdateStoreStatus.|   store.go 666: newStore := store.ShallowClone(SetLeaderCount(leaderCount),  | 124109   |     22%
Tests 
- Unit test

Improve the heartbeat processing by store ShallowClone.

---

server/cluster/cluster.go
server/schedule/operator_controller.go
server/schedule/storelimit/store_limit.go
tests/server/cluster/cluster_test.go

After #2226, the speed of both add and remove a store may be slower because of the rate limit of removing peers. 
This PR changes the rate of removing peers to unlimited when a store is offline.
Change rate limit of removing peers to unlimited when offline a store
Tests 
- Manual test 
When removing a store, the limit of removing peers for the offline store will be `556780641449999900` which represents unlimited.
```
» store limit region-remove
{
"1": {
"rate": 556780641449999900,
"mode": "auto"
},
"104": {
"rate": 15,
"mode": "auto"
},
"116": {
"rate": 15,
"mode": "auto"
}
```
For operator:
It's no longer 15/min and depends on how many stores in the cluster.

schedule: change store limit to unlimited when offline a store

---

server/api/config_test.go
server/config/config.go
server/replication/replication_mode.go
server/server.go
tests/pdctl/config/config_test.go
tests/server/cluster/cluster_test.go
tools/pd-ctl/pdctl/command/config_command.go

Fix #2386 
Fix #2387 
Fix #2388 
- change `dr_auto_sync` to `dr-auto-sync` (and auto convert `_` to `-`)
- validate config, if wrong return error
- support pd-ctl set numbers (e.g. primary-replicas)
- switch status to sync_recover when the label key is updated
Tests 
- Unit test

replication_mode: fix config issues

---

server/cluster/cluster.go

Improve the heartbeat processing
UCP #2395 
Reduce the call counts of updateStoreStatusLocked.
The test conditions are: 1 million region 20store 0.1 region-update-ratio, 10heartbeat-rounds. The average heartbeat is the average of the last 9 times.
the improve percent like this:
no.|improve content |related code |average heartbeat/s | improve percent
---|---|---|---|---
1|   master branch |     |   101652 | 0%    
2|use ShallowClone when UpdateStoreStatus.|   store.go 666: newStore := store.ShallowClone(SetLeaderCount(leaderCount),  | 124109   |     22%
3|use reduce the number of updates when update related stores.|   cluster.go 572-583: c.updateStoreStatusLocked(key),  | 132076   |     7.8%
Tests 
- Unit test

Reduce the unnecessary updateStoreStatusLocked call counts.

---

.github/pull_request_template.md

Make description easy be checked by release note checker
Change PR template
Change content of PR template and make it easy to be checked by release note checker
Tests 
- Unit test
- No code
Code changes
Side effects

Make release note easy to be checked by release note checker

---

server/api/region.go
server/api/router.go
tests/pdctl/region/region_test.go

Fix the `404` problem when using region key in pd-ctl, which is mentioned in #2351.
This PR uses [`UseEncodedPath`](https://www.gorillatoolkit.org/pkg/mux#Router.UseEncodedPath) to solve the `%2F` problem.
Fix the `404` problem when using `region key` in pd-ctl
Tests 
- Unit test

api: fix the encoded path of region key

---

server/config/config.go
server/config/persist_options.go

Fix #2365.
This PR uses `typeutil.Duration` instead of `time.Duration`. 
Fix the issue that the config item of the max gap to reset ts is not readable
Tests 
- Unit test

config: make max reset ts gap readable

---

metrics/grafana/pd.json

Some metrics of cluster meta have been renamed like TSO and id allocation. The monitor cannot show them currently.
This PR fixes it by adjust the Grafana template. After this PR, the PD dashboard looks like:
Tests 
- No code
- Fix the issue that the monitors of TSO and id allocation are missing

metrics: fix the tso and id monitor

---

Dockerfile
Makefile
tools/pd-recover/main.go

Closes #2402.
This PR does three things:
- change `make` target to compile pd-recover together
- add pd-recover to the docker image
- add `-V` parameter to show the version of pd-recover
Tests 
- Unit test
- Fix the issue that pd-recover is not included in the docker image

*: add pd-recover to Dockerfile

---

tests/pdctl/scheduler/scheduler_test.go
tools/pd-ctl/pdctl/command/scheduler.go

Fix #2356.
This PR adds default output for shuffle-region-scheduler when using `scheduler config` subcommand.
Tests 
- Unit test
- Fix the issue that there is no default output when using `scheduler config shuffle-region-scheduler` in pd-ctl.

pdctl: fix the default config output of shuffle region scheduler

---

Makefile
server/util.go

ref https://github.com/pingcap/tidb/pull/17170
needs to distinguish `Enterprise` and `Community` editions after v4.0.0 GA, and print the edition information in the log.
- add a compile option.
Tests 
```
❯ ./bin/pd-server -V
Release Version: v4.0.0-rc-49-g0e3d2188-dirty
Edition: Community
Git Commit Hash: 0e3d21884c952afe96af96b8c4f0ef851d5a9204
Git Branch: edition
UTC Build Time:  2020-05-13 09:56:14
```
- add the edtion infromation.

*: add edtion information

---

server/config/config.go

This PR resolves data path to an absolute directory, like what [TiKV did](https://github.com/tikv/tikv/blob/007556d3bc0ae058d08caed39e71c4ddd4de4195/src/storage/config.rs#L59).
This make PD instance to display correctly in TiDB Dashboard since TiDB Dashboard uses the data-directory to determine which disk information need to be displayed. Other paths are untouched for now.
Resolve to absolute directory in config adjust.
Tests 
- Manual test : After this change TiDB Dashboard becomes normal
Resolve data directory to absolute path.

config: resolve data path to absolute directory

---

client/client.go
go.mod
go.sum
server/api/admin_test.go
server/api/region.go
server/cluster/cluster.go
server/cluster/cluster_test.go
server/cluster/cluster_worker.go
server/grpc_service.go
tests/client/client_test.go

TiDB needs to identify down and pending peers to first connect to good peer.
- update kvproto
- return down peers and pending peers list
- update pd client
Tests 
- Unit test
Side effects
- Breaking backward compatibility (pd client has interface changed)
- https://github.com/pingcap/kvproto/pull/620
- Add DownPeers and PendingPeers in region response

server, client: add down_peer and pending_peer in region response

---

server/core/basic_cluster.go

UCP: #2430 
Improve the heartbeat processing
When call the method of PreCheckPutRegion, reduce the number of calls to the method getOverlaps.
The test conditions are: 1 million region 20store 0.1 region-update-ratio, 10heartbeat-rounds. The average heartbeat is the average of the last 9 times.
the improve percent like this:
no.|improve content |related code |average heartbeat/s | improve percent
---|---|---|---|---
1|   master branch |     |   101652 | 0%    
2|use ShallowClone when UpdateStoreStatus.|   store.go 666: newStore := store.ShallowClone(),  | 124109   |     22%
3|use reduce the number of updates when update related stores.|   cluster.go 572-583: c.updateStoreStatusLocked(key),  | 132076   |     7.8%
4|try not to remove the region from the subTree.|   region.go 580-584: …

Improve the heartbeat processing by reduce the number of getOverlaps.

---

server/core/region.go
server/core/region_test.go

UCP: #2431 
Improve the heartbeat processing
When removing the region, try not to remove the region from the region tree,
The test conditions are: 1 million region 20store 0.1 region-update-ratio, 10heartbeat-rounds. The average heartbeat is the average of the last 9 times.
the improve percent like this:
no.|improve content |related code |average heartbeat/s | improve percent
---|---|---|---|---
1|   master branch |     |   101652 | 0%    
2|use ShallowClone when UpdateStoreStatus.|   store.go 666: newStore := store.ShallowClone(SetLeaderCount(leaderCount),  | 124109   |     22%
3|use reduce the number of updates when update related stores.|   cluster.go 572-583: c.updateStoreStatusLocked(key),  | 132076   |     7.8%
4|try not to remove the region from the subTree.|   region.go 580-584: …

Improve the heartbeat processing by not remove region from the tree

---

go.mod
go.sum
server/config/config.go

In https://github.com/pingcap/pd/pull/2454 we added publicPath support. However it has a problem that publicPath cannot be set to simply `/`.
Add additional logic to allow publicPath to be `/`.
Tests 
Tested with: No configuration, configure with `/abc/def`, configure with `/`. All works fine.
Support setting public path for the embedded Dashboard.

Allow publicPath to be root `/`

---

conf/config.toml
go.mod
go.sum
pkg/dashboard/adapter/apiserver.go
pkg/dashboard/uiserver/embedded_assets_rewriter.go
server/config/config.go

Cherry pick #2454 to release-4.0
TiDB Dashboard.
Tests 
- Manual test
Support setting public path for the embedded Dashboard.

Cherry pick #2454 to release-4.0

---

.github/auto_assign.yml

The current assignee rule is to assign a PR to its author. We need to choose an assignee randomly for a PR created by the contributor. Related to #2455.
This PR modifies the rule of the assignee.
Tests 
- No code

*: update the assignee rule

---

server/core/store.go
server/core/store_test.go

Signed-off-by: JaySon-Huang <tshent@qq.com>
Fix #2470 
If store's used size is zero, just set `amplification = 1` to avoid divide by zero error.
Tests 
- Fix bug that can not get store information when store's used size is zero

server: Fix bug for region_score with store's used_size is zero

---

server/core/store.go
server/core/store_test.go

manual cherry-pick #2471 to release-3.1
* * *
Signed-off-by: JaySon-Huang <tshent@qq.com>
Fix #2470 
If store's used size is zero, just set `amplification = 1` to avoid divide by zero error.
Tests 
- Fix bug that can not get store information when store's used size is zero

server: Fix bug for region_score with store's used_size is zero (#2471)

---

pkg/cache/cache_test.go
pkg/cache/ttl.go
server/cluster/cluster.go
server/cluster/cluster_test.go
server/cluster/cluster_worker.go
server/cluster/cluster_worker_test.go
server/cluster/coordinator.go
tests/server/cluster/cluster_test.go
tests/server/cluster/cluster_work_test.go

Fix #2422
- `raftCluster` maintains a cache, namely `suspectRegions`. It contains all regions that potentially broken and need to fix
- when region splits, add all sub regions to the cache (we can include more cases later, for example, operator timeout)
- when coordinator patrols all regions, it first checks suspect regions
Tests 
- Unit test

cluster: add suspect regions cache

---

client/base_client.go
client/client.go
pkg/testutil/leak.go
server/cluster/cluster_test.go
server/grpc_service.go
tests/client/client_test.go

Close #2473 
This PR adds a new field in base client named `timeout` and it can be changed when we use `WithCustomTimeoutOption` to create a new client.
Tests 
- Unit test
- support setting a custom timeout for PD client

client: support custom client timeout

---

conf/config.toml
pkg/dashboard/adapter/redirector.go
pkg/dashboard/dashboard.go
server/config/config.go
tests/dashboard/service_test.go

realize [#532 Each pd can handle dashboard front-end resource requests](https://github.com/pingcap-incubator/tidb-dashboard/issues/532)
* config: add `Dashboard.InternalProxy` config
* dashboard: support internal proxy
Tests
- Unit test
Code changes
* The built-in dashboard supports internal proxy.

dashboard: support internal proxy

---

client/base_client.go
client/client.go
pkg/testutil/leak.go
server/cluster/cluster_test.go
server/grpc_service.go
tests/client/client_test.go

cherry-pick #2480.
This PR adds a new field in base client named timeout and it can be changed when we use WithCustomTimeoutOption to create a new client.
Tests
- Unit test
- Support setting a custom timeout for PD client

client: support custom client timeout (#2480)

---

pkg/dashboard/adapter/manager.go
pkg/dashboard/adapter/redirector.go
server/cluster/cluster.go
server/config/config.go
server/config/config_test.go
server/config/util.go
server/config/util_test.go
server/server.go

* fix #2503 
* When setting the `pd-server` config, validate the `dashboard-address` and reject the incorrect setting.
Tests
- Unit test

config: validate dashboard-address

---

server/schedule/selector/selector.go
server/schedule/selector/selector_test.go
server/schedulers/balance_test.go
server/schedulers/label.go
server/schedulers/scheduler_test.go

The `BalanceSelector` is not used by `balance-leader-scheduler` and `balance-region-scheduler` any more. It is only used by `label-scheduler`. We can remove it.
- remove `BalanceSelector`
- `label-scheduler` use `RandomSelector` instead of `BalanceSelector`. (`label-scheduler` don't need to care much about balance)
- migrate the test case that checks leader balance policy
Tests
- Unit test

schedule/selector: remove BalanceSelector

---

server/schedule/operator/operator.go
server/schedule/operator/operator_test.go

Close https://github.com/pingcap/pd/issues/1665
- get operator start time from OpStatusTracker directly
- record and observe the finish time of each operator step excatly once using CAS (Compare And Swap)
Tests
- Unit test
No release note

make operatorStepDuration metric thread-safe

---

pkg/mock/mockoption/mockoption.go
server/schedule/operator_controller.go
server/schedule/operator_controller_test.go

Closes #2540.
This PR checks if the store limits of adding peer and removing peer are existed before calling `Mode`.
Tests
- Unit test
- Fix the issue that It may panic when setting `store-limit-mode` to `auto`

schedule: fix panic when setting store-limit-mode to auto

---

server/cluster/cluster.go
tests/cluster.go
tests/pdctl/cluster/cluster_test.go
tools/pd-ctl/pdctl/command/cluster_command.go

Signed-off-by: 5kbpers <tangminghua@pingcap.com>
We need a way to check the replication_mode status (close https://github.com/pingcap/pd/issues/2444)
Add a subcommand `pd-ctl cluster status` for checking the status.
Tests
- Unit test
* `pd-ctl cluster status`
- Add a subcommand for checking cluster status

pd-ctl: add subcommand for checking cluster status

---

server/schedule/checker/rule_checker.go
server/schedule/checker/rule_checker_test.go

Fix https://github.com/pingcap/pd/issues/2419
- always try to remove orphan peers, even if failed to replace down/offline peer
- add restriction to remove orphan peer, it only be checked when all rules are satisfied (to avoid too small replica count)
Tests
- Unit test
```
1. start cluster with 4 tikv (A, B, C, D)
2. enable placement rules, set rules to 3voters+1learner
3. the region becomes voter(A) + voter(B) + voter(C) + learner(D)
4. set C to offline
5. remove the learner rule
6. make sure region becomes voeter(A) + voter(B) + voter(D)
7. check PD's log, operator history is `remove D + replace C with D`
```
- fix the placement rules …

rule checker: try to remove orphan peer after fix rule peers

---

server/schedule/operator/step.go
server/schedule/operator_controller.go
server/schedule/operator_controller_test.go

Fix https://github.com/pingcap/pd/issues/2493
If the leader changed cause by TiKV(maybe too busy or network problem), the operator cannot step to the final state, such as
```
PD:
try to remove peer 24
TiKV:
reject remove peer 24 because it is a leader.
``` 
Then the operator needs 10mins to timeout, which may cause the rule sync learner became slow.
Tests
- Unit test
- Let the operator fast fail if the leader changed to the RemovePeer

operator: fast-fail if the leader changed to the RemovePeer (#2530)

---

server/api/store.go
server/cluster/cluster.go
server/config/config.go
server/grpc_service.go
server/handler.go
tests/server/cluster/cluster_test.go

Related to #2505.
This PR adds a default limit config for TiFlash stores when calling `PutStore`.
Tests
- Unit test
- Set a suitable default store limit of the TiFlash stores

schedule: consider TiFlash when setting the store limit

---

go.mod
go.sum

fix https://github.com/pingcap/pd/issues/2562
update the log package to the latest can solve the issue.
Tests
config the log format to json, check the output
- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn): N/A
Support json formatted log

go.mod: update pingcap/log to support json formatted log

---

go.mod
go.sum
server/cluster/cluster.go
server/grpc_service.go

Signed-off-by: qupeng <qupeng@pingcap.com>
PD distributes cluster version to all stores.
Use latest kvproto, and fill field `ClusterVersion` in `StoreHeartbeatResponse`.
Tests
- No code
Code changes
Side effects
- https://github.com/pingcap/kvproto/pull/629
- https://github.com/tikv/tikv/pull/8098

service: add ClusterVersion into StoreHeartbeatResponse

---

server/cluster/cluster.go
server/config/config.go
server/config/persist_options.go
server/core/store.go
server/grpc_service.go
server/server.go
server/util.go
tests/server/cluster/cluster_test.go

Fix #2566.
This PR will init a default store limit config for stores when upgrading from the previous version.
Tests
- Unit test
- Fix the issue that PD may panic when upgrading from the previous version

schedule: fix the zero store limit

---

server/schedulers/balance_leader.go
server/schedulers/balance_test.go

We miss op influence when sort target store in balance leader scheduler. To fix #2571 
add it
Tests
- Unit test

scheduler: add opinfluence for balance leader scheduler

---

server/schedule/filter/filters.go
server/schedule/filter/filters_test.go
server/schedule/region_scatterer.go
server/schedulers/adjacent_region.go
server/schedulers/balance_region.go
server/schedulers/hot_region.go
server/schedulers/shuffle_hot_region.go
server/schedulers/shuffle_region.go

Enhance distinctScoreFilter to allow it can be used as score safe guard or improve placement.
- add 2 different policies: `safeGuard` and `improve` (the improve policy will be used by replicaChecker later)
- add tests
Tests
- Unit test

filter, schedulers: split DistinctScoreFilter to LocatoinSafeguard and LocationImprover

---

server/api/region.go
server/api/router.go
tests/pdctl/region/region_test.go

cherry-pick #2399.
This PR uses UseEncodedPath to solve the %2F problem.
Tests
- Unit test
- Fix the 404 problem when using region key in pd-ctl

api: fix the encoded path of region key (#2399)

---

server/schedule/operator/builder.go
server/schedule/operator/create_operator.go

now that Go has `sort.Slice`, we don't need define `u64slice` any more.

operator: remove u64slice

---

server/api/plugin.go

Function processPluginCommand specifies that the path prefix must be "./pd/plugin", and then determines whether there is a file under the path.
This limits the environment in which plugin can be loaded through pdctl or http.
For example, you need to create a path "pd/plugin" in the same directory as pdctl.

plugin: remove the extra path

---

server/api/store.go
tests/pdctl/store/store_test.go

Closes #2584.
When setting the store limit, we first check if it is zero and reject the request if it is.
Tests
- Unit test
- Prevent store limit from changing to zero

api: prevent store limit from changing to zero

---

server/heartbeat_streams.go

When store disconnected, the log message looks critical.
Adjust log level and reword.
Tests
- no test

server: adjust store disconnect log level and message

---

pkg/mock/mockoption/mockoption.go
server/schedule/filter/filters.go
server/schedule/filter/filters_test.go

make `StoreStateFilter` more easy to maintain.
- extract `conditionFunc`s
- table driven check conditions
- support `AllowTemporaryStates` (aims to be used by `replicaChecker` later)
The rules are defined by following table:
```
// The condition table.
// Y: the condition is temporary (expected to become false soon).
// N: the condition is expected to be true for a long time.
// X means when the condition is true, the store CANNOT be selected.
//
// Condition    Down Offline Tomb Block Disconn Busy RmLimit AddLimit Snap Pending Reject
// IsTemporary  N    N       N    N     Y       Y    Y       Y        Y    Y       N
//
// LeaderSource X            X    X     X
// RegionSource                                 X    X                X
// LeaderTarget …
```

filter: refactor StoreStateFilter

---

server/cluster/cluster.go
server/core/store_option.go
tests/server/cluster/cluster_test.go

Closes #2595.
This PR updates the existed store's deploy path when `Putstore` is called after restarting.
Tests
- Unit test
- Fix the issue that the deploy path of the store is not updated if the deploy directory is moved

misc: fix the deploy path not being updated

---

go.mod
go.sum
server/cluster/cluster.go
server/region_syncer/client.go
server/region_syncer/server.go
tests/server/region_syncer/region_syncer_test.go

Add the feature requested in issue #2542 
Add `region_leaders ` field in `SyncRegionResponse` to pass the region's leader info between PD leader and follower. And the region leader changing will also trigger sync now to make the region leader info more accurate.
Tests
- Unit test
- PR to update [`pingcap/kvproto`](https://github.com/pingcap/kvproto/pull/639)

syncer: sync region leaders between PD leader and follower

---

server/schedule/checker/rule_checker_test.go
server/schedule/placement/fit.go
server/schedule/placement/fit_test.go

Fix https://github.com/pingcap/pd/issues/2601
Use `DistinctScore` way to compare placements.
Tests
- Unit test
- Fix the issue that when enable placement rules, sometimes replicas of region may not be able to adjust to the best location

placement: fix placement location issue

---

server/cluster/coordinator_test.go
server/config/config.go
server/config/config_test.go
server/config/persist_options.go

Stale scheduler may appear after PD leader change, caused by the reload behavior that it merges in-memory config with persist config.
Drop in-memory state and merge default schedulers with persist configuration.
Tests
- Unit test
- Manually test
```
start 3pd + 1tikv
add evict-leader-scheduler-1
remove evict-leader-scheduler-1
kill pd1
show schedulers
make sure there is no evict-leader-scheduler-1
```
- Fix the problem of stale scheduler after leader change

config: improve scheduler config reload behavior

---

server/api/region.go
server/api/region_test.go
server/api/router.go

Add one new region HTTP API.
close https://github.com/pingcap/pd/issues/2593
Add one new region related http api to accelerate regions schedule by given key range.
Tests
- Unit test
- Support Region HTTP API to promote regions schedule by given key range

region: Add accelerate regions schedule API

---

server/tso/tso.go
tests/server/tso/tso_test.go

It takes too long (20s) for a follower PD to return an error to client. It may cause a longer unavailable time when PD leader changes.
Note: The client will not wait for 20s, but will timeout after 3 seconds.
Check lease before alloc ts.
Tests
- Unit test
- Fix the issue that the TSO request may take too long when PD leader switches

tso: make follower fail fast for tso requests

---

server/grpc_service.go
tests/client/client_test.go

Signed-off-by: MyonKeminta <mk@mkmkm.me>
Fixes https://github.com/pingcap/pd/issues/2628
Do not skip updating service safepoint when the requested safepoint equals to the minimum safepoint currently.
Tests
- Unit test
- release-4.0
* Fixes the issue that sometimes service safepoint can't be set properly, which may make BR and dumpling fail.

service: Fix the issue that cannot update only TTL of the min service safepoint

---

client/client.go

This PR uses an extra goroutine to check if creating stream causes too much time and will call `cancel` once it reaches the timeout setting of the client.
Tests
- TODO

client: check the timeout for creating stream

---

server/cluster/coordinator.go

The PD service cannot serve after remove the scheduler.
The main reason:
goroutine 1:
* To delete the schedule, call `func (c *RaftCluster) RemoveScheduler(name string)
* Hold RaftCluster write lock
* Wait for coordinator write lock
goroutine  2:
* Background thread, collect statistics continuously, call func (c *coordinator) collectHotSpotMetrics()
* Hold the coordinator read lock
* Call s.Scheduler.(hasHotStatus).GetHotWriteStatus() to wait for hotScheduler read lock
goroutine3:
* Scheduling process, scheduling, call func (h *hotScheduler) Schedule(cluster opt.Cluster)
* Hold hotScheduler write lock
* Call cluster.GetStoresStats() to wait for RaftCluster read lock
- fix the issue that caused …

cooridinator: fix the issue caused adeadlock when deleting scheduler 

---

server/cluster/cluster.go
server/cluster/coordinator.go
server/handler.go

Close #2630.
This PR changes the return value of `getSchedulers` from `map` to `[]string` and adds a new function named `GetSchedulerHandlers`.
Tests
- Unit test
- Fix the issue that `getSchedulers` may cause a data race

cluster: change return value for getSchedulers

---

client/client.go

cherry-pick #2616.
This PR uses an extra goroutine to check if creating stream causes too much time and will call cancel once it reaches the timeout setting of the client.
- Fix the issue that creating TSO stream may block for a while if the server crashes

client: check the timeout for creating stream (#2616)

---

plugin/scheduler_example/evict_leader.go
server/schedule/checker/replica_strategy.go
server/schedule/filter/candidates.go
server/schedule/filter/candidates_test.go
server/schedule/filter/comparer.go
server/schedulers/adjacent_region.go
server/schedulers/balance_region.go
server/schedulers/evict_leader.go
server/schedulers/label.go
server/schedulers/random_merge.go
server/schedulers/shuffle_leader.go
server/schedulers/shuffle_region.go

After switch to using `StoreCandidates`, there is, in fact, no selector in package `selector`.
Remove package selector and move candidates files to package filter.
Tests
- Unit test

schedule: merge package selector into filter

---

Makefile
conf/config.toml
go.mod
go.sum
pkg/dashboard/adapter/config.go
server/api/status.go
server/api/status_test.go
server/api/version.go
server/config/config.go
server/config/config_test.go
server/server.go
server/util.go
server/versioninfo/versioninfo.go

* Update tidb-dashboard to v2020.07.15.
* Unified telemetry config name.
* Disable telemetry by default for non-community edition.
* Update tidb-dashboard to v2020.07.15.
* Use `dashboard.enable-telemetry` in config. (`dashboard.disable-telemetry` is deprecated now).
* Disable telemetry by default for non-community edition.
Tests
- Unit test
- `pd-ctl config show all | grep telemetry`
Code changes
* Update tidb-dashboard to v2020.07.15.
* Use `dashboard.enable-telemetry` in config. (`dashboard.disable-telemetry` is deprecated now). …

dashboard: update to v2020.07.15 and disable telemetry by default for non-community edition

---

Makefile
conf/config.toml
go.mod
go.sum
pkg/dashboard/adapter/config.go
server/api/status.go
server/api/status_test.go
server/api/version.go
server/config/config.go
server/config/config_test.go
server/server.go
server/util.go
server/versioninfo/versioninfo.go

cherry-pick #2651 to release-4.0
---
* Update tidb-dashboard to v2020.07.15.
* Unified telemetry config name.
* Disable telemetry by default for non-community edition.
* Update tidb-dashboard to v2020.07.15.
* Use `dashboard.enable-telemetry` in config. (`dashboard.disable-telemetry` is deprecated now).
* Disable telemetry by default for non-community edition.
Tests
- Unit test
- `pd-ctl config show all | grep telemetry`
Code changes
* Update tidb-dashboard to v2020.07.15.
* Use …

dashboard: update to v2020.07.15 and disable telemetry by default for non-community edition (#2651)

---

go.mod
go.sum

Signed-off-by: baurine <2008.hbl@gmail.com>
Related issues and PRs:
- https://github.com/pingcap-incubator/tidb-dashboard/issues/665
- https://github.com/pingcap/sysutil/pull/19
- https://github.com/tikv/tikv/pull/8224
Problem Summary:
- If the log files include invalid lines in the beginning or end, it will be skipped.
- If the log files include invalid lines in the middle, the lines will be ignored.
- Check at most 10 lines in the beginning or end to find the first valid line
- Treat the invalid line in the middle as a normal log with pre valid log time and level
Tests
- Unit test
- Support search the log file even it includes some invalid lines

search logs: update sysutil to support search logs include invalid lines

---

server/tso/tso.go

Close #2663 
Under the current latest version of PD, TSO request may fail at the time of leader changing because `SyncTimestamp` is not yet completed but PD receives a TSO request at the same time.
Add leader lease check and try to sleep a while to wait for `SyncTimestamp`.
Tests
- Unit test
Code changes
- Has `GetRespTS` method change
- PR #2614 
Fix the bug that TSO request may fail at the time of leader changing.

tso: fix the bug that TSO request may fail at the time of leader changing

---

tests/pdctl/store/store_test.go
tools/pd-ctl/pdctl/command/store_command.go

Previous PR #2586 prevents store limit from being zero. But the hint message of `pd-ctl` is still `>=0`.
This PR makes the hint message consistent with code.
Tests
- No code

pd-ctl: make the hint message consistent with code

---

pkg/mock/mockoption/mockoption.go
server/api/config_test.go
server/cluster/cluster.go
server/config/config.go
server/config/persist_options.go
server/schedule/checker/replica_checker.go
server/schedule/checker/replica_strategy.go
server/schedule/filter/filters.go
server/schedule/filter/filters_test.go
server/schedule/opt/opts.go
server/statistics/schedule_options.go

Add a new replication config named `isolation-level` according to #2528 #2418 
With the new config `isolation-level`, `SelectStoreToAdd` in `replica_strategy.go` will filter out stores to isolate replicas explicitly and forcibly. For example, a region has 3 replicas in z1, z2 and z3 individually. With IsolationLevel = zone, if the region on z1 is down, we need to filter out z2 and z3 because these two zones already have one of the region's replicas on them. We need to choose a store on z1 or z4 to place the new replica to meet the `isolation-level`.
Tests
- Unit test
Code changes
- Has `replica_strategy` change
- Has `filter` change
Add a new replication config named `isolation-level` to isolate …

config, replica_strategy, filter: add new replication config isolation-level to isolate replicas explicitly and forcibly

---

server/server.go
server/tso/tso.go
tests/cluster.go
tests/server/tso/tso_test.go

Previous PR #2665 tries to fix a bug that tso allocation may fail though it's already a PD leader, which lacks of a test case can cover this situation. This pr adds a test case and makes some slight changes than before.
According to these two TiDB jenkins tests, tso may still have some problems when leader changes. I need more logs to figure out why, so this pr also adds some log info when a tso request arrive.
* https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/42444/pipeline/
* https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/42068/pipeline/
* Try to set `lease` as soon as possible in `SyncTimestamp`.
* Add some new …

tso, server, tests: add a test case for tso allocation bug
