- Makefile
- scripts/embed-dashboard-ui.ps1
- scripts/embed-dashboard-ui.sh
* Prevent the version information of pd-server from being dirty.
* `build.ps1` failed to run
* Synchronize the core modifications of `embed-dashboard-ui.sh` to `embed-dashboard-ui.ps1`
* Download the dashboard embed asset file to the cache directory.
* Run `go mod tidy` at the end of `make swagger-spec` to restore `go.mod`.
Tests
- `git clone` to get a clean code directory
- run `make pd-server`
- run `./build.ps1` in Windows
> build: update script file

- server/api/router.go
- server/api/rule.go
- server/api/rule_test.go
- server/schedule/placement/rule_manager.go
Related to #2680.
Now one can post an array of rules to `/config/rules`, to set all rules in one request. In case there is an error, all modifications are cancelled.
Tests
- Unit test
Code changes
- atomic POST api `/config/rules` for setting all rules in one request, parameter is an array of rules
> placement: api for adding rules in one request

- pkg/mock/mockcluster/mockcluster.go
- server/schedule/filter/filters.go
- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
During `filterDstStores` in hot region scheduler, it didn't consider the placement rule enabled in `transferLeader` case.
This requests add `PlacementLeaderSafeguard` filter in the `filterDstStores`
> Add leader filter in hot region scheduler

- server/api/router.go
- server/api/rule.go
- server/api/rule_test.go
- server/schedule/placement/rule_manager.go
- server/schedule/placement/rule_manager_test.go
Related to #2680.
Now one can post an array of operations(insert/delete) to `/config/rules/batch` in one request. In case there is an error, all modifications are cancelled.
Two notable points:
1. Operations should be independent. Their IDs should be different.
2. I noticed that this PR and the previous PR is not completely safe. See https://github.com/xhebox/pd/blob/delete/server/schedule/placement/rule_manager.go#L294-L299.
Tests
- Unit test
Code changes
- atomic POST api `/config/rules/batcch` for batch(insert/delete) rules in one request
> placement: support batch deletions, with insertions

- go.mod
- go.sum
Update dashboard
This PR updates the dashboard version to release 2020.08.03.1
> dashboard: update dashboard to version 2020.08.03.1

- server/cluster/cluster.go
- server/cluster/cluster_test.go
When handling store heartbeats, pd needs to persist store info with new stats and heartbeatTS. However, after checking if the new store info needs to persist, pd wrongly stores the original store info into storage.
Store the new store info with latest heartbeatTS and stats instead of the original one.
- Unit test
> server/cluster: fix storing old store info into storage when handling heartbeat

- tools/pd-ctl/pdctl/command/config_command.go
#2694, as title, save rules using the new api.
Tests
- Manual test
Test save rules with `[{count=3}, {count=0}, {count=0}, {count=3}]`, and `[{count=3}, {count=3}, {count=0}]`.
> pd-ctl: make use of new batch ruledef api

- tools/pd-analysis/analysis/parse_log.go
- tools/pd-analysis/analysis/parse_log_test.go
When parse log by pd-analysis, run
`./bin/pd-analysis -input temp_log -operator balance-region -style transfer-counter`
get
`[2020/08/06 12:00:39.900 +08:00] [FATAL] [main.go:73] ["strconv.ParseInt: parsing \"\": invalid syntax"] [stack="main.main\n\t/Users/zeyuantan/Temp/my/pd/tools/pd-analysis/main.go:73\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]`
Move peer operator log is `store [1] to [2]` instead of `store 1 to 2`, fix parsing format.
Tests
- Unit test
Code changes
- If operator needs move peer, fix store parse format.
Side effects
- Fix pd-analysis parse log bug.
> pd-analysis: Fix mv peer log parse bug

- tests/pdctl/member/member_test.go
In go1.15, the vet tool now warns about conversions of the form `string(x)` where `x` has an integer type other than rune or byte. Because of this, pd will not pass tests with go1.15. This pr fix this wrong usage.
More details: https://golang.org/doc/go1.15#vet
`string(id)` -> `fmt.Sprint(id)`
Tests
- Unit test
Fix a bug that pd will not pass the vet check in go1.15.
> tests: fix the vet warning in go1.15

- pkg/autoscaling/calculation.go
- pkg/typeutil/comparison.go
- pkg/typeutil/comparison_test.go
- server/cluster/coordinator_test.go
- server/schedulers/base_scheduler.go
- server/schedulers/scheduler_test.go
- server/schedulers/utils.go
According to the [comment](https://github.com/pingcap/pd/pull/2738#discussion_r467715596), it's better to support the customized scale in/out step. After this PR, we need to make `MaxScaleOutStep` and `MaxScaleInStep` configurable, see #2754.
This PR moves out some common functions from `scheduler/utils.go` to `pkg/comparison.go` and use the `MaxScale*Step` to control the max step of scaling in/out.
Tests
- Unit test
> autoscaling: use variables to control scale step

- pkg/mock/mockcluster/mockcluster.go
- server/schedule/opt/opts.go
- server/schedule/region_scatterer.go
- server/schedule/region_scatterer_test.go
Before region scattering, scatter will check the region status, if the region is not valid, scatter will refuse to scatter the region and wait coordinator to fix it.
This request let scatter put the invalid region into high priority schedule queue instead of discarding it directly.
ref https://github.com/pingcap/pd/issues/2733
#2736 is over-designed, this request simplies it.
Add a new interface called HighPrioritySchedule to handle the regions for high priority scheduling need.
Tests
- Unit test
> Add priority schedule after scatter check failed.

- server/schedule/placement/rule_manager.go
> If an operand implements method String() string, that method will be invoked to convert the object to a string, which will then be formatted as required by the verb (if any).
Due to this behavior, the line 388 in rule_manager.go:
```
log.Info("placement rules updated", zap.String("batch", fmt.Sprint(todo)))
```
did not print all fields in `RuleOp`. This PR adds an explicit stringer interface for `RuleOp` to display all infomation.
Tests
- Unit test
> placement: add stringer for RuleOp

- server/api/member.go
- server/member/leader.go
- server/server.go
- tests/cluster.go
Currently, we have two kinds of in a PD cluster. One is PD leader, another is etcd leader. Under this circumstance, many methods and comments are ambiguous in package `server` and `member`. To help developers better distinguish between these two kinds of leaders, I update all related methods and comments to be more clear on theres two points. 
Update leader related methods and comments.
Tests
- Unit test
Update leader related methods and comments.
> server, member: update leader related methods and comments

- Makefile
Sometimes if you cancel `make test` during the process, you will find that your workspace being filled with `*.bak` and failpoint files. So I add a new `clean` command to help clean these test intermediate files.
Add a new command to `Makefile`.
Tests
- No code
Code changes
- Has `Makefile` change
No release note.
> Add a new "clean" command to Makefile

- server/schedule/placement/rule_list.go
- server/schedule/placement/rule_manager.go
- server/schedule/placement/rule_manager_test.go
This PR comes from the discussion between me and @djshow832. As the PD community pointed out that it is invalid to define multiple leaders over the same range. Now it is forbidden.
First, `adjustRule` will filter out rules like `{role=leader, count=3}`. Then, when building the rule list, a loop is used to avoid cases like two rules `{role=leader, count=1}, {role=leader, count=1}` over the same range.
**EDIT**: Suggested by @djshow832 , now it also checks if there is still one leader after add/del. In another word, it is only valid iff `(leader+voter) >= 1 && leader <= 1`.
Tests
- Unit test
- Forbid adding multiple leaders over the same range.
> placement: forbid mutiple leader replicas, and require at least one leader

- go.mod
- go.sum
Use the `kvproto` from branch release-4.0.
Update `go.mod`.
Tests
- Unit test
* Update `kvproto` to the correct version.
> go.mod: update to kvproto/release-4.0

- client/base_client.go
- client/client.go
- go.mod
- go.sum
- pkg/dashboard/adapter/manager.go
- pkg/errs/errno.go
- pkg/errs/errs.go
- pkg/errs/errs_test.go
- pkg/etcdutil/etcdutil_test.go
- server/kv/etcd_kv.go
- server/member/member.go
- server/schedule/placement/rule_manager.go
Related to #2704.
This PR updates the way to define an error and uses `Wrap` and `FastGenWithCause` to output the internal error.
Tests
- Unit test
> *: update the error dependency and do the corresponding changes

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/schedulers/hot_region.go
- server/statistics/store.go
Before this PR, we have not filtered unhealthy store in `summaryStoresLoad`, it will make exp to be inaccurate 
Fix it
Tests
- Unit test
- Fix the issue that no filtered unhealthy store in `summaryStoresLoad`
> scheduler: filter unhealthy store in summaryStoresLoad

- go.mod
- go.sum
- pkg/errs/errno.go
- pkg/etcdutil/etcdutil.go
- pkg/metricutil/metricutil.go
Part of #2704.
This PR refines logs according to RFC and update the error dependency.
Tests
- Unit test
> *: refine log in metricutil/etcdutil

- server/cluster/store_limiter.go
Signed-off-by: 1150310621 <2604947873@qq.com>
when store limit mode is auto, tidb calculate limit rate on seconds and add it to schedule config mistakely.
return the calculated rate without divide by the store balance base time
- Fix the unit of store limit rate when the mode is auto
> bug fix: calculate limit rate bases on minute when mode is auto

- pkg/autoscaling/calculation.go
- pkg/autoscaling/prometheus.go
- pkg/autoscaling/prometheus_test.go
If the query metrics duration is longer than 1 minute, Prometheus cannot parse the duration expression generated by `time.Duration.String()` method. And if the duration is too short, nothing returns from Prometheus.
Convert duration to string expression using our own method.
Tests
- Unit test
> autoscaling: add some comments and fix duration expression conversion

- server/api/router.go
- server/api/rule.go
- server/api/rule_test.go
- server/schedule/placement/rule.go
- server/schedule/placement/rule_manager.go
With placement rule API, we can update Rule config and RuleGroup config separately. But a common requirement is to update the Group configuration and the configuration of all Rules in the Group at the same time.
Some previous discussion can be found in https://github.com/tikv/pd/issues/2680
Introduce a new series of APIs:
- `GET /config/placement-rule` read all rules by groups
return:
```
[
{
"group_id": "foo",
"index": 0,
"override": false,
"rules":  [ /* rules in group foo */ ]
},
{
"group_id": "bar",
"index": 1,
"override": true,
"rules":  [ /* rules in group bar */ ]
},
... other groups
]
```
- `GET /config/placement-rule/{group}` read rules from a group
returns
```
{
"group_id": "foo",
"index": 0,
"override": false,
"rules":  [ /* rules in group foo */ ]
},
```
- `POST …
> placement: add bundle APIs to allow updating group and rule configurations with a single request

- server/config/config.go
- tests/pdctl/config/config_test.go
cannot set the filed with `pd-ctl`
Tests
- Unit test
> config: fix the bool field about `trace-region-flow`

- pkg/autoscaling/calculation.go
- pkg/autoscaling/calculation_test.go
PD does not have resource type information for each group when making auto-scaling decisions.
We assume that every instance added by auto-scaling has a label `resource-type` and we associate the group name with `resource-type` to provide the missing information.
Tests
- Unit test
> autoscaling: get resource type from instance label

- metrics/grafana/pd.json
Sometimes, we encounter the problem of leader changed, but we have no idea why it changed. Also, we may find "apply entries took too long" in our log. It could be caused by disk or CPU. Add more metrics may help us find the problem.
According to [etcd metrics](https://github.com/etcd-io/etcd/blob/93ae5d2f5b75d25405b651721f06c5e808cd6465/Documentation/metrics.md#disk), this PR adds `backend_commit_duration_seconds` to monitor the disk latency. 
After this PR:
Tests
- No code
Code changes
- Add `backend_commit_duration_seconds` metrics to grafana template.
> metrics: add backend_commit_duration_seconds

- pkg/autoscaling/calculation.go
We expect to output the complete scaled group even if there is no action of auto scaling. But for now, it will only output nil as a result. 
Another problem is if there is no auto scaling group, it will create a new one. But in the previous implementation, it didn't contain a label in the returned value.
This PR fixes the above problems.
Tests
- Manual test
> autoscaling: fix label and scaled group

- pkg/codec/codec.go
- tools/pd-simulator/simulator/cases/import_data.go
- tools/pd-simulator/simulator/config.go
- tools/pd-simulator/simulator/simutil/key.go
we count the old regions in the statistics for the table, This is not the result I want.
Tests
```
❯ ./bin/pd-simulator -regionNum=10000 -case="import-data" -simLog=info
["import data information"]:
[table-leader="1001 leader: [store 1]:97.60% [store 4]:2.40%"] 
[table-peer="3003 peer:  [store 1]:32.53% [store 2]:0.60% [store 3]:0.50% [store 4]:32.43% [store 5]:0.20% [store 6]:0.23% [store 7]:0.30% [store 8]:0.43% [store 9]:32.43% [store 10]:0.33%"]
[total-leader="11000 leader: [store 1]:9.13% [store 2]:9.13% [store 3]:9.06% [store 4]:9.15% [store 5]:9.14% [store 6]:9.11% [store 7]:9.05% [store 8]:9.12% [store 9]:9.14% [store 10]:9.11%"]
[total-peer="33000 peer: [store 1]:10.08% [store 2]:9.97% …
```
> simulator/cases: import-data only count the newly regions of the table

- server/api/label.go
- server/api/scheduler.go
- server/api/store.go
We should call `.Error` to convert `error` to `string`, otherwise we will get an empty result.
Add missing `.Error()` call for API error responses.
Tests
- No test
> *: fix missing calls to .Error()

- server/core/store.go
- server/core/store_test.go
The previous PR uses a hard limit for low space. If the capacity beyond 500G, it will use 100G as its low space threshold. It doesn't seem reasonable.
This PR changes back to the original way to control low space.
Tests
- Unit test
- Change back to the original way to control the low space threshold
> scheduler: revert low space threshold hard limit

- pkg/errs/errno.go
- server/tso/global_allocator.go
- server/tso/tso.go
- tests/server/tso/tso_test.go
This PR does some optimization for the error handling by defining the error when we first meet it in `tso`.
Tests
- Unit test
- #2853 
* Optimize the err handling in `tso` pkg.
> tso: optimize the err handling and make their specification consistent

- pkg/errs/errno.go
- server/grpc_service.go
- server/handler.go
- server/server.go
- server/tso/allocator_manager.go
- server/tso/tso.go
- tests/server/tso/tso_test.go
- tools/pd-backup/pdbackup/backup.go
Solve #2858 
Tests
- Unit test
* Introduce the `AllocatorManager` to manage all TSO Allocators a PD server will hold.
> tso: introduce the AllocatorManager

- server/schedule/placement/rule_manager.go
Unify the code style for RuleManager during matian ruleConfig. Now a standard rule operation pattern would be like:
```golang
patch := ruleManager.beginPatch()
patch.setRule() / patch.DeleteRule()
ruleManager.tryCommitPatch(patch)
```
> placement: unify the code style in RuleManager

- server/member/member.go
- server/server.go
Remove invalid parameters for the function `member.CheckLeader()`.
Remove unused function parameters.
Tests
- Unit test
* Remove some invalid function parameters.
> member, server: remove some invalid function parameters

- pkg/testutil/operator_check.go
* Use dot import for the check package
* Add missing Assert
Tests
- Unit test
> testutil: refine operator_check

- metrics/grafana/pd.json
- server/grpc_service.go
- server/metrics.go
Signed-off-by: Zheming Li <nkdudu@126.com>
Add more metrics about heartbeat. Solve #2800
- Add heartbeat handle duration for region heartbeat and store heartbeat.
- Add panel in pd grafana dashboard.
- Fix RegionHeartBeat still count "ok" when error occurs.
Tests
- Manual test: using tiup to run this pd and import pd.json manually in grafana.
Code changes
- Has metrics changed.
> metrics: add more metrics for region and store heartbeat

- server/schedule/checker/learner_checker_test.go
- server/schedule/checker/merge_checker_test.go
- server/schedule/checker/replica_checker_test.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/region_scatterer_test.go
- server/schedulers/balance_test.go
- server/schedulers/hot_test.go
- server/schedulers/scheduler_test.go
- tests/client/client_test.go
* disable joint consensus feature for some test
* put some stores in the preparation phase of some tests
* add heartbeat time to some stores to prevent the store from being judged as `isDown`
Tests
- Unit test
> test: refine unit test

- cmd/pd-server/main.go
- pkg/errs/errno.go
- pkg/logutil/log.go
- pkg/typeutil/convension.go
- server/config/config.go
- server/core/store.go
- server/join/join.go
- server/kv/levedb_kv.go
- server/region_syncer/history_buffer.go
- server/schedule/scheduler.go
- server/schedulers/adjacent_region.go
- server/util.go
- server/versioninfo/feature.go
- server/versioninfo/versioninfo.go
Part of #2704.
This PR refines all the fatal level log according to the RFC
Tests
- Unit test
> *: refine the fatal log

- server/api/rule_test.go
- server/schedule/placement/rule_list.go
- server/schedule/placement/rule_manager.go
- server/tso/tso.go
- tests/server/tso/tso_test.go
cherry-pick #2708 #2878 to release-4.0
Tests
- Unit test
> *: add missing error handling

- pkg/apiutil/serverapi/middleware.go
* When the request contains the header `PD-Allow-follower-handle`, even if the leader responds to the request, it also contains the header `PD-Follwer-handle`.
* Fix typo
* The `PD-Follower-handle` header is set only when the follower responds to the api.
Tests
- Unit test
* api: fix wrong follower handle header
> api: fix wrong follower handle header

- pkg/autoscaling/calculation.go
- pkg/autoscaling/calculation_test.go
- pkg/autoscaling/types.go
Change the type of `labels` in autoscaling API response from `[]*metapb.StoreLabel` to `map[string]string`
Change the type of `labels` in autoscaling API response from `[]*metapb.StoreLabel` to `map[string]string`
Tests
- Unit test
Code changes
> autoscaling: use map for labels in autoscaling response

- server/member/member.go
- server/server.go
- server/tso/allocator_manager.go
- tests/server/tso/manager_test.go
Part of #2759. Each PD server of a cluster needs to know the topology of DC in order to elect the corresponding Local TSO Allocator. We need to write the dc-location config into etcd to persist it in the cluster.
Write the dc-location config into etcd during the server initialization.
Tests
- Unit test
> tso, config, test: persist dc-location config in the cluster

- pkg/autoscaling/calculation.go
Autoscaling API will panic if some components are not for autoscaling because of division by zero.
Skip calculating plans for non-autoscaling components
Tests
- Unit test
> autoscaling: skip calculating plans for non-autoscaling components

- server/config/config.go
- server/config/persist_options.go
- server/schedule/operator/builder.go
* schedule: add `enable-joint-consensus` config
Code changes
* schedule: add `enable-joint-consensus` config
> schedule: add enable-joint-consensus config

- server/schedule/checker/joint_state_checker.go
- server/schedule/checker/joint_state_checker_test.go
- server/schedule/checker_controller.go
* schedule: add joint state checker
Tests
- Unit test
- support use joint consensus to change region peers
> schedule: add joint state checker

- server/schedule/checker/replica_checker.go
Making up replicas should be a high priority.
This PR sets the `make-up-replica` operator to high priority.
Tests
- Unit test
- Set the `make-up-replica` operator to high priority
> checker: set high priority for making up replicas

- go.mod
- go.sum
- server/election/leadership.go
- server/kv/etcd_kv.go
After updating the errors dependency, the PD will panic. Due to https://github.com/pingcap/errors/pull/26, when we wrap nil, it will return nil which causes panic of PD.
This PR fixes a potential panic when updating the errors dependency
Tests
- Unit test
- Fix a panic problem when using the latest errors
> *: fix a potential panic when updating the errors dependency

- server/api/rule.go
- server/schedule/placement/rule_manager.go
- tests/pdctl/config/config_test.go
- tools/pd-ctl/pdctl/command/config_command.go
Add `partial` parameter and `partial` option to `pd-ctl`. Refer to https://github.com/tikv/pd/issues/2680#issuecomment-694600556.
Tests
- Unit test
Code changes
- add partial parameter to the post request of `/config/placement-rule`
> placement: add override parameter to setallgroups

- server/cluster/coordinator.go
- server/handler.go
Currently, we don't use individual schedulers for stores to evict leader. Instead, we use configuration to control the store whose leader should be evicted. But there is a problem that it's hard to tell which store is configured through the log because the log only prints evict-leader-scheduler is created without store ID.
This PR adds arguments into the log to help us make clear about it.
Tests
- Manual test
> *: improve scheduler logs

- server/election/leadership.go
- server/server.go
- server/tso/allocator_manager.go
- server/tso/local_allocator.go
- tests/server/tso/allocator_test.go
Part of #2984 and #2759. Prepare for the next step of implementing the global TSO generation algorithm.
After merging this pr, the `AllocatorDaemon` will check the `dc-location` config in the cluster periodically. If any new new `dc-location` found, it will set up the corresponding Local TSO Allocator.
Tests
- Unit test
> tso: add the allocator checker

- server/server.go
- tests/pdctl/config/config_test.go
After placement rues enabled, updating `max-replicas` or `location-labels` won't work. User may not know it and get confused if they did not read doc carefully.
Give some warning when user want to update config.
Tests
- Unit test
> server: warn useless config change when placement rules enabled

- server/cluster/cluster_worker.go
- server/grpc_service.go
Currently, we first handle the region heartbeat then check if the region is valid.
This PR moves the check logic to `RegionHeartbeat`
Tests
- Unit test
> cluster: check if region is valid before handling it

- server/api/scheduler.go
Closes #3052.
This PR supports the status query parameter for the scheduler API. For now, it only supports the `paused` status. If there is no status query parameter, the default behavior is the same as before.
Tests
- Manual test
> api: add status query parameter for the scheduler API

- server/api/rule.go
- server/api/rule_test.go
Signed-off-by: Zheming Li <nkdudu@126.com>
#3054 
- Using `GroupBundle.ID` to auto fill `GroupId` field in Rule when unset.
Tests
- Unit test
Code changes
> api: auto fill group id in rules when unset

- server/cluster_info.go
Related to https://github.com/tikv/pd/issues/2427, but for release-3.0
This PR changes the log level of the stale region when loading.
Tests
- Unit test
- Change the log level of the stale region when loading regions
> server: change log level for the stale region when loading

- pkg/mock/mockcluster/mockcluster.go
- server/schedule/filter/filters.go
- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
Fix the bug that PD might panic if there is down store with 10 minutes
#3053 
replace healthy filter with Connected filter
Tests
- Unit test
- Fix the bug that PD might panic if there is down store with 10 minutes
> Fix the bug that PD might panic if there is down store with 10 minutes

- metrics/grafana/pd.json
Related #3079.
This PR adds a monitor to show db size of etcd for release 4.0 and collapse some panels.
Tests
- No code
> show db size of etcd

- server/api/config.go
- server/api/config_test.go
- server/api/router.go
- server/api/store.go
- server/api/store_test.go
- server/cluster/cluster.go
- server/config/persist_options.go
- server/handler.go
- server/server.go
1. Provide a temporary API to support temporary configuration for some configurations.
2. Make `/store/{id}/limit` and `/stores/limit` support ttl param.  
**Note that this API is only supported for lightning and BR as a temporary way. Don't call this API.**
As the temporary configuration only is saved in the memory, a recommended way to use API is calling it with short interval (once a minute) and long ttl (10 minutes).
> api: support temporary configuration

- server/config/persist_options.go
The `SetTTLData` may have goroutine leak as `NewStringTTL` would create an extra goroutine to do the gc work. When updating an existed key, we need to call the cancel function to close the extra goroutine.
```golang
// SetTTLData set temporary configuration
func (o *PersistOptions) SetTTLData(ctx context.Context, key string, value interface{}, ttl time.Duration) {
if data, ok := o.ttl[key]; ok {
data.Clear()
// the goroutine would leak here
}
o.ttl[key] = cache.NewStringTTL(ctx, 5*time.Second, ttl)
o.ttl[key].Put(key, value)
}
```
As the origin context is directly use the server context, this request fix it by replace a new context which is success from the server context and maintained its cancel function.
> config: fix goroutine leak risk

- go.mod
- go.sum
Update TiDB Dashboard to resolve a panic bug caused by KeyViz.
Update the TiDB Dashboard vendor to v2020.10.21.1
Tests
- Unit test
TiDB Dashboard: Fix a bug that KeyViz may panic
> Update TiDB Dashboard to v2020.10.21.1

- go.mod
- go.sum
Related PR: https://github.com/pingcap/sysutil/pull/23
example in TiDB:
```sql
information_schema> select * from `CLUSTER_SYSTEMINFO` where name = 'transparent_hugepage_enabled';
+------+------------------+-------------+-------------+------------------------------+------------------------+
| TYPE | INSTANCE         | SYSTEM_TYPE | SYSTEM_NAME | NAME                         | VALUE                  |
+------+------------------+-------------+-------------+------------------------------+------------------------+
| tidb | 172.16.5.40:4019 | system      | kernel      | transparent_hugepage_enabled | always madvise [never] |
+------+------------------+-------------+-------------+------------------------------+------------------------+
```
- Need …
> update sysutil in go.mod for transparent hugepage enabled information

- .gitignore
- scripts/check-errdoc.sh
Multiple users cannot run tests due to the permission of error.toml.before.
This PR changes the file path from /tmp to the current directory and remove the file after comparision.
Tests
- No code
> *: solve the error.toml.before permission problem

- pkg/autoscaling/calculation.go
- pkg/autoscaling/types.go
The API definition says that the `count` field in a resource is optional. It means a resource is unlimited when the field is unset.
Change the type of `count` from `uint64` to `*uint64`
Tests
- No code
> autoscaling: fix count in resource to be optional

- server/cluster/cluster_test.go
- server/config/config.go
- server/config/config_test.go
- server/server.go
* The config of `store-balance-rate` and `trace-region-flow` will be lost during `Clone`.
* config: refine config clone
* server: clone config in `GetConfig`
- Fix the bug that `trace-region-flow` will be accidentally changed to `false`.
> config: refine config clone

- server/grpc_service.go
- server/tso/allocator_manager.go
- server/tso/global_allocator.go
`GetLocalAllocatorLeaders` can only get all the Local TSO Allocator leaders that the current server holds. But the Global TSO generation needs PD to know all Local TSO Allocator leaders in the cluster. 
* Replace the `GetLocalAllocatorLeaders` with `GetAllLocalAllocatorLeaders`.
* Refine the method names.
Tests
- Unit test
> tso: fix the incorrect use of GetLocalAllocatorLeaders

- server/tso/global_allocator.go
Before returning the `maxTSO` as the result, we need to update the Global TSO in memory even in etcd to make it persistent, but because the setting process is not atomic completely, the TSO in memory may be greater after we call `ResetUserTimestamp` then failed the whole synchronization, which will reduce the success rate of obtaining the Global TSO.
Actually, it's ok to let `SetTSO` fail when we update the Global TSO in memory. To make it not fail the Global TSO sync when update memory, I replace the err returning with a warning log.
Tests
- Unit test
> tso: do not fail the Global TSO sync when update memory

- server/grpc_service.go
- tests/client/client_test.go
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
Fix infinite TTL doesn't work
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
Fixes #3128 
In the original code the expire time of service safepoints are calculated by `time.Unit() + TTL`, and we use MaxInt64 to represent infinite TTL. Then it overflows to a minus value and expires immediately. This PR fixes the issue.
Tests
- Unit test
Code changes
- 
Side effects
- 
- release-4.0
* Fix a bug that service safe points with  infinite TTL may disappear.
> server: Fix the bug that infinite TTL for service safepoint doesn't work

- server/schedule/operator/builder.go
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/pd_test/detail/pd_test/12810/pipeline
```
WARNING: DATA RACE
[2020-11-04T08:01:36.332Z] Write at 0x0000028a9638 by goroutine 146:
[2020-11-04T08:01:36.332Z]   github.com/tikv/pd/server/schedule/filter.(*StoreStateFilter).isTombstone-fm()
[2020-11-04T08:01:36.332Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/schedule/filter/filters.go:250 +0x55
[2020-11-04T08:01:36.332Z]   github.com/tikv/pd/server/schedule/filter.(*StoreStateFilter).anyConditionMatch()
[2020-11-04T08:01:36.332Z]       /home/jenkins/agent/workspace/pd_test/go/src/github.com/pingcap/pd/server/schedule/filter/filters.go:343 +0x1a5
[2020-11-04T08:01:36.332Z] …
```
> operator: fix data race

- pkg/autoscaling/calculation.go
This PR adds a dash in the scaling store label.
Tests
- Unit test
> autoscaling: fix the label of auto scaling group

- server/config/config.go
See https://docs.google.com/document/d/1KKVGJMOY6gmuVrVwqGiA2p0sQL5YqF2zoDbqNSgAhKg/edit#
This PR enables cross table merge by default.
Tests
- Unit test
> config: enable cross table merge by default

- server/cluster/coordinator.go
- server/cluster/metrics.go
We only need to record the latest time spent on patrol regions. No need to use histogram.
This PR replaces histogram with gauge in patrol region.
Tests
- Unit test
> metrics: replace histogram with gauge in patrol region

- server/config/config.go
- server/tso/global_allocator.go
- server/tso/local_allocator.go
- server/tso/tso.go
Close #3126, close #3127, close #3161.
This PR basically refines the Global TSO synchronization algorithm from two parts.
* Make the `resetUserTimestamp` method atomically set the TSO in memory.
* Allow the `resetUserTimestamp` method to ignore and skip the smaller TSO error check.
* Make the `syncMaxTS` method handle the gRPC response more precisely.
* Rewrite the `resetUserTimestamp` method.
* Update the `syncMaxTS` method.
Tests
- Unit test
> tso: refine the Global TSO synchronization algorithm

- metrics/grafana/pd.json
We need to know the time spent on patrolling the region to help us know more about our system.
This PR adds the monitor about patrolling regions. The unit of this metrics is second. After this PR:
Tests
- No code
> metrics: add patrol time monitor

- client/client.go
- client/metrics.go
PR #3122 updated the method `ScatterRegion` to a better version, however, it also broke the backward compatibility. This PR adds it back and you can check the TiDB tests result in pingcap/tidb#20980.
* Add method `ScatterRegion` back.
Tests
- Unit test
> client: fix the compatibility of ScatterRegion method

- .github/workflows/check-dashboard.yaml
- go.mod
* Error: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
* build: use the new env setting method in github action
Tests
- No code
> build: use the new env setting method in github action

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/grpc_service.go
- server/statistics/store.go
- server/statistics/store_collection_test.go
- tests/server/cluster/cluster_test.go
* When changing a `Tombstone` store to `Up` or `Offline`, if the `cluster-version` has been upgraded at this time, the operation should fail.
* The store of lower version is no longer allowed to change from `Tombstone` back to `Up`.
* Fix the bug that restarting the store will cause store-limit and statistics to be reset.
Tests
- Unit test
- The store of lower version is no longer allowed to change from `Tombstone` back to `Up`.
- Fix the bug that restarting the store will cause store-limit and statistics to be reset.
> server: check the store version when changing tombstone status

- pkg/movingaverage/max_filter.go
- pkg/movingaverage/max_filter_test.go
- pkg/movingaverage/median_filter_test.go
Add `MaxFilter` that returns the maximum value in a past time window.
- Unit test
> movingaverage: add max filter

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- tests/server/cluster/cluster_test.go
Signed-off-by: qupeng <qupeng@pingcap.com>
Check and update cluster version on a store becomes tombstone.
Tests
- Unit test
Code changes
Side effects
* check cluster version on stores become tombstone
> check cluster version on store tombstone

- tools/pd-tso-bench/main.go
After running tso-bench, Ctrl-C cannot exit.
Use a timer to check if the test exceeds the time.
Tests
- Manual test
> tools: fix tso bench cannot exit

- server/schedulers/hot_region.go
- server/schedulers/shuffle_hot_region.go
As `hotPeerFilterType` is always `mixed`, we can remove it.
`hotRegionThreshold` is only used when `hotPeerFilterType` is not `mixed` so we can remove it too.
Removed unused code to make it easier to read. We can add it back in the future if we want it again.
Tests
- Unit test
> hot scheduler: remove unused code

- server/statistics/hot_cache.go
`GetFilledPeriod` may return wrong value. It should only affect tests.
check kind and return the corresponding value.
Tests
- Unit test
> statistics: fix GetFilledPeriod

- server/region_syncer/client.go
Signed-off-by: Xintao <hunterlxt@live.com>
fix "Got too many pings" GRPC error in sync region client. We should ensure that the grpc parameters are consistent on the client and server sides. Etcd server cannot set `PermitWithoutStream` so it's false by default.
close https://github.com/tikv/pd/issues/3230
make `PermitWithoutStream` false in region_syncer client.
- Fix "Got too many pings" GRPC error in sync region client-side
> Fix "Got too many pings" GRPC error in sync region client-side

- server/grpc_service.go
Fix the wrong use of `validateInternalRequest`.
* `SplitRegions` is not an internal request, it should use `validateRequest` instead.
* `GetDCLocations` is an internal request that may be started by a PD follower, so the sender check is not necessary here.
Tests
- Unit test
> server: fix the wrong use of validateInternalRequest

- server/api/member.go
- server/member/member.go
- server/tso/allocator_manager.go
- tests/server/member/member_test.go
Signed-off-by: Riptide3 <riptide.yzy@gmail.com>
Close #3239. In this issue we want a method (e.g. a `pd-ctl` command) to delete the old `dc-location` info persisted in the etcd, however, we may only use it when a PD is deleted.
This PR modified the process of deleting a PD member to automatically delete its `dc-location` info also. So we can achieve the same goal without introducing a redundant command.
Tests
- Unit test
> member: delete its dc-location info while deleting a member

- Makefile
- scripts/check-missing-tests.sh
In macOS, there are two problems with the `scripts/check-missing-tests.sh`.
* If you don't specify a directory, `grep` will try to search in the standard input, but the recursive search does not make sense there.
* `dirname` on macOS only takes a single pathname.
Update the `check-missing-tests.sh`.
Tests
- Unit test
- Manual test
> scripts: make check_missing_tests compatible with macOS

- tools/pd-tso-bench/main.go
Signed-off-by: ZenoTan <zenotan1998@gmail.com>
Add avg latency metric in tso-bench.
Store avg latency in metrics, output it in the report.
Tests
- Manual test
> tso: add avg latency metric in tso-bench

- tests/pdctl/scheduler/scheduler_test.go
- tools/pd-ctl/pdctl/command/scheduler.go
Closes https://github.com/tikv/pd/issues/3241
This PR improves the output when there is no such scheduler.
Tests
- Unit test
- Improve the output of `scheduler config` when there is no scheduler
> tools: improve the output of scheduler config when there is no scheduler

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/coordinator_test.go
- server/schedule/operator_controller_test.go
- server/schedulers/balance_test.go
Currently, we use 1GB storage size and 10M region size for tests. It is different from the real configuration.
Use 100GiB storage size and 96MiB region size by default.
Tests
- Unit test
> mockcluster: use realistic store size and region size in unit tests

- .deepsource.toml
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
Tests
- Unit test
- No code
Code changes
Side effects
> Add deepsource analyze

- pkg/autoscaling/prometheus_test.go
- server/cluster/coordinator.go
- server/schedule/filter/filters.go
- server/schedule/region_splitter.go
- server/schedulers/hot_region.go
- server/tso/allocator_manager.go
- server/tso/global_allocator.go
- tools/pd-analysis/analysis/transfer_counter.go
Making empty slices is somewhat dangerous in some cases. https://github.com/tikv/pd/issues/3272 gives an example.
replace `x = make([]T, 0)` with `var x []T`.
Tests
- Unit test
- 
> *: avoid making empty slices

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/statistics/hotstat.go
`HotCache` and `StoreStats` are always used together. Wrap them up can make it easier to use.
wrap `HotCache` and `StoreStats` with `HotStat`.
Tests
- Unit test
> statistics: merge HotCache and StoreStats

- client/client.go
- client/client_test.go
Signed-off-by: leoppro <zhaoyilin@pingcap.com>
Fix the PD client could be blocked in some cases
There are two levels of context in PD client: `client context` and `tso request context`.
the `tsoRequest.Wait()` function could be blocked when the `client context` is canceled because the `Wait()` function haven't listened the `client context`
the version of PD server: v4.0.8
before this PR:
```
Start benchmark #0, duration: 5s
Create 3 client(s) for benchmark
count:768290, max:9, min:0, avg:0, >1ms:34372, >2ms:2037, >5ms:457, >10ms:0, >30ms:0 >50ms:0 >100ms:0 >200ms:0 >400ms:0 >800ms:0 >1s:0
count:800952, max:9, min:0, avg:0, >1ms:96750, >2ms:13593, >5ms:1495, >10ms:0, >30ms:0 >50ms:0 >100ms:0 >200ms:0 >400ms:0 >800ms:0 >1s:0
count:745906, max:8, min:0, avg:0, >1ms:12877, >2ms:3652, …
```
> client: fix the pd client could be blocked in some cases

- errors.toml
- pkg/errs/errno.go
- server/auth/auth.go
- server/auth/auth_test.go
- server/auth/role.go
- server/auth/role_test.go
- server/auth/user.go
- server/auth/user_test.go
- server/auth/util.go
- server/auth/util_test.go
Signed-off-by: PhotonQuantum <self@lightquantum.me>
ref: https://github.com/tikv/tikv/issues/8621
server/auth: implement user & user manager.
Related PR: #3256 
server/auth `userManager` is implemented to handle user-related CRUD operations, including querying users in memory, loading them from etcd and persisting them to etcd.
Tests
- Unit test
Code changes
- Has persistent data change (etcd)
> server/auth: implement user & user manager.

- server/election/leadership.go
- server/grpc_service.go
- server/member/member.go
- server/server.go
- server/tso/allocator_manager.go
- server/tso/local_allocator.go
- tests/cluster.go
If you check the leader immediately after the campaign failed by `leadership.Check()`, it will return true wrongly because the lease is not expired yet. And to be more specific, this bug could cause a PD to make a non-leader Local TSO Allocator participate in a Global TSO synchronization, which will make the synchronization fail, right after the campaign failed. This PR will fix this problem.
Also, I rearrange the logic in `allocatorLeaderLoop` to reduce the RPC requests and etcd IO, which should improve the performance.
* Merge `IsStillLeader` and `IsLeader` methods, they are doing the same thing.
* Improve the leader check to make it more precise.
* Rearrange the logic in `allocatorLeaderLoop` to reduce the RPC requests and etcd IO.
Tests
- …
> election, member, tso: fix the leader check bug and refine the logic

- server/tso/allocator_manager.go
Revising the defer `Stop` in order to avoid goroutine leak.
Tests
> server: fix goroutine leak in allocatorLeaderLoop

- pkg/etcdutil/etcdutil.go
- pkg/etcdutil/etcdutil_test.go
- server/election/leadership_test.go
- server/tso/allocator_manager.go
- server/tso/global_allocator.go
- server/tso/tso.go
- tests/server/tso/allocator_test.go
- tests/server/tso/global_tso_test.go
- tests/server/tso/local_tso_test.go
- tests/server/tso/manager_test.go
Refine the codes of TSO and TSO tests.
* Add and merge some common methods.
* Refine the codes.
* Add and adjust some comments.
Tests
- Unit test
> tso: refine the codes of TSO and TSO tests

- server/id/id.go
- server/server.go
- tests/server/id/id_test.go
This PR tries to make the id monotonic since there are many components that depend on this property. ref: https://github.com/tikv/pd/issues/3303
Tests
- Unit test
> id: fix the id allocator is not monotonic

- scripts/run-tls
Add a helper for running locally with TLS
Tests
I tested with certs generated by [this PR](https://github.com/tikv/tikv/pull/8829) which is the same as the PingCAP docs. Using grpc_cli with the tikv-ctl certs.
Code changes: None
Side effectsL None
- [TiKV PR](https://github.com/tikv/tikv/pull/8829) - but this is not required
No release note
> scripts: add a helper for running with tls

- server/config/config.go
- server/config/persist_options.go
- server/schedule/operator/builder_test.go
- server/schedule/operator/create_operator_test.go
- server/schedule/operator_controller_test.go
* config: joint-consensus is disabled by default due to experimentation
Code changes
> config: joint-consensus is disabled by default due to experimentation

- server/id/id.go
- tests/server/id/id_test.go
* After the PD restarts, the id will be allocated from 1 again. This bug was introduced by #3305.
* Close [tidb#22117](https://github.com/pingcap/tidb/issues/22117)
* id: fix the bug that id may be duplicated
Tests
- Unit test
> id: fix the bug that id may be duplicated

- tools/pd-ctl/pdctl/ctl.go
Signed-off-by: Shenjun Ma <mashenjun0902@gmail.com>
Issue Number: close #3333 
Problem Summary: When under non-interactive mode, `pd-ctl` should exits with a non-zero code for invalid commands.
modify `func startCmd` to return error.
modify `func MainStart` to check the returned error and set exit code correspondingly.
Tests
1. build `pd-ctl`
2. check the exist code as follow:
``` 
./pd-ctl unknown command 
unknown command "unknown" for "pd-ctl" 
echo $? 
1
```
`pd-ctl` exits with a non-zero code for invalid commands under non-interactive mode.
> pd-ctl: set exit code for invalid command

- server/schedule/checker/replica_checker.go
- server/schedule/checker/replica_checker_test.go
Issue Number: close #3117 
Do not remove the down peer until the normal peers are enough
Tests
- Unit test
Do not remove the down peer until the normal peers are enough
> server/scheduler: Do not remove the down peer until the normal peers are enough

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
- server/schedulers/shuffle_hot_region.go
- server/statistics/hot_cache.go
- server/statistics/hot_peer_cache.go
- server/statistics/hot_peer_cache_test.go
- server/statistics/region_stat_informer.go
Check minHotDegree inside `HotPeerCache` and only return regions that are hot enough so we don't have to consider hotDegree in schedulers.
Tests
- Unit test
> statistics: filter regions by hotDegree

- server/cluster/cluster.go
Related #3076
* cluster: if a tombstone store still has peers, it cannot be removed
Tests
```
curl -X POST 'http://{pd_ip}:{pd_port}/pd/api/v1/store/{store_id}/state?state=Tombstone'
pd-ctl remove-tombstone
```
- If a tombstone store still has peers, make it cannot be removed.
> cluster: if a tombstone store still has peers, it cannot be removed

- README.md
Currently we still use `pingcap/pd` in docker hub to save our image. Closes #3354.
This PR changes it back.
Tests
- No code
> *: fix the misleading docker image address

- metrics/grafana/pd.json
- server/cluster/coordinator.go
- server/schedule/operator/metrics.go
- server/schedulers/balance_region.go
- server/schedulers/metrics.go
- server/schedulers/scatter_range.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_region.go
ref https://github.com/tikv/pd/issues/3350
Add `OperatorLimitCounter` for region-schedule-limit. For the other limit situations, I will add support those in the next several pr.
> scheduler, operator:  support operatorLimitCounter for region-schedule-limit

- metrics/grafana/pd.json
- server/schedule/filter/filters.go
- server/schedule/filter/metrics.go
Add label for `filterCounter`. If the `Filter` filter the `target` by comparing origin store and target store, we can record the origin store id into metrics.
Then we can query the metrics like this:
By this way, we can easily judge whether the filter is reasonable.
Tests
- Unit test
> filter: add label for filterCounter

- pkg/mock/mockcluster/mockcluster.go
- server/schedule/opt/healthy.go
- server/schedulers/balance_region.go
- server/schedulers/balance_test.go
After `drop table` or such kind of operation, there might be a large number of empty regions which cannot be merged immediately. The balance region scheduler will balance them if the stores' size have the difference. In this case, it may cause a lot of balance operation which affect the performance.
This PR will skip the empty region when selecting the region.
Tests
- Unit test
> scheduler: do not balance the empty regions

- client/client.go
- pkg/tsoutil/tso.go
- tests/client/client_test.go
Some type assertions in the PD client are not safe. This PR fixs them.
Make sure the `interface{}` is not nil before we do the type assertion.
Tests
- Unit test
> client: avoid the potential PD client panic

- server/core/storage.go
- server/core/storage_test.go
- server/grpc_service.go
- tests/client/client_test.go
Signed-off-by: MyonKeminta <MyonKeminta@users.noreply.github.com>
Fixes #3366
Though we did a fix in PR #3146 , there's still a problem for clusters upgraded from older version, where the gc_worker's service safepoint may be invalid or missing and there are other service safepoints in the cluster.
Checks if "gc_worker"'s service safepoint exist and has a infinite TTL every time loading safepoints, and tries to fix it if possible.
Tests
- Unit test
Code changes
- 
Side effects
- release-4.0
> server: Auto fix gc_worker's service safepoint for upgraded clusters

- server/tso/global_allocator.go
- tests/cluster.go
- tests/server/tso/global_tso_test.go
- tests/server/tso/local_tso_test.go
Fix a bug that will cause the Global TSO generation to be critically wrong. If `maxTSO.Logical` is bigger than `maxLogical`, it will be set to zero but without adding the count.
Add the count to `maxTSO.Logical` after being set to zero.
Tests
- Unit test
> tso: fix a global TSO generation bug

- server/metrics.go
- server/server.go
Add PD server info in Prometheus metrics. This is use for DBaaS metrics.
related PR: https://github.com/pingcap/tidb/pull/22556
N/A
Tests 
```shell
▶ bin/pd-server
▶ curl '127.0.0.1:9090/api/v1/query?query=pd_server_info&time=2021-01-27T06:15:00.781Z'
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"__name__":"pd_server_info","hash":"cbb89ec085979727cf1250aef92fe3c6ff4e63ee","instance":"127.0.0.1:2379","job":"pd","version":"v4.0.0-rc.2-434-gcbb89ec0-dirty"},"value":[1611728100.781,"1611728088"]}]}}%
```
Side effects
- N/A
- N/A
> metrics: add server info metric

- errors.toml
- go.mod
- go.sum
- pkg/errs/errno.go
- server/api/operator_test.go
- server/api/store.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/core/store.go
- server/core/store_option.go
- server/statistics/store.go
- tests/client/client_test.go
- tests/server/cluster/cluster_test.go
It is part of #3076 
This PR support to offline a store and set it physically destroyed which means this store can never up and we can start a new store with the same address 
- The API to offline a store
```
DELETE /store/{id}?force=${force}
```
force is a boolean value:
- true: means the store shouldn't be up again and PD can remove it, also we can up a new store with the same address
- false: means the store is offline, it can be up again.
Tests
- Unit test
Code changes …
> server/api:support offline a store with physically destroyed 

- server/schedulers/balance_test.go
- server/schedulers/scatter_range.go
Closes https://github.com/tikv/pd/issues/3356
This PR fixes the limit constriction for scatter range scheduler.
Tests
- Unit test
- Fix the limit constriction of the scatter range scheduler
> scheduler: fix scatter range scheduler limit

- server/cluster/cluster.go
- server/config/persist_options.go
- server/handler.go
- tests/pdctl/store/store_test.go
The store limit cannot persist due to we only change the value in the memory. Close #3382.
This PR persists the store limit once it changes and if persistence fails, we will roll back to the original one.
Tests
- Unit test
- Fix the issue that the store limit cannot be persisted
> config: fix the store limit cannot be persisted

- server/election/leadership.go
- server/tso/allocator_manager.go
- server/tso/local_allocator.go
- tests/cluster.go
- tests/server/tso/manager_test.go
close https://github.com/tikv/pd/issues/3386
During `leaderCampaign`, the `next-leader-key` should be considered as `Cmp` so that the`next-leader-key` will be guaranteed 
Tests
- Unit test
> tso: make next-leader-key guaranteed by etcd txn

- server/server.go
- server/tso/allocator_manager.go
- tests/client/client_test.go
- tests/cluster.go
* Fix a bug that causes `TestLeaderTransfer` test to cost too much time and refine the code logic.
* Fix the Global TSO Allocator initialization bug which will cause the new PD leader after transferring will be unable to provide TSO service.
* Fix `TestLeaderTransfer` test which will take too long time to run before by using `ResignLeader()`.
* Move Global TSO Allocator initialization to `campaignLeader()`.
Tests
- Unit test
> test, tso: fix test and the Global TSO Allocator initialization bug

- client/client.go
- go.mod
- go.sum
- server/tso/global_allocator.go
- server/tso/tso.go
- tests/client/client_test.go
- tests/cluster.go
- tests/server/tso/global_tso_test.go
Close #3374 and refine the TSO uniqueness tests.
* Make PD client consider the suffix of Local and Global TSO while doing the computing.
* Make the `CheckTSOUnique` become a method of `TestCluster`.
Tests
- Unit test
pingcap/kvproto#713
> tso, client: make the TSO computing unique

- client/client.go
In low-cpu resource env, the dispatcher for the `global` might haven't been initialized after the global tso has been requested.
During `NewClient.....`, we can create global dispatcher before `tsloop`
*  No release note
> client: revise pdclient dc dispatcher

- tests/dashboard/service_test.go
- tests/pdctl/cluster/cluster_test.go
- tests/pdctl/completion/completion_test.go
- tests/pdctl/config/config_test.go
- tests/pdctl/health/health_test.go
- tests/pdctl/helper.go
- tests/pdctl/hot/hot_test.go
- tests/pdctl/label/label_test.go
- tests/pdctl/log/log_test.go
- tests/pdctl/member/member_test.go
- tests/pdctl/operator/operator_test.go
- tests/pdctl/region/region_test.go
- tests/pdctl/scheduler/scheduler_test.go
- tests/pdctl/store/store_test.go
- tests/pdctl/tso/tso_test.go
Signed-off-by: xhe <xw897002528@gmail.com>
Nobody is using the returned command struct. Remove it. It is equivalent according to https://github.com/spf13/cobra/blob/master/command.go#L899-L902.
Tests
- Unit test
- No code
> *: no one is using the returned command

- server/server.go
- server/tso/allocator_manager.go
- tests/server/tso/global_tso_test.go
Close #3423.
If a PD leader resigns and becomes leader again, due to the old closed `parentCtx`, the Global TSO Allocator will be reset immediately. To fix this bug, we need to update the `parentCtx` every time we set up the Global TSO Allocator.
Tests
- Unit test
> tso: fix the TSO reset bug after leader change

- client/base_client.go
- tests/client/client_test.go
ref https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/pd_test/detail/pd_test/19200/pipeline/
TestGlobalAndLocalTSO is not stable. This request fix it.
Tests
- Unit test
- No code
Code changes
Side effects
- …
> tests: fix error in TestGlobalAndLocalTSO

- pkg/autoscaling/prometheus.go
autoscaling about tidbSumCPUUsageMetricsPattern is wrong , result is empty.
tidbSumCPUUsageMetricsPattern base on component="tidb",will return the correctt result
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
> autoscaling/prometheus.go tidbSumCPUUsageMetricsPattern problem

- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/hot_peer_cache_test.go
Before PR, we add peer to the hot peer cache when its interval is less than normal, which causes topn will increase a lot when the heartbeat interval is unstable. We calculate the threshold by the 60th item in the hot peer cache, so the threshold will reduce to the default threshold while a lot of peers are added to the hot peer cache.
we add peer to the hot peer cache when its interval is less than normal only when it is hot too.
Tests
- Unit test
> Fix hot peer cache threshold unstable when interval unstable

- server/schedule/checker/merge_checker.go
- server/schedule/checker/merge_checker_test.go
* checker: prevent the regions in split-cache from becoming the target of merge
Tests
- Unit test
- checker: prevent the regions in split-cache from becoming the target of merge
> checker: prevent the regions in split-cache from becoming the target of merge

- server/schedulers/hot_region.go
`hot-region` scheduler may cause PD panic in the following order:
1.  load `storesLoads` before hot region scheduling
```golang
storesLoads := cluster.GetStoresLoads()
```
2. receive new `PutStore` request
```golang
// put Store in grpc_service.go
if err := rc.PutStore(store); err != nil {
return nil, status.Errorf(codes.Unknown, err.Error())
}
```
3. select candidates from `raft.cluster`
```golang
candidates = bs.cluster.GetStores()
```
This will cause make `pickDstStores` panic in following code because `stLoadDetail` didn't have the storeID which candidates hold as it was newly put before.
```golang
detail := bs.stLoadDetail[store.GetID()]
```
Make the candidates should be searched from `stLoadDetail` during hot region schedule
Tests
- Unit …
> schedule: fix panic during hot schedule

- client/client.go
- pkg/grpcutil/grpcutil.go
- server/grpc_service.go
- tests/server/tso/global_tso_test.go
We need to retry several times when the leader connection is failed to avoid unnecessary forwarding.
BTW, since TiKV uses TSO stream in a unary way, it will print lots of logs in the follower which is responsible to forward the requests when there is a network problem.
This PR adds the retry mechanism for connecting the leader when there is a network problem and changes TSO stream log to debug level. 
Tests
- Unit test
- Add the retry mechanism for connecting leader and change the noisy log to debug level
> *: add retry mechanism for connecting leader

- errors.toml
- pkg/errs/errno.go
- server/schedule/operator/builder.go
- server/schedule/operator/create_operator.go
- server/schedule/operator/create_operator_test.go
close #3494 
* operator: allow the joint state region to create `transfer-leader` operator
* operator: force to find the target leader, when creating the leave joint state operator
Tests
- Unit test
- fix the bug that the `joint-state-checker` cannot fix the region containing `offline-peer`
> schedule: fix the bug that the joint state checker cannot fix the region containing offline-peer

- server/api/router.go
It would be easier to construct test cases if we could configure failpoint in runtime. Both TiKV and TiDB support such an API.
This PR adds `/pd/api/v1/fail/` to configure failpoints. 
Tests
First set `GO_FAILPOINTS="github.com/tikv/pd/server/api/enableFailpointAPI=return"` environment variable to enable this API.
Then, we can run HTTP requests like this to set failpoints:
```
curl -X PUT -d "return" http://{PD_ADDR}:2379/pd/api/v1/fail/github.com/tikv/pd/server/tso/systemTimeSlow
```
And we can also get the enabled failpoint list:
```
❯ curl http://{PD_ADDR}:2379/pd/api/v1/fail/
github.com/tikv/pd/server/api/enableFailpointAPI=return
github.com/tikv/pd/server/tso/systemTimeSlow=return
```
Code changes
- …
> server/api: add an API to configure failpoints in runtime

- client/client.go
- server/grpc_service.go
TiKV will get TSO in a fixed interval, while it cannot work well when the network partition happens. This is because after sending the request to the forwarding stream, it will continue to handle the next request. But TiKV uses this streaming method in a unary way, the next request will be EOF which will cancel the forwarding mechanism.
Closes https://github.com/tikv/pd/issues/3500
This PR changes the way to handle forwarding TSO requests to avoid handling the next request before the forwarding stream responds.
Tests
- Manual test
- Fix the problem that get TSO cannot work well in a network partition environment
> server: fix the problem that get tso cannot work well in network partition environment

- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
To close #3504
This pr will skip the region which just transfer leader in `filterHotPeer`.
Tests
- Unit test
Before 
repeat test in #3504 and hot region is stable
Enable Load base split and those new regions can be scheduled.
> schdueler: fix unstable transfer leader in hot scheduler and add some log

- pkg/movingaverage/avg_over_time.go
- pkg/movingaverage/queue.go
- pkg/movingaverage/queue_test.go
- server/core/region_option.go
- server/statistics/hot_peer_cache_test.go
support concurrency safe queue in AvgOverTime
Benchmark Test with concurrency queue
```sh
$ go test -bench=BenchmarkCheckRegionFlow -benchtime=10s                                                     
OK: 11 passed
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/statistics
BenchmarkCheckRegionFlow-4       5084605              1996 ns/op
PASS
ok      github.com/tikv/pd/server/statistics    13.584s
```
Benchmark Test with origin queue
```sh
$ go test -bench=BenchmarkCheckRegionFlow -benchtime=10s
OK: 11 passed
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/statistics
BenchmarkCheckRegionFlow-4       6700020              1814 ns/op
PASS
ok      github.com/tikv/pd/server/statistics    15.019s
```
> movingaverage: support concurrency safe queue in AvgOverTime

- server/grpc_service.go
Sometimes we see the handle tso duration is high in the PD side, which usually caused by the network.
Tests
- Unit test
- metrics: let tso processing time not include consumption on the network
> metrics: let tso processing time not include consumption on the network

- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
ref https://github.com/tikv/pd/issues/3521
the problem is when offline a store, we may add learner multiple times if the operator is timeout.
Tests
- Unit test
> checker: priority to fix orphan peers 

- server/server.go
- tests/pdctl/config/config_test.go
Compatible with 4.0 default behavior，the default config can set with :
```
config set max-replicas xxx
config set location-labels xxx,xxx
```
Tests
- Unit test
> *: let location-labels works if only exist the default rule

- go.mod
- go.sum
Remove some unnecessary replaces in `go.mod`.
* Replacing `github.com/oleiade/reflections` and `github.com/sirupsen/logrus` is due to some related go module bugs, such as oleiade/reflections#14. Now the problems have gone, I think we should remove them.
* Replacing `go.etcd.io/bbolt` is due to that we want to update `bbolt` independently while keeping the `etcd` version the same, so I keep it here.
Tests
- Unit test
> go.*: remove some unnecessary replaces

- server/core/region.go
server: Defer region Clone to String() method so that it doesn't trigger if the logging isn't actually happening
Signed-off-by: Fred Wulff <frew@cs.stanford.edu>
In running `perf` on our pd node, we see a lot of the time under the cluster lock in https://github.com/tikv/pd/blob/master/server/core/region_tree.go#L99 - the zap library defers the String() method of a Stringer until it's actually doing the logging (so in this case would never execute it since Debug logging is not enabled), but currently the heavyweight proto Clone() method is called on creation. I verified that HexRegionMeta is only used by logging calls, so the change in the actual contents shouldn't affect anything unexpected.
HexRegionMeta now does the clone and hex-ification in String() rather than constructor
Tests
- Has …
> server: Defer region Clone to String() method

- metrics/grafana/pd.json
- server/cluster/cluster.go
- server/schedule/metrics.go
- server/schedule/operator_controller.go
- server/statistics/metrics.go
- server/statistics/store_collection.go
Closes #3546 
After this PR:
We can get the current store limit directly from Grafana. Some examples are listed as follow:
change the limit of store 1
offline store 1
Tests
- Manual test 
- Support showing the store limit in Grafana
> metrics: support showing the store limit in Grafana

- server/api/member.go
- server/api/member_test.go
- server/member/member.go
This PR is to solve #3517.
There's no need to resign member when only one member left in etcd cluster, therefore the `ResignEtcdLeader()` should just return in this scenario.
Tests
- Unit test
Origin:  
Fixed:
> api: fix resign myself error

- metrics/grafana/pd.json
- server/schedule/filter/filters.go
- server/schedule/metrics.go
- server/schedule/region_scatterer.go
> schedule: add metrcis for region scatter

- server/core/store_option.go
- server/core/store_stats.go
- server/schedule/range_cluster.go
Fix #3598
#3598 are caused with two problems, this pr fix one, another is #3597
Tests
- Unit test
- Avoid unexpected statistic modify after adding scatter region scheduler
> cluster: avoid unexpected statistic modify in range cluster

- server/core/store.go
issue: #3589
core regionScoreV2 calculator, store's score will increase rapidly when it disk space less than F 
Tests
Code changes
Side effects
- modify score calculator to satisfy isomerous stores
> core: change score calculator in few disk space to avoid offline earlier

- server/cluster/cluster.go
- server/core/basic_cluster.go
- server/core/store.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/operator_controller.go
- server/statistics/hot_peer_cache_test.go
Remove some duplicated code.
Just as above says.
Tests
- Unit test
> *: simplify some code

- server/config/persist_options.go
- server/server.go
- server/statistics/store_collection.go
Closes #3601 
This PR uses `Clone` to get the config.
Tests
- Unit test
> *: fix the data race problem

- server/tso/global_allocator.go
- server/tso/local_allocator.go
- server/tso/tso.go
* Fix the bug that causes TSO fallback.
* Fix the problem of Local TSO physical time advancing too fast.
`typeutil.SubTimeByWallClock` will use the nanosecond to compare the physical time, though the smallest unit of TSO is millisecond, there is a possibility that on the millisecond level it's the same but on nanosecond level is different when updating the physical time of TSO while restoring the logical time, which will be a fallback for TSO (physical time remains unchanged, logical time goes to 0).
If `enable-local-tso` is false, this bug won't happen because we will call `setTSOPhysical` every `50ms` at least, the interval is big enough to avoid this problem. However, in Local TSO, the TSO may be written frequently by the Global TSO …
> tso: fix the bugs of TSO fallback and Local TSO physical time advancing too fast

- server/tso/global_allocator.go
- server/tso/tso.go
For now, we only know that the sync is failed and which DCs are unsynced, but we don't know which phase it failed on.
```
[2021/04/22 00:41:32.000 +00:00] [ERROR] [client.go:473] ["[pd] getTS error"] [dc-location=global] [error="[PD:client:ErrClientGetTSO]rpc error: code = Unknown desc = [PD:tso:ErrSyncMaxTS]sync max ts failed, unsynced dc-locations found, synced dc-locations: [cross-region-chaos-1619051746-dc-1 cross-region-chaos-1619051746-dc-3], unsynced dc-locations: [cross-region-chaos-1619051746-dc-2]"] [stack="github.com/pingcap/log.Error\n\t/go/pkg/mod/github.com/pingcap/log@v0.0.0-20201112100606-8f1e84a3abc8/global.go:42\ngithub.com/tikv/pd/client.(*client).handleDispatcher\n\t/go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20210225143804 …
```
> tso: refine the err handling and log of TSO

- server/tso/global_allocator.go
- server/tso/tso.go
Part of #3633.
* Make sure the PD leadership before we return a Global TSO response.
* Remove TSO resetting process in Global TSO generation.
Tests
- Unit test
> tso: check leadership before generating a Global TSO response

- server/server.go
- server/tso/allocator_manager.go
Only run Local TSO related daemons when `EnableLocalTSO` is true.
Check `EnableLocalTSO` flag before running these daemons.
Tests
- Unit test
> tso: only run Local TSO related daemons when EnableLocalTSO

- server/tso/allocator_manager.go
- tests/cluster.go
- tests/server/tso/allocator_test.go
#3634 makes the TSO Allocator Manager only run the Local TSO daemons when `EnableLocalTSO` is true. This PR fixes some problems the previous change has and adds a test for it.
* `am.ClusterDCLocationChecker()` should run even `EnableLocalTSO` is false to check and maintain the cluster DC info because this kind of PDs could also become PD leaders to allocate the Global TSO.
* Add a test case for this change. 6 PDs while only 3 of them enable Local TSO.
Tests
- Unit test
> tso: test: refine and add a test for EnableLocalTSO

- pkg/typeutil/time.go
- pkg/typeutil/time_test.go
- server/tso/tso.go
Fix the TSO fallback caused by `resetUserTimestamp`.
In the previous code, we use the nanosecond to compare the next physical with TSO physical in memory, which will cause a TSO fallback in such case:
```
second    |ms |ns  logical
now  1619094171|741|10     15
next 1619094171|741|00     10
```
While also `ignoreSmaller` flag is true, the next TSO will escape from the comparison check and make a TSO fallback eventually.
Tests
- Unit test
> tso: fix the TSO fallback caused by resetUserTimestamp

- server/tso/global_allocator.go
Fix the bug that `maxTSO` may be changed unexpectedly in retry loop.
If `maxTSO` is changed to non-empty in the collecting phase and fails because an unsynced DC is found, retry will make it enter the writing phase instead of another new collecting due to `maxTSO` is not empty anymore. We should keep `maxTSO` remaining the same every time we retry.
Tests
- Unit test
> tso: fix the bug that maxTSO may be changed unexpectedly in retry loop

- server/config/config.go
- server/tso/tso.go
- tests/server/tso/tso_test.go
Part of #3633. We need to ensure the TSO consistency when the Local/Global cluster back to a single-point normal TSO. 
* For the Global TSO, `loadTimestamp` will get all Local and Global TSO time windows persisted in etcd and choose the biggest one.
* For the Local TSO, `loadTimestamp` will only get its own dc-location time window persisted before.
Tests
- Unit test
> tso: ensure cluster TSO consistency after Local TSO is turned off

- Makefile
Not all systems have bash installed in `/bin/bash`.
```
[dvaneeden@freebsd-tidb ~]$ which bash
/usr/local/bin/bash
[dvaneeden@freebsd-tidb ~]$ uname -sr
FreeBSD 13.0-RELEASE
```
Instead of hardcoding this as `/bin/bash` use `$(shell which bash)`
Tests
Run a `gmake build` on FreeBSD 13.0
> Makefile: don't rely on hardcoded path for bash

- tests/pdctl/config/config_test.go
- tools/pd-ctl/pdctl/command/config_command.go
There are too many configurations that are barely used, we can hide these configurations to improve UE.
This PR deletes some fields for the output of pd-ctl config show command.
Tests
- Manual test 
After this PR:
```
» config show
{
"replication": {
"enable-placement-rules": "true",
"isolation-level": "",
"location-labels": "",
"max-replicas": 3,
"strictly-match-label": "false"
},
"schedule": {
"enable-cross-table-merge": "true",
"enable-joint-consensus": "true",
"high-space-ratio": 0.7,
"hot-region-cache-hits-threshold": 3,
"hot-region-schedule-limit": 4,
"leader-schedule-limit": 4,
"leader-schedule-policy": "count",
"low-space-ratio": 0.8,
"max-merge-region-keys": 200000,
"max-merge-region-size": 20,
"max-pending-peer-count": 16, …
```
> tools: hide some barely used configurations

- server/cluster/coordinator.go
- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
- server/schedulers/utils.go
Currently, the pending influence holding by hot region scheduler is classified by the `resourceType`, not `read/write type`.
This will cause the write-peer and write-leader can't see each other's influence(either do read-peer and read-leader in the future)
1. unify hot region scheduler's influence
2. make read/write pending influence can be summarized by each hot schedule operator
Tests
- Unit test
* No release not
> schedulers: unify hot region scheduler's influence

- pkg/autoscaling/calculation_test.go
- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/core/kind.go
- server/core/peer.go
- server/replication/replication_mode_test.go
- server/schedule/checker/joint_state_checker_test.go
- server/schedule/checker/learner_checker_test.go
- server/schedule/checker/merge_checker_test.go
- server/schedule/checker/replica_checker_test.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/filter/filters_test.go
- server/schedule/hbstream/heartbeat_streams_test.go
- server/schedule/operator/builder_test.go
- server/schedule/operator/create_operator_test.go
- server/schedule/operator/operator_test.go
- server/schedule/operator_controller_test.go
- server/schedule/opt/healthy_test.go
- server/schedule/region_scatterer_test.go
- server/schedule/region_splitter_test.go
- server/schedulers/balance_test.go
- server/schedulers/hot_test.go
- server/schedulers/scheduler_test.go
- server/statistics/hot_cache.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/hotstat.go
- server/tso/global_allocator.go
- server/tso/tso.go
make hotPeerCache maintained by peer level
> statistics: support hotPeerCache maintained in Peer level

- server/api/member_test.go
- server/api/scheduler.go
- server/server.go
According to the [overview of package "net/http"](https://golang.org/pkg/net/http/#Response), the client must close the response body when finished with it. This could be detected by:
```shell
golangci-lint run -E bodyclose
```
Tests
- Unit test
> *: close the response body when finished with it

- pkg/autoscaling/calculation.go
- pkg/autoscaling/calculation_test.go
- server/api/router.go
- server/api/server.go
- server/api/store_test.go
- server/cluster/cluster_test.go
- server/cluster/coordinator_test.go
- server/encryptionkm/key_manager.go
- server/grpc_service.go
- server/schedule/checker/rule_checker.go
- server/schedulers/balance_test.go
- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
- server/schedulers/scheduler_test.go
- server/tso/allocator_manager.go
- tests/client/client_tls_test.go
- tests/server/cluster/cluster_test.go
- tests/server/cluster/cluster_work_test.go
- tools/pd-analysis/analysis/transfer_counter.go
Clean up useless parameters that are detected by:
```shell
golangci-lint run -E unparam
```
Clean up useless parameters.
Tests
- Unit test
> *: clean up useless parameters

- server/core/store.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_leader.go
- server/schedulers/scheduler_test.go
close: https://github.com/tikv/pd/issues/3660 
Fix the probles:
1. create a cluster with 4 TiKV using TiUP
2. add evict leader scheduler for one store, e.g. store 2
3. delete store 2 and remove tombstone by using pd-ctl
4. remove evict leader scheduler by using pd-ctl
Panic!
Tests
- Unit test
```release-note
Fix the panic issue about remove evict leader scheduler from a nonexistent store
```
> schedulers: fix the panic issue about remove evict leader scheduler from a nonexistent store

- .github/auto_assign.yml
Synchronize the list of `auto-assign` with `include_reviewers` in `ti-community-blunderbuss`.
Related [ti-community-infra/configs#313](https://github.com/ti-community-infra/configs/pull/313)
Tests
- No code
```release-note
None
```
> github: update auto-assign config

- server/grpc_service.go
Remove unnecessary gRPC forwarding checks.
`SyncMaxTS` and `GetDCLocationInfo` are internal RPC calls that will only be used inside the cluster. So they don't need the forwarding checks.
Tests
- Unit test
```release-note
None.
```
> server: remove unnecessary gRPC forwarding checks

- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
To keep consistent with the original implementation.
This PR adds back the high priority for some kinds of operators.
Tests
- Unit test
```release-note
Fix the priority problems for some kinds of operators
```
> checker: fix the operator priority

- metrics/grafana/pd.json
- server/statistics/hot_cache.go
- server/statistics/metrics.go
Add metrics for the hot cache flow queue status.
Panel in statistics hot write
panel in statistics hot read
```release-note
None
```
> statistics: add metrics for the hot cache flow queue

- server/cluster/cluster.go
- server/server.go
- tests/server/member/member_test.go
Fix https://github.com/tikv/pd/issues/3697
When the store's number is 180. we resign pd leader  may need one minute or more to finish elect the new leader:
details replay: https://gist.github.com/disksing/a1bf78007b674da7e15b52a9e25eb3a5 
make leader can be lost lease as soon as possible
Tests
```release-note
Fix the issue that leader re-election be slow when there are many stores
```
> server: make leader can lost lease as soon as possible

- tests/pdctl/tso/tso_test.go
- tools/pd-ctl/pdctl/command/tso_command.go
Before:
```
$ ./bin/pd-ctl tso 425223599947776000
system:  2021-05-27 09:08:24 +0200 CEST
logic:  0
```
After:
```
$ ./bin/pd-ctl tso 425223599947776000
system:  2021-05-27 09:08:24 +0200 CEST
logic:   0
```
Tests
Look at `pd-ctl tso <tso>` output
```release-note
None
```
> command: Align TSO output format

- server/core/region.go
- server/core/region_test.go
Peers need to be sorted every time in `shouldRemoveFromSubTree`.
Sort Peers at the time of creation, and use `SortedPeersEqual` to compare Peers.
Tests
- Unit test
```release-note
None
```
> core: sort peers when creating RegionsInfo

- tests/dashboard/service_test.go
- tests/pdctl/cluster/cluster_test.go
- tests/pdctl/completion/completion_test.go
- tests/pdctl/config/config_test.go
- tests/pdctl/health/health_test.go
- tests/pdctl/helper.go
- tests/pdctl/hot/hot_test.go
- tests/pdctl/label/label_test.go
- tests/pdctl/log/log_test.go
- tests/pdctl/member/member_test.go
- tests/pdctl/operator/operator_test.go
- tests/pdctl/region/region_test.go
- tests/pdctl/scheduler/scheduler_test.go
- tests/pdctl/store/store_test.go
- tests/pdctl/tso/tso_test.go
- tools/pd-ctl/pdctl/ctl.go
close #3419 
Changes:
1. Unite `getBasicCmd`, `getMainCmd` and `getInteractCmd` into `GetRootCmd`. Removed `GetEcho`, `Start`, `pdctlRun`, `startCmd`. Only `MainStart` is left.
2. Removed unused `detach` flag, `hiddenFlag` function.
3. Make flags like `cacert` and more local
Tests
- Unit test
> pd-ctl: expose GetRootCmd for integration tests, clean up interfaces

- server/core/region.go
- server/core/region_test.go
- server/core/region_tree.go
- server/core/region_tree_test.go
The functions of `regionTree`, `regionSubTree`, and `regionMap` are duplicated.
* Remove unnecessary `totalKeys` statistics
* Merge `regionSubTree` into `regionTree`
* Remove the statistical function of `regionMap`
Tests
- Unit test
```release-note
None
```
> core: simplify regionSubTree and regionMap

- server/api/trend.go
- server/schedulers/utils.go
- server/statistics/hot_regions_stat.go
After #3591, we use []float64 to represent hot peer loads, but output is no friendly.
After this pr:
Tests
- Unit test
```release-note
None.
```
> statistics: more friendly output

- server/grpc_service.go
- server/tso/global_allocator.go
Close #3732.
Plus 1 to the logical part to prevent the Global TSO fallback than the previous Local TSO after being differentiating with a suffix.
Tests
- Unit test
```release-note
None.
```
> tso: fix the Global TSO fallback bug

- pkg/mock/mockcluster/config.go
- server/schedule/checker/replica_checker.go
- server/schedule/checker/replica_checker_test.go
- server/schedule/checker/replica_strategy.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
Fix https://github.com/tikv/pd/issues/3705
Root cause of the bug:
Before 4.0, PD can first remove the down replica then add a new peer replica.
In 5.0, we restricted that down replicas can only be repaired by replacing in order to maintain a sufficient number of replicas during the process. And replacing comes with the restriction that the isolation level could not be worse than before.
- Rename `SelectStoreToReplace` to `SelectStoreToFix` and remove the use of `LocationSafeguard` filter.
- add tests.
Tests
- Unit test
- Need to cherry-pick to the release branch (release-5.0)
```release-note
Fix the issue that when all tikv in a zone are offline or down, PD does not move replicas to another zone
```
> checker: allow location placement get worse when fix replica

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/config/config.go
- server/config/config_test.go
- server/config/persist_options.go
deprecate `trace-region-flow`
Tests
- Unit test
situation 1
```
➜  pd git:(remove-trace-flow) ✗ ./bin/pd-ctl config set trace-region-flow false
Success!
➜  pd git:(remove-trace-flow) ✗ ./bin/pd-ctl config show all |grep flow        
"trace-region-flow": "false"
➜  pd git:(remove-trace-flow) ✗ ./bin/pd-ctl config show all |grep flow
"flow-round-by-digit": 9223372036854775807
➜  pd git:(remove-trace-flow) ✗ ./bin/pd-ctl config set flow-round-by-digit 9
Success!
➜  pd git:(remove-trace-flow) ✗ ./bin/pd-ctl config show all |grep flow      
"flow-round-by-digit": 9
➜  pd git:(remove-trace-flow) ✗ ./bin/pd-ctl config show all |grep flow      
"flow-round-by-digit": 9
```
situation 2 …
> *: make flow-round-by-digit compatible with trace-region-flow

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/core/basic_cluster.go
- server/core/region.go
- server/core/region_test.go
- server/core/region_tree.go
- server/core/region_tree_test.go
- server/schedule/range_cluster.go
- server/schedulers/scheduler_test.go
* The current heartbeat processing speed can be increased.
* Move `hotStat` out of the read lock
* Move `storage.DeleteRegion` out of the write lock
* Simple processing logic is used for RegionHeartbeat that only has statistics updated.
Tests
- Unit test
```release-note
None
```
> core: optimize the processing speed of RegionHeartbeat

- server/schedulers/balance_test.go
- server/schedulers/utils.go
Improve `GetStoreRegionCount`
Part of https://github.com/tikv/pd/issues/3744
Calculate `tolerantSizeRatio` when the `balancePlan` is created and reuse it later.
Tests
- Unit test
```release-note
None
```
> schedulers: avoid recalculate tolerantRatio

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/cluster/cluster_worker_test.go
- server/cluster/coordinator_test.go
- server/statistics/hot_cache.go
- server/statistics/hot_cache_task.go
- server/statistics/hot_peer_cache.go
- server/statistics/hotstat.go
- tests/pdctl/scheduler/scheduler_test.go
try to remove mutex
We use mutex in hotPeerCache which may cause mutex contention.
This request remove the mutex and refactor `flowItem` with a proper way.
I used `pd-heartbeat-bench` to test pd heartbeat (1 server / 6 cpu), here is the result
```
v5.0.0
Update speed of each category:
Requests/sec:      8263.3143
Save-Tree/sec:        0.0000
Save-KV/sec:          0.0000
Save-Space/sec:       0.0000
Save-Flow/sec:     4131.6572
Skip/sec:          4131.6572
```
```
master
Update speed of each category:
Requests/sec:      6137.2065
Save-Tree/sec:        0.0000
Save-KV/sec:          0.0000
Save-Space/sec:       0.0000
Save-Flow/sec:     3068.6033
Skip/sec:          3068.6033
```
```
This request
Update speed …
```
> statistics: remove mutex in hotPeerCache

- .github/workflows/check-dashboard.yaml
- .github/workflows/pd-tests.yaml
ci: make github action effective for `release-5.1`
Tests
- No code
Code changes
Side effects
```release-note
None
```
> ci: make github action effective for release-5.1

- server/schedule/region_scatterer.go
- server/schedule/region_scatterer_test.go
As `totalCountByStore` calling the function `getDistributionByGroupLocked`, this function should be procteded by rw mutex otherwise it will cause data race panic
Add mutex to protect it.
Tests
- Unit test
```release-note
Fix pd may get panic during scattering region
```
> schedule: fix race for region scatter

- server/cluster/cluster.go
- server/statistics/hot_cache.go
- server/statistics/hot_cache_task.go
statistics task will hold raftCluster mutex during running which is unnecessary. Also the waiting return channel didn't have buffer which may also block the running the task.
Fix these problems.
Tests
- Unit test
```release-note
None
```
> statistics: fix task might get stuck and hold raftcluster mutex

- server/api/admin.go
- server/api/component.go
- server/api/label.go
- server/api/middleware.go
- server/api/region.go
- server/api/replication_mode.go
- server/api/rule.go
- server/api/stats.go
- server/api/store.go
ref https://github.com/tikv/pd/issues/3753
We use middleware to verify the cluster is created. But the `GetRaftCluster` can return `nil` after the check. For example, when the server is closing.
It can potentially cause server panic.
In middleware, save the `RaftCluster` in request context. So that later we can always take a `RaftCluster` and use.
Tests
- Unit test
```release-note
None
```
> api: save cluster in request context

- server/server.go
Closes #3771.
This PR moves the process of loading TTL configs before starting raftCluster. 
Tests
- Unit test
```release-note
Fix the data race when the scheduler is started before loading TTL configurations
```
> server: fix the data race problem

- metrics/grafana/pd.json
In some cluster, there may be some other etcd instance or other components using etcd. To avoid metrics been affected and lead to false alarms. We can restrict metrics by using `job`.
Add `job="pd"` in expresssion.
Tests
- No code
```release-note
None
```
> metrics: update grafana template

- client/base_client.go
This PR do some tiny refactor for the function `getMembers` in BaseClient
with this PR, we can use `pd/clint` by `go get github.com/tikv/pd/client` 
```release-note
NONE
```
> client/base_client: do tiny refator for the function getMembers

- tools/pd-ctl/pdctl/ctl.go
Seems cobra command does not support interactive mode, that is we need to init a new command every new line in the REPL. 
1. `readlineCompleter` global variables are removed, it is now inlined and created-as-need.
2. `PersistentFlags` from the root command will be inherited in the REPL, pd address for example.
3. Start a new command every new evaluation round.
Tests
- Unit test
```
pd-ctl -i -u http://127.0.0.1:34/
store --help
store
```
Interactive should print normally, and show connection refused on port 34.
```release-note
Fix broken interactive pd-ctl mode
```
> pd-ctl: try to fix interactive mode

- go.mod
- go.sum
Signed-off-by: Xuanwo <github@xuanwo.io>
ref https://github.com/tikv/pd/issues/3780
Fix the wrong usage of go.mod replace.
`replace` in `go.mod` only affects current modules build and other modules that depend on this module will not be effected.
In this PR, I finished following work:
- Remove not used deps (maybe missing `make tidy` in workflow?)
- Specify the version directly instead of `replace` it.
Tests
- No code
```release-note
None
```
> *: Fix the wrong usage of go.mod replace

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
* move part of the code of the hot-region-scheduler to the test package
* remove the useless code in hot-region-scheduler
* fix nil pointer warning
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> scheduler: remove the useless code in hot-region-scheduler

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
- server/schedulers/scheduler_test.go
related #3778 
changes caused by #3820
`OpLeader` and `LeaderScheduleLimit` are no longer judged in `balance-hot-region-scheduler`.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> scheduler: simplify the limit judgment of hot-region-scheduler

- server/grpc_service.go
- server/tso/global_allocator.go
- tests/server/tso/global_tso_test.go
Close #3866.
* Check whether `maxLocalTS` is nil before using it to compare.
* Add retry mechanism for the Global TSO generation. 
Tests
- Unit test
```release-note
None.
```
> tso: fix the Global TSO sync panic and add retry mechanism

- server/schedule/region_scatterer_test.go
Closes #3872.
If `TestScatterGroupInConcurrency` runs over 20 seconds, the store will become disconnected which fails the test.
Tests
- Unit test
```release-note
None
```
> *: make TestScatterGroupInConcurrency more stable

- server/schedule/opt/healthy.go
- server/schedule/opt/healthy_test.go
close #3896 
The current implementation, when using only `isRegionHealthy`, unexpect schedule regions with learners when enabling placement rules.
However, in addition to `isRegionHealthy`, there is also `isReplicated`, which are often used together. When used together, it is actually okay because it will be checked in `isReplicated`.
Only when `isRegionHealthy` is used alone, such as in evict-leader, balance-leader, shuffle-leader, grant-leader and random-merge leaders, only `opt. HealthRegion`, but not `isReplicated`. There is not much difference whether it is allowed or not here.
So, to simplify the semantics and ensure consistent behavior, let `isRegionHealthy` only determine pending peer and down peer.
Tests
- Unit test
```release-note
None
```
> schedule: `isRegionHealthy` only care pending peer and down peer

- pkg/typeutil/comparison.go
- server/cluster/coordinator.go
- server/schedule/filter/filters.go
- server/schedule/region_scatterer.go
- server/schedule/region_scatterer_test.go
- tests/pdctl/operator/operator_test.go
ref https://github.com/tikv/pd/issues/3450
cherry-pick: https://github.com/tikv/pd/pull/3451
Also the code in region scatter is too complex to maintain.
refactor the region scatter to make it simple and fix the reference bug.
After this pr, the result was like following: 
```sh
mysql> create table t(id int);
Query OK, 0 rows affected (0.09 sec)
mysql> SPLIT TABLE t BETWEEN (0) AND (1000000000) REGIONS 200;                                +--------------------+----------------------+
| TOTAL_SPLIT_REGION | SCATTER_FINISH_RATIO |
+--------------------+----------------------+
|                199 |                    1 |
+--------------------+----------------------+
1 row in set (11.89 sec)
mysql> select count(s.region_id) cnt, s.index_name, p.store_id from …
```
> cherry pick #3451 to release-4.0

- server/api/hot_status.go
- server/cluster/cluster.go
- server/core/basic_cluster.go
- server/core/region.go
- server/core/region_test.go
- server/core/region_tree.go
- server/statistics/kind.go
- server/statistics/store.go
- server/statistics/store_collection.go
- server/statistics/util.go
- tests/pdctl/hot/hot_test.go
related #3671 
Count the `write-rate` in the `RegionTree`, and then observe it regularly in `StoreStats`.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> cluster: calculate StoreWriteRate based on the stats of RegionHeartbeat

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- server/schedulers/utils.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- tests/pdctl/scheduler/scheduler_test.go
- tools/pd-ctl/pdctl/command/scheduler.go
The current hotspot identification mainly uses byte and key dimensions, which are not very fit for load requests with high CPU overhead but low hard disk overhead, we plan to add QPS dimension to better describe the distribution of CPU resources.
use qps dimension  as the first priority in  hot region scheduler
Tests
- Unit test
- 
```release-note
use qps dimension  as the first priority in  hot region scheduler
```
> scheduler: use qps priority with multi priorities in hot region scheduler 

- go.mod
- go.sum
Signed-off-by: crazycs <chen.two.cs@gmail.com>
Update `sysutil` in `go.mod` for https://github.com/pingcap/sysutil/pull/31.
Tests 
```release-note
None
```
> *: update sysutil in go.mod to fix panic when search log

- server/statistics/hot_peer_cache.go
- server/statistics/hot_peer_cache_test.go
- server/statistics/util.go
it is similiar with  #3707, After getting the hot read peer information from store heartbeat, a region that previously took two minutes to get cold will take only 20 seconds to get cold, so that the balance leader scheduler will go to the balance hotspot for a more variable load.
for read-peer/write-peer/write-store, the period of filter is 5, but it is 3 for read store.
Tests
- Unit test
```release-note
None.
```
> scheduler: fix anticount and improving the Robustness of Hotspot Statistics

- server/schedulers/hot_region_config.go
- tests/pdctl/scheduler/scheduler_test.go
fix json tag for hot region scheduler config which will cause pd-ctl setting failed.
```release-note
None
```
> scheduler: fix json tag for hot region scheduler config

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- tests/pdctl/scheduler/scheduler_test.go
- tools/pd-ctl/pdctl/command/scheduler.go
write-leader and write-peer need to have different priorities because write leader needs to have balanced metrics that reflect the leader, such as sum of key or qps, but write-peer does not, and write-peer does not necessarily have data on qps.
set different priorities for write-leader and write-peer
Tests
- Unit test
```release-note
None.
```
> scheduler: set different priorities for write-leader and write-peer

- server/schedule/operator/operator.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
- server/schedulers/utils.go
* The current `pendings` and `regionPendings` records duplicate data, and they are each useful.
* The current weight attenuation strategy is unreasonable.
* Misuse of `CreateTime` by the current GC strategy may lead to premature GC.
* unify the use and GC of hot-region's `pendings` and `regionPendings`, no longer related to `CreateTime`.
* `weight` is constant at 1.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> schedulers: unify the use and GC of hot-region's pendings and regionPendings

- server/schedulers/hot_region.go
scheduler: use the store qps stats in the hot-write-leader-balance
Tests
Code changes
Side effects
```release-note
None
```
> scheduler: use the store qps stats in the hot-write-leader-balance

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- server/schedulers/utils.go
* scheduler: fix inaccurate statistics and config
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> scheduler: fix inaccurate statistics and config

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
Previously, we gave priority to the transfer leader and only used the move leader when there was no transfer leader, which is not necessarily the optimal solution, so this pr will be compared uniformly and then selected
Tests
- Unit test
```release-note
unify leaderSolver and peerSolver in hot read scheduler
```
> scheduler: unify leaderSolver and peerSolver in hot read scheduler

- metrics/grafana/pd.json
add `Store write qps` and `Store read qps`
remove `Total written bytes on hot peer Regions`  and `Total read bytes on hot peer Regions`
Tests
- No code
```release-note
None.
```
> metrics: add qps metrics and remove unnecessary metrics

- server/schedulers/hot_region_test.go
* After #3834 , `HotRegionScheduleLimit` only affects `IsScheduleAllowed`, not `Schedule`.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> scheduler: fix some test

- pkg/mock/mockcluster/mockcluster.go
- server/config/config.go
- server/config/persist_options.go
- server/core/store.go
- server/schedule/filter/filters.go
- server/schedule/region_scatterer.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/utils.go
- tests/pdctl/scheduler/scheduler_test.go
scheduler: balance-hot-region-scheduler supports TiFlash
Tests
- Unit test
Code changes
Side effects
```release-note
Support hot-region balance scheduling for TiFlash
```
> scheduler: balance-hot-region-scheduler supports TiFlash

- pkg/mock/mockcluster/mockcluster.go
- server/core/region_option.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- server/schedulers/metrics.go
- server/schedulers/scheduler_test.go
- server/schedulers/utils.go
In the past, for two stores with large differences, it was easy to have redundant scheduling behavior, because as the difference between the two stores approached, the speed might not come down in time, so we limited the speed by adding pending amps, and the closer the two stores were, the fewer regions were allowed to be scheduled at the same time.
Before
After
isTolerance checks source store and target store by checking the difference value with pendingAmpFactor * pendingPeer. This will make the hot region scheduling slow even serialized running when each 2 store's pending influence is close.
Tests
- Unit test
```release-note
None
```
> scheduler: use pending amp in hot region scheduler

- server/api/admin.go
- server/api/admin_test.go
- server/server.go
the `persist-file` API allows to store arbitrary file to disk. It can be dangerous.
accept only JSON file.
Tests
- Unit test
```release-note
None
```
> api: restrict persist-file to only accept JSON data

- pkg/mock/mockcluster/mockcluster.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- server/schedulers/utils.go
- tests/pdctl/scheduler/scheduler_test.go
fix #3959
1. consider evict leader when calc expect
2. reduce the pending amp factor
3. unify qps and query as query, to ensure consistency with the documentation https://github.com/pingcap/docs-cn/pull/6835
Tests
- Unit test
- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn): https://github.com/pingcap/docs-cn/pull/6835
-  - 4.0 5.0 5.1 5.2
```release-note
None.
```
> scheduler: consider evict leader when calc expect

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
scheduler: use compatible config after upgrading for hot-region
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> scheduler: use compatible config after upgrading for hot-region

- server/replication/replication_mode.go
- server/replication/replication_mode_test.go
Fix https://github.com/tikv/pd/issues/3924
start up one zone, and the another zone do not startup.
```
➜  pd git:(master) curl http://127.0.0.1:30058/pd/api/v1/replication_mode/status
{
"mode": "dr-auto-sync",
"dr-auto-sync": {
"label_key": "",
"state": "sync",
"state_id": 4
}
}
```
Tests
- Unit test
```release-note
replication: fix the issue that the state cannot switch to async 
```
> replication: check the up stores to switch to async

- errors.toml
- pkg/errs/errno.go
- server/core/storage.go
- server/schedule/labeler/labeler.go
- server/schedule/labeler/labeler_test.go
- server/schedule/labeler/rules.go
Add labeler implementation and support key-range type label rule.
https://github.com/tikv/pd/issues/3839
Tests
- Unit test
```release-note
None
```
> labeler: add region label

- cmd/pd-server/main.go
- pkg/assertutil/assertutil.go
- pkg/assertutil/assertutil_test.go
- server/api/server_test.go
- server/api/version_test.go
- server/join/join_test.go
- server/server_test.go
- server/testutil.go
- tests/client/client_test.go
- tests/server/member/member_test.go
Signed-off-by: you06 <you1474600@gmail.com>
PD imports [check](https://github.com/pingcap/check) in some un-test packages. This makes a flag pollution like `check.v` appears in production environment, more details can be found in pingcap/tidb#27156.
This PR removes the imports of check lib not in test packages.
Tests
- Unit test
Code changes
Side effects
- 5.0
```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```
> test: move check package into test packages

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster_test.go
- server/cluster/coordinator.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/checker/split_checker.go
- server/schedule/checker/split_checker_test.go
- server/schedule/checker_controller.go
- server/schedule/labeler/labeler.go
Fix https://github.com/tikv/pd/issues/4000
Now that both placement rules and region labels need to split region based on key range, we can extract it to create a `SplitChecker` to handle region splits in the same place.
- add split checker
- remove region split logic from rule checker
- add test
Tests
- Unit test
```release-note
None
```
> schedule: add split checker for region splits

- server/api/region_label_test.go
- server/schedule/checker/merge_checker.go
- server/schedule/checker/merge_checker_test.go
- server/schedule/labeler/labels.go
Fix https://github.com/tikv/pd/issues/4001
When regions are marked `nomerge`, don't merge them.
Also fixed an unstable test.
Tests
- Unit test
```release-note
Support using region labels to control specific regions from being merged.
```
> checker: skip merge regions that are marked nomerge

- server/schedule/filter/filters.go
related #3744， repalce fmt.Sprintf  with strconv.ParseUint to imporve filter performance . 
some itoa  test: https://gist.github.com/evalphobia/caee1602969a640a4530
Tests
- bench test
Code changes
Side effects
```release-note
replace fmt.Sprint with strconv.parseUint64
```
> filter: replace fmt.Sprint with strconv.parseUint64

- server/api/region_label.go
- server/schedule/labeler/labeler.go
- server/schedule/labeler/labeler_test.go
After adding some testings, I realize that TiDB doesn't know how many rules PD has. Once we need to update some rules, we need to provide all IDs related to the table and partitions. In this case, we should return the existed rules and omit the other invalid rule's ID.
Otherwise, we can only get the rule one by one or get all rules stored in PD which may not be a good choice.
Tests
- Unit test
Code changes
```release-note
None
```
> regionlabel: don't return 404 when the id is not existed

- metrics/grafana/pd.json
scheduler some metrics using delta is not correct. 
[delta](https://prometheus.fuckcloudnative.io/di-san-zhang-prometheus/di-4-jie-cha-xun/functions#delta): return the last element - the first element in time zone ,so it could not express the ops 
[rate](https://prometheus.fuckcloudnative.io/di-san-zhang-prometheus/di-4-jie-cha-xun/functions#rate): return the average increase rate in the time zone
replace delta with rate 
Tests
Code changes
Side effects
```release-note
replace delta with rate in scheduler panel
```
> metrics: replace delta with rate

- errors.toml
- metrics/grafana/pd.json
- pkg/errs/errno.go
- pkg/errs/errs_test.go
- server/election/leadership.go
- server/grpc_service.go
- server/tso/global_allocator.go
- server/tso/tso.go
Remove some unnecessary logs from the TSO hot path.
```go
log.Warn("get timestamp too slow", zap.Duration("cost", elapsed))
```
This indicator can be observed through metrics, so it is not necessary to hit the log here.
```go
log.Info("this PD is a new leader, but sync hasn't been completed yet, wait for a while")
```
In past experience, this log has not been very helpful and may be very noisy.
```go
log.Error("invalid timestamp",
zap.Any("timestamp-physical", currentPhysical),
zap.Any("timestamp-logical", currentLogical),
errs.ZapError(errs.ErrInvalidTimestamp))
```
Ditto.
Remove some unnecessary logs from the TSO hot path.
Tests
- Unit test
```release-note
None.
```
> tso, election: remove some unnecessary logs from the TSO hot path

- go.mod
- go.sum
Signed-off-by: Weizhen Wang <wangweizhen@pingcap.com>
Without this fix running a binary can cause a panic, see upstream go issue: golang/go#45702
Bump x/sys so that this project supports go 1.17.
Tests
- Unit test
```
None
```
> *: update sys in go.mod to fix panic when using golang1.17

- tools/pd-tso-bench/main.go
Fix the microsecond precision bug of `pd-tso-bench`. 
* Count the latency that is less than 1 millisecond.
* Use `float64` to calculate.
Tests
- Manual test
```release-note
None.
```
> tools: fix the microsecond precision problem of pd-tso-bench

- server/election/leadership_test.go
- server/election/lease.go
https://github.com/tikv/pd/pull/4044 makes `(*Leadership).Reset()` will set its `lease` to `nil`, which will cause panic due to the `nil` pointer when we call some methods of the `lease`.
Check `lease` itself before we deref it.
Tests
- Unit test
```release-note
None.
```
> election: fix the panic bug of lease

- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
If the fit is fetched from cache, the rule checker will skip checking instead of generating operator.
Tests
- Unit test
```release-note
None
```
> checker: skip generating operator if fit is cached for rule checker

- server/schedule/placement/fit.go
FitRegion will search all possible solutions which will consume much cpu resources while for some common cases the best solution is quite similar for other cases.
early exit searching for some common cases in order to save cpu resource.
Tests
- Manual Bnechmark Test
```sh
3 default peers
BenchmarkFitRegion-4   	 1054921	      1053 ns/op
5 peers
BenchmarkFitRegion-4   	  657933	      1582 ns/op
3 peers with 1 learner
BenchmarkFitRegion-4   	  763387	      1586 ns/op
3 peers in each zone
BenchmarkFitRegion-4   	  696102	      1553 ns/op
```
```sh
3 default peers
BenchmarkFitRegionMoreStores-4   	  829810	      1274 ns/op
5 peers
BenchmarkFitRegionMoreStores-4   	  437342	      2740 ns/op
3 peers with 1 learner
BenchmarkFitRegionMoreStores-4 …
```
> placement: early exit searching during FitRegion

- server/cluster/coordinator_test.go
- server/core/region_storage.go
- server/region_syncer/server.go
- tools/pd-tso-bench/main.go
There are some tickers that are not closed.
Tests
- Unit test
```release-note
None
```
> *: close ticker when function returns

- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
- tools/pd-tso-bench/main.go
fixes https://github.com/tikv/pd/issues/4045
- Need to cherry-pick to the release-5.0
```release-note
None
```
> placement: do not delete orphan peers if some peers selected by RuleFit is down or pending

- server/schedule/checker/replica_checker.go
- server/schedule/checker/rule_checker.go
Fix #4077 
After #3462, `DownSeconds` no longer update with the heartbeat. It will cause the down-peer to not be repaired in time.
Judging that the peer is down is no longer based on `DownSeconds`.
Tests
- Unit test
Code changes
Side effects
- PD judge that the peer is down is no longer based on `DownSeconds`. In extreme cases, down-peers that would not have been processed will be fixed.
```release-note
Fix the bug that PD would not fix down-peer in time.
```
> checker: judging that the peer is down is no longer based on DownSeconds

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/schedule/checker/priority_checker.go
- server/schedule/checker/rule_checker.go
- server/schedule/filter/filters.go
- server/schedule/operator/builder.go
- server/schedule/opt/healthy.go
- server/schedule/opt/opts.go
```go
// FitRegion tries to fit the region with placement rules.
func (c *RaftCluster) FitRegion(region *core.RegionInfo) *placement.RegionFit {
return c.GetRuleManager().FitRegion(c, region)
}
```
Due to the above code, `CacheCluster` in #4003 has no real effect. It is called `RaftCluster.GetStores`, not `CacheCluster.GetStores`.
Implementation of abstract FitRegion.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> rules: optimize the implementation of FitRegion

- server/election/lease.go
- server/tso/allocator_manager.go
Fix the data race of the leadership resetting.
ref: https://ci2.pingcap.net/blue/rest/organizations/jenkins/pipelines/pd_test/runs/2203/nodes/50/steps/94/log/?start=0
Make sure the leadership is not expired before resetting it.
Tests
- Unit test
```release-note
None.
```
> election: fix the data race of the leadership resetting

- pkg/cache/cache_test.go
- server/cluster/cluster.go
- server/core/basic_cluster.go
- server/core/hot_region_storage.go
- server/grpc_service.go
- server/schedule/checker/priority_checker.go
- server/schedule/checker/replica_checker_test.go
- server/schedule/operator_controller.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_test.go
- server/schedulers/hot_region.go
- server/schedulers/utils.go
- tests/server/cluster/cluster_test.go
- remove `GetLeaderSchedulePolicy`
- remove `adjustBalanceLimit`
Tests
- Unit test
```release-note
None
```
> *: remove functions which are not useful anymore

- server/schedule/operator/builder.go
- server/schedule/operator/builder_test.go
- server/schedule/operator/operator.go
- server/schedule/operator/step.go
- server/schedule/operator_controller.go
- server/schedule/operator_controller_test.go
- server/schedule/test_util.go
This PR removes the light learner/peer.
Use a flag `IsLightWeight` to represent the learner/peer without the limitation of store limit.
Tests
- Unit test
```release-note
None
```
> *: remove light learner/peer

- errors.toml
- pkg/errs/errno.go
- server/api/checker.go
- server/api/checker_test.go
- server/api/router.go
- server/api/scheduler.go
- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/handler.go
- server/schedule/checker/checker_pause.go
- server/schedule/checker/joint_state_checker.go
- server/schedule/checker/learner_checker.go
- server/schedule/checker/merge_checker.go
- server/schedule/checker/priority_checker.go
- server/schedule/checker/replica_checker.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/split_checker.go
- server/schedule/checker_controller.go
Signed-off-by: Peng Guanwen <pg999w@outlook.com>
When TiKV is in import mode, we don't want PD to merge regions. This PR add a new API to stop region merge for a given time.
A new PD REST API `/checker/{name}` with a paramenter `{delay}` is added. When called, PD will not trigger corresponding checker in the following `{delay}` seconds.
- Unit test
Code changes
```release-note
Add a `/checker/{name}` API to pause region merge.
```
> api: Add pause or resume checker REST api

- server/encryptionkm/key_manager.go
Fix #4071
encryption: refine key manager watcher loop
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> encryption: refine key manager watcher loop

- server/cluster/coordinator_test.go
- server/schedule/operator_controller.go
This PR is trying to make `TestStoreOverloaded` more stable. 
Just sleep 1s before scheduling.
Tests
- Unit test
```release-note
None
```
> testing: make TestStoreOverloaded stable

- server/schedulers/hot_region_config.go
Close #4159.
Use the lock correctly.
Tests
- Unit test
```release-note
Fix the data race problem of hot region config
```
> *: fix race in hot region config

- server/encryptionkm/key_manager_test.go
close #4165 
The watcher has been blocked. After troubleshooting its own problem, it is suspected that too many etcd have been started at the same time, causing the FD to run out.
*: use SerialSuites to reduce the servers in tests at the same time
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> *: use SerialSuites to reduce the servers in tests at the same time

- server/core/peer.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/operator/create_operator.go
- server/schedule/placement/fit.go
close https://github.com/tikv/pd/issues/4140
Rule checker didn't support to demote voters in order to satisfy the learner rule. This request fixes it by making voter and learner rules as loose match during `FitRegion`.
Tests
- Unit test
```release-note
None
```
> checker: support demote voter in rule checker

- server/schedule/checker/rule_checker.go
The debug log `fail to fix orphan peer` is printed even if the `err` is nil.
```log
[2021/09/27 14:17:48.826 +00:00] [DEBUG] [rule_checker.go:103] ["fail to fix orphan peer"] []
```
Only debug this log when the `err` is not nil.
Tests
- Unit test
```release-note
None.
```
> schedule: reduce an unnecessary debug log in the rule_checker

- server/schedulers/hot_region_config.go
This is a cherry-pick of #4167
Close #4159.
Use the lock correctly.
Tests
- Unit test
```release-note
Fix the data race problem of hot region config
```
> *: fix race in hot region config (#4167)

- server/schedule/checker/replica_checker.go
- server/schedule/checker/rule_checker.go
This is a cherry-pick of #4078
Fix #4077 
After #3462, `DownSeconds` no longer update with the heartbeat. It will cause the down-peer to not be repaired in time.
Judging that the peer is down is no longer based on `DownSeconds`.
Tests
- Unit test
Code changes
Side effects
- PD judge that the peer is down is no longer based on `DownSeconds`. In extreme cases, down-peers that would not have been processed will be fixed.
```release-note
Fix the bug that PD would not fix down-peer in time.
```
> checker: judging that the peer is down is no longer based on DownSeconds (#4078)

- server/cluster/cluster.go
- server/core/region.go
- server/core/region_test.go
ref tikv/tikv#11114
Signed-off-by: p4tr1ck <patrick.li@pingcap.com>
Part of https://github.com/tikv/tikv/issues/11114
close #4258
If region size is zero, try to use the previous size in origin region info.
Tests
- Unit test
Code changes
none
Side effects
```release-note
None
```
> core: use previous size if heartbeat's size is zero

- tests/client/client_test.go
Use only one PD client during the `TestGlobalAndLocalTSO`.
Since the TSO Follower Proxy could be enabled/disabled online, there is no need to create a new PD client to test it.
Tests
- Unit test
```release-note
None.
```
> tests: use only one PD client during the TestGlobalAndLocalTSO

- tools/pd-ctl/pdctl/command/store_command.go
Close #4263.
Remove the incorrect parameter.
Tests
- No code
```release-note
None.
```
> tools: fix the help message of store limit

- server/core/storage_test.go
- server/kv/mem_kv.go
Part of #3453. Trying to sort out the usage of `core.Storage` and `kv.Base`.
There is no need to introduce a `KVWithMaxRangeLimit` here. I think injecting a failpoint is a more suitable way.
Tests
- Unit test
```release-note
None.
```
> kv, tests: use failpoint to mock the memory KV range limit

- metrics/alertmanager/pd.rules.yml
Tests
- Unit test
```release-note
None.
```
> metrics: fix tso alert

- go.mod
- go.sum
Signed-off-by: baurine <2008.hbl@gmail.com>
Update TiDB Dashboard to v2021.11.08.1.
Upstream commit: https://github.com/pingcap/tidb-dashboard/commit/80363dfbe88469e288d0a0a68204c64ee31ef9cd .
```release-note
None
```
> Update TiDB Dashboard to v2021.11.08.1 [master]

- server/core/region.go
- server/core/region_option.go
- server/core/region_test.go
- server/grpc_service.go
fix #4295 
A change in `flowRoundDivisor` also considers that the flow statistics have changed.
Tests
- Unit test
Code changes
Side effects
```release-note
Fix the bug that region statistics are not updated after `flow-round-by-digit` change.
```
> cluster: fix the bug that region statistics are not updated after flow-round-by-digit change

- go.mod
- go.sum
Signed-off-by: baurine <2008.hbl@gmail.com>
Update TiDB Dashboard to v2021.11.08.1.
Upstream commit: https://github.com/pingcap/tidb-dashboard/commit/80363dfbe88469e288d0a0a68204c64ee31ef9cd .
**TiDB Dashboard related PRs:**
- https://github.com/pingcap/tidb-dashboard/pull/1038
- https://github.com/pingcap/tidb-dashboard/pull/1043
- https://github.com/pingcap/tidb-dashboard/pull/1044
- https://github.com/pingcap/tidb-dashboard/pull/1048
```release-note
None
```
> Update TiDB Dashboard to v2021.11.08.1 [release-5.3]

- server/schedule/checker/rule_checker_test.go
- server/schedule/placement/fit.go
fixes #4233 
Adjust the peers order in `newFitWorker` to put healthy peers in front
Tests
- Unit test
```release-note
NONE
```
> server/schedule: priority to fit healthy peers

- tests/pdctl/scheduler/scheduler_test.go
- tools/pd-ctl/pdctl/command/scheduler.go
Signed-off-by: Hua Lu <hua.lu@pingcap.com>
Resolves #3951 
- Add new command `show` under `pd-ctl scheduler config balance-hot-region-scheduler` with same behavior as `list`
- Add deprecated warning message when execute `list` command under `pd-ctl scheduler config balance-hot-region-scheduler`
- Modify short description of `list` with deprecate message.
- Add test case for `show` command, usage the same logic as `list` command
Tests
- Unit test
- Compare outputs from `pd-ctl scheduler config balance-hot-region-scheduler show` and `pd-ctl scheduler config balance-hot-region-scheduler list`
- Check `pd-ctl scheduler config balance-hot-region-scheduler list` has deprecated message printed.
Code changes
Related …
> Add show command under pd-ctl scheduler config

- metrics/grafana/pd.json
`Current ID allocation & scatter operator event` duplicate panel id
`Current ID allocation `Invalid data sources
Tests
- No code
Code changes
Side effects
```release-note
None.
```
> fix duplicate panel id & Invalid data sources

- server/core/store.go
- server/core/store_test.go
- server/core/test_util.go
close: #4323
available space unit is not same 
Tests
- Unit test
capacity
store1,store4: 161gb
others: 215gb
available ratio and score
balance:
there is no balance roll back 
Code changes
Side effects
```release-note
None
```
> scheduler: low space tikv can not balance 

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/grpc_service.go
- server/region_syncer/server.go
- server/replication/replication_mode.go
- server/statistics/hot_cache.go
- server/statistics/hot_cache_task.go
- server/statistics/hot_stat.go
close #4293
* `RaftCluster` uses its own `ctx` to replace the original `quit`.
* `RegionSyncer` can stop immediately when `ctx` is `Done` during service.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> *: use context to manage RaftCluster

- server/core/storage.go
Part of #3453. Trying to sort out the usage of `core.Storage` and `kv.Base`.
Remove an unused function and reduce unnecessary method exports.
* `LoadScheduleConfig` is not called by anyone.
* `SaveJSON` and `LoadRangeByPrefix` are unnecessary to be exported methods.          
Tests
- Unit test
- Integration test 
```release-note
None.
```
> core: remove an unused function and reduce unnecessary method exports

- go.mod
- go.sum
- server/grpc_service.go
Close #4345
Copy some codes from https://github.com/tikv/pd/pull/4333 to implement the `SplitAndScatterRegions` interface. 
Tests
Build TiDB successfully.
Code changes
Side effects
```release-note
None
```
> grpc_service: add missing SplitAndScatterRegions method

- server/cluster/cluster.go
Closes #4354.
Release the RLock if it returns early.
Tests
- Unit test
```release-note
Fix the issue that the RLock is not released
```
> cluster: fix the unreleased RLock issue

- server/server.go
close #4325
clone the config so it will be safe to update.
```release-note
Fix data race when updating replication mode configuration
```
> server: clone ReplicationModeConfig to avoid data race

- server/cluster/coordinator.go
… busy
fix #3827 
Use `break` instead of `continue` when checker is busy
Tests
Code changes
Side effects
```release-note
should break the suspect region range loop when checker is busy
```
> cluster: break loop when checker is busy

- server/schedule/checker/replica_strategy.go
- server/schedule/region_scatterer.go
- server/schedulers/shuffle_region.go
- server/statistics/store.go
- server/statistics/store_test.go
close #4344
If we use `remove tombstone`, `GetStore` may return nil. We should check it.
Tests
- Unit test
```release-note
Fix panic issue after TiKV node scales in
```
> *: check if GetStore returns nil

- server/schedulers/evict_leader.go
- server/schedulers/evict_slow_store.go
- server/schedulers/scheduler_test.go
close #4376
`evict-slow-store-scheduler` uses the correct `name` and `type`
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> schedulers: evict-slow-store-scheduler uses the correct name and type

- server/server.go
- tests/server/server_test.go
fix #4328 
`ReplicateFileToAllMembers` quits when it meets the first error. The rest members are ignored.
To fix it, we can record the error and continue to try other nodes.
Tests
- Unit test
```release-note
Fix incomplete replicate file
```
> server: fix incomplete replicate file

- server/schedule/checker/merge_checker.go
- server/schedule/checker/merge_checker_test.go
Close #4119.
Make `merge_checker.go` check whether there is a peer of the adjacent region on an offline store, while the source region has no peer on it. This is to prevent from bringing any other peer into an offline store to slow down the offline process.
Tests
- Unit test
```release-note
Make merge-region not to merge a region into the offline store.
```
> checker: merge-region should consider the peer on an offline store

- server/api/region.go
- server/api/region_test.go
- tests/pdctl/region/region_test.go
- tools/pd-ctl/pdctl/command/region_command.go
Tracking Issue: #4400
This is a supplementary work of #4142.
* fix a index out of range error in pd-ctl `region keys` command 
> when query regions start from `a` by `region keys --formate=raw a`, the length of args is 1, privious code use args[1] without check length.
* update comment.
```release-note
Fix an index out of range bug of the region keys command in pd-ctl
```
> api,pd-ctl: foramte scanRegions api and fix a index out of range bug in relevant pdctl command

- .golangci.yml
- server/api/admin_test.go
- server/api/component_test.go
- server/api/member_test.go
- server/api/rule_test.go
- server/api/scheduler.go
- server/api/scheduler_test.go
- server/api/service_gc_safepoint_test.go
- server/api/store_test.go
- server/api/util.go
- server/cluster/cluster.go
- server/server.go
- tests/server/api/api_test.go
- tests/server/member/member_test.go
ref #4322
Enable bodyclose linter.
Tests
- Unit test
```release-note
None
```
> *: enable bodyclose linter

- Makefile
There is no need to compile the dashboard before doing the TSO tests. So we should remove it.
Test the TSO without compiling the dashboard.
Tests
- Unit test
```release-note
None.
```
> Makefile: test the TSO without compiling the dashboard

- client/client.go
- go.mod
- go.sum
- server/grpc_service.go
- server/server.go
- tests/server/global_config/global_config_test.go
Signed-off-by: lemonhx <lemonhx@lemonhx.tech>
previously we have discussions about adding global config into PD and store in etcd for easier to maintain the config and for the ease of usage of  all components such as tikv tidb and tiflash
adding three functions into kvproto for loading ,storing and watching the global config, and implement it for etcd
Tests
-  [x] Unit test
- No code
Side effects
-  [x] Possible performance regression 
-  [x] Increased code complexity 
-  [x] Breaking backward compatibility
- kvproto https://github.com/pingcap/kvproto/pull/828
```release-note
None
```
> implement `GlobalConfig` for grpc server and client

- server/tso/allocator_manager.go
- tests/server/tso/allocator_test.go
Close https://github.com/tikv/pd/issues/4109.
Add a prefix to the root path to prevent being conflicted with other system key paths such as leader, member, alloc_id, raft, etc.
Tests
- Unit test
Side effects
**Since the Local TSO has not been released yet, I think it's ok to break the backward compatibility.**
```release-note
None.
```
> tso: add a local TSO prefix to prevent being conflicted with other system key paths

- server/testutil.go
- tools/pd-simulator/simulator/config.go
close #4442
It set default  lease time to 10s(1s) for test and 3s for simulator  to keep consitence with develop.
Tests
Code changes
Side effects
```release-note
None
```
> test: increase test lease time to tolerate higher delayed time

- tools/pd-ctl/main.go
- tools/pd-ctl/pdctl/ctl.go
- tools/pd-ctl/pdctl/ctl_test.go
close #4478
String split mention If s does not contain sep and sep is not empty, Split returns a
slice of length 1 whose only element is s. It will add args if the arg is nil in char device mode.
So it needs to check the args is nil. 
Tests
Code changes
Side effects
```release-note
pdctl args lens is wrong in char device mode.
```
>  ctl: pd-ctl cmd will work well in char device mode

- server/api/store.go
- server/api/store_test.go
- server/api/trend.go
- tests/cluster.go
- tests/pdctl/helper.go
- tests/pdctl/store/store_test.go
refer to https://github.com/pingcap/tiup/issues/1684
Revert #4334  
```release-note
None.
```
> api: Revert for showing State in StoreInfo

- server/config/config.go
- server/config/config_test.go
ref https://github.com/tikv/pd/issues/4429
This PR support setting the max request bytes of gRPC requests for PD.
Tests
- Unit test
Code changes
- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`](https://github.com/pingcap/docs-cn): TODO
```release-note
None
```
> config: expose max request bytes

- server/api/region_test.go
- server/core/region.go
- tests/pdctl/region/region_test.go
- tools/pd-ctl/pdctl/command/region_command.go
Close #4496, close #4216.
* Check if the last end key is not empty.
* Add some help info for the `region range-holes` command.
Tests
- Unit test
```shell
❯ ./bin/pd-ctl region range-holes -h
There are some cases that the region range is not continuous, for example, the region doest't send the heartbeat to PD after a spliting.
This command will output all empty ranges without any region info.
Usage:
pd-ctl region range-holes [flags]
Examples:
If PD now holds the region ranges info like ["", "a"], ["b", "x"], ["x", "z"]. The the output will be like:
[
[
"a",
"b"
],
[
"z",
""
],
]
Flags:
-h, --help   help for range-holes
Global Flags:
--cacert string   path of file that …
```
> api, pd-ctl: fix the region range hole end key check and add some help info

- pkg/apiutil/serverapi/middleware.go
- server/config/config.go
- server/config/util.go
close #4505.
This PR moves `ParseUrls` to `util.go` and make it private.
Tests
- Unit test
```release-note
None
```
> *: move `parseUrls` to util

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/handler.go
- server/schedulers/hot_region_test.go
- server/statistics/hot_cache.go
- server/statistics/hot_cache_task.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/hot_peer_cache_test.go
- server/statistics/kind.go
Close #4463.
This PR does the following changes:
- move task queue inside cache 
- replace `isNew` and `needDelete` with `opType`
- remove `justTransferLeader` from `HotPeerStat`
- make some functions and fields private.
Tests
- Unit test
```release-note
None
```
> statistics: small refactor of hot statistics

- server/config/config.go
- server/config/config_test.go
close https://github.com/tikv/pd/issues/4518
assign default value
Tests
- Unit test
```release-note
None
```
> config: fix the display value of the log level

- go.mod
- go.sum
- pkg/logutil/log_test.go
close https://github.com/tikv/pd/issues/4528
fix wrong `boltdb` dependency
fix the go.mod
Tests
- Unit test
```release-note
None
```
> ci: fix wrong boltdb dependency

- cmd/pd-server/main.go
- go.mod
- pkg/logutil/log.go
- pkg/logutil/log_test.go
- server/api/region.go
- tools/pd-simulator/main.go
close https://github.com/tikv/pd/issues/4531.
There are some logger exist in PD: `capnslog`, `logrus`,`zap` and so on.
after https://github.com/tikv/pd/pull/1452. etcd supports customize the logger, so we can remove the redundant loggers that remaining for compatibility purpose.
remove useless code
Tests
- Unit test
```release-note
None
```
> log: remove useless log

- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/hot_peer_cache_test.go
- server/statistics/kind.go
To close #4510 
- remove inherit in hot statistic
- rename `directly` to `inherit`
Tests
- Unit test
```release-note
None.
```
> statistic: replace old inherit with adopt in hot statistic

- go.mod
- go.sum
Signed-off-by: baurine <2008.hbl@gmail.com>
ref #4257 
Update TiDB Dashboard to v2022.01.12.1.
Upstream commit: https://github.com/pingcap/tidb-dashboard/commit/eef0c13b5546b4363642296f554b5e5e0a8ea105 .
Related tidb-dashboard PRs:
- https://github.com/pingcap/tidb-dashboard/pull/1137
```release-note
1. Hide the `cluster diagnostic` app that is not ready yet, which is opened in the last release uncarefully.
```
> Update dashboard to v2022.01.12.1

- server/schedule/operator/builder.go
- server/schedule/operator/builder_test.go
close #4411 
Tests
- Unit test
Code changes
Side effects
```release-note
Prevent removing a voter from 2 replicas raft group directly, instead, demote the voter firstly.
```
> schedule: prevent removing voters directly in 2 replica raft group

- Makefile
- plugin/scheduler_example/Makefile
Makefile is not well organized and there many stale targets.
- remove some targets
- reorder some targets
- merge some targets
- rewrite some targets
- remove go version check and GO111MODULE setting
Tests
- Unit test
```release-note
None
```
> build: reorg Makefile

- server/schedule/region_scatterer.go
- server/schedule/region_scatterer_test.go
close #4565
If an originPeer is already in `selectStore`, `continue` directly. Otherwise, it will end up picking a `targetPeer` which is either itself or some other store that is not in the initial peer list. Since entering the select phase, it is guaranteed that it is not in the `selectStore`, so it is always guaranteed that the worst-case selection itself is feasible at this time. In the end, the number of peers before and after can be guaranteed to remain unchanged.
Tests
- Unit test
When not modified, the following operator may be generated:
scatter-region {rm peer: store [3]} (kind:region,leader, region:201(0,0), createAt:2022-01-13 18:24:32.375399 +0800 CST m=+0.014571751, startAt:0001-01-01 00:00:00 +0000 UTC, currentStep:0, steps:[transfer leader from store 3 to store 4, remove …
> region_scatterer: fix the bug that could generate schedule with too few peers

- server/schedule/region_scatterer_test.go
close #4583
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> region_scatterer: fix incorrect test

- Makefile
- server/cluster/cluster.go
- server/server.go
- server/storage/endpoint/key_path.go
- server/util.go
- tests/server/cluster/cluster_test.go
Close https://github.com/tikv/pd/issues/4284.
Use `server/storage/endpoint/key_path.go` to manage the key path joining.
Tests
- Unit test
```release-note
None.
```
> *: unify the root key path joining

- server/cluster/cluster.go
After #3747, `TraceRegionFlow` has been replaced by `FlowRoundByDigit` and `IsTraceRegionFlow()` and should no longer be used.
ref #4399
Remove useless `traceRegionFlow`
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> cluster: remove useless `traceRegionFlow`

- client/option_test.go
- pkg/mock/mockhbstream/mockhbstream_test.go
- pkg/testutil/testutil.go
- server/api/server_test.go
- server/api/tso_test.go
- server/cluster/coordinator_test.go
- server/server_test.go
- tests/client/client_test.go
- tests/cluster.go
- tests/pdctl/member/member_test.go
- tests/server/api/api_test.go
- tests/server/member/member_test.go
- tests/server/region_syncer/region_syncer_test.go
- tests/server/server_test.go
- tests/server/tso/allocator_test.go
- tests/server/tso/consistency_test.go
- tests/server/tso/manager_test.go
- tests/server/watch/leader_watch_test.go
There is always a `C` in the context, so we don't need the extra parameter.
Remove `C` from `CheckFunc`.
Tests
- Unit test
```release-note
None
```
> *: simplify WaitUntil usage

- server/api/pprof_test.go
- server/api/stats_test.go
- server/api/util_test.go
This PR will fix the failure caused by `golangci-lint`, the details:
```
go version
go version go1.17.6 darwin/amd64
golangci-lint --version
golangci-lint has version v1.44.0 
```
the error imformation after running `make check`
```
make check
gofmt ...
golangci-lint ...
server/api/util_test.go:43:27: response body must be closed (bodyclose)
result := response.Result()
^
server/api/util_test.go:57:27: response body must be closed (bodyclose)
result := response.Result()
^
server/api/util_test.go:66:28: response body must be closed (bodyclose)
result := response.Result()
^
make: *** [static] Error 1
```
This PR will fix the above failure.
It closed the related bodies(This PR only changes the test file)
Now we can run the command `make check` …
> server/api/*test: fix ci-lint caused by bodyclose

- server/core/region.go
- server/core/region_test.go
The function [SetRegion](https://github.com/tikv/pd/blob/master/server/core/region.go#L645) is not very friendly to our reviewers, exp: too many `{}` in `{}`,  the max degree of `{}` is 4. 
This PR tidy refactor the function [SetRegion](https://github.com/tikv/pd/blob/master/server/core/region.go#L645) to make it more friendly to our reviewers and maintainers, exp: we decrease the max degree of `{}` from 4 to 2 and try to return as early as possible. The function is still very long and it is not the perfect refactor, however, we are trying to make it better. Feel free to refactor it ～～
And we  use closure to avoid the performance loss, now the benchmark function ```BenchmarkRegionTreeUpdate-8` `BenchmarkRegionTreeUpdateUnordered-8 `  works well :
```
core git:(server/core/set_region) go …
> server/core/region.go: tiny refactor set_region

- client/client.go
- errors.toml
- pkg/errs/errno.go
Issue Number: Close https://github.com/tikv/pd/issues/4629
```commit-message
Do not return error when a `ctx.Done` signal arrives.
```
Tests
- Unit test
- Manual test
After this PR:
```shell
[2022/02/11 16:05:58.289 +08:00] [INFO] [client.go:754] ["[pd] stop fetching the pending tso requests due to context canceled"] [dc-location=global]
[2022/02/11 16:05:58.289 +08:00] [INFO] [client.go:692] ["[pd] exit tso dispatcher"] [dc-location=global]
```
Before this PR:
```shell
[2022/02/11 16:07:07.509 +08:00] [ERROR] [client.go:753] ["[pd] fetch pending tso requests error"] [dc-location=global] [error="[PD:client:ErrClientGetTSO]context canceled"]
[2022/02/11 16:07:07.509 +08:00] [INFO] [client.go:692] ["[pd] exit tso dispatcher"] …
```
> client: do not return error when a ctx.Done signal arrives

- pkg/cache/ttl.go
- server/schedule/checker/merge_checker.go
- server/schedule/checker/merge_checker_test.go
Close #4614.
Update TTL when split-merge-interval is changed.
Tests
- Unit test
```release-note
None
```
> checker: update TTL according to SplitMergeInterval

- pkg/typeutil/conversion.go
- pkg/typeutil/conversion_test.go
- server/api/operator.go
- server/api/region.go
- server/api/region_test.go
- server/api/util.go
Fix #4617.
Correctly convert `[]interface{}` to `[]uint64` after JSON `Unmarshal`.
Tests
- Unit test
```release-note
Fix the Region ID list cannot be converted to `uint64`
```
> api: fix invalid interface conversion

- client/Makefile
- pd.code-workspace
Issue Number: See https://github.com/golang/go/issues/32394#issuecomment-498385140. 
```commit-message
client: add the VS Code workspace file to handle the client module
```
Tests
- Unit test
```release-note
None.
```
> client: add the VS Code workspace file to handle the client module

- tests/pdctl/config/config_test.go
- tools/pd-ctl/pdctl/command/config_command.go
Issue Number: close #4651
pdctl was trying to convert duration to number. The condition is not correct: it should only convert int fields.
```commit-message
pdctl: fix the issue that duration fields of dr-autosync cannot be set
```
Tests
- Unit test
```release-note
Fix the issue that duration fields of dr-autosync cannot be set
```
> pdctl: fix the issue that duration fields of dr-autosync cannot be set

- server/api/router.go
- server/server.go
Issue Number: Ref #4679.
`tidb-operator` still uses `/pd/health` according to https://github.com/tikv/pd/issues/4679#issuecomment-1052144141. This PR is going to temporarily add them back. Once we update the `tidb-operator`, we will remove it again.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> api: add part of deprecated APIs back

- server/schedule/placement/region_rule_cache.go
- server/schedule/placement/region_rule_cache_test.go
Issue Number: Close #4690
change `and` to `or`
```commit-message
change ValidateStores condition
```
Tests
- Unit test
- 
```release-note
None.
```
> placement: change ValidateStores condition

- server/core/region_tree_test.go
Issue Number: ref https://github.com/tikv/pd/issues/4455
```commit-message
server/core: add more benchmarks for region tree
```
Tests
- Unit test
```release-note
None
```
> server/core: add more benchmarks for region tree

- pd.code-workspace
just like #4658
Tests
- No code
```release-note
None.
```
> *: update the VS Code workspace file to handle other module

- server/storage/endpoint/config.go
- server/storage/endpoint/gc_safe_point.go
- server/storage/endpoint/meta.go
- server/storage/endpoint/replication_status.go
- server/storage/endpoint/util.go
Tests
- Unit test
```release-note
None.
```
> storage: reformat load function to reduce code

- go.mod
- go.sum
- tests/client/go.sum
Update TiDB Dashboard to v2022.03.16.1.
Related tidb-dashboard PR https://github.com/pingcap/tidb-dashboard/pull/1199
- Fix conprof profile URL
- Fix missing fields in slow query
- Telemetries of top SQL and conprof
Tests
- 5.4
- 6.0
```release-note
1. Fix conprof profile URL
2. Fix missing fields in slow query
3. Telemetries of top SQL and conprof
```
> Update TiDB Dashboard to v2022.03.16.1 ref #4257

- server/replication/replication_mode.go
- server/replication/replication_mode_test.go
Issue Number: Close #4737
- In `sync_recover` state, if there is not majority peers, don't switch state.
- update test to make it more easy to read
Tests
- Unit test
```release-note
None
```
> dr-autosync: do not switch to async when there is not enough peers

- server/config/config.go
- server/config/config_test.go
Issue Number: Close #4753
https://github.com/tikv/pd/pull/4532 removed the code to initialize the default value of `log.format`. This PR adds it back.
```commit-message
config: fix the default value of log.format
```
Tests
- Unit test
```release-note
None.
```
> config: fix the default value of log.format

- server/grpc_service.go
- tests/client/client_test.go
Issue Number: Close https://github.com/tikv/pd/issues/4763
```commit-message
server: use old interface for scatter region
```
Tests
```release-note
None
```
> server: use old interface for scatter region

- server/schedulers/evict_leader_test.go
- server/schedulers/scheduler_test.go
Move tests for evict_leader to the file evict_leader_test.go.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> server/schedulers: move evict_leader's tests to the related file

- server/grpc_service.go
- tests/server/cluster/cluster_test.go
Issue Number: Ref #4797.
This PR removes unnecessary `withStack` and partially fix the above issue.
```commit-message
```
Tests
- Unit test (TODO)
```release-note
Fix the issue that the status code of `not leader` is sometimes wrong 
```
> server: partially fix grpc status

- server/schedulers/evict_slow_store.go
- server/schedulers/evict_slow_store_test.go
- server/schedulers/scheduler_test.go
Issue Number: Close #4802 
Tests
- Unit test
```release-note
None.
```
> schedulers/evict_slow_store: return directly  when there is more than 1 slow store.

- server/statistics/store_collection.go
Issue Number: Close #4825.
Before collecting the metrics, reset the `placementStatusGauge`
```commit-message
```
Tests
- Manual test (the detailed steps can be found in the above issue)
```release-note
Fix the issue that the label distribution has residual labels
```
> metrics: fix the residual label

- server/core/store.go
- server/core/store_test.go
- server/core/test_util.go
Issue Number: Close #4805
if  the biggest store's capacity is more than 2T , the store's score may be closed to the up score as b(1e7). so the smallest store will not be balanced even if they has less available capacity.
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
> core: change scoreV2 to adapt the higher disk capacity and amp . 

- errors.toml
- pkg/errs/errno.go
- server/api/unsafe_operation.go
- server/api/unsafe_operation_test.go
- server/cluster/cluster.go
- server/cluster/cluster_worker.go
- server/cluster/coordinator.go
- server/cluster/coordinator_test.go
- server/cluster/unsafe_recovery_controller.go
- server/cluster/unsafe_recovery_controller_test.go
- server/grpc_service.go
- tests/pdctl/unsafe/unsafe_operation_test.go
- tools/pd-ctl/pdctl/command/unsafe_command.go
Issue Number: ref #4242 which is part of tikv/tikv#10483
Split/merge and conf change can cause PD make wrong decisions during unsafe recovery. Previously, we expect the user to stop all the schedulers themselves, but that is not reliable, Unsafe Recovery should be responsible for pausing all the schedulers.
Pause all the schedulers before collecting store reports. Note that, to avoid reporting stale info, tikv also need to do its own parts, such as making sure apply index is equal to commit index.
Tests
- Unit test
Code changes
- N/A
Side effects
- All schedulers are paused until the recovery is finished or timed out.
- N/A
```release-note
None
```
> unsafe recovery: Pause all schedulers and checkers when doing unsafe recovery 

- server/election/leadership_test.go
- server/election/lease.go
Issue Number: Close https://github.com/tikv/pd/issues/4782.
```commit-message
election: fix the unstable TestLeadership test (again).
```
`keepAliveWorker` may update the `expireTime` concurrently while the `Reset` set it to zero. We need to make sure that the  `expireTime` won't be updated anymore when the context is canceled.
Tests
- Unit test
```release-note
None.
```
> election: fix the unstable TestLeadership test (again)

- server/cluster/cluster.go
- server/cluster/unsafe_recovery_controller_test.go
Issue Number: Close #4857 
```commit-message
Acquire reader lock while reading the unsafe recovery controller, acquire writer lock while modifying it.
```
Tests
- Unit test
Code changes
N/A
Side effects
N/A
- PR introduced the bug https://github.com/tikv/pd/pull/4475
```release-note
None
```
> Fix data race, ref #4857

- server/server.go
- server/tso/tso.go
- tests/client/client_test.go
Issue Number: Close #4884.
This bug will occur when the following conditions are met:
1. PD-0 resigns the leader.
2. PD-0 updates the TSO right after resetting it concurrently and leaves the non-empty TSO in memory.
3. PD-0 becomes the leader again.
4. PD-0 receives a TSO request after the leadership is available and before the TSO synchronization is done.
5. A smaller TSO will be generated with this request.
6. BOOM!!!
```commit-message
tso: fix the corner case that may cause TSO fallback
```
Do not update the TSO in memory if it's zero.
Tests
- Unit test
```release-note
Fix the corner case that may cause TSO fallback.
```
> tso: fix the corner case that may cause TSO fallback

- server/schedule/labeler/labeler.go
Issue Number: Close #4895 
Tests
- Unit test
```release-note
None.
```
> server/scheduler/labeler: delete region rule instead of delete placement rule when region rule expired

- server/cluster/cluster.go
- server/statistics/hot_peer_cache_test.go
- server/statistics/util.go
- tests/pdctl/hot/hot_test.go
If DefaultAotSize is 2, a random fluctuation will affect two interval.
Tests
- Unit test
```release-note
None.
```
> statistics: make aot more stable

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
Tests
- Unit test
```release-note
None.
```
> scheduler: refactor calcProgressiveRank in hot-scheduler

- metrics/grafana/pd.json
- pkg/progress/progress.go
- pkg/progress/progress_test.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/cluster/metrics.go
- tests/pdctl/config/config_test.go
- tests/server/api/api_test.go
This PR changes the way of calculating progress speed. After this PR, we use a sliding window to get the speed through the delta in a fixed time interval.
Now, the monitor becomes:
```commit-message
```
Tests
- Unit test
```release-note
None
```
> pkg: make speed estimation more accurate

- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/cluster/coordinator_test.go
- server/cluster/prepare_checker.go
- server/cluster/unsafe_recovery_controller_test.go
- server/core/region.go
- server/core/region_option.go
- server/grpc_service.go
- server/region_syncer/client.go
- tests/server/region_syncer/region_syncer_test.go
Issue Number: Close #4769.
This PR uses the flag to distinguish if the region's heartbeat is new when transferring the PD leader.
```commit-message
```
Tests
- Unit test
```release-note
Fix the issue that scheduling cannot immediately start after PD leader transfers
```
> *: fix scheduling can not immediately start after transfer leader

- server/grpc_service.go
Issue Number: Close https://github.com/tikv/pd/issues/4833
https://github.com/tikv/pd/pull/4938 create scatter_region operator with OpAdmin for batch scatter, but it ignored the old method.
```commit-message
server/grpc_service: create scatter_region operator with OpAdmin for old method
```
Tests
```release-note
None
```
> server/grpc_service: create scatter_region operator with OpAdmin for old method

- server/cluster/prepare_checker.go
Issue Number: Close #4987.
This PR fixes the problem by replacing `Rlock` with `Lock`.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: fix the prepare checker data race

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/grpc_service.go
- server/metrics.go
- server/statistics/buckets/bucket_stat_informer.go
- server/statistics/buckets/hot_bucket_cache.go
- server/statistics/buckets/hot_bucket_task.go
- server/statistics/buckets/hot_bucket_task_test.go
- server/statistics/buckets/metric.go
Issue Number: Close #4991
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
> server: implement for BucketStatInformer

- server/cluster/unsafe_recovery_controller_test.go
Issue Number: Close #4857 
It was resolved in #4881, then reverted in #4704, I am now fixing the data race in a different way
```commit-message
Reorder the code logic, and acquire the lock before modifying the cluster to avoid data race.
```
Tests
- Unit test
Code changes
N/A
Side effects
N/A
- PR reverted the fix #4704
- PR fixed it using reader lock #4881
- PR introduced the bug https://github.com/tikv/pd/pull/4475
```release-note
None
```
> Fix data race,ref #4857

- .github/workflows/check.yaml
- Makefile
- client/Makefile
- go.mod
- go.sum
- pkg/swaggerserver/empty_handler.go
- tests/client/Makefile
- tests/client/go.sum
Issue Number: Close https://github.com/tikv/pd/issues/4932
```
before:
make pd-server  213.93s user 43.70s system 279% cpu 1:32.05 total
after:
make pd-server  209.82s user 37.90s system 286% cpu 1:26.54 to
```
imporve about 5/43.7 = 11% 
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
> Makefile: disable swagger server

- server/replication/replication_mode.go
fix #4940
Issue Number: Close #4940
add a new flag to indicate if the state can make sure the data in DR is ACID consistant.
```commit-message
```
Tests
Code changes
```release-note
None
```
> replication: add acid_consistant flag in HTTP response

- server/config/config.go
Issue Number: Close #5008 
Too small max request bytes make grpc always fail.
Assume that each peer report occupies about 500KB at most, then 150MB can fit for store reports that have 30w regions information. 
```commit-message
Enlarge max request bytes to fit the large store report for unsafe recovery
```
Tests
- No code
```release-note
None
```
> config: Enlarge max request bytes

- server/cluster/cluster.go
Issue Number: Close #5006.
This PR adds the RLock back because we need to ensure the correctness of concurrency.
```commit-message
```
```release-note
None
```
> cluster: add the RLock back

- server/cluster/cluster.go
- server/cluster/coordinator.go
- tests/server/api/api_test.go
Issue Number: Close #5025
The reason why the speed isn't accurate is that when the leader changes, the check stores won't wait for all regions' heartbeats to finish. So it will push a small store region size into the statistics window. Then in the later 10 mins, PD will use the latest store region size, which could be big after the heartbeat finish, minus that one to get the delta for calculating the speed. After the 10min passed away, the first value of the statistics window will be removed, then the speed becomes normal.
```commit-message
```
Tests
- Unit test
- Manual test 
After：
```release-note
Fix the issue that the store online speed is not accurate when the PD leader …
```
> cluster: calculate speed until cluster is prepared

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
Issue Number: Close #5005 
Fixes the panic problem by calling `GetStoreId()` instead of using `StoreId` directly.
```commit-message
```
Tests
- Unit test
```release-note
Fix the issue that the hot region may cause panic due to no leader
```
> scheduler: fix the hot scheduler panic due to region with no leader

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- tests/server/api/api_test.go
Issue Number: Ref #5025
Offline progress has the same problem which will change the ETA to N/A. This PR will check if the cluster is prepared before the offline progress calculation.
```commit-message
```
Tests
- Unit test
- Manual test
```release-note
Fix the issue that the store offline speed is N/A when the PD leader transfers.
```
> cluster: calculate offline speed until cluster is prepared

- server/cluster/coordinator.go
- server/cluster/coordinator_test.go
- server/schedule/checker/replica_checker.go
- server/schedule/checker/replica_strategy.go
- server/schedule/checker/rule_checker.go
- server/schedule/filter/candidates.go
Issue Number: Close #4920.
This PR stops adding regions, which cannot be fixed due to no proper store instead of a temporary store state, to the waiting list.
```commit-message
```
Tests
- Manual test
It is not affected by the waiting list anymore. Here is the CPU cost at the beginning:
After BR is finished:
```release-note
None
```
> checker: only temp state should be added in waiting list

- .github/workflows/check.yaml
Issue Number: Close #5078
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
```commit-message
change timeout-minutes of `statics` to 8
```
Tests
- Unit test
```release-note
None.
```
> workflow: change timeout-minutes of `statics` to 8

- pkg/encryption/crypter_test.go
- scripts/check-test.sh
```commit-message
Refine the use of require.Error/NoError.
```
Tests
- Unit test
```release-note
None.
```
> pkg, scripts: refine the use of require.Error/NoError

- server/schedule/filter/candidates_test.go
- server/schedule/filter/filters_test.go
Signed-off-by: LLThomas <zs033@qq.com>
Issue Number: Ref #4813
```
```
Tests
- Unit test
```release-note
None
```
> filter: migrate test framework to testify

- tests/autoscaling/autoscaling_test.go
- tests/compatibility/version_upgrade_test.go
- tests/dashboard/race_test.go
- tests/dashboard/service_test.go
- tests/pdbackup/backup_test.go
```commit-message
Testify the autoscaling/compatibility/dashboard/pdbackup tests.
```
Tests
- Unit test
```release-note
None.
```
> tests: testify the autoscaling/compatibility/dashboard/pdbackup tests

- server/storage/hot_region_storage_test.go
- server/storage/storage_gc_test.go
- server/storage/storage_test.go
Signed-off-by: LLThomas <zs033@qq.com>
Issue Number: Ref #4813
```commit-message
As the title says.
```
Tests
- Unit test
```release-note
None
```
> storage: migrate test framework to testify

- server/region_syncer/client_test.go
- server/region_syncer/history_buffer_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
> syncer: migrate test framework to testify

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/config/persist_options.go
- server/core/region.go
- server/statistics/region_collection.go
Issue Number: Close #5107.
```commit-message
Fix the bug that causes wrong statistics for over/undersized regions.
```
Tests
- Unit test
```release-note
None.
```
> server: fix the bug that causes wrong statistics for over/undersized regions

- server/region_syncer/client.go
- server/region_syncer/client_test.go
Issue Number: Ref #5122.
This PR removes the wrapper of the gRPC error.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> syncer: fix the wrong gRPC code usage

- pkg/encryption/master_key_test.go
- pkg/etcdutil/etcdutil.go
- pkg/etcdutil/etcdutil_test.go
- server/election/leadership_test.go
- server/election/lease_test.go
- server/encryptionkm/key_manager_test.go
- server/region_syncer/client_test.go
- server/storage/kv/kv_test.go
- tests/client/client_tls_test.go
Issue Number: Close #5152 
This pull request replaces `os.MkdirTemp` with `t.TempDir`. We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete. 
This saves us at least 2 lines (error check, and cleanup) on every instance, or in some cases adds cleanup that we forgot.
Reference: https://pkg.go.dev/testing#T.TempDir
```go
func TestFoo(t *testing.T) {
// before
tmpDir, err := ioutil.TempDir("", "")
require.NoError(t, err)
defer os.RemoveAll(tmpDir)
// now
tmpDir := t.TempDir()
}
```
Tests
- Unit test
```release-note
None
```
> tests: use `T.TempDir` to create temporary test directory

- server/gc/safepoint.go
- server/gc/safepoint_test.go
- server/grpc_service.go
- server/server.go
Issue Number: Close #5019 
Tests
- Unit test
```release-note
None.
```
> server/grpc_service: make the lock for `UpdateServiceGCSafePoint` smaller

- server/api/config.go
- server/cluster/coordinator.go
Issue Number: Close #5163.
```commit-message
```
Tests
- Manual test
```
» scheduler remove balance-region-scheduler
```
Before:
After:
```release-note
None
```
> metrics: delete the metrics instead of setting them to 0

- tests/pdctl/helper.go
- tests/server/api/api_test.go
- tests/server/storage/hot_region_storage_test.go
```commit-message
Testify the api and storage tests.
```
Tests
- Unit test
```release-note
None.
```
> tests: testify the api and storage tests

- tests/server/cluster/cluster_test.go
- tests/server/cluster/cluster_work_test.go
```commit-message
Testify the cluster tests.
```
Tests
- Unit test
```release-note
None.
```
> tests: testify the cluster tests

- pkg/testutil/operator_check.go
- server/schedule/checker/joint_state_checker_test.go
- server/schedule/checker/learner_checker_test.go
- server/schedule/checker/merge_checker_test.go
- server/schedule/checker/priority_inspector_test.go
- server/schedule/checker/replica_checker_test.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/checker/split_checker_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
> checker: migrate test framework to testify

- server/api/region_test.go
- server/core/basic_cluster.go
- server/core/region.go
- server/core/region_option.go
- server/core/region_tree_test.go
- server/schedule/checker/merge_checker.go
- server/schedule/checker/replica_strategy.go
- server/schedule/test_util.go
- server/schedulers/balance_region.go
- server/schedulers/grant_hot_region.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_region.go
- tests/server/cluster/cluster_work_test.go
- tools/pd-simulator/simulator/event.go
- tools/pd-simulator/simulator/raft.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: replace `Id` with `ID`

- tests/server/id/id_test.go
- tests/server/join/join_fail/join_fail_test.go
- tests/server/join/join_test.go
- tests/server/member/member_test.go
- tests/server/region_syncer/region_syncer_test.go
- tests/server/server_test.go
- tests/server/watch/leader_watch_test.go
```commit-message
Testify some server tests.
```
Tests
- Unit test
```release-note
None.
```
> tests: testify some server tests

- pkg/testutil/operator_check.go
Signed-off-by: LLThomas <zs033@qq.com>
Issue Number: Ref #4813
```commit-message
Add a WithTestify func for CheckTransferLeader and CheckTransferLeaderWithTestify will be used in server/cluster/coordinator_test.go.
```
View [comment](https://github.com/tikv/pd/issues/4813#issuecomment-1161477449).
Tests
- Unit test
```release-note
None.
```
> pkg/testutil: add a WithTestify func for CheckTransferLeader

- scripts/check-test.sh
- tests/pdctl/store/store_test.go
```commit-message
Update the check-test.sh to detect more inefficient assert functions.
```
Tests
- Unit test
```release-note
None.
```
> scripts, tests: update the check-test.sh to detect more inefficient assert functions

- client/testutil/testutil.go
- pkg/cache/cache_test.go
- pkg/testutil/testutil.go
- scripts/check-test.sh
- server/api/tso_test.go
- server/schedule/operator/status_tracker_test.go
- tests/client/client_test.go
- tests/server/member/member_test.go
- tests/server/tso/allocator_test.go
- tests/server/tso/manager_test.go
Issue Number: close #5105, ref #4813.
```commit-message
Clean up the surrounding code of check pkg.
```
Tests
- Unit test
```release-note
None.
```
> *: clean up the surrounding code of check pkg

- server/api/admin_test.go
- server/api/checker_test.go
- server/api/cluster_test.go
- server/api/config_test.go
- server/api/hot_status_test.go
- server/api/label_test.go
- server/api/log_test.go
- server/api/min_resolved_ts_test.go
- server/api/operator_test.go
- server/api/pprof_test.go
- server/api/region_label_test.go
- server/api/region_test.go
- server/api/rule_test.go
- server/api/scheduler_test.go
- server/api/server_test.go
- server/api/service_gc_safepoint_test.go
- server/api/service_middleware_test.go
- server/api/stats_test.go
- server/api/store_test.go
- server/api/trend_test.go
- server/api/tso_test.go
- server/api/unsafe_operation_test.go
- server/server_test.go
- server/testutil.go
- tests/client/client_test.go
- tests/server/api/api_test.go
- tests/server/config/config_test.go
- tests/server/member/member_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: unify the must wait leader

- tests/server/global_config/global_config_test.go
```commit-message
Testify the global_config tests.
```
Tests
- Unit test
```release-note
None.
```
> tests: testify the global_config tests

- pkg/testutil/operator_check.go
- server/api/config_test.go
- server/api/region_label_test.go
- server/api/region_test.go
- server/api/rule_test.go
- server/api/scheduler_test.go
- server/api/store_test.go
- server/cluster/coordinator_test.go
- server/schedule/checker/merge_checker_test.go
- server/schedule/checker/replica_checker_test.go
- server/schedule/operator/builder_test.go
- server/schedule/region_splitter_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/4813.
Tests
- Unit test
```release-note
None.
```
> *: some misc modify for testify

- server/schedule/placement/fit.go
Issue Number: Close #5245  
```commit-message
```
Tests
- Unit test
- benchmark test
The benchmark test improve the speed of operators **_2x+_** than the master branch.
```
placement git:(schedule/placement/fit_improve_2) ✗ go test -benchmem -run=^$ -bench ^BenchmarkFitRegionMorePeers  -benchtime=20x  
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/schedule/placement
cpu: VirtualApple @ 2.50GHz
BenchmarkFitRegionMorePeers-8                         20              1092 ns/op             560 B/op         14 allocs/op
BenchmarkFitRegionMorePeersEquals-8                   20              1356 ns/op             624 B/op         20 allocs/op
BenchmarkFitRegionMorePeersSplitRules-8               20              1665 ns/op             744 …
```
> schedule/placement/fit: stop searching once the number of candidates was not enough

- server/schedule/placement/fit.go
- server/schedule/placement/fit_region_test.go
- server/schedule/placement/rule_manager.go
Issue Number: Close #5243 
```commit-message
```
Tests
- Unit test
- benchmark test
The benchmark test improve the speed of operators **_10x+_** than the master branch.
```
➜  placement git:(fit_region_improve) ✗ go test -benchmem -run=^$ -bench ^BenchmarkFitRegionWithMoreRulesAndStoreLabels -benchtime=10x  
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/schedule/placement
cpu: VirtualApple @ 2.50GHz
BenchmarkFitRegionWithMoreRulesAndStoreLabels-8               10          46847242 ns/op         2639625 B/op     108312 allocs/op
PASS
ok      github.com/tikv/pd/server/schedule/placement    1.417s
➜  placement git:(fit_region_improve) ✗ go test -benchmem -run=^$ -bench ^BenchmarkFitRegionWithMoreRulesAndStoreLabels -benchtime=10x …
```
> schedule/placement/fit: check the logic with low complexity(O(1)) before the one with higher complexity

- server/schedule/checker/replica_strategy.go
- server/schedule/checker/rule_checker.go
- server/schedule/filter/filters.go
- server/schedule/filter/filters_test.go
- server/schedule/region_scatterer.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_leader.go
- server/schedulers/shuffle_region.go
Issue Number: Ref #5257.
This PR removes the `engineFilter`, `ordinaryEngineFilter` and `specialUseFilter` since they are all special cases of `labelConstraintFilter`. For `specialUseFilter`, this PR also removes the conditional judgment of low space.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> filter: use `labelConstraintFilter` instead

- server/schedule/checker/replica_strategy.go
- server/schedule/checker/rule_checker.go
- server/schedule/filter/filters.go
- server/schedule/filter/filters_test.go
- server/schedule/region_scatterer.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_leader.go
- server/schedulers/shuffle_region.go
This reverts commit c1a6652908d9ecc1b80e8f5cec208e490d6215b7.
Issue Number: Ref #5257.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> Revert "filter: use `labelConstraintFilter` instead (#5235)"

- client/base_client.go
- client/client.go
- client/errs/errno.go
- tests/client/client_test.go
Issue Number: Close #5278.
```commit-message
Let the client check if the cluster ID matches during the initialization and updating.
```
Tests
- Unit test
```release-note
None.
```
> client, tests: make client check if the cluster ID matches

- server/cluster/coordinator.go
- server/cluster/coordinator_test.go
Issue Number: ref #5257 
add a new struct named `diagnosisManager` and `coordinator` have it. `diagnosisManager`will share scheduler with `coordinator`. 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> cluster: Scheduler Dry Run mechanism

- server/core/store.go
- server/core/store_option.go
- server/core/store_stats.go
- server/core/store_test.go
- server/schedule/range_cluster.go
Issue Number: Close #3291
Tests
- Unit test
```
> $ go test -benchmem -run=^$ -bench ^BenchmarkStoreClone -benchtime=100x                                                                                       [±proto_clone ●]
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/core
cpu: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
BenchmarkStoreClone-12               100               789.0 ns/op           552 B/op         12 allocs/op
PASS
ok      github.com/tikv/pd/server/core  0.066s
wuxuelian@fun-2 ~/go/pd/server/core                                                                                                                                   [17:11:16] 
> $ go test -benchmem -run=^$ -bench ^BenchmarkStoreClone -benchtime=100x …
```
> server/core: reduce the cost of CPU for Store.Clone

- server/schedule/placement/fit.go
- server/schedule/placement/fit_test.go
Issue Number: Close #5268 
Tests
- Unit test
- benchmark
```
➜  placement git:(improve_fit) go test -benchmem -run=^$ -bench ^BenchmarkFitRegionWithMoreRulesAndStoreLabels -benchtime=100x
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/schedule/placement
cpu: VirtualApple @ 2.50GHz
BenchmarkFitRegionWithMoreRulesAndStoreLabels-8              100          24242994 ns/op         1334621 B/op      55080 allocs/op
PASS
ok      github.com/tikv/pd/server/schedule/placement    3.437s
```
```
➜  placement git:(master) go test -benchmem -run=^$ -bench ^BenchmarkFitRegionWithMoreRulesAndStoreLabels -benchtime=100x
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/schedule/placement
cpu: VirtualApple @ 2.50GHz …
```
> schedule/placement/fit: remove the recursion in pick peers for on rule

- server/api/admin.go
- server/api/admin_test.go
- server/api/router.go
- server/tso/tso.go
Add an API to drop all region cache.
Issue Number: Close #5282 
```commit-message
Currently, the interface "/admin/cache/region/{id}" just only can drop one region when needed.
This new interface provides an API to clear all caches of the region in PD.
```
Tests
- Unit test
Code changes
[WIP] Add an HTTP API interface changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentation))
```release-note
None.
```
> api: add an interface to drop all region caches

- server/schedulers/hot_region.go
Tests
- Unit test
```
None
```
> metrics: make hot split region more readable

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
Issue Number: Ref #4949 
Allows a solution to contain multiple Operators to expand the search set, guaranteeing that a better solution can be found in some cases.
Tests
- Unit test
```release-note
Optimized the search strategy of the balance-hot-region-scheduler.
```
> scheduler: support the hot-region-scheduler to generate multiple operators at the same time

- server/cluster/cluster.go
- server/region_syncer/client.go
- server/region_syncer/server.go
- server/server.go
- server/storage/endpoint/meta.go
- server/storage/storage.go
- server/storage/storage_test.go
- tests/server/cluster/cluster_test.go
Issue Number: Ref #3453
Currently, in the interface definition of `RegionStorage`, `LoadRegions` and `LoadRegionsOnce` are repeated, and the implementation of the `LoadRegionsOnce` is not always consistent with the definition. In addition, some interface conversions based on `coreStorage` are tricky.
```commit-message
storage: optimize the storage interface
```
Tests
- Unit test
```release-note
None
```
> storage: optimize the storage interface

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/coordinator_test.go
- server/core/region.go
- server/core/store.go
- server/core/store_test.go
- server/core/test_util.go
- server/grpc_service.go
- server/schedule/range_cluster.go
- tests/server/cluster/cluster_test.go
Issue Number: Close #5307
unit.KB= 1000
unitKiB= 1024
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
> server: clean some repeat code by use `1<<20` or `1<<30`

- server/core/region_tree.go
- server/core/region_tree_test.go
Issue Number: Close https://github.com/tikv/pd/issues/5318
```commit-message
```
Tests
- Unit test
```release-note
Fix the issue that the statistics of the region tree may be not accurate
```
> core: fix the wrong statistics of the region tree

- server/id/id.go
- server/id/id_test.go
- server/id/metrics.go
- server/server.go
Signed-off-by: David <8039876+AmoebaProtozoa@users.noreply.github.com>
The current implementation of id allocator permits only one id allocator due to fixed alloc path `$rootPath/alloc_id` and metrics label.
This PR attempts to make it more general purpose by parametrize its alloc path and metrics label.
Issue Number: Close #5294 
```commit-message
make id allocator general purpose
```
Tests
- Unit tests
```release-note
None.
```
> id: make id allocator general purpose

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- tests/server/config/config_test.go
Issue Number: Close #5234.
```commit-message
```
Tests
- Unit test
```release-note
Fix the issue that the online process is not accurate when having invalid label settings.
```
> *: improve the topology weight calculation

- server/schedulers/hot_region.go
Issue Number: Close #5368 
```commit-message
Remove redundant judgment in hot-region
```
```release-note
None.
```
> schedulers: Remove redundant judgment in hot-region

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- tools/pd-heartbeat-bench/main.go
Issue Number: Ref https://github.com/tikv/pd/issues/4949
Tests
- Unit test
```release-note
None.
```
> schedulers: skip uniform store to reduce schedule

- metrics/grafana/pd.json
Issue Number: Ref #5396.
```commit-message
```
Tests
- Manual test
```release-note
None
```
> metrics: fix the table compatibility problem

- go.mod
- server/schedule/filter/filters.go
- server/server.go
Issue Number: Ref #5414.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: only keep one protobuf dependency

- server/schedule/operator/builder.go
- server/schedule/operator/create_operator.go
- server/schedule/operator/create_operator_test.go
Issue Number: Close #5401 
Allows skipping placement rules checks when creating operators.
Tests
- Unit test
Code changes
```release-note
Fixed the bug where the Learner Peer of TiFlash Replica might not be created.
```
> operator: allows to skip placement rules checks

- tests/client/keyspace_test.go
Issue Number: Close #5481 
The original `TestWatchKeyspace` attempts to flush the testSuite storage by manually calling `TearDownSuite` and then `SetupSuite`, which causes the testSuite to be unstable.
This PR makes `TestWatchKeyspace` compare expected and actual result using `re.Contains` instead of doing direct indexed comparison, thus making flushing the storage unnecessary.
Tests
```release-note
none
```
> test: fix TestWatchKeyspace

- errors.toml
- pkg/errs/errno.go
- server/api/config_test.go
- server/cluster/cluster_worker.go
- server/config/config.go
- server/config/persist_options.go
- tests/server/cluster/cluster_work_test.go
Issue Number: Close #5486
ref: https://github.com/pingcap/tidb/issues/35489
- add a ttl configuration to disable tikv split
```commit-message
```
Tests
- Unit test
- max region size set to 10k
- insert data until trigger region split
- disable tikv split for 60s
- insert data, see tikv report warning that `ErrSchedulerTikvSplitDisabled`
- after ttl expired, insert some data, tikv can split normally.
- No code
Code changes
Side effects
Related …
> add ttl config to disable tikv split

- server/cluster/cluster_test.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/hot_peer_cache_test.go
Issue Number: Close #5478
1. The cold peer needs to wait the same time as the cooling interval before being activated again 
2. For unreported peers, the padding load uses 0 instead of the threshold
Tests
- Unit test
```release-note
None.
```
> statistics: fix anticount and cold peer statistics

- pkg/mock/mockcluster/mockcluster.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
Issue Number: Close https://github.com/tikv/pd/issues/5491
```commit-message
checker: fix the issue that unhealthy region cause panic
```
Tests
- Unit test
```release-note
Fix the issue that unhealthy region cause panic
```
> checker: fix the issue that unhealthy region cause panic

- server/schedule/filter/filters.go
- server/schedulers/balance_leader.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
Issue Number: Close #5492 
For the read load, there are actually two kinds, one is to read data from the leader, and the other is to read data from the follower, which includes stale read and follower read.
For strong read, there are two kinds of operators, including transfer-leader and move-leader, move-leader is a combination of transfer-leader and move-peer; for stale read and follower read, we only have one kind of operator, that is, move-peer.
In the previous strategy, for the move-peer operator, if the role of the source peer is leader, it will be changed to move-leader. That is to say, the judgment and filtering of the move-leader operator are completely based on the move-peer. So, we don't consider whether the target store can receive the …
> scheduler: fix target filter in hot scheduler when source peer is leader

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
- server/statistics/store_load.go
`maxZombieDur` is not correct when the first priority is query in hot write scheduler, query is reported by store heartbeat rather than region heartbeat, so the interval should be base store heartbeat rather than region heartbeat
It's the same reason with [`tikvCollector.GetLoads`](https://github.com/tikv/pd/blob/bca2afae417921c9e31fd2c208eea485d4d3597d/server/statistics/collector.go#L52)
Tests
- Unit test
```release-note
None.
```
> scheduler: fix write leader max zombie duration

- errors.toml
- pkg/errs/errno.go
- server/api/router.go
- server/api/store.go
- server/cluster/cluster.go
- server/config/util.go
- server/core/store.go
- tests/pdctl/store/store_test.go
- tools/pd-ctl/pdctl/command/store_command.go
Issue Number: Close https://github.com/tikv/pd/issues/5509
```commit-message
*: supports store command to delete the specified label
```
Tests
- Unit test
```release-note
store command of pdctl supports to delete the specified label for a store
```
> *: supports delete store label

- server/schedulers/hot_region.go
After #4912, we replace `first-only` with `any-of`, but it introduced an error that the result should be false when the dim is not selected with `any-of` policy.
Tests
- Unit test
```release-note
None
```
> scheduler: fix policy on `any of` in hot scheduler

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
The write leader dimension only compares the first dimension when it is good, and should only compare the first dimension when filtering.
Tests
```release-note
None
```
> scheduler: fix policy with `write-leader` in hot scheduler

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
- server/statistics/hot_cache.go
- server/statistics/hot_cache_task.go
- server/statistics/hot_peer_cache.go
- server/statistics/kind.go
- server/statistics/region_stat_informer.go
Although there is a `regionPendings` in the hot scheduler, there is only read or write load during `tryAddPendingInfluence`.
Hot write scheduler and hot read scheduler may affect each other but cannot be perceived by each other.
Tests
- Unit test
```release-note
None.
```
> statistic: collect both read and write pending influence at the same time

- server/schedulers/hot_region.go
- server/schedulers/hot_region_config.go
- server/schedulers/hot_region_test.go
- server/schedulers/hot_region_v2.go
- server/schedulers/hot_region_v2_test.go
- server/statistics/collector.go
- server/statistics/hot_peer.go
- server/statistics/kind.go
- tools/pd-ctl/pdctl/command/scheduler.go
Issue Number:  ref #4949
Tests
- Unit test
```release-note
None.
```
> *: move `dim` to `statistics`

- server/schedule/operator/step.go
- server/schedule/operator/step_test.go
Signed-off-by: Connor1996 <zbk602423539@gmail.com>
Issue Number: Close #5540
Keep the behavior as previous
```commit-message
Fix possible nil pointer when getting command
```
Tests
- Unit test
```release-note
None
```
> schedule: Fix possible nil pointer when getting command

- server/cluster/unsafe_recovery_controller.go
- server/cluster/unsafe_recovery_controller_test.go
Issue Number: Close #5418 
```commit-message
PD crashed because:
1. Region 1 and region 2 are ordered differently while creating the newest peer map and the newest region tree, since r1.Ver < r2.Ver but r1.ConfVer > r2.ConfVer. So, an error was reported while building the tree.
2. While handling the error, previous implementation cleans up the reports and then tries to read it again which results in seg fault.
To fix it:
1. Give Epoch.Ver and Epoch.ConfVer different priorities.
2. Do not clean up reports if PD is exiting force leader due to failures.
```
Tests
- Unit test
Code changes
N/A
Side effects
No
N/A
```release-note
None
```
> Prevent PD from crashing due to epoch comparison error

- tools/pd-backup/pdbackup/backup_test.go
- tools/pd-simulator/simulator/simutil/key_test.go
This PR adds unit tests to the `tools/pd-backup/pdbackup` and `tools/pd-simulator/simulator` packages, to improve their test coverage:
```sh
$ go test -cover ./tools/pd-backup/pdbackup/...                                                                                          
ok      github.com/tikv/pd/tools/pd-backup/pdbackup     0.257s  coverage: 77.8% of statements
$ go test -cover ./tools/pd-simulator/simulator/...                                                                                    
?       github.com/tikv/pd/tools/pd-simulator/simulator [no test files]
?       github.com/tikv/pd/tools/pd-simulator/simulator/cases   [no test files]
?       github.com/tikv/pd/tools/pd-simulator/simulator/info    [no test files]
ok …
```
> backup, simulator: Add Unit Tests For pd-backup And pd-simulator 

- server/cluster/coordinator.go
- tools/pd-simulator/main.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
> checkers: reduce the duplicated logic

- client/client.go
- client/errs/errno.go
- tests/client/client_test.go
Issue Number: Close #5207
```commit-message
fix Stream timeout logic
```
Tests
- Unit test
> After the leader recovers the service, the interval of client tso service recovery is tested. Compared with the previous worst-case recovery time of 23 seconds, the current recovery time can be controlled within one second
before
This PR
Side effects
```release-note
None.
```
> client: fix Stream timeout logic

- plugin/scheduler_example/evict_leader.go
- server/cluster/coordinator_test.go
- server/core/kind.go
- server/schedule/checker/joint_state_checker.go
- server/schedule/checker/replica_checker.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/operator/operator.go
- server/schedule/operator/operator_test.go
- server/schedule/operator_controller.go
- server/schedule/region_scatterer.go
- server/schedule/waiting_operator_test.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_hot_region.go
- server/schedulers/grant_leader.go
- server/schedulers/hot_region.go
- server/schedulers/random_merge.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_leader.go
- server/schedulers/shuffle_region.go
Issue Number: Close #5388
This PR does the following things:
1. For admin operators, we use Urgent priority. These operators will also pass the store limit check.
2. For shuffle/random operators, which are used in the testing environment, we use Low priority.
3. For hot/replica/evict/grant operators, we use High priority.
4. The others use Medium priority.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> schedule: refine the operator priority

- server/schedule/plan/plan.go
- server/schedulers/balance_plan.go
- server/schedulers/balance_plan_test.go
Issue Number: ref #5539
If we determine  which stores cannot be targets at the beginning of the scheduling,  we should set resource with step. 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> schdeuler: Set resource with step for collecting plan

- tools/pd-ctl/pdctl/command/region_command.go
Signed-off-by: Hua Lu <hualu@gmail.com>
Issue Number: Close #5585 
```commit-message
- parse response string with jq query
```
Tests
- Build pd-ctl
- Execute `pd-ctl region check empty-region --jq=".regions[].id"` and check the result
Code changes
Side effects
None
> Add jq for region check command

- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/core/basic_cluster.go
- server/core/region.go
- server/core/region_tree.go
Issue Number: Ref #5586.
This PR split the basic cluster lock into two and move out some logic from the lock section in the region heartbeat.
```commit-message
```
Tests
- Manual test
Test via 1000K Region/40 Store/1PD
**[8e18727](https://github.com/tikv/pd/pull/5587/commits/8e1872731c6ab516a971580bc1a745b37dd03588)**
```
Update speed of each category:
Requests/sec:     41370.8813
Save-Tree/sec:     2482.2529
Save-KV/sec:       1654.8353
Save-Space/sec:    6205.6322
Save-Flow/sec:    14479.8085
Skip/sec:         20627.0333
```
**[7d128cb](https://github.com/tikv/pd/pull/5587/commits/7d128cbfdb37fbb4dccaf1e57c74eda8f0553a63)**
```
Update speed of each category:
Requests/sec:     34475.6364
Save-Tree/sec:     2068.5382
Save-KV/sec: …
```
> *: use independent lock

- metrics/alertmanager/pd.rules.yml
When the filesystem of a TiKV node of a v5.3.0 cluster becomes read-only (e.g. due to filesystem errors, or simulated with `fsfreeze(8)` it seems to `store_disconneced_count` for 10m and then to `store_unhealth_count` for another 20m before eventually ending up in `store_down_count`.
Issue Number: Close #5611
See also https://github.com/pingcap/monitoring/pull/172
It looks like there isn't a check for `store_unhealth_count`, so that's what this PR tries to add.
Tests
- Unit test
- No code
Code changes
- Has persistent …
> metrics: Add check for unhealthy stores

- server/schedule/operator/step.go
- server/schedule/operator/step_test.go
Issue Number: Close #5623 
* Improve checks of `PromoteLearner` and `DemoteVoter`
* Allow to directly promote or demote in `ChangePeerV2Enter`.
Tests
- Unit test
Code changes
Side effects
- Since this issue just results in incorrect logging, this PR is not cherry-picked.
```release-note
None
```
> operator: fix some error checks

- pkg/rangetree/range_tree.go
- server/core/region.go
- server/core/region_test.go
- server/core/region_tree.go
- server/core/region_tree_test.go
Issue Number: Ref #5606.
```
go test -benchmem -count 5 -run=^$ -bench ^BenchmarkLoadRegionsByVolume$ github.com/tikv/pd/server/storage
name                                       old time/op    new time/op    delta
LoadRegionsByVolume/input_size_10000-40      0.05ns ±13%    0.04ns ±25%     ~     (p=0.056 n=5+5)
LoadRegionsByVolume/input_size_100000-40     0.60ns ± 9%    0.47ns ± 6%  -21.15%  (p=0.008 n=5+5)
LoadRegionsByVolume/input_size_1000000-40     6.84s ± 3%     5.35s ± 6%  -21.84%  (p=0.008 n=5+5)
name                                       old alloc/op   new alloc/op   delta
LoadRegionsByVolume/input_size_10000-40       0.00B          0.00B          ~     (all equal)
LoadRegionsByVolume/input_size_100000-40      0.00B          0.00B …
```
> *: reduce call when comparing key

- server/api/trend_test.go
- server/core/region_option.go
- server/schedule/operator_controller_test.go
- tools/pd-simulator/simulator/node.go
- tools/pd-simulator/simulator/statistics.go
- tools/pd-simulator/simulator/task.go
Issue Number: Close #5469 
Refactor `task.go`
* Split `AddVoter` and `PromoteLearner`
* Merge `AddVoter` and `AddLearner`
* `PendingPeer` will now be added first, and will be removed after the simulated snap transfer is complete.
* Support original `ChangePeer` in v2 (`ChangePeerV2` and `len(Changes) == 1`)
* Support `DemoteVoter`, and check if the Peer is not the Leader
* Support enter joint state (`ChangePeerV2` and `len(Changes) > 1`)
* Support leave joint state (`ChangePeerV2` and `len(Changes) == 0`)
* `TransferLeader` adds `Voter` checks
* `TransferLeader` supports the parsing field `Peers` (used to let TiKV find the optimal Peer by itself)
* `RemovePeer` now always also removes the corresponding `DownPeer` and `PendingPeer`
Tests
- …
> simulator: support change peer v2

- server/storage/endpoint/key_path.go
- server/storage/endpoint/key_path_test.go
Issue Number: Ref #5586.
```
name           old time/op    new time/op    delta
RegionPath-40     601ns ±25%     213ns ± 5%  -64.51%  (p=0.008 n=5+5)
name           old alloc/op   new alloc/op   delta
RegionPath-40     96.0B ± 0%     48.0B ± 0%  -50.00%  (p=0.008 n=5+5)
name           old allocs/op  new allocs/op  delta
RegionPath-40      4.00 ± 0%      2.00 ± 0%  -50.00%  (p=0.008 n=5+5)
```
Before:
After:
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: improve region path

- server/schedule/checker/merge_checker.go
- server/schedule/checker/merge_checker_test.go
Issue Number: Close #4399
```commit-message
merge_checker: use leader info to valid region
```
Tests
- Unit test
```release-note
None
```
> merge_checker: use leader info  to valid region

- tests/pdctl/scheduler/scheduler_test.go
Issue Number: Close #5667
Tests
- Unit test
```release-note
None.
```
> tests: fix unstable test `pdctl/TestScheduler`

- server/api/min_resolved_ts_test.go
- tests/server/cluster/cluster_test.go
Issue Number: Close #5589
Tests
- Unit test
```release-note
None.
```
> tests: fix unstable test `TestMinResolvedTS`

- server/schedule/filter/filters.go
- server/schedule/filter/filters_test.go
- server/schedule/filter/region_filters.go
- server/schedule/region_scatterer.go
- server/schedulers/balance_region.go
- server/schedulers/grant_hot_region.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_region.go
- server/schedulers/utils.go
Issue Number: Close #5537
```commit-message
```
Tests
the bench cmd： 
```
go test -benchmem -run=^$ -bench ^BenchmarkPlacementRule$ github.com/tikv/pd/server/schedulers -benchtime=10s  -cpuprofile profile-fit.out -cpu=2
```
master：
this pr：
Code changes
Side effects
```release-note
None.
```
> schedulers: region fit once in one attemption.

- server/api/region.go
- server/api/region_test.go
- server/api/router.go
- server/core/region.go
- server/core/region_option.go
- tools/pd-ctl/pdctl/command/region_command.go
Issue Number: Close #4042.
```commit-message
Since the region CPU metering is on by default now on TiKV side, this PR supports to get the top CPU usage regions with command `pd-ctl region topcpu`.
```
Tests
- Unit test
- Manual test
```release-note
None.
```
> api, ctl: support get the top CPU usage regions

- server/cluster/coordinator_test.go
- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
Issue Number: Close #5701 
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
> scheduler: fix the bug that balance-hot-region-scheduler does not store config when it starts

- server/schedulers/hot_region.go
- server/schedulers/hot_region_test.go
Issue Number: Close #5698 
Tests
Code changes
Side effects
```release-note
None
```
> scheduler: keep rank-formula-version at v1 when upgrading from a lower version

- tools/pd-simulator/simulator/cases/add_nodes.go
- tools/pd-simulator/simulator/cases/add_nodes_dynamic.go
- tools/pd-simulator/simulator/cases/balance_leader.go
- tools/pd-simulator/simulator/cases/balance_region.go
- tools/pd-simulator/simulator/cases/cases.go
- tools/pd-simulator/simulator/cases/delete_nodes.go
- tools/pd-simulator/simulator/cases/diagnose_label_isolation.go
- tools/pd-simulator/simulator/cases/diagnose_rule.go
- tools/pd-simulator/simulator/cases/hot_read.go
- tools/pd-simulator/simulator/cases/hot_write.go
- tools/pd-simulator/simulator/cases/import_data.go
- tools/pd-simulator/simulator/cases/makeup_down_replica.go
- tools/pd-simulator/simulator/cases/redundant_balance_region.go
- tools/pd-simulator/simulator/cases/region_merge.go
- tools/pd-simulator/simulator/cases/region_split.go
- tools/pd-simulator/simulator/config.go
- tools/pd-simulator/simulator/drive.go
- tools/pd-simulator/simulator/event.go
- tools/pd-simulator/simulator/node.go
Issue Number: Ref #5468
Prevent the following situation from happening.
```commit-message
```
Tests
- Manual test
```release-note
None
```
> tools: fix the inconsistency of available space

- tools/pd-simulator/simulator/task.go
Issue Number: Ref #5468 
Fix logic bugs from #5609  and #5323 
Tests
Code changes
Side effects
```release-note
None
```
> simulator: fix some logic bugs

- server/statistics/hot_peer_cache.go
Passing the `StoreID` into the `GetPeer` parameter causes `IsLearner` to be `false`. Only affects log and display.
Tests
Code changes
Side effects
```release-note
None
```
> statistics: fix wrong is-learner

- tests/pdctl/member/member_test.go
Issue Number: Close #5714
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: make `TestMember` stable

- server/cluster/coordinator.go
- server/cluster/coordinator_test.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/store_hot_peers_infos.go
- server/statistics/store_load.go
Issue Number: Ref https://github.com/tikv/pd/issues/5692
Before:
After:
```commit-message
```
Tests
- Unit test
```
None.
```
> statistics: reduce unnecessary copy when collect hot metrics

- go.mod
- go.sum
- server/schedule/checker/rule_checker_test.go
- server/schedule/operator/builder.go
- server/schedule/operator/create_operator.go
- server/schedule/operator/create_operator_test.go
- server/schedule/operator/kind.go
- server/schedule/operator/step.go
- server/schedule/operator/step_test.go
- tests/client/go.mod
- tests/client/go.sum
Issue Number: Close #5633
```
Split ConvertWitness from ChangePeer
```
Tests
- Unit test
- No code
Code changes
Side effects
- Need to …
> operator: split SwitchWitness from ChangePeer

- server/cluster/cluster.go
- server/cluster/cluster_test.go
Issue Number: Close https://github.com/tikv/pd/issues/5348
In a long-running cluster, there are too many tombstones. introduce auto gc mechanism.
```commit-message
server/cluster: automatic gc tombstone store
```
Tests
- Unit test
```release-note
cluster: automatic gc tombstone store
```
> server/cluster: automatic gc tombstone store

- server/cluster/cluster.go
Issue Number: Close #4823 
```commit-message
server/cluster/cluster.go: use atomic for running check instead of sharing lock with all attribbutes
```
Tests
- Unit test
Code changes
- N/A
Side effects
- N/A
- N/A
```release-note
None
```
> server/cluster/cluster.go: use atomic for running check instead of sharing lock with all attributes

- pkg/mock/mockcluster/mockcluster.go
- server/cluster/cluster_test.go
- server/cluster/coordinator_test.go
- server/core/basic_cluster.go
- server/core/region.go
- server/core/region_test.go
- server/schedule/range_cluster.go
- server/schedulers/balance_test.go
- server/schedulers/hot_region_test.go
- server/schedulers/scheduler_test.go
- tests/server/cluster/cluster_test.go
Issue Number: Ref #5712, #5586, #5648.
master:
```
[2022/11/23 15:13:15.599 +08:00] [INFO] [main.go:452] ["update speed of each category"] [rps=56747.8917] [save-tree=3404.8735] [save-kv=2269.9157] [save-space=8512.1838] [save-flow=19861.7621] [skip=28286.8378]
[2022/11/23 15:13:15.706 +08:00] [INFO] [main.go:398] ["region heartbeat stats"] [total=35.2433s] [slowest=34.8643s] [fastest=0.0000s] [average=16.5034s] [stddev=10.3169s] [rps=56748.3756]
```
this branch:
```
[2022/11/23 15:20:38.078 +08:00] [INFO] [main.go:452] ["update speed of each category"] [rps=80912.1055] [save-tree=4854.7263] [save-kv=3236.4842] [save-space=12136.8158] [save-flow=28319.2369] [skip=40331.8527]
[2022/11/23 15:20:38.239 +08:00] [INFO] [main.go:398] ["region …
```
> core: separate region lock

- server/core/region.go
- server/core/region_test.go
Issue Number: Ref #5648.
This PR skips some unnecessary checks and returns `GenerateRegionGuideFunc` early.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> core: reorder the check

- server/cluster/cluster.go
- server/core/region.go
- tests/server/cluster/cluster_test.go
Issue Number: Close #5757, #5755.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: fix `AtomicCheckAndPutRegion` deadlock

- server/statistics/hot_peer_cache.go
Issue Number: Ref #5692.
This PR reduces the number of calling `DefaultAntiCount`.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> statistics: reduce the call times of `DefaultAntiCount`

- server/core/region.go
Issue Number: Ref #5648. 
The problem is the same as the above issue and was introduced by #5615. This problem only exists in the master, no need to cherry-pick.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: fix lock in `CheckAndPutRegion`

- server/schedule/operator/step.go
- server/schedule/operator/step_test.go
Issue Number: Close #5788
Rolled back some code from #5568 and added unittest.
Tests
- Unit test
Code changes
Side effects
```release-note
Fixed an issue that `replace-down-peer` could be too slow.
```
> operator: When replacing-down-peer, it should not stop at the step of leave-joint-state

- server/schedule/operator/step.go
ref tikv/tikv#12876
Issue Number: Close #5823
When PD sends RaftCmd (batch switch witness) to TiKV, TiKV applied, the region confver will change imm, but non-witness peer is pending (waiting for snapshot), it shouldn't used to judge ConfVerChanged, so remove it.
```commit-message
step: fix non-witness ConfVerChanged impl
```
Tests
- Manual test
Code changes
- step.go
Side effects
- None
- None
```release-note
None
```
> step: fix non-witness ConfVerChanged impl

- server/cluster/unsafe_recovery_controller.go
- server/cluster/unsafe_recovery_controller_test.go
Issue Number: Close #5418 
```commit-message
PD crashed because:
1. Region 1 and region 2 are ordered differently while creating the newest peer map and the newest region tree, since r1.Ver < r2.Ver but r1.ConfVer > r2.ConfVer. So, an error was reported while building the tree.
2. While handling the error, previous implementation cleans up the reports and then tries to read it again which results in seg fault.
To fix it:
1. Give Epoch.Ver and Epoch.ConfVer different priorities.
2. Do not clean up reports if PD is exiting force leader due to failures.
```
Tests
- Unit test
Code changes
N/A
Side effects
No
N/A
```release-note
None
```
> Prevent PD from crashing due to epoch comparison error (#5449)

- tests/msc/Makefile
- tests/msc/go.mod
- tests/msc/go.sum
- tests/msc/resource_manager/resource_manager_test.go
Issue Number: Ref #5851.
Let `make check` work for `msc`.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: add Makefile for msc

- pkg/storage/endpoint/gc_key_space.go
- pkg/storage/endpoint/key_path.go
- server/storage/storage.go
- server/storage/storage_gc_test.go
Issue Number: ref #5293.
```commit-message
Unify the keyspace naming.
```
Tests
- Unit test
```release-note
None.
```
> storage: unify the keyspace naming

- pkg/core/region.go
This pr avoid zap before passing the reference but we need a better way to reduce zap cpu time
Issue Number: Ref #5692
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> core: reduce log zap cpu time

- server/config/config.go
- server/schedule/operator/kind.go
- server/schedulers/transfer_witness_leader.go
Issue Number: ref #5638
Separate the limit configuration of `transfer-witness-leader` and `balance-leader`. Otherwise, when the witness becomes the leader, the op could not be created in time because the quota was full. The client will return a backoff error: `is_witness`.
```commit-message
schedulers: split transfer-witness-leader's limit from balance-leader
```
Tests
Code changes
Side effects
- None
```release-note
None
```
> schedulers: split transfer-witness-leader's limit from balance-leader

- server/schedule/placement/region_rule_cache.go
- server/schedule/placement/region_rule_cache_test.go
- server/schedule/placement/rule_manager.go
Issue Number: Ref #5864
There is `labels map[string]string` in `storeCache`. When the store has longer or more labels, each region cache will use a lot of memory.
part of #5860
use public stores cache in placement rules cache.
Tests
- Unit test
```release-note
None
```
> schedule: use public stores cache in placement rules cache

- pkg/mcs/resource_manager/client/client.go
- pkg/mcs/resource_manager/client/config.go
- pkg/mcs/resource_manager/client/limiter.go
- pkg/mcs/resource_manager/client/limiter_test.go
Issue Number: ref #5851
Take the facts, we don't have to check too big request.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> resource_manager: remove `maxRequestTokens` in limiter

- server/cluster/coordinator_test.go
- server/config/config.go
It is very unfriendly to let the user manually enable this scheduler, it has no effect if witness is not supported.
Issue Number: ref tikv/pd#5638
```commit-message
enable transfer-witness-leader by default
```
Tests
- Unit test
- Manual test
Code changes
- None
Side effects
- None
- None
```release-note
None
```
> schedulers: enable transfer-witness-leader by default

- metrics/grafana/pd.json
ref tikv/pd#5568
Issue Number: ref #5568
```commit-message
```
Tests
- No code
Code changes
- None
Side effects
- None
- None
```release-note
None
```
> metrics: add witness count

- pkg/mcs/resource_manager/server/manager.go
- pkg/mcs/resource_manager/server/resource_group.go
- pkg/storage/endpoint/key_path.go
- server/grpc_service.go
- server/server.go
- tests/client/global_config_test.go
Issue Number: Ref #5851 
This PR and #5886 will fix #https://github.com/pingcap/tiflow/issues/8110
Create a new storage endpoint and uses separate root path different from PD server
```commit-message
```
Tests
- Unit test
Code changes
```release-note
None.
```
> resource_manager, storage: create new storage endpoint for resource manager

- metrics/grafana/pd.json
ref tikv/pd#5568
Issue Number: ref #5568
```commit-message
```
Tests
- None
Code changes
- None
Side effects
- None
- None
```release-note
None
```
> metrics: fix witness count id and datasource

- pkg/mcs/resource_manager/server/manager.go
Issue Number: ref #5854
```
Collect kvCPUTime metrics when sqlCPUTime is 0.
```
Tests
Code changes
Side effects
```release-note
None
```
> resource_manager: fix missing kvCPUTime when sqlCPUTime is 0

- pkg/mock/mockcluster/mockcluster.go
- pkg/storage/endpoint/key_path.go
- pkg/storage/endpoint/resource_group.go
- pkg/storage/endpoint/tso.go
- pkg/tso/allocator_manager.go
- server/cluster/coordinator_test.go
- server/storage/storage.go
- server/storage/storage_tso_test.go
Issue Number: Ref #5849.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> storage: add TSO storage

- server/schedulers/transfer_witness_leader.go
Issue Number: Close #5638 
```commit-message
- Reduce the batch size to avoid discarding if it exceeds MaxWaitingOperator
- Increase the channel capacity to avoid discarding when the capacity is full
```
Tests
- No code
Code changes
- None
Side effects
- None
- None
```release-note
None
```
> schedulers: reduce the batch size to avoid discarding

- cmd/pd-server/main.go
- pkg/basic_server/basic_server.go
Signed-off-by: Bin Shi <binshi.bing@gmail.com>
Issue Number: Ref #5836
A service in different mode has different config struct and initialization logic, so we need to abstract an interface to create server.
```commit-message
A service in different mode has different config struct and initialization logic, so we need to abstract an interface to create server.
```
Tests
I did some compatibility test manually by verifying that the all-in-one pd-server can start normally w/o and w/ parameter.
None.
```release-note
None.
```
> *: refactor server entry point to support multi-mode service

- cmd/pd-server/main.go
- server/api/hot_status_test.go
- server/api/scheduler_test.go
- server/cluster/cluster_worker_test.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/balance_witness.go
- server/schedulers/evict_leader.go
- server/schedulers/evict_slow_store.go
- server/schedulers/grant_hot_region.go
- server/schedulers/grant_leader.go
- server/schedulers/hot_region.go
- server/schedulers/init.go
- server/schedulers/label.go
- server/schedulers/random_merge.go
- server/schedulers/scatter_range.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_leader.go
- server/schedulers/shuffle_region.go
- server/schedulers/split_bucket.go
- server/schedulers/transfer_witness_leader.go
- server/testutil.go
- tests/dashboard/race_test.go
- tests/dashboard/service_test.go
- tests/server/server_test.go
- tools/pd-simulator/main.go
Issue Number: Ref #5837
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> scheduler: move init function

- server/schedule/operator/step.go
ref tikv/pd#5656
Issue Number: Close #5656
When region A's witness and region B's witness not on the same store. It will gen the op with
step1:  Demote witness voter -> witness learner
step2: switch witness learner -> non-witness leaner
step3: Promote non-witness learner -> voter
When calculating the conf ver change, after the third step is executed, the conf ver change condition of the first step is not satisfied, resulting in the difference between the actual region conf ver change and the calculated one.
So add witness change as a condition to solve this.
```commit-message
step: fix merge region failed caused by mismatch confver
```
Tests
- Manual test 
- test with sysbench prepare
Code changes
- None
Side effects
- None …
> step: fix merge region failed caused by mismatch confver

- client/resource_manager/client/limiter.go
Issue Number: Ref https://github.com/tikv/pd/issues/5945
```commit-message
limiter: remove the warn log
```
Tests
- Unit test
```release-note
None
```
> limiter: remove the warn log

- server/schedule/checker/checker_controller.go
- server/schedule/checker/rule_checker.go
- server/schedule/placement/fit.go
- server/schedule/placement/fit_test.go
- server/schedule/placement/region_rule_cache.go
- server/schedule/placement/rule_manager.go
- server/schedule/placement/rule_manager_test.go
Issue Number: Ref #5864
`bestFit` uses more memory, but it is rarely used.
part of #5860
Only cache bestFits that have been used more than 10 times.
Tests
- Unit test
```release-note
None
```
> schedule: placement rules cache reduce cache low usage fit

- pkg/utils/etcdutil/etcdutil.go
- server/server.go
Issue Number: Close #5837
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> server: move client function to util

- server/cluster/cluster.go
Issue Number: Close #5965
no more redundant etcd writes when `SetMinResolvedTS` is called
Tests
- Unit test
- This PR is based on c64be1f858c4c79356fecdc0f232ba786b1c9d70
- Make `putStoreLocked` called by `SetMinResolvedTS` slower [7a47041](https://github.com/HunDunDM/pd/commit/7a47041234ec37d92774fee2e8f78080e7d865da)
- `tiup playground v6.5.0 --kv=15 --db=1 --pd=1 --tiflash=0 --pd.binpath=bin/pd-server`
- The problem can be reproduced in grafana
- <img width="714" alt="image" src="https://user-images.githubusercontent.com/19789302/218397521-f76b8c1a-3f3b-4e6c-8651-48ae0de98556.png">
- <img width="713" alt="image" src="https://user-images.githubusercontent.com/19789302/218397660-978c8c6a-0112- …
> cluster: no more redundant etcd writes when `ReportMinResolvedTS` is called

- Dockerfile
Signed-off-by: David <8039876+AmoebaProtozoa@users.noreply.github.com>
Issue Number: Close #5968
current runner image from docker file is based on alpine 3.5, which reached end of life more than 4 years ago (2018-11-01) and does not support arm build. This PR bumps it to a more recent 3.17, same as golang:1.19-alpine used in builder.
further more, `binutils-gold` is added to avoid errors like `fatal error: cannot find 'ld'`, similar issues can be seen here: https://github.com/golang/go/issues/52399
Tests
`make docker-image` now finished successfully on m1 mac.
```release-note
None
```
> build: bump alpine image to 3.17

- conf/config.toml
- server/config/config.go
Issue Number: Close https://github.com/tikv/pd/issues/5973
```commit-message
dashboard: default close telemetry
```
Tests
- Unit test
```release-note
default close TiDB dashboard's telemetry
```
> dashboard: default close telemetry

- pkg/utils/etcdutil/etcdutil.go
- pkg/utils/etcdutil/etcdutil_test.go
- pkg/utils/grpcutil/grpcutil.go
- server/grpc_service.go
- server/server.go
- server/util.go
This change is split from "basic implement tso gPRC service #5949"
Signed-off-by: Bin Shi <binshi.bing@gmail.com>
Issue Number: Ref #5836
This change is split from [basic implement tso gPRC service #5949](https://github.com/tikv/pd/pull/5949)
```commit-message
Refactor some common utilities which will be used by tso mcs
```
Tests
- Unit test
Code changes
Side effects
None
```release-note
None
```
> Refactor some common utilities which will be used by the upcoming TSO microservice change

- cmd/pd-server/main.go
- pkg/mcs/tso/server/server.go
- pkg/tso/config.go
- pkg/utils/logutil/log.go
- server/api/server_test.go
- server/config/config.go
- server/config/config_test.go
- server/server.go
- server/testutil.go
- tests/cluster.go
- tests/config.go
- tools/pd-heartbeat-bench/config/config.go
- tools/pd-heartbeat-bench/main.go
- tools/pd-simulator/main.go
This PR has a similar functionality to #5964 but uses the independent config for starting the TSO server. Besides, we can use the same function to init log for all binaries now. 
Update: 
Replace the original implementation with the cobra.
```commit-message
```
Tests
- Unit test
```release-note
None
```
> *: add service subcommand

- pkg/cgroup/cgroup_cpu.go
- pkg/cgroup/cgroup_cpu_test.go
Issue Number: Ref #5953
Ignore error 'no cpu controller detected' on old kernel but still panic on new kernel. (Thanks a lot for the advice from @nolouch)
Remove TestGetCgroupCPU from the flaky test list.
Reference:
https://github.com/pingcap/tidb/pull/41347
https://github.com/pingcap/tidb/pull/41475
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> cgroup: refine the handling of error 'no cpu controller detected'

- Makefile
```commit-message
Use the absolute path to cd during the check.
```
Sometimes we may encounter the error like:
```shell
revive ...
make[1]: Entering directory '/home/runner/work/pd/pd/client'
cd .. && make install-tools
make[2]: Entering directory '/home/runner/work/pd/pd'
make[2]: Leaving directory '/home/runner/work/pd/pd'
make[1]: Leaving directory '/home/runner/work/pd/pd/client'
make[1]: Entering directory '/home/runner/work/pd/pd/tests/mcs'
cd ../../ && make install-tools
make[2]: Entering directory '/home/runner/work/pd/pd'
make[2]: Leaving directory '/home/runner/work/pd/pd'
level=error msg="Running error: context loading failed: no go files to analyze"
make[1]: *** [Makefile:21: static] Error 5
make[1]: Leaving directory …
```
> Makefile: use the absolute path to cd during the check

- .github/pull_request_template.md
```commit-message
Use `None` as the default release note placeholder.
```
Tests
- No code
```release-note
None.
```
> .github: use None as the default release note placeholder

- cmd/pd-server/main.go
- pkg/audit/audit.go
- pkg/audit/audit_test.go
- pkg/cache/ttl.go
- pkg/dashboard/adapter/manager.go
- pkg/dashboard/distroutil/distro.go
- pkg/dashboard/keyvisual/input/core.go
- pkg/encryption/key_manager.go
- pkg/mcs/resource_manager/server/server.go
- pkg/mcs/tso/server/server.go
- server/cluster/unsafe_recovery_controller.go
- server/region_syncer/client.go
- server/schedule/labeler/labeler.go
- server/server.go
- tests/server/api/api_test.go
- tools/pd-analysis/analysis/parse_log.go
- tools/pd-analysis/analysis/transfer_counter.go
- tools/pd-analysis/main.go
- tools/pd-heartbeat-bench/main.go
- tools/pd-simulator/simulator/cases/cases.go
- tools/pd-simulator/simulator/cases/import_data.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: remove periods and align case at the beginning of sentences

- client/base_client.go
- pkg/mcs/resource_manager/server/server.go
- pkg/utils/etcdutil/etcdutil.go
- pkg/utils/etcdutil/etcdutil_test.go
- pkg/utils/etcdutil/testutil.go
- tests/client/client_test.go
Issue Number: Close #6042
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> etcdutil: support multi backends client

- pkg/mcs/resource_manager/server/server.go
- tests/mcs/resource_manager/server_test.go
This PR is going to register the resource manager into etcd after starting.
Issue Number: Ref #5766.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> mcs: register resource manager to etcd

- server/schedule/region_scatterer.go
- server/schedule/region_scatterer_test.go
Issue Number: Close #6017 
Use a more correct method to select candidate leaders.
Tests
- Unit test
Code changes
Side effects
```release-note
Fix a bug that the leaders may be unbalanced during scatter region.
```
> region_scatter: fix a bug that the leaders may be unbalanced after scatter region

- client/resource_group/controller/config.go
- client/resource_group/controller/controller.go
- tests/mcs/resource_manager/resource_manager_test.go
Issue Number: ref #6038. Should merge after #6041.
```commit-message
- Load RU config from the remote server when initializing controller. 
```
Tests
- Unit test
```release-note
None.
```
> resource_controller: load RU config from the remote server when initializing controller

- tests/client/client_test.go
Issue Number: Close #6071.
The watch might start after other etcd operations, which may cause test timeout.
```commit-message
```
Tests
- Unit test
- Manual test
Successfully run 100 times in the local environment.
```release-note
None.
```
> *: make `TestWatch` stable

- pkg/movingaverage/median_filter.go
Issue Number: Close #6069
after #5798 we use cache result in `median.Get` to reduce memory, but it introduces a write operation in `get`, so we remove write op in `get` function to avoid data race. And considering there is more `get` than `add`, it still is valid to reduce memory and CPU time.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> moving_filter: fix data race with cache result

- server/cluster/cluster.go
Issue Number: ref #6045
Try to fix a data race. See #6045 for more information.
```commit-message
```
Tests
- Unit test
- No code
```release-note
None.
```
> try fix data race

- pkg/mcs/discovery/register.go
Fix a deadloop in ServiceRegister which happens after etcd exits then the server receives the exit-signal
Issue Number: Ref #5836
```commit-message
```
Tests
Before:
1. start etcd with `./pd-server`
2.start one tso server `./pd-server services tso --listen-addr="127.0.0.1:3379" --backend-endpoints="http://127.0.0.1:2379"`
3. kill pd(etcd)
4. ctl-c to terminate tso server. tso server will in the deadloop of renew lease in the service registry.
_[2023/03/06 21:34:15.076 -08:00] [ERROR] [register.go:87] ["grant lease failed"] [key=/pd/microservice/tso/registry/127.0.0.1:3380] [error="context canceled"]
[2023/03/06 21:34:16.576 -08:00] [WARN] [retry_interceptor.go:62] ["retrying of unary invoker failed"] …
> Fix a deadloop in ServiceRegister

- client/resource_group/controller/model.go
- tests/mcs/resource_manager/resource_manager_test.go
Issue Number: Ref #5851
```
Change the cpu time uint from ms to ns because ms is too coarse-grained that it will ignore duration small than 1ms.
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
> resource_manager: change cpu time unit from ms to ns

- pkg/mcs/discovery/register.go
Fix deadloop in discovery.Deregister when the etcd backend isn't available and the server received exit-signal.
Issue Number: Ref #5836 
```commit-message
Fix deadloop in discovery.Deregister when the etcd backend isn't available and the server received exit-signal.
```
Tests
With the repro steps below:
1. start etcd with `./pd-server`
2.start one tso server `./pd-server services tso --listen-addr="127.0.0.1:3379" --backend-endpoints="http://127.0.0.1:2379"`
3. kill pd(etcd)
4. ctl-c to terminate tso server. 
**Before:**
[2023/03/07 16:29:57.374 -08:00] [INFO] [server.go:281] ["closing tso server ..."]
[2023/03/07 16:29:57.374 -08:00] [ERROR] [register.go:94] ["grant lease failed"] [key=/pd/microservice/tso/registry/127.0.0.1:3379] …
> Fix deadloop in discovery.Deregister

- client/client.go
- client/pd_service_discovery.go
- client/tso_dispatcher.go
- client/tso_service_discovery.go
- pkg/mcs/tso/server/server.go
- tests/mcs/tso/testutil.go
- tests/mcs/tso/tso_service_test.go
Issue Number: Ref #5836 
```commit-message
Add and initialize cluster id in the TSO service.
PD/API service discovery gets cluster id from the API service.
It then passes the cluster id to the TSO service because both share the same cluster id.
```
Tests
- Unit test
```release-note
None.
```
> Add and initialize cluster id in the TSO service

- client/resource_group/controller/controller.go
- client/resource_group/controller/controller_test.go
- client/resource_group/controller/testutil.go
- tests/mcs/resource_manager/resource_manager_test.go
Issue Number: ref #5851. Part of https://github.com/pingcap/tidb/issues/41972.
```commit-message
- Return the consumption info on RU request/response.
- Remove some unnecessary `goto`s.
```
Tests
- Unit test
```release-note
None.
```
> controller: return the consumption info on RU request/response

- client/resource_group/controller/config.go
- client/resource_group/controller/controller.go
The default value (1s) of maxWaitDuration may not suitable for some cases.
make configurable.
```commit-message
```
Tests
- Unit test
Code changes
```release-note
None.
```
> client/resource_group: make maxWaitDuration configurable

- client/tso_service_discovery.go
- pkg/mcs/resource_manager/server/server.go
- pkg/mcs/tso/server/server.go
- server/server.go
This PR uses cluster id for the election instead of using 0.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> mcs: use cluster ID for election

- client/client.go
- client/errs/errno.go
Fix panic issue when client.getClient is called to fetch pd proto client and there is no available one.
The fix is, when client.getClient returns nil, the current logic will detect it and returns errs.ErrClientGetProtoClient instead.
Mostly, the root cause is that, after the pd client is closed, there is a very small time window in which the pd client user is still calling pd client APIs.
Issue Number: Close #6159 
```commit-message
Fix panic issue when client.getClient is called to fetch pd proto client and there is no available one.
```
Tests
- Unit test
```release-note
None.
```
> Fix panic issue when client.getClient returns nil.

- go.mod
- go.sum
- pkg/mcs/resource_manager/server/resource_group.go
- pkg/mcs/resource_manager/server/resource_group_test.go
- tests/client/go.mod
- tests/client/go.sum
- tests/mcs/go.mod
- tests/mcs/go.sum
- tests/mcs/resource_manager/resource_manager_test.go
- tests/mcs/resource_manager/server_test.go
Issue Number: Close #6179 
```commit-message
Add priority field for resource group
```
Tests
- Unit test
```release-note
None.
```
> resource control: add priority field for resource group

- tests/pdctl/config/config_test.go
- tools/pd-ctl/pdctl/command/config_command.go
Issue Number: Close #5967 
- Change `rule-group delete` func to `delRuleBundle`
- Add regex usage message in `rule-group delete` command desc
- Add deprecated message in `rule-group delete` command desc 
Tests
- Compile & build pd-ctl
- start a tiup playground, and added few placement rules
- use `pd-ctl config placement-rules rule-group delete` command to delete one or some groups
- check and validate the result
Code changes
Side effects
```release-note
None.
```
> change rule-group delete func to rule-bundle delete func

- pkg/mcs/resource_manager/server/server.go
- pkg/mcs/tso/server/server.go
- pkg/utils/etcdutil/etcdutil.go
- pkg/utils/etcdutil/etcdutil_test.go
- server/server.go
Issue Number: Close #6124
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> etcdutil: revert etcd client in pd legacy server

- client/client.go
- client/pd_service_discovery.go
- client/tso_client.go
- client/tso_dispatcher.go
- client/tso_service_discovery.go
```commit-message
Some code refinements for `serviceModeKeeper`.
```
Tests
- Unit test
```release-note
None.
```
> client: refine serviceModeKeeper code

- pkg/core/region_tree.go
- pkg/mcs/tso/server/server.go
- pkg/member/member.go
- pkg/movingaverage/moving_average_test.go
- pkg/schedule/filter/candidates.go
- pkg/schedule/waiting_operator.go
- pkg/utils/etcdutil/etcdutil.go
- server/server.go
Issue Number: Close #6134.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: remove unnecessary rand init

- pkg/storage/kv/etcd_kv.go
The lock here is used for multiple callers using the same Txn. But we barely have this situation in PD. At least, we don't have a such scenario for now. So this PR is going to remove it to improve the TSO saving performance.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> pkg: remove txn lock

- pkg/mcs/resource_manager/server/manager.go
- tests/integrations/mcs/resource_manager/server_test.go
Issue Number: ref #4399 Ref https://github.com/pingcap/tidb/issues/42595
```commit-message
resource_manager: change the default group fillrate to MaxInt32
```
Tests
- Unit test
```release-note
None.
```
> resource_manager: change the default group fillrate to MaxInt32

- client/resource_group/controller/limiter.go
Issue Number: Close #6236
When burst < 0, the `isLowTokensLocked` always return false.
```commit-message
When burst < 0, the `isLowTokensLocked` always return false.
```
Tests
> alter resource group rg2 RU_PER_SEC=200 BURSTABLE;
alter user 'user2' resource group rg2;
sysbench --mysql-host=127.0.0.1 --mysql-user=user2 --mysql-port=4000 --mysql-db=sbtest --percentile=99 --report-interval=1 --tables=4 --table_size=1000000 oltp_read_only --range_selects --threads=4 --time=1800 run
Code changes
Side effects
- …
> resource_manager/client: fix too many token request when burst < 0

- server/cluster/unsafe_recovery_controller.go
- server/cluster/unsafe_recovery_controller_test.go
This is a cherry-pick of #6108, replacing the ti-chi-bot automated cherry-pick #6111 to resolve merge conflicts.
Issue Number: Close #6107
```commit-message
fix online recovery timeout mechanism
```
Tests
- Unit test
- No code
Code changes
Side effects
- PR …
> online recovery: fix online recovery timeout mechanism (#6108)

- pkg/keyspace/keyspace.go
- pkg/keyspace/keyspace_test.go
- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- pkg/storage/endpoint/tso_keyspace_group.go
- server/server.go
- tests/server/apiv2/handlers/keyspace_test.go
- tests/server/apiv2/handlers/tso_keyspace_group_test.go
Issue Number: Ref #6231.
This PR defines the user kind for the keyspace group and adds the interface for assigning the group ID to the keyspace.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: define user kind for keyspace group

- client/pd_service_discovery.go
- tests/integrations/tso/server_test.go
Issue Number: Close #6285.
Fix the issue mentioned above.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: fix unexpected log

- tests/integrations/client/client_test.go
Issue Number: Close #6250.
Ignore the leader change error to make test more stable.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: make TestGlobalAndLocalTSO stable

- pkg/keyspace/keyspace.go
- pkg/keyspace/keyspace_test.go
- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- pkg/keyspace/util.go
- pkg/slice/slice.go
- pkg/slice/slice_test.go
- server/apiv2/handlers/tso_keyspace_group.go
Issue Number: Close #6231.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: auto assign keyspace group

- client/resource_group/controller/controller.go
- client/resource_group/controller/controller_test.go
- client/resource_group/controller/limiter.go
- client/resource_group/controller/metrics.go
- tests/integrations/mcs/resource_manager/resource_manager_test.go
Issue Number: Close #6298 close #6300
1. notify when the limiter reserve token fails. In addition, the limit of notify times is set when the limiter is limit state.
2. Update the logic of RU consumption statistics. This ensures that speed includes the application in progress when notifying
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> resource_manager/client: fix exceed error when ru consump of query is greater than ru fill rate

- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- pkg/keyspace/util.go
- pkg/storage/endpoint/tso_keyspace_group.go
- pkg/tso/keyspace_group_manager.go
- server/apiv2/handlers/tso_keyspace_group.go
- tests/server/apiv2/handlers/tso_keyspace_group_test.go
```commit-message
Support the keyspace group split and add related tests.
```
Tests
- Unit test
```release-note
None.
```
> keyspace, api: support the keyspace group split

- pkg/tso/allocator_manager.go
- pkg/tso/keyspace_group_manager.go
- pkg/tso/keyspace_group_manager_test.go
Issue Number: Ref #6232 
```commit-message
Use the RWMutex instead of individual atomic types to better protect the state of the keyspace group manager
```
Tests
- Unit test
```release-note
None.
```
> Improve lock mechanism in tso.KeyspaceGroupManager

- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- pkg/storage/endpoint/tso_keyspace_group.go
- tests/server/apiv2/handlers/tso_keyspace_group_test.go
Issue Number: ref #6232. This field is necessary since we have to know which keyspace group this new one comes from, so we can get the corresponding member info to implement the election constraint during the TSO split.
```commit-message
Add `split-from` field for `endpoint.KeyspaceGroup`.
```
Tests
- Unit test
```release-note
None.
```
> keyspace: add split-from field for endpoint.KeyspaceGroup

- pkg/keyspace/keyspace.go
- pkg/keyspace/tso_keyspace_group.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/server.go
- tests/server/apiv2/handlers/keyspace_test.go
- tests/server/apiv2/handlers/tso_keyspace_group_test.go
- tests/server/cluster/cluster_test.go
Issue Number: Ref #6231.
This PR uses a mode check to decide if the keyspace group should be initialized and bootstrapped.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: bootstrap keyspace group when server is in API mode

- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- pkg/keyspace/util.go
- pkg/storage/endpoint/tso_keyspace_group.go
- tests/server/apiv2/handlers/tso_keyspace_group_test.go
Issue Number: ref #6232. In order to avoid the disruption of consistency, this restriction is added to ensure the integrity of all kinds of information during the split.
```commit-message
Prevent keyspace from being updated during the split.
```
Tests
- Unit test
```release-note
None.
```
> keyspace: avoid keyspace being updated during the split

- pkg/tso/global_allocator.go
Issue Number: Close #6275.
There might be a small time window that TSO in memory has been reset but the request still pass the leadership check.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: fix `TestConcurrentlyReset`

- pkg/keyspace/tso_keyspace_group.go
- pkg/mcs/tso/server/handler.go
- pkg/mcs/tso/server/server.go
- pkg/mcs/utils/constant.go
- pkg/tso/keyspace_group_manager.go
- pkg/tso/keyspace_group_manager_test.go
- pkg/utils/tsoutil/tso_request.go
- server/apiv2/handlers/tso_keyspace_group.go
- server/grpc_service.go
- server/server.go
Issue Number: Ref #6232
```commit-message
Changes:
1. Introduce the initialization logic of the default keyspace group.
- If the default keyspace group isn't configured in the etcd, every tso node/pod should initialize it and join the election for the primary of this group.
- If the default keyspace group is configured in the etcd, the tso nodes/pods which are assigned with this group will initialize it and join the election for the primary of this group.
2. Introduce the keyspace group membership restriction -- default keyspace always belongs to default keyspace group.
```
Tests
- Unit test
```release-note
None.
```
> bootstrap default keyspace group in the tso service

- pkg/keyspace/tso_keyspace_group.go
- pkg/tso/keyspace_group_manager.go
- server/server.go
Issue Number: Ref #6343 
```commit-message
Fixed the following two bugs:
1. When re-watch a range, to continue from what left by the last watch, the revision is wresp.Header.Revision + 1 instead of wresp.Header.Revision, where wresp.Header.Revision is the revision indicated in the response of the last watch. Because of this bug, it was processing the same event endless as you can see from the log below.
2. In tso service watch loop in /Users/binshi/code/pingcap/my-pd/pkg/keyspace/tso_keyspace_group.go, If this is delete event, the json.Unmarshal(event.Kv.Value, s) will fail with the error "unexpected end of JSON input", so there is no way to get s.serviceAddr from the result of json.Unmarshal.
```
Tests
- Unit test
```release-note
None.
```
> Fixed bugs in tso service registry watching loop.

- errors.toml
- pkg/errs/errno.go
- pkg/mcs/tso/server/server.go
- pkg/member/participant.go
- pkg/tso/allocator_manager.go
- pkg/tso/global_allocator.go
- pkg/tso/keyspace_group_manager.go
- tests/integrations/mcs/cluster.go
- tests/integrations/mcs/tso/keyspace_group_manager_test.go
- tests/server/apiv2/handlers/testutil.go
- tests/server/apiv2/handlers/tso_keyspace_group_test.go
```commit-message
Add more TSO split tests.
```
Tests
- Unit test
```release-note
None.
```
> tests, tso: add more TSO split tests

- pkg/keyspace/tso_keyspace_group.go
- pkg/tso/keyspace_group_manager.go
Issue Number: Ref #6232 
```commit-message
The next revision to watch should always be Header.Revision + 1 where header is response header of watch/Get/RangeScan
```
Tests
- Unit test
```release-note
None.
```
> keyspace, tso: fix next revision to watch after watch/Get/RangeScan

- pkg/storage/endpoint/tso.go
- pkg/storage/storage_tso_test.go
Issue Number: Close #6355.
Previously, we use txn to save timestamps. But if the timestamp is equal to or less than the previous one, we only return nil, which may cause memory to have an inconsistent state. This PR returns an error in such a case.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> pkg: fix tso inconsistent problem

- pkg/mcs/tso/server/server.go
- tests/integrations/mcs/cluster.go
- tests/integrations/tso/client_test.go
```commit-message
Use TSO cluster to do the failover test.
```
Tests
- Unit test
```release-note
None.
```
> mcs, tests: use TSO cluster to do the failover test

- pkg/keyspace/keyspace_test.go
- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- server/cluster/cluster.go
Issue Number: Ref #6351.
Use the cluster's context instead of the keyspace group manager's context.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: fix `startWatchLoop` leak

- server/grpc_service.go
Issue Number: Close #6340
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> mcs: update client when meet transport is closing

- tests/integrations/mcs/tso/server_test.go
This PR adds the basic keyspace group bootstrap test.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> mcs: add bootstrap test

- pkg/tso/keyspace_group_manager_test.go
Reduce the count of keyspace groups from 4096 to 512 in TestKeyspaceGroupManagerTestSuite/TestLoadKeyspaceGroupsAssignment to avoid timeout when test running slow.
Issue Number: Close #6360 
```commit-message
Reduce the count of keyspace groups from 4096 to 512 in TestKeyspaceGroupManagerTestSuite/TestLoadKeyspaceGroupsAssignment to avoid timeout when test running slow.
```
Tests
- Unit test
```release-note
None.
```
> mcs, tso : fix flaky TestLoadKeyspaceGroupsAssignment test

- pkg/mcs/tso/server/server.go
- tests/integrations/mcs/cluster.go
- tests/integrations/mcs/testutil.go
- tests/integrations/mcs/tso/server_test.go
Issue Number: Ref #6355 
```commit-message
Change participant election-prifix from listen-addr to advertise-listen-addr to guarantee uniqueness.
If multiple participants have the same unique name/id, they all could become the primary and cause ts fallback seen by the client.
```
Tests
- Unit test
```release-note
None.
```
> mcs, tso: fix ts fallback caused by multi-primary of the same keyspace group 

- pkg/statistics/region_collection.go
Issue Number: Close #6366 
https://github.com/prometheus/client_golang/blob/d7896d4bd082b17e525c29055d79cc29484aa9cb/prometheus/vec.go#L125 doesn't reset the gauge in this metrics vec, instead, it deletes them all.
```commit-message
*: fix deletion of region stats metrics after resign
```
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
> *: fix deletion of region stats metrics after resign

- pkg/core/storelimit/limit_test.go
Issue Number: Close #6369
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
> fix data race issue in the store limit test

- server/cluster/cluster.go
Issue Number: Close #6351
```commit-message
The root cause is that the multi-thread locking issue in RaftCluster.Start. RaftCluster.Start can be invoked concurrently in different routines -- one is from becoming new leader; another is Server.BootStrap RPC called by test or other callers. Both routines check that RaftCluster isn't running, so both proceed to c.Lock and only one enters the critical section and complete all the start work including GroupManager.Bootstrap in which watchServiceAddrs could dynamically update the serverRegistryMap; after the first one exits the critical section, the second one enters and calls GroupManager.Bootstrap() again and it will concurrently update serverRegistryMap with the previously created loop. The fundermal issue is that the second one should check, …
```
> mcs: fix duplicate start of RaftCluster.

- tests/pdctl/scheduler/scheduler_test.go
Issue Number: Close #6359.
When the scheduler is running, if we change pause the scheduler, it might have a time window that the pause status is not set to the diagnostic result which causes the test unstable.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> *: make TestScheduler stable

- pkg/tso/keyspace_group_manager.go
- tests/integrations/mcs/tso/keyspace_group_manager_test.go
If the desired keyspace group fall back to the default keyspace group and the AM isn't initialized, return not served error.
Issue Number: Close #6381 
```commit-message
If the desired keyspace group fall back to the default keyspace group and the AM isn't initialized, return not served error.
```
Tests
- Unit test
```release-note
None.
```
> mcs, tso: fix Nil pointer deference when (*AllocatorManager).GetMember

- client/client.go
- server/keyspace_service.go
- tests/integrations/mcs/testutil.go
- tests/integrations/mcs/tso/server_test.go
Due to TiDB using the string as the keyspace identity, we need to handle such a case and create a PD client through the name.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> client: add `NewClientWithKeyspaceName` for client

- pkg/tso/keyspace_group_manager.go
- pkg/tso/keyspace_group_manager_test.go
- tests/integrations/mcs/tso/keyspace_group_manager_test.go
Issue Number: Ref #6232
```commit-message
fix bugs to make split test case to pass
```
Tests
- Unit test
```release-note
None.
```
> tso: fix bugs to make split test case to pass

- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- tests/integrations/mcs/tso/keyspace_group_manager_test.go
```commit-message
Patrol the keyspace assignment before the first split to make sure every keyspace has its group assignment.
```
Tests
- Unit test
```release-note
None.
```
> keyspace: patrol keyspace assignment before the first split

- tests/integrations/tso/server_test.go
Issue Number: Close #6385 
```commit-message
Get a copy of now then call base.add, because now is shared by all goroutines and now.add() will add to itself which isn't atomic and multi-goroutine safe.
```
Tests
- Unit test
```release-note
None.
```
> tests: fix Flaky TestMicroserviceTSOServer/TestConcurrentlyReset

- pkg/keyspace/tso_keyspace_group.go
- pkg/slice/slice.go
- pkg/slice/slice_test.go
- tests/integrations/mcs/keyspace/tso_keyspace_group_test.go
Issue Number: Ref #6231 
```commit-message
Improve code efficiency in membership ops
```
Tests
- Unit test
```release-note
None.
```
> keyspace, slice: improve code efficiency in membership ops

- tests/integrations/mcs/tso/keyspace_group_manager_test.go
```commit-message
Enable `TestTSOKeyspaceGroupSplitClient`.
```
Tests
- Unit test
```release-note
None.
```
> tests: enable TestTSOKeyspaceGroupSplitClient

- pkg/mcs/tso/server/server.go
- pkg/tso/keyspace_group_manager.go
- tests/integrations/mcs/cluster.go
- tests/integrations/mcs/testutil.go
- tests/integrations/mcs/tso/keyspace_group_manager_test.go
- tests/integrations/mcs/tso/server_test.go
- tests/integrations/tso/client_test.go
- tests/server/tso/common_test.go
```commit-message
Add CheckMultiKeyspacesTSO() and WaitForMultiKeyspacesTSOAvailable in test utility. Add TestTSOKeyspaceGroupManager/TestKeyspacesServedByNonDefaultKeyspaceGroup. Cover TestGetTS, TestGetTSAsync, TestUpdateAfterResetTSO in TestMicroserviceTSOClient for multiple keyspace groups.
```
Tests
- Unit test
```release-note
None.
```
> tests: add more tests for multiple keyspace groups

- pkg/election/leadership_test.go
Issue Number: Close #6399
```commit-message
fix test code
```
Tests
- Unit test
```release-note
None.
```
> election: update leadership_test.go

- client/client.go
Adding retry for getting the keyspace meta in the client.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
> client: retry load keyspace meta when creating a new client

- tests/integrations/tso/client_test.go
Issue Number: Close #6404 
```commit-message
We need to make sure the selected keyspaces are from different keyspace groups, otherwise multiple goroutines below could try to resign the primary of the same keyspace group and cause race condition.
```
Tests
- Unit test
```release-note
None.
```
> Fix test issue in TestRandomResignLeader.

- pkg/keyspace/keyspace.go
- pkg/keyspace/keyspace_test.go
- pkg/keyspace/tso_keyspace_group.go
- pkg/keyspace/tso_keyspace_group_test.go
- pkg/storage/endpoint/keyspace.go
- pkg/storage/keyspace_test.go
- server/apiv2/handlers/tso_keyspace_group.go
- server/server.go
```commit-message
Fix the keyspace assignment patrol consistency.
```
Tests
- Unit test
```release-note
None.
```
> keyspace, api2: fix the keyspace assignment patrol consistency
