.github/auto_assign.yml, .github/challenge-bot.yml, .github/workflows/assign-to-one-project.yaml, .github/workflows/auto-assignee.yaml, .github/workflows/check-dashboard.yaml, .github/workflows/pd-tests.yaml
Update the CI config for `release-5.0` branch.
Update the GitHub Actions workflow and config.
Tests
- Unit test
=> *: update the CI config

client/client.go
Closes #3502. 
This PR regards the "Canceled" as a kind of network error.
Tests
- Manual test 
- Reduce time of retrying before trying to connect to the follower
=> client: reduce the retry time before trying follower

client/client.go
Closes https://github.com/tikv/pd/issues/3511.
This PR changes the log level to debug.
Tests
- Manual test
- change the log level of getting follower client to debug
=> client: change the log level of getting follower client to debug

Makefile
Signed-off-by: 9547 <nivefive9547@gmail.com>
Open
make: install revive if not found
- Unit test
- No code
=> make: install revive if not found

metrics/grafana/pd.json
Add panel : cpu usage, memory usage, uptime and goroutine count
Modify panel location in cluster
Tests
- Unit test
=> metrics: add metrics in cluster

pkg/movingaverage/avg_over_time.go
=> movingaverage: fix missing queue

pkg/autoscaling/prometheus_test.go, server/config/util_test.go
fix sonar security hotspots
modify security IP (eg. 1.2.3.4) to 127.0.0.1  
Tests
- Unit test
=> *: fix sonar security hotspot

metrics/grafana/pd.json
cherry-pick #3520 and #3537 to release-5.0
——————————
To close #3531
Previous legend may not be compatible with operator and tiup deployed clusters
replace instance with job
Tests
- Unit test
Test in k8s cluster
Test in tiup cluster
=> metrics: add metrics in cluster #3520

server/core/store.go
Signed-off-by: mantuliu <240951888@qq.com>
Fix wrong comment.
No release note
=> Fix wrong comment.

server/schedule/operator/metrics.go
Before metrics is not  accurate
make more suitable buckets.
Tests
- Unit test
- make operator metrics more accurate
=> metrics: make operator metrics more accurate

metrics/grafana/pd.json
=> metrics: correction of statistical unit errors

metrics/grafana/pd.json
=>  metrics: keep unit consistent with tikv

client/client_test.go
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/pd_test/detail/pd_test/21230/pipeline/
See etcd-io/etcd#3317.
Tests
- Unit test
=> client: fix the goroutine leak of client unit test

client/client_test.go
Close #3575.
Try to avoid using the same address with proxy.
Tests
- Unit test
- PR #3574.
=> client: fix etcd proxy loop detection error in unit test

server/join/join.go
modify log level
Tests
- Unit test
=> join: modify log level

server/cluster/cluster_test.go, server/core/test_util.go, server/statistics/region_collection.go
fix #3611
clear defunct region in offline stats after merge offline peer
Tests
- Unit test
- fix offline_stats statistic after merge offline peer
=> statistic: fix offline stats statistic after merge offline peer

README.md
Update the badges in `README.md`.
Update the badge URLs in `README.md`.
Tests
- No code
=> README: update the badges in README.md

client/base_client.go
* fix #3579 
* client: adjust the log level in updateMember
Tests
* tiup starts a 3 PD cluster
* manually make a PD stop
* tiup display
=> client: adjust the log level in updateMember

client/base_client.go
* client: fix comment typo in #3630 
Tests
- No code
=> client: fix comment typo

server/cluster/cluster.go, server/statistics/hot_cache.go, server/statistics/hot_peer_cache.go, server/statistics/store.go, server/statistics/store_hot_peers_infos.go
Minor clean up the code.
1. remove some unused functions
2. remove the hot spot statistic after the store becomes tombstone.
Tests
- Unit test
-
=> *: clean up some code

.github/pull_request_template.md
Signed-off-by: Cadmus <CadmusJiang@gmail.com>
Help Tichi to realize the information collection function of release note.
Add a release note reference to pull_ request_template.md
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
=> github: add release-note description format to pull request template

go.sum, server/encryptionkm/key_manager_test.go, tests/dashboard/service_test.go, tests/server/member/member_test.go, tests/server/region_syncer/region_syncer_test.go, tests/server/tso/local_tso_test.go, tests/server/tso/tso_test.go, tests/server/watch/leader_watch_test.go
Remove some duplicated code.
Tests
- Unit test
=> *: remove duplicated code by abstracting functions

server/statistics/hot_peer_cache.go
rename function with a proper name
```release-note
None
```
=> statistics: rename function with a proper name

pkg/mock/mockcluster/mockcluster.go, server/cluster/cluster.go
Close https://github.com/tikv/pd/issues/3701
Adjust the threshold for the threshold for the read stats.
```release-note
None
```
=> statistics: adjust threshold for the Region read stats

server/schedulers/balance_leader.go, server/schedulers/balance_region.go, server/schedulers/balance_test.go, server/schedulers/utils.go
Fix https://github.com/tikv/pd/issues/835
Extract `balancePlan` so we don't have to pass all parameters around.
Tests
- Unit test
```release-note
None
```
=> schedulers: extract balancePlan for balancers

server/schedulers/hot_region.go, server/schedulers/hot_test.go
fix sort hotpeer in hot scheduler
Tests
- Unit test
```release-note
None.
```
=> scheduler: fix sort hotpeer in hot scheduler

server/cluster/coordinator.go, server/schedulers/hot_region.go
The hot metrics are hard to maintain.
This PR uses a type field for the hot metrics to reduce some duplicated code.
Tests
- Unit test
```release-note
None
```
=> metrics: refactor the hot region metrics

LICENSE
The license doesn't correct.
Make it correct.
Tests
- No code
```release-note
None
```
=> *: fix the license

.github/workflows/check-dashboard.yaml, .github/workflows/pd-tests.yaml
ci: make github action effective for `release-5.1`
Tests
- No code
Code changes
Side effects
```release-note
None
```
=> ci: make github action effective for release-5.1

.github/workflows/check-dashboard.yaml, scripts/embed-dashboard-ui.ps1, scripts/embed-dashboard-ui.sh
When running make, there will be a diff which is caused by the behavior change of go (1.16beta1 -> 1.16rc1).
This PR run tidy after go mod download.
Tests
- No code
```release-note
None
```
=> *: solve the diff problem

server/schedule/checker/merge_checker.go, server/schedulers/balance_leader.go, server/schedulers/balance_region.go
We have some monitors like the balance region scheduler which records the scheduling event. But it's hard to find something when we investigate the problem.
This PR records the total number of events so that we can know the relationship between each event.
Tests
- Unit test
```release-note
None
```
=> *: improve the some metrics

tests/pdctl/store/store_test.go, tools/pd-ctl/pdctl/command/store_command.go
Signed-off-by: xuhui-lu <luxuhui12345@126.com>
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None
```
=> Tools: Add store check sub command to list the stores with specified state

server/cluster/coordinator_test.go, server/config/config.go, server/config/config_test.go, tests/pdctl/scheduler/scheduler_test.go
close #3822.
This PR disables the label scheduler by default.
Tests
- Unit test
```release-note
Disable label scheduler by default
```
=> config: disable label scheduler by default

.github/labeler.yml, .github/workflows/label.yaml
Add a labeler. Now it only adds labels for TiDB Dashboard PRs.
Add a new GitHub Action.
Tests
```release-note
None
```
=> Add auto label action to add labels for TiDB Dashboard PRs

metrics/alertmanager/pd.rules.yml
pd_regions_status{type="down_peer_region_count"}  typo ，pd_regions_status{type="down-peer-region-count"} is right
Tests
- No code
Code changes
Side effects
```release-note
None.
```
=> fix alert rules down-peer

pkg/movingaverage/exponential_moving_average.go, pkg/movingaverage/hull_moving_average.go, pkg/movingaverage/max_filter.go, pkg/movingaverage/median_filter.go, pkg/movingaverage/moving_average.go, pkg/movingaverage/moving_average_test.go, pkg/movingaverage/weight_moving_average.go, server/statistics/store.go
Add `GetInstantaneous` to `MovingAvg` interface.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
=> moving average: MovingAvg supports GetInstantaneous

pkg/errs/errno.go, server/api/region_test.go, server/schedule/operator_controller_test.go, server/schedule/region_scatterer.go
Related to #3872.
This PR makes TestStoreLimitWithMerge more stable and fixes some minor things.
Tests
- Unit test
```release-note
None
```
=> *: make TestStoreLimitWithMerge more stable

go.mod, go.sum
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
Use a dedicated kvproto branch https://github.com/pingcap/kvproto/tree/release-5.1
Change the kvproto branch to release-5.1.
Tests
Code changes
Side effects
```release-note
None
```
=> *: use release-5.1 kvproto

Makefile
We might run our tests in different environments and some of them may not have good performance.
This PR enlarges the timeout for testing to 20m.
Tests
- No code
```release-note
None
```
=> *: enlarge testing timeout

server/schedulers/hot_region.go, server/schedulers/hot_region_test.go, tests/pdctl/scheduler/scheduler_test.go, tools/pd-ctl/pdctl/command/scheduler.go
support priority for each dimension in hot scheduling
Tests
- Unit test
I used `oltp_read_only` to test the dimension priority in hot scheduling, here is the result.
```release-note
Support priority for each dimension in hot scheduleing
```
=> scheduler: support priority for each dimension in hot scheduling

server/schedulers/hot_region.go, server/schedulers/hot_region_config.go, server/schedulers/hot_region_test.go, tests/pdctl/scheduler/scheduler_test.go
Support picking store with loose condition
Tests
- Unit test
```release-note
Support `strict-picking-store` in hot region scheduler in order to control whether picking store with strict condition.
```
=> scheduler: support loose store picking for hot region scheduling

server/statistics/store_collection.go
Some metrics need to be reset once the store is Tombstone.
Tests
- Unit test
```release-note
None
```
=> metrics: reset some store statistics metrics

metrics/grafana/pd.json
metrics: add store regions stats, related #3819 
Tests
- No code
Code changes
Side effects
```release-note
None
```
=> metrics: add store regions stats

server/core/store.go, server/schedule/filter/filters.go, server/schedule/placement/label_constraint.go, server/schedulers/hot_region_test.go, server/schedulers/utils.go
*: use constants instead of string
Tests
- No code
Code changes
Side effects
```release-note
None
```
=> *: use constants instead of string

server/api/region_label.go, server/api/region_label_test.go, server/api/router.go
We may use `xxx/xxx` as the label rule's ID. So we should escape ID to support getting/deleting the rule according to it.
- support escaping ID
- fix a bug when failing to delete the rule.
Tests
- Unit test
```release-note
None
```
=> regionlabel: fix the escape ID problem

go.mod, go.sum, pkg/mock/mockcluster/mockcluster.go, server/core/region.go, server/core/region_option.go, server/core/test_util.go, server/statistics/kind_test.go
add more write query kind for hot region scheduler
insert 1200 tables
write test with Pessimistic
Tests
- Unit test
```release-note
None.
```
=> statistics: add more write query kind

server/schedule/placement/config.go, server/schedule/placement/rule.go, server/schedule/placement/rule_manager.go, server/schedule/placement/rule_manager_test.go, tests/pdctl/config/config_test.go
refer https://github.com/tikv/pd/issues/4025
Introducing version for rule in order to judge whether the is updated from last checking.
Tests
- Unit test
```release-note
None
```
=> placement: introduing rule version

metrics/grafana/pd.json, server/schedule/placement/fit_region_test.go
add some benchmark cases for FitRegion
```release-note
None
```
=> placement: add some benchmark cases for FitRegion

metrics/grafana/pd.json
add hidden query for exp in hot scheduler
Tests
- Unit test
```release-note
None.
```
=> metrics: add hidden query for exp in hot scheduler

tests/client/client_test.go
Add a test case to guarantee the semantic of `TSFuture` is correct.
Add a test case to call `Wait()` of `TSFuture` in reversed time order.
Tests
- Unit test
```release-note
None.
```
=> client: add a test case for (*client).GetTSAsync

go.mod, go.sum, pkg/dashboard/distro/distro.go, pkg/dashboard/distro/placeholder.go
Signed-off-by: Suhaha jklopsdfw@gmail.com
As same as #4070.
Update TiDB Dashboard to v2021.09.03.1. to fix distro build bug.
Tests
```release-note
None
```
=> dashboard: update TiDB Dashboard to v2021.09.03.1

pkg/btree/btree_mem.go, pkg/dashboard/dashboard.go, pkg/dashboard/without_dashboard.go, pkg/swaggerserver/empty_handler.go, pkg/swaggerserver/swagger_handler.go, pkg/tempurl/check_env.go, pkg/tempurl/check_env_linux.go, tests/server/tso/allocator_test.go, tests/server/tso/consistency_test.go, tests/server/tso/global_tso_test.go, tests/server/tso/manager_test.go, tests/server/tso/tso_test.go, tools.go
[Bug-resistant build constraints](https://go.googlesource.com/proposal/+/master/design/draft-gobuild.md)
Tests
- No code
Code changes
Side effects
```release-note
None
```
=> *: support go:build lines for go1.17

client/client.go
Refine some client forwarding code.
`changeCh` is unnecessary since `streamCh` has blocked the goroutine already.
Tests
- Unit test
```release-note
None.
```
=> client: remove unnecessary use of a blocked channel

server/schedule/checker_controller.go
An issue Introduced in cherry-pick #3395, that did not exist in the original PR #3367.
Tests
Code changes
Side effects
```release-note
None
```
=> schedule: fix incorrect operator limit metrics [release-4.0]

client/base_client.go, client/client.go
We have many options inside both the `client` and `baseClient`, however, each of them may work in different scopes. To make the scope clear, we need to do some refactoring.
Distinguish between different client scopes of options.
Tests
- Unit test
```release-note
None.
```
=> client: refactor the client options to make the scope clear

tests/client/client_test.go
There are many ways of creating a PD client in the client test, which needs to be unified into one.
Unify the use of `setupCli` in the client test.
Tests
- Unit test
```release-note
None.
```
=> test: unify the use of setupCli in the client test

metrics/alertmanager/pd.rules.yml
the offline store should be a down store.
s/offline/down/
Test
```release-note
metrics: change alter name from `PD_cluster_offline_tikv_nums` to `PD_cluster_down_tikv_nums`
```
=> metrics: adjust the alter rule name

server/grpc_service.go
Close #3940 #2908
Before syncing the region, we need to check if the server is closed.
Tests
- Unit test
```release-note
None
```
=> *: fix race in region syncer

server/cluster/coordinator_test.go
Close #4169.
Remove unnecessary test settings.
Tests
- Unit test
```release-note
None
```
=> *: fix race in priority checker

go.mod, go.sum
Update tidb-dashboard to v2021.09.27.1
Tests
- Need to cherry-pick to the release branch except **release-5.2**, since a pr has been manually opened and there are some code changes. https://github.com/tikv/pd/pull/4070
```release-note
Update tidb-dashboard to v2021.09.27.1
```
=> dashboard: update TiDB Dashboard to v2021.09.27.1

server/config/config.go
close https://github.com/tikv/pd/issues/4259
Since this feature has not yet undergone a complete and real stress test, I will be turn it off first in 5.3.
- Manual test 
```release-note
None
```
=> config: default not record hot history region 

server/kv/etcd_kv.go, tests/server/cluster/cluster_test.go
Part of https://github.com/tikv/pd/issues/3453. Trying to sort out the usage of `core/Storage` and `kv/Base`.
There is no need to introduce a `testErrorKV` here. I think injecting a failpoint is a more suitable way.     
Tests
- Unit test
```release-note
None.
```
=> kv, tests: use failpoint to mock the failed KV saving

.github/CODEOWNERS
Signed-off-by: Qiang Zhou <zhouqiang.cl@gmail.com>
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
Please add a release …
```
=> Add code owner for config file

client/option_test.go
Part of pingcap/tidb#29698.
Add the float test for `MaxTSOBatchWaitInterval`.
Tests
- Unit test
```release-note
None.
```
=> client: add the float test for MaxTSOBatchWaitInterval

.golangci.yml, client/option_test.go, pkg/encryption/config.go, server/api/config_test.go, server/api/diagnose.go, server/api/member.go, server/cluster/coordinator.go, server/core/region_tree.go, server/encryptionkm/key_manager.go, server/encryptionkm/key_manager_test.go, server/schedule/checker/rule_checker_test.go, server/schedule/checker_controller.go, server/schedule/labeler/labeler.go, server/schedule/operator/operator_test.go, server/schedule/operator/status_tracker.go, server/schedule/placement/config.go, server/schedule/placement/rule_manager.go, server/schedulers/hot_region_config.go, server/schedulers/hot_region_test.go, server/statistics/hot_peer_cache.go, server/statistics/topn_test.go, server/tso/allocator_manager.go, tests/pdctl/config/config_test.go, tests/pdctl/store/store_test.go, tools/pd-ctl/pdctl/command/completion_command.go, tools/pd-ctl/pdctl/command/hot_command.go
Ref #4307.
This PR enables the following linters:
- gocritic
- unparam
- unconvert
- whitespace
- makezero
Tests
- Unit test
```release-note
None
```
=> *: enable more linters

plugin/scheduler_example/evict_leader.go, server/cluster/cluster_test.go, server/handler.go, server/schedule/checker/merge_checker.go, server/schedule/opt/healthy.go, server/schedule/opt/healthy_test.go, server/schedulers/balance_leader.go, server/schedulers/balance_region.go, server/schedulers/evict_leader.go, server/schedulers/grant_leader.go, server/schedulers/hot_region.go, server/schedulers/random_merge.go, server/schedulers/shuffle_leader.go, server/schedulers/shuffle_region.go
Part of #4119.
Before fixing the merge checker, I find some unnecessary schedule/opt functions that needed to be removed.
Tests
- Unit test
```release-note
None.
```
=> schedule: remove unnecessary schedule/opt functions

server/api/diagnose.go, server/api/label_test.go, server/api/member.go, server/api/operator_test.go, server/api/store_test.go, server/api/tso.go, server/grpc_service.go, server/server.go, tests/client/client_test.go, tests/cluster.go, tests/compatibility/version_upgrade_test.go, tests/pdctl/helper.go, tests/server/cluster/cluster_test.go
close #4363
Define `GrpcServer` to wrap `Server` into a grpc service.
Tests
- Unit test
```release-note
None
```
=> server: extract GrpcServer from Server

server/cluster/cluster.go, server/region_syncer/server.go, tests/cluster.go, tests/server/region_syncer/region_syncer_test.go
ref #4348
add more failpoint
- Unit test
```release-note
None
```
=> server: make TestRegionSynce stable

server/replication/replication_mode.go, server/replication/replication_mode_test.go
close #4341
- use `*time.Time` instead of `time.Time`
- add test
- add some logs
Tests
- Unit test
Code changes
```release-note
Improve DR_STATE file content format
```
=> dr-autosync: improve state file content

server/schedulers/scheduler_test.go
ref #4377
fix incorrect test in #4377
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
=> *: fix incorrect test in #4377

server/kv/etcd_kv.go
Close https://github.com/tikv/pd/issues/4391.
Just return the original `SlowLogTxn` instead of creating a new one every time.
Tests
- Unit test
```release-note
None.
```
=> kv: refine the use of the SlowLogTxn

server/schedulers/grant_hot_region.go
close #4408
use lock to avoid data race
Tests
- Unit test
```release-note
None
```
=> schedulers: protect config field with lock

server/cluster/cluster.go
This is to solve the error skip code found in https://github.com/tikv/pd/issues/4422
ref #4422
we should gets the total count of a store's leader and follower RegionInfo by storeID rather than get the Region count of the store.
Tests
- Unit test
```release-note
None.
```
=> fixbug-#4422

server/handler.go
Ref #4406. It's hard to tell if the operation has been done from PD's perspective.
When changing the scheduler, it will print the corresponding log for the operation.
Tests
- Manual test
When do the following operations:
```
» scheduler pause balance-region-scheduler 10000
Success!
» scheduler resume balance-region-scheduler
Success!
» scheduler remove balance-region-scheduler
Success!
» scheduler add balance-region-scheduler
Success!
```
We can obtain the corresponding logs:
```
[2021/12/10 17:48:32.083 +08:00] [INFO] [handler.go:258] ["pause scheduler successfully"] [scheduler-name=balance-region-scheduler] [pause-seconds=10000]
[2021/12/10 17:48:45.771 +08:00] [INFO] [handler.go:256] ["resume scheduler successfully"] …
```
=> server: improve scheduler handler log

tools/pd-ctl/pdctl/command/scheduler.go
close #4405
Add parameter prompt for scheduler show --status ref #4405
Just add parameter prompt for scheduler show --status
Tests
- Unit test
```release-note
None.
```
=> Add parameter prompt for scheduler show --status ref #4405

server/config/config.go
Close #4493.
This PR removes `nextRetryDelay` which is no longer used.
Tests
- Unit test
```release-note
None
```
=> config: remove unused nextRetryDelay 

server/config/config.go, server/config/config_test.go
https://github.com/pingcap/tidb/issues/25281 is going to release.
```release-note
None
```
=> config: enable record history hot region

plugin/scheduler_example/evict_leader.go, server/api/region.go, server/cluster/cluster_test.go, server/cluster/coordinator.go, server/handler.go, server/schedule/checker/checker_controller.go, server/schedule/checker/merge_checker.go, server/schedule/checker/merge_checker_test.go, server/schedule/healthy.go, server/schedule/healthy_test.go, server/schedule/operator_controller_test.go, server/schedule/region_scatterer.go, server/schedule/region_splitter.go, server/schedulers/balance_leader.go, server/schedulers/balance_region.go, server/schedulers/evict_leader.go, server/schedulers/grant_leader.go, server/schedulers/hot_region.go, server/schedulers/random_merge.go, server/schedulers/shuffle_leader.go, server/schedulers/shuffle_region.go
Ref #4340.
This PR does the following changes:
- move some function out of `opt` package
- move `checker_controller.go` to `checker` package
- rename `CheckerController` to `Controller` since we can tell apart through the package name
- use `newRegionInfo` to simplify the test cases.
Tests
- Unit test
```release-note
None
```
=> *: move some functions from `opt` to `schedule`

pkg/mock/mockhbstream/mockhbstream.go, pkg/mock/mockhbstream/mockhbstream_test.go, server/cluster/coordinator_test.go, server/schedule/hbstream/heartbeat_streams.go, server/schedule/opt/opts.go
Ref #4340. This PR can be reviewed after #4517 is merged.
Move `HeartbeatStream` out of `opt` package.
Tests
- Unit test
```release-note
None
```
=> *: move `HeartbeatStream` out of `opt`

pkg/mock/mockcluster/mockcluster.go, server/cluster/cluster.go, server/cluster/cluster_worker.go, server/grpc_service.go, server/schedule/checker/learner_checker_test.go, server/schedule/checker/merge_checker_test.go, server/schedule/checker/replica_checker_test.go, server/schedule/checker/rule_checker_test.go, server/schedule/operator/builder.go, server/schedule/operator/builder_test.go, server/schedule/operator/create_operator_test.go, server/schedule/opt/opts.go, server/schedule/region_scatterer_test.go, server/schedulers/balance_test.go, server/schedulers/hot_region_config.go, server/schedulers/hot_region_test.go, server/schedulers/scheduler_test.go, server/versioninfo/versioninfo.go
Ref #4340. 
Tests
- Unit test
```release-note
None
```
=> *: remove `IsFeatureSupported` from `Cluster` interface

go.mod, go.sum
Update TiDB Dashboard to v2022.01.07.1.
Related tidb-dashboard PR:
- https://github.com/pingcap/tidb-dashboard/pull/1126
Tests
- 5.4
- 5.3
```release-note
1. Fix cross browser hashtag compatibility fix: add a slash (/) before the hashtag for cross browser compatibility.
2. Update the year of copyright chore: update copyright to 2022
3. Tweak Top SQL UX refine(topsql): ux
4. Add E2E test chore: add e2e test
```
=> Update tidb-dashboard to v2022.01.07.1

go.mod, go.sum
Update TiDB Dashboard to v2022.01.10.1.
Related tidb-dashboard PR:
- https://github.com/pingcap/tidb-dashboard/pull/1130
Tests
- 5.4
- 5.3
```release-note
1. Tweak Top SQL ux experience
2. Update ngm & top sql description text
```
=> Update TiDB Dashboard to v2022.01.10.1

server/schedule/checker/merge_checker.go
Signed-off-by: Hua Lu <hua.lu@pingcap.com>
Closes #4476 
Split `checkTarget` func and add metrics for each condition
Tests
- build & compile the changes and deploy on a new cluster
- Monitor the "Region Merge Checker" panel in Grafana while testing the cluster using sysbench
- Make sure the new metrics do not break the panel and reflect the real scenario
```release-note
None
```
=> checker: enhance the observability for no-target metrics

server/schedule/operator/builder.go
Signed-off-by: MrCroxx <mrcroxx@outlook.com>
fix #4562
Sort target store ids.
Tests
fix #4562 
```release-note
None
```
=> operator: sort multi target leader transfer store ids

go.mod, go.sum
Update TiDB Dashboard to v2022.01.17.1.
Related tidb-dashboard PR:
- https://github.com/pingcap/tidb-dashboard/pull/1145
Tests
- 5.4
```release-note
1. Add skip ngm check option
```
=> Update TiDB Dashboard to v2022.01.17.1 ref #4257

tests/pdctl/log/log_test.go, tools/pd-ctl/pdctl/command/global.go, tools/pd-ctl/pdctl/command/log_command.go
Close #4511. This PR can be reviewed after #4571 is merged.
This default behavior isn't changed and after this PR, we can use the following method to change the instance log level:
```
>> log debug 172.16.4.3:37810
Success!
```
Tests
- Unit test
```release-note
None
```
=> tools: support changing instance log level

.github/pull_request_template.md, CONTRIBUTING.md
Issue Number: close #4603 
```release-note
Please add a release note.
If you don't think this PR needs a release note then fill it with None.
```
=> doc: update CONTRIBUTING.md and pr template

server/id/id.go, server/id/metrics.go
Issue Number: Close https://github.com/tikv/pd/issues/4623
```commit-message
server/id: pre-alloc id gauge metrics
```
Tests
- Unit test
```release-note
None
```
=> server/id: pre-alloc id gauge metrics

tests/client/client_test.go
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects …
=> [DNM] tests: test the CI status check

tests/client/client_test.go
Revert tikv/pd#4638.
```commit-message
Revert tikv/pd#4638.
```
Tests
- Unit test
```release-note
None.
```
=> Revert "[DNM] tests: test the CI status check"

tests/server/global_config/global_config_test.go
Issue Number: Close #4576 
This test case is not useful and will cause panic since it may send to a closed channel.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> testing: remove TestClientWatchCloseReceiverExternally case

.github/workflows/pd-tests.yaml, .github/workflows/tso-function-test.yaml
Fix the GitHub Actions workflows on release branches.
```commit-message
workflows: fix the GitHub Actions workflows on release branches
```
Tests
- Unit test
```release-note
None.
```
=> workflows: fix the GitHub Actions workflows on release branches

.github/workflows/assign-to-one-project.yaml, .github/workflows/check.yaml, .github/workflows/pd-docker-image.yaml, .github/workflows/pd-tests.yaml, .github/workflows/tso-function-test.yaml, README.md
See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency. This will be helpful to reduce the GitHub Actions resources comsuming when we have multiple commits at the same time inside the same PR.
```commit-message
workflows: add corresponding concurrency groups for the GitHub Actions CI workflows
```
Tests
- Unit test
```release-note
None.
```
=> workflows: add corresponding concurrency groups for the GitHub Actions CI workflows

server/schedule/labeler/labeler.go, server/schedule/labeler/labeler_test.go, server/schedule/labeler/rules.go
This PR tiny refactor server/scheduler/labeler*, move some functions of `RegionLabeler` to `LabelRule` rules.go. 
```commit-message
This PR tiny refactor server/scheduler/labeler*, move some functions of `RegionLabeler` to `LabelRule` rules.go. 
```
Tests
- Unit test
```release-note
None.
```
=> server/scheduler/labeler: tiny refactor

.github/workflows/check.yaml, Makefile, tools/pd-tso-bench/go.sum
Issue Number: Close #4701.
Add `make tools` in the `check` script.
```commit-message
```
Tests
- Manual test
```release-note
None
```
=> *: add make tools in github action

.github/workflows/check.yaml, .github/workflows/pd-tests.yaml, .github/workflows/tso-consistency-test.yaml, .github/workflows/tso-function-test.yaml
Issue Number: ref https://github.com/tikv/pd/issues/4710
```commit-message
ci: upgrade go version to 1.18 in github action
```
Tests
- Unit test
```release-note
None
```
=> ci: upgrade go version to 1.18 in github action

server/grpc_service.go
Signed-off-by: 5kbpers <tangminghua@pingcap.com>
Issue Number: Close #4733
```commit-message
Return an error for unimplemented ReportBuckets rpc
```
Tests
- Unit test
```release-note
None.
```
=> return error for unimplemented ReportBuckets rpc

server/server.go
add a log for persisting file.
```release-note
None
```
=> server: add persist file log

server/schedulers/balance_leader.go
Issue Number: Close #4610
add lock to avoid data race
```commit-message
add lock to avoid data race in balance-leader-scheduler
```
Tests
- Unit test
```release-note
None.
```
=> scheduler: Add lock for balance leader config

server/cluster/coordinator_test.go, server/schedulers/balance_leader.go
Issue Number: Close #4610
```commit-message
adjust `Batch` size when created by `ConfigJSONDecoder`
```
Tests
- Unit test
```release-note
None.
```
=> scheduler: adjust `Batch` size when created by `ConfigJSONDecoder`

server/api/min_resolved_ts.go, server/api/min_resolved_ts_test.go, server/api/router.go, server/cluster/cluster.go, tests/server/cluster/cluster_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/4686
This PR will ensure cluster min resolved ts increase, it will compare the real-time one with the old one,  and only save when the old one is smaller.
This PR will make  min resolved ts persistent interval dynamic configurable 
Tests
- Unit test
```release-note
None.
```
=> dr-ausosync: ensure cluster min resolved ts increase

.github/workflows/pd-tests.yaml, .github/workflows/tso-consistency-test.yaml, .github/workflows/tso-function-test.yaml
* Add GitHub Actions workflows for `release-6.x`.
* Update the Go version.
```commit-message
ci: add GitHub Actions workflows for release-6.x
```
Tests
- Unit test
```release-note
None.
```
=> ci: add GitHub Actions workflows for release-6.x

client/go.mod, client/go.sum, go.mod, go.sum, tests/client/go.mod, tests/client/go.sum, tools/pd-tso-bench/go.sum
ref #4399
Issue Number: Close #4770
Update dependency to resolve https://nvd.nist.gov/vuln/detail/CVE-2021-3121
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: update kvproto and gogo/protobuf

server/schedulers/evict_leader.go, server/schedulers/evict_leader_test.go
Issue Number: Close [#4785](https://github.com/tikv/pd/issues/4785)
Fix issue #4785
Tests
- Unit test
```release-note
None.
```
=> server/scheduler/evict_leader: fix a data race in the func `config.Clone`

server/cluster/cluster.go
Issue Number: Close #4787.
```commit-message
cluster: fix the storage data race in test.
```
Tests
- Unit test
```release-note
None.
```
=> cluster: fix the storage data race in test

pkg/ratelimit/concurrency_limiter.go, server/api/min_resolved_ts_test.go, tests/server/cluster/cluster_test.go
Issue Number: close #4791
Make fail point work again.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: fix unused failpoint

.github/pull_request_template.md
Signed-off-by: TomShawn <41534398+TomShawn@users.noreply.github.com>
Issue Number: Close #4796 
```commit-message
add release notes style guide link
```
Tests
- No code
```release-note
None
```
=> add release notes style guide link

pkg/apiutil/apiutil.go, server/api/config.go, server/api/config_test.go, server/config/persist_options.go, server/server.go
Issue Number: Close #4780.
If we change this config which has a TTL setting, the error will be returned.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> config: reject the config setting request if TTL config exists

server/schedulers/evict_slow_store.go, server/schedulers/scheduler_test.go
…store recoverd
Issue Number: Close #4799 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedulers/evict_slow_store: fix bug in persist config when the slow store recovers

pkg/progress/progress.go, pkg/progress/progress_test.go, server/api/router.go, server/api/store.go, server/cluster/cluster.go, server/cluster/cluster_test.go, server/cluster/coordinator.go, server/cluster/metrics.go, server/handler.go, tests/server/api/api_test.go
This PR adds a progress indicator and supports showing offline progress through API or metrics.
```commit-message
```
Tests
- Unit test
- Manual test (TODO)
Code changes
```release-note
None
```
=> pkg: add progress indicator

server/cluster/cluster.go
Issue Number: Close #4809 
Tests
- Unit test
```release-note
None.
```
=> server/cluster:remove the public function GetReplicationConfig

client/client.go, client/metrics.go, server/grpc_service.go, server/server.go
Issue Number: ref #4095
The original region split and scatter are handled by tikv and pd respectively, in order to improve efficiency, the split is also changed to be handled and controlled by pd.
Add a method splitAndScatterRegions in grpc-service
let pd handle split and scatter regions
Code changes based on this [work](https://github.com/hzh0425/pd/tree/add_split_and_scatter_region)
Thanks to [hzh0435](https://github.com/hzh0425)
Tests
Code changes
Side effects
```release-note
None
```
=> server,client: Add_split_and_scatter_region 

errors.toml, pkg/errs/errno.go, server/api/store_test.go, server/cluster/cluster.go, server/cluster/cluster_test.go, server/schedulers/evict_leader.go, tests/pdctl/store/store_test.go, tests/server/cluster/cluster_test.go
Issue Number: part of  #3998 
```commit-message
Consider the number of left online stores and evict-leader stores before removing(offline) a store.
```
Tests
```release-note
None.
```
=> server/cluster: consider the number of left evict-leader &  online store before offline a store.

server/cluster/cluster.go, server/cluster/coordinator.go, server/cluster/coordinator_test.go
Issue Number: Close #4815 
Tests
- Unit test
```release-note
None.
```
=> server/cluster/coordinator.go: new function to avoid visiting private attributes from another struct

server/tso/global_allocator.go
This PR removes an unused nil check.
```commit-message
tso: remove an unused nil check
```
Tests
- Unit test
```release-note
None.
```
=> tso: remove an unused nil check

errors.toml, pkg/errs/errno.go, server/cluster/cluster.go, tests/server/cluster/cluster_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: fix typos

server/cluster/cluster.go, server/cluster/cluster_worker.go, server/core/basic_cluster.go, server/grpc_service.go, server/statistics/region_collection.go, tests/server/cluster/cluster_test.go
Issue Number: Ref #4515.
This PR removes some necessary lock.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: optimize lock usage

server/election/leadership_test.go
Issue Number: Close https://github.com/tikv/pd/issues/4853, close https://github.com/tikv/pd/issues/4782.
```commit-message
election: fix the unstable TestLeadership test.
```
Tests
- Unit test
```release-note
None.
```
=> election: fix the unstable TestLeadership test

.github/pull_request_template.md
Issue Number: ref https://github.com/tikv/pd/issues/4820.
```commit-message
.github: refine the pull request template.
```
Tests
- No code
```release-note
None.
```
=> .github: refine the pull request template

server/api/config.go, server/api/config_test.go
Issue Number: Close #4801
Check if the TTL parameter is extracted
```commit-message
Support clean up ttl setting
```
Tests
- Unit test
```release-note
None.
```
=> api: Support clean up ttl setting

pkg/dashboard/adapter/manager.go
Issue Number: Close #4859 
Tests
- Unit test
```release-note
None.
```
=> dashboard/adapter/manager.go:stop the loop once meet the right condition

server/api/middleware.go, server/api/router.go, tests/server/api/api_test.go
Issue Number: Close #4846 Ref 
Create one middleware for each HTTP API interface.
And I remove failpoint in audit middleware because it has two backends to test. 
```commit-message
Refactor Service Middleware
```
Tests
- Unit test
```release-note
None.
```
=> api: Refactor Service Middleware

server/grpc_service.go, tests/server/cluster/cluster_test.go
Signed-off-by: Xintao <hunterlxt@live.com>
Issue Number: close #4868 
```commit-message
Add remove peer logic for damaged regions when handling store heartbeat
```
Tests
- Unit test
Code changes
- only logic changed
Side effects
- when this kind of errors happen, user need intervention manually with pd-ctl
```release-note
Add remove peer logic for damaged regions when handling store heartbeat
```
=> Add remove peer logic for damaged regions when handling store heartbeat

tests/server/cluster/cluster_test.go
Issue Number: Close #4870.
This PR changes back to the original logic which is more stable.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: make the test more stable

go.mod, server/apiv2/router.go
Issue Number: Close #4872.
This PR uses `once` to prevent `mode` from being set twice.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> api: fix the potential race problem

pkg/progress/progress.go, pkg/progress/progress_test.go, server/cluster/cluster.go, server/cluster/coordinator.go, server/storage/endpoint/meta.go
This PR is a part of #4718. Split it for easier reviewing.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> pkg: refactor the progress indicator

server/api/region.go, server/handler.go, server/schedule/region_scatterer.go, server/schedule/region_scatterer_test.go
Issue Number: Close #4833
Tests
- Unit test
```release-note
None.
```
=> server/api: create scatter_region operator with opAdmin

metrics/grafana/pd.json
This PR fixes the wrong settings for the progress indicator in Grafana.
```commit-message
```
Tests
- Manual test (http://172.16.5.86:30802/d/Q6RuHYIWk1/test-cluster-pd?orgId=1&from=1651779447334&to=1651789711194) I 
```release-note
None
```
=> *: fix the progress indicator monitor

server/api/store.go, server/cluster/cluster.go, tests/pdctl/store/store_test.go, tools/pd-ctl/pdctl/command/store_command.go
Issue Number: Close #4098
```commit-message
```
```
» store --help
manipulate or query stores
Usage:
pd-ctl store [command] [flags]
pd-ctl store [command]
Available Commands:
cancel-delete    cancel delete the store
check            Check all the stores with specified status
delete           delete the store
label            set a store's label value
limit            show or set a store's rate limit
limit-scene      show or set the limit value for a scene
remove-tombstone remove tombstone record if only safe
weight           set a store's leader and region balance weight
Flags:
-h, --help            help for store
--jq string       jq query
--state strings   state filter
Use "pd-ctl store [command] --help" for more information about a command.
```
First, delete store 2:
```
» store delete …
```
=> tools: add cancel-delete store command for pd-ctl

server/grpc_service.go, server/schedulers/grant_hot_region.go, tools/pd-ctl/pdctl/command/scheduler.go
Issue Number: ref #4820
fix some typos
Tests
- Unit test
```release-note
None.
```
=> *: fix some typos

metrics/grafana/pd.json
hide unnecessary metrics
Tests
- No code
```release-note
None.
```
=> metrics: hide unnecessary metrics

server/api/store.go, tests/server/api/api_test.go
This PR changes the response code from 200 to 404 when there is no such progress.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> api: change the status code when there is no such progress

server/grpc_service.go
Issue Number: Close #4833
Tests
- Unit test
```release-note
None.
```
=> server/grpc_service: create scatter_region operator with OpAdmin

metrics/grafana/pd.json, server/schedule/metrics.go, server/schedule/operator_controller.go
Issue Number: Close #4935
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> metrics:  add operator region size metric 

errors.toml, pkg/errs/errno.go, pkg/progress/progress.go, pkg/progress/progress_test.go, server/api/store.go, server/cluster/cluster.go, server/cluster/cluster_test.go, server/core/region.go, server/handler.go, server/schedulers/balance_region.go
This PR will return err if the unexpected situation happens, also change back the tombstone condition from size to count.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> * : return error if get progress status failed

metrics/grafana/pd.json, server/schedule/checker/rule_checker.go
The `errors.New` in `pingcap/errors` will cost much CPU if it is called frequently.
Issue Number: Close #4968.
Replace it with errors in the standard library.
```commit-message
```
Tests
- Manual test 
```release-note
None
```
=> *: replace pingcap/errors

server/schedulers/hot_region.go, server/schedulers/hot_region_test.go
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
=> scheduler: refactor solve in hot-region-scheduler

server/schedulers/hot_region.go
The score is expanded from -3 ~ 0 to -4 ~ 1, and the previous design problem that the score of the first dimension is better and the second dimension is not worsened is -1, and the score of the first dimension is not worsened and the second dimension is better is -2. The solution still needs to take a score of -1 and below. The original 0 points become 0 and 1.
Tests
- Unit test
Code changes
Side effects
```release-note
None
```
=> scheduler: redesigned `progressiveRank` of the hot-region-scheduler

server/schedule/operator_controller.go, server/schedule/operator_controller_test.go
Issue Number: Close #4946
If it is promoting operator, don't check waiting queue count
```commit-message
If it is promoting operator, don't check waiting queue count
```
Tests
- Unit test
```release-note
None.
```
=> schedule: If it is promoting operator, don't check waiting queue count

server/cluster/cluster.go, tests/pdctl/store/store_test.go
Issue Number: Close #5024.
This PR collects the failed store ID and returns them to the user.
```commit-message
```
Tests
- Unit test
```release-note
Fix the issue that the remove-tombstone command shows success but actually is not.
```
=> api: return an error when remove-tombstone failed

pkg/ratelimit/ratelimiter.go
Issue Number: Close #5034 
Tests
- Unit test
```release-note
None.
```
=> pkg/ratelimit/ratelimiter: reduce the usage of CPU in Available

server/cluster/coordinator_test.go, server/config/config.go, server/config/config_test.go, server/config/store_config.go, server/schedulers/split_bucket.go, tests/pdctl/scheduler/scheduler_test.go
Issue Number: Close #5042
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> config: add split-bucket to default schedulers

go.mod, pkg/apiutil/apiutil_test.go, pkg/audit/audit_test.go, pkg/autoscaling/calculation_test.go, pkg/autoscaling/prometheus_test.go, pkg/cache/cache_test.go
```commit-message
Testify the pkg/apiutil, pkg/audit, pkg/autoscaling, pkg/cache tests.
```
Tests
- Unit test
```release-note
None.
```
=> apiutil, audit, autoscaling, cache: testify the tests

pkg/codec/codec_test.go, pkg/encryption/config_test.go, pkg/encryption/crypter_test.go, pkg/encryption/master_key_test.go, pkg/encryption/region_crypter_test.go, pkg/errs/errs_test.go
```commit-message
Testify the pkg/codec, pkg/encryption, pkg/errs tests.
```
Tests
- Unit test
```release-note
None.
```
=> codec, encryption, errs: testify the tests

pkg/assertutil/assertutil_test.go, pkg/etcdutil/etcdutil_test.go, pkg/grpcutil/grpcutil_test.go, pkg/keyutil/util_test.go, pkg/logutil/log_test.go, pkg/metricutil/metricutil_test.go
```commit-message
Testify the pkg/assertutil, pkg/etcdutil, pkg/grpcutil, pkg/keyutil, pkg/logutil, pkg/metricutil tests.
```
Tests
- Unit test
```release-note
None.
```
=> assertutil, etcdutil, grpcutil, keyutil, logutil, metricutil: testify the tests

pkg/mock/mockhbstream/mockhbstream_test.go, pkg/movingaverage/avg_over_time_test.go, pkg/movingaverage/max_filter_test.go, pkg/movingaverage/moving_average_test.go, pkg/movingaverage/queue_test.go, pkg/netutil/address_test.go, pkg/progress/progress_test.go
```commit-message
Testify the pkg/mockhbstream, pkg/movingaverage, pkg/netutil, pkg/progress tests.
```
Tests
- Unit test
```release-note
None.
```
=> mockhbstream, movingaverage, netutil, progress: testify the tests

server/api/admin_test.go, server/api/server_test.go
```commit-message
Fix the `testServiceSuite`.
```
Tests
- Unit test
```release-note
None.
```
=> api: fix the testServiceSuite

server/schedule/rangelist/range_list_test.go
Issue Number: Close #5098
Tests
- Unit test
```release-note
None
```
=> rangelist: migrate test framework to testify

server/replication/replication_mode_test.go
Issue Number: Close #5099
migrate test framework
Tests
- Unit test
```release-note
None
```
=> replication: migrate tests to testify

client/client_test.go, pkg/autoscaling/calculation_test.go, pkg/cache/cache_test.go, pkg/logutil/log_test.go, pkg/typeutil/conversion_test.go, pkg/typeutil/string_slice_test.go, tests/client/client_test.go
Issue Number: Close #5104.
```commit-message
Use require.Equal to replace reflect.DeepEqual.
```
Tests
- Unit test
```release-note
None.
```
=> *: use require.Equal to replace reflect.DeepEqual

server/election/leadership_test.go, server/election/lease_test.go
Issue Number: Ref #4813 
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> election: migrate test framework to testify

server/core/region_test.go, server/core/region_tree_test.go, server/core/store_stats_test.go, server/core/store_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> core: migrate test framework to testify

server/encryptionkm/key_manager_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> encryptionkm: migrate test framework to testify

.gitignore, tools/pd-analysis/analysis/parse_log_test.go, tools/pd-analysis/analysis/transfer_counter_test.go, tools/pd-ctl/pdctl/ctl_test.go, tools/pd-simulator/simulator/simutil/key_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> tools: migrate test framework to testify

tests/pdctl/cluster/cluster_test.go, tests/pdctl/completion/completion_test.go, tests/pdctl/config/config_test.go, tests/pdctl/global_test.go, tests/pdctl/health/health_test.go, tests/pdctl/helper.go, tests/pdctl/hot/hot_test.go, tests/pdctl/label/label_test.go, tests/pdctl/log/log_test.go, tests/pdctl/member/member_test.go, tests/pdctl/operator/operator_test.go, tests/pdctl/region/region_test.go, tests/pdctl/scheduler/scheduler_test.go, tests/pdctl/store/store_test.go, tests/pdctl/tso/tso_test.go, tests/pdctl/unsafe/unsafe_operation_test.go, tests/server/api/api_test.go, tests/server/storage/hot_region_storage_test.go
```commit-message
Testify the pd-ctl tests.
```
Tests
- Unit test
```release-note
None.
```
=> tests: testify the pd-ctl tests

server/schedulers/balance_leader.go, server/schedulers/balance_leader_test.go
Issue Number: Close #5156 
Tests
- Unit test
```release-note
None.
```
=> scheduler/balance_leader: fix data race in the function of clone for config

pkg/testutil/testutil.go, tests/client/client_test.go, tests/cluster.go, tests/server/tso/allocator_test.go, tests/server/tso/common_test.go, tests/server/tso/consistency_test.go, tests/server/tso/global_tso_test.go, tests/server/tso/manager_test.go, tests/server/tso/tso_test.go
```commit-message
Testify the TSO tests.
```
Tests
- Unit test
```release-note
None.
```
=> tests: testify the TSO tests

server/schedule/operator/builder_test.go, server/schedule/operator/status_test.go, server/schedule/operator/status_tracker_test.go, server/schedule/operator/step_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/4813.
Tests
- Unit test
```release-note
None.
```
=> operator: migrate test framework to testify

server/core/region_test.go, server/schedule/checker/rule_checker_test.go, server/schedule/placement/region_rule_cache_test.go, server/schedule/placement/rule_test.go, server/schedule/region_scatterer_test.go, server/schedulers/hot_region_test.go, server/schedulers/scheduler_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: replace `testcase` with `testCase`

pkg/errs/errs_test.go, pkg/movingaverage/moving_average_test.go, server/schedule/checker/joint_state_checker_test.go, server/schedule/checker/priority_inspector_test.go, server/schedule/placement/rule_test.go, tests/client/client_test.go, tests/pdctl/config/config_test.go, tests/server/tso/manager_test.go, tools/pd-ctl/pdctl/ctl_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/4813.
wait #5193
Tests
- Unit test
```release-note
None.
```
=> *: some misc modify for testify

tools/pd-simulator/simulator/client.go
Issue Number: Close #5222
It should clone before send.
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> pd-simulator: clone before request

server/api/router.go
Issue Number: Close #5247
- check cluster running before api call
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects …
=> api: fix /min-resolved-ts panic

server/schedule/filter/filters_test.go
Issue Number: Ref #5257.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> filter: add special filter tests

server/schedule/placement/fit_region_test.go
Issue Number: Close #5295 
```
go test -benchmem -run=^$ -bench ^BenchmarkFitRegionWithLocationLabels -benchtime=10x                                                                  [±bench_fit_region ●]
goos: darwin
goarch: amd64
pkg: github.com/tikv/pd/server/schedule/placement
cpu: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
BenchmarkFitRegionWithLocationLabels-12               10            312177 ns/op           77248 B/op       3113 allocs/op
PASS
ok      github.com/tikv/pd/server/schedule/placement    0.088s
```
Tests
- Unit test
```release-note
None.
```
=> server/schedule/placement: add test to bench fit region with location labels

go.mod, go.sum, pkg/testutil/operator_check.go, server/schedulers/balance_test.go, server/schedulers/evict_leader_test.go, server/schedulers/evict_slow_store_test.go, server/schedulers/hot_region_test.go, server/schedulers/scheduler_test.go, server/schedulers/split_bucket_test.go, server/schedulers/utils_test.go, tests/client/go.sum, tools/pd-tso-bench/go.sum
Issue Number: Close #5121
Tests
- Unit test
```release-note
None
```
=> scheduler: migrate test framework to testify

server/config/config.go, server/schedule/checker/rule_checker.go, server/schedule/filter/candidates_test.go, server/schedule/filter/filters.go, server/schedule/filter/filters_test.go, server/schedule/operator/builder.go, server/schedule/plan/status.go, server/schedule/region_scatterer.go
Issue Number: Ref #5257.
This PR defines some plan status for filter and non-filter. And each scheduling plan will have a result finally. We can use NewStatus to create a result with a status code and a detailed reason.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: define plan status

server/schedule/region_scatterer.go, server/schedule/region_scatterer_test.go
Issue Number: Close #5317
create new filter every scatter action
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedule: fix Scatter's ordinary filter causing data race

.github/workflows/check.yaml, go.mod, go.sum, server/schedule/filter/filters.go, server/server.go, tests/client/go.sum
Issue Number: Ref https://github.com/tikv/pd/issues/4257
Update TiDB Dashboard to v2022.07.21.2.
Tests
- No code
- 6.2
```release-note
1. Add more metrics
2. Support visual plan
```
=> Update TiDB Dashboard to v2022.07.21.2 ref #4257

metrics/grafana/pd.json
Issue Number: Close https://github.com/tikv/pd/issues/5324
```commit-message
metrics: add tikv side heartbeat status to PD panel
```
Tests
```release-note
None
```
=> metrics: add tikv side heartbeat status to PD panel

server/core/store_stats.go, server/core/store_stats_test.go, server/statistics/store_collection.go
Issue Number: Close #5328
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> core:  clean some remain code about deviation filter.

pkg/dashboard/adapter/redirector.go, pkg/dashboard/adapter/redirector_test.go
This is a cherry-pick of #5326
Issue Number: Close #5321 
Only process headers added by PD.
Tests
- Unit test
```release-note
Fix a bug that could not handle dashboard proxy requests correctly.
```
=> dashboard: fix a bug that could not handle proxy requests correctly (#5326)

go.mod, go.sum, tests/client/go.mod, tests/client/go.sum
Signed-off-by: YiniXu9506 <xuyini@pingcap.com>
Issue Number: Close https://github.com/tikv/pd/issues/5366
Update TiDB Dashboard to v2022.07.27.1.
Tests
- No code
- 6.2
```release-note
- Updates metrics query.
- Renames `metrics` to `monitoring` on TiDB Dashboard.
```
=> Update TiDB Dashboard to v2022.07.27.1, ref #4257

server/grpc_service.go, tests/client/client_test.go
Issue Number: Close #5373
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
grpc: fix the wrong error handler 
```
=> grpc: fix the wrong error handler.

server/grpc_service.go, tests/client/client_test.go
close tikv/pd#5373
Co-authored-by: nolouch <nolouch@gmail.com>
Conflicts:
tests/client/client_test.go
Issue Number: Close #5373
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
grpc: fix the wrong error handler 
```
=> grpc: fix the wrong error handler. (#5374)

go.mod, go.sum, tests/client/go.mod, tests/client/go.sum
Signed-off-by: YiniXu9506 <xuyini@pingcap.com>
Issue Number: Close https://github.com/tikv/pd/issues/5366
Update TiDB Dashboard to v2022.07.28.1.
Tests
- No code
- 6.2
```release-note
- Update TiKV IO metrics query.
- Fix api/visualplan/generate Content-Type.
```
=> Update TiDB Dashboard to v2022.07.28.1, ref #4257

plugin/scheduler_example/evict_leader.go, server/cluster/cluster_test.go, server/election/leadership.go, server/schedule/filter/region_filters.go, server/schedule/filter/region_filters_test.go, server/schedulers/balance_leader.go, server/schedulers/balance_region.go, server/schedulers/evict_leader.go, server/schedulers/grant_leader.go, server/schedulers/random_merge.go, server/schedulers/shuffle_leader.go, server/schedulers/shuffle_region.go
Issue Number: Close #5389.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: fix some typo issues

metrics/grafana/pd.json, server/schedulers/balance_leader.go, server/schedulers/balance_test.go
Issue Number: Close #5396.
```commit-message
```
Tests
- Manual test
```release-note
None
```
=> metrics: remove scheduler event monitor

server/schedule/filter/candidates_test.go, server/schedule/filter/filters.go, server/schedule/filter/filters_test.go, server/schedule/filter/region_filters.go, server/schedule/filter/status.go, server/schedule/plan/status.go
Issue Number: Close #5399.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: optimize status definition

client/client.go, pkg/audit/audit_test.go, pkg/autoscaling/calculation.go, pkg/autoscaling/prometheus_test.go, pkg/etcdutil/etcdutil.go, pkg/ratelimit/limiter_test.go, pkg/systimemon/systimemon_test.go, server/api/trend_test.go, server/cluster/cluster_test.go, server/cluster/coordinator_test.go, server/config/config.go, server/schedule/operator_controller_test.go, server/schedule/region_scatterer.go, server/schedule/region_splitter.go, server/statistics/hot_peer_cache_test.go, server/statistics/topn_test.go, server/storage/kv/etcd_kv.go, server/tso/allocator_manager.go, tests/server/tso/manager_test.go
Tests
- Unit test
```release-note
None.
```
=> *: remove unnecessary calculations about time duration 

Makefile, pkg/mock/mockcluster/mockcluster.go, server/api/region.go, server/cluster/coordinator.go, server/grpc_service.go, server/handler.go, server/schedule/operator/create_operator.go, server/schedule/region_scatterer.go, server/schedule/region_scatterer_test.go
cherry-pick #5439 to release-5.4-20220826 branch.
Issue Number: Close #4703 Close #4804
After getting an operator, it is immediately added to the queue of the OperatorController.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedule: add scatter operator into OperatorController immediately(#5439)

server/api/config_test.go, server/api/min_resolved_ts_test.go, server/cluster/cluster.go, server/config/config.go, tests/server/cluster/cluster_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/4399
Tests
- Unit test
```release-note
dr-auto-sync: enable min-resolved-ts persist by default
```
=> dr-auto-sync: enable min-resolved-ts persist by default

server/core/region.go, server/core/region_option.go
Issue Number: Ref #5468
1. rename `QueryStats` to `queryStats`
2. add `queryStats` to `region.Clone`, which is used in test and simulator
3. add `addQueryStats`, which is used in test and simulator
Tests
- Unit test
```release-note
None.
```
=> test: fix query statistic

server/schedulers/hot_region.go, server/schedulers/hot_region_test.go
Issue Number: Close #5489
replace `cur.load` with `best.load` in pending influence
Tests
- Unit test
Before this pr
After this pr
```release-note
None.
```
=> scheduler: fix pending influence collect

pkg/cache/cache_test.go, pkg/cache/fifo.go
Issue Number: Ref #5257 
add a function to get continuous items that have the same comparable attribute with the the lastest one.
```commit-message
get continuous items that have the same comparable attribute with the the lastest one.
```
Tests
- Unit test
```release-note
None.
```
=> cache: add a function for FIFO

server/schedulers/balance_leader.go, server/schedulers/balance_plan.go, server/schedulers/balance_plan_test.go, server/schedulers/balance_test.go
Issue Number: ref #5257
```commit-message
support collecting plan for balance-leader
```
Tests
- Unit test
```release-note
support collecting plan for balance-leader
```
=> scheduler: support collecting plan for balance-leader

server/replication/replication_mode.go
Issue Number: Close https://github.com/tikv/pd/issues/5512
```commit-message
dr: speed up the dr ticker
```
Tests
- Unit test
```release-note
None.
```
=> dr: speed up the dr ticker

server/schedule/filter/filters.go, server/schedule/filter/region_filters.go, server/schedulers/balance_leader.go, server/schedulers/balance_region.go
reduce the cost of `runtime.newObject` for `Option`
Issue Number: ref #5257 
add nil check for collector
```commit-message
add nil check for collector
```
Tests
```release-note
None.
```
=> schedulers: Add nil check for Collector

pkg/slice/slice.go
Issue Number: Close #5554
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> pkg：remove reflect from slice

server/config/persist_options.go, server/config/store_config.go, server/schedule/region_scatterer.go, server/schedulers/balance_test.go, server/schedulers/evict_slow_store.go, server/statistics/hot_cache.go, server/statistics/hot_cache_task.go, server/statistics/hot_peer_cache.go, server/statistics/store_hot_peers_infos.go, server/storage/hot_region_storage_test.go
Issue Number: Close #5488, ref #4820.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: remove unnecessary interface

server/schedule/placement/fit.go
Issue Number: Close #5552
```commit-message
```
Tests
- Unit test
master：
This PR：
The memory allocation has decrease 1/3，and the performan improve 1.2X
Code changes
Side effects
```release-note
None.
```
=> schedule: use sync pool to decrease fit peer new

server/election/leadership.go, server/server.go
Issue Number: Close #5434.
There is a probability that the `ResetLeader` can run at the same time as `KeepLeader`, which may cause a race.
```commit-message
```
Tests
- Manual test
```release-note
None
```
=> *: fix election race

.github/workflows/check.yaml, .github/workflows/pd-docker-image.yaml, .github/workflows/pd-tests.yaml, .github/workflows/tso-consistency-test.yaml, .github/workflows/tso-function-test.yaml
Update actions/setup-go, actions/checkout and actions/cache.
```commit-message
```
Tests
- No code
```release-note
None
```
=> *: update actions 

server/schedule/filter/filters.go, server/schedule/filter/metrics.go
The usage of this filter metrics : https://github.com/tikv/pd/blob/750aada580eb718a12eefe04523e3b0b3f6d4169/metrics/grafana/pd.json#L7815-L7849
Issue Number: Close #5576
```commit-message
```
Tests
- No code
Code changes
Side effects
```release-note
h None.
```
=> remove address and store from filter counter

server/handler.go, server/schedule/checker/rule_checker.go, server/schedule/filter/filters.go, server/schedule/filter/filters_test.go, tests/pdctl/scheduler/scheduler_test.go
Issue Number: Close #5578
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: make `TestScheduler` stable

server/schedule/waiting_operator.go, server/schedule/waiting_operator_test.go
Issue Number: Close #5595
We add a new priority level without changing the bucket number, which causes panic.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> schedule: fix priority bucket number

server/api/diagnostic_test.go
The balance region scheduler may not finished, so the result status needs to wait .
Issue Number: Close #5641
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> api: fix unstable test for TestSchedulerDiagnosticAPI

metrics/grafana/pd.json, server/schedule/filter/counter.go
Issue Number: Close #5646
```commit-message
```
Tests
this PR
Code changes
Side effects
```release-note
None.
```
=> metrics: fix bug that the target is wrong

tools/pd-simulator/simulator/drive.go
Issue Number: Ref #5468.
```commit-message
```
Tests
- Manual test
```release-note
None
```
=> tools: accelerate prepare speed

server/schedule/filter/filters.go, server/schedule/filter/filters_test.go
Issue Number: Close #5665
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> schedule: fix bug for disbaled move leader

server/schedule/placement/fit.go
After #5523 we use `replace` 
Tests
- Unit test
```release-note
None.
```
=> schedule: remove unused function

server/config/store_config.go, server/config/store_config_test.go, server/schedule/checker/merge_checker_test.go
Issue Number: Close #5649
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> config: cache  `ParseMbFrom` call to speed up region heartbeat

tools/pd-simulator/main.go
Issue Number: Ref #5468.
Here is an example:
```commit-message
```
Tests
- Manual test 
```release-note
None
```
=> tools: support profiling simulator

server/schedule/region_scatterer.go, server/schedule/region_scatterer_test.go
Issue Number: Close #5622
Add leader filter
```commit-message
schedule: Add leader filter for scatter
```
Tests
- Unit test
```release-note
None.
```
=> schedule: Add leader filter for scatter

server/cluster/cluster.go, server/cluster/cluster_test.go, server/core/store.go
Issue Number: Close #5680 
```commit-message
Lower down the frequency of AwakenRegions from 30s to 10min.
```
Tests
- Unit test
Code changes
- Just default values on AwakenTimeInterval has been modified.
Side effects
- None
- Need to cherry-pick to the release branch v6.4
```release-note
None
```
=> Lower down the frequency of sending AwakenRegions.

server/cluster/cluster.go
Issue Number: ref #5648.
```commit-message
Eliminate some duplicated code in `processRegionHeartbeat`.
```
Tests
- Unit test
```release-note
None.
```
=> cluster: eliminate some duplicated code in processRegionHeartbeat

server/cluster/cluster.go, server/cluster/cluster_test.go, server/grpc_service.go, tests/pdctl/hot/hot_test.go, tests/server/storage/hot_region_storage_test.go
Issue Number: Close #5678 
```commit-message
Polish and refine the strategy on updating `lastAwakenTime` in stores, to remove an extra and unnecessary `Store.Clone(...)`.
```
Tests
- Unit test
Code changes
Side effects
- None
- None
```release-note
None
```
=> Polish the mechanism on updating `lastAwakenTime` 

Dockerfile
Fix tidb-operator pd health check question,ref :https://github.com/pingcap/tidb-operator/issues/4764.
```commit-message
Add curl command into docker image.
```
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
=> Add curl command into docker image

client/go.mod, client/go.sum, go.mod, go.sum, tests/client/go.mod, tests/client/go.sum, tools/pd-tso-bench/go.mod, tools/pd-tso-bench/go.sum
PD only call ReplaceGlobals once in the beginnign of the server, so the bug has no effect on the release 6.4. 
Issue Number: close: #5604
ref #https://github.com/pingcap/log/issues/30
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> mod: upgrade log module

server/api/trend_test.go, server/cluster/cluster.go, server/cluster/cluster_test.go, server/cluster/metrics.go, tests/server/cluster/cluster_test.go
Issue Number: Ref #5648.
After changing the update interval to 1ms and leader-schedule-limit to 2000:
After changing the interval to 5ms:
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: move update store to another place

tools/pd-heartbeat-bench/config-template.toml, tools/pd-heartbeat-bench/config/config.go, tools/pd-heartbeat-bench/main.go
Issue Number: Close #5690
Now, it can be run through `tiup playground nightly --kv=1 --kv.binpath=/path/to/pd-heartbeat-bench --kv.config=/path/to/config-template.toml --pd=1 --db=0 --host <your_host>`
```commit-message
```
Tests
- Manual test
```release-note
None
```
=> tools: support using tiup playground to bench region heartbeat

pkg/movingaverage/avg_over_time.go, pkg/movingaverage/queue.go, server/statistics/hot_peer_cache.go, server/statistics/hot_peer_cache_test.go
Issue Number: Ref #5692
1. reduce unnecessary `newItem`
2. reduce unnecessary queue init
Tests
- Unit test
```release-note
None.
```
=> statistics: reduce unnecessary clone and init in hot cache

server/core/region.go, server/core/region_test.go
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> core: use map directly

tests/client/client_test.go, tests/pdctl/cluster/cluster_test.go, tests/pdctl/scheduler/scheduler_test.go
Issue Number: Close #4933.
The original test logic is not correct, this PR fixes it.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: make TestScheduler stable

server/schedulers/grant_hot_region.go, server/schedulers/hot_region.go, server/schedulers/hot_region_test.go, server/schedulers/shuffle_hot_region.go
Issue Number: Ref #5691
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> scheduler: introduce base class of hot region scheduler

tests/server/cluster/cluster_test.go
Issue Number: Close #5682
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: make `TestExternalTS` stable

pkg/cache/cache_test.go, pkg/mock/mockcluster/mockcluster.go, server/core/region_option.go, server/core/region_test.go, server/statistics/hot_peer_cache_test.go, server/statistics/kind.go, tests/pdctl/hot/hot_test.go, tests/pdctl/store/store_test.go, tests/server/storage/hot_region_storage_test.go
It is a part of #5721
Tests
- Unit test
```release-note
None.
```
=> tests: speed up test by reducing sleep time

pkg/mock/mockcluster/mockcluster.go, server/cluster/coordinator_test.go, server/schedulers/hot_region.go, server/statistics/hot_cache.go, server/statistics/hot_peer.go, server/statistics/hot_peer_cache.go, server/statistics/hot_peer_cache_test.go, server/statistics/kind.go
Issue Number: Ref #5692 
It is a part of https://github.com/tikv/pd/pull/5721
Tests
- Unit test
```release-note
None.
```
=> statistics: remove `Kind` from hot peer stat

go.mod, go.sum, pkg/movingaverage/max_filter.go, pkg/movingaverage/median_filter.go, pkg/movingaverage/median_filter_test.go, tests/client/go.mod, tests/client/go.sum
Issue Number: Ref #5692.
```
name             old time/op    new time/op    delta
MedianFilter-40     618ns ± 8%     156ns ± 9%  -74.74%  (p=0.008 n=5+5)
name             old alloc/op   new alloc/op   delta
MedianFilter-40      104B ± 0%       80B ± 0%  -23.08%  (p=0.008 n=5+5)
name             old allocs/op  new allocs/op  delta
MedianFilter-40      2.00 ± 0%      1.00 ± 0%  -50.00%  (p=0.008 n=5+5)
```
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> pkg: use another `Median`

server/config/config.go, server/config/persist_options.go, server/schedule/checker/rule_checker.go, server/schedule/checker/rule_checker_test.go, server/schedule/placement/rule_manager.go
ref tikv/pd#5627
Issue Number: Close #5627 
Address comments from: https://github.com/tikv/pd/pull/5630
```commit-message
rule_checker: address witness pr commits
```
Tests
- No code
Code changes
Side effects
- No
- none
```release-note
None
```
=> rule_checker: address witness pr commits

Dockerfile, go.mod, tests/client/go.mod
```commit-message
```
Tests
- No code
```release-note
None
```
=> *: upgrade go 1.19

go.mod, server/schedule/checker/rule_checker.go, server/schedule/placement/rule_manager.go, server/schedule/placement/rule_manager_test.go
ref tikv/tikv#12876
Issue Number: Close #5747
```
rule_checker: prohibit tiflash from being a witness
```
Tests
- Unit test
Code changes
- rule_checker.go
Side effects
- none
- none
```release-note
None
```
=> rule_checker: prohibit tiflash from being a witness

server/schedule/filter/filters.go, server/schedule/filter/filters_test.go
close tikv/pd#5750
Issue Number: Close #5750
```commit-message
balance leader filter witness
```
Tests
- Unit test
Code changes
- filter
Side effects
- None
- None
```release-note
None
```
=> balance leader filter witness

tools/pd-heartbeat-bench/config-template.toml, tools/pd-heartbeat-bench/main.go
Issue Number: Ref #5468.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> tools: fix the key range

tools/pd-heartbeat-bench/main.go
Issue Number: Close #5796
update store info
Tests
- Unit test
```release-note
None.
```
=> tools: fix store update flow

pkg/mcs/docs.go, pkg/mcs/registry/registry.go, pkg/mcs/resource_manager/server/apis/v1/api.go, pkg/mcs/resource_manager/server/grpc_service.go, pkg/mcs/resource_manager/server/install/install.go, server/schedule/checker/checker_controller.go, server/server.go, server/util.go, tests/registry/registry_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: fix typo

server/region_syncer/client.go, tests/server/region_syncer/region_syncer_test.go
Issue Number: Ref #5825.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> syncer: fix sync buckets

pkg/mock/mockcluster/mockcluster.go, tests/pdctl/hot/hot_test.go
Issue Number: ref #5828.
There are some other places using the incorrect functions.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: fix other timestamp

server/api/scheduler.go, server/api/scheduler_test.go, server/config/config.go, server/handler.go, tools/pd-ctl/pdctl/command/scheduler.go
ref tikv/tikv#12876
Issue Number: Close #5762 
```commit-message
pdctl: support dynamic addition of witness-related schedulers
```
Tests
Code changes
- pdctl 
Side effects
- None
- None
```release-note
None
```
=> pdctl: support dynamic addition of witness-related schedulers

server/server.go
line 216 is the same with the line 214
Tests
- Unit test
```release-note
None.
```
=> server: remove duplicate line

go.mod, go.sum, server/statistics/hot_cache.go, server/statistics/hot_peer_cache.go, server/statistics/hot_peer_cache_test.go, tests/client/go.mod, tests/client/go.sum
Issue Number: Close #5791
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> statistics: use unbounded chan in hot task item queue

go.mod, pkg/mcs/resource_manager/client/client.go, pkg/mcs/resource_manager/client/client_test.go, pkg/mcs/resource_manager/client/limiter.go, pkg/mcs/resource_manager/client/limiter_test.go, pkg/mcs/resource_manager/server/token_bukets.go, tests/msc/resource_manager/resource_manager_test.go
Issue Number: ref #4399 ref https://github.com/pingcap/tidb/issues/40380
```commit-message
resource_manager: supports burstable mode
```
Tests
- Unit test
```release-note
None
```
=> resource_manager: supports burstable mode

pkg/versioninfo/feature.go
ref tikv/pd#5568
Issue Number: ref tikv/pd#5568
```commit-message
```
Tests
- Unit test
Code changes
- None
Side effects
- None
- None
```release-note
None
```
=> feature: update the min version supported witness

server/statistics/region_collection.go, server/statistics/region_collection_test.go
Issue Number: ref #5638 
```commit-message
```
Tests
- Unit test
Code changes
- None
Side effects
- None
- None
```release-note
None
```
=> metrics: add witness leader region metrics

pkg/mcs/resource_manager/client/client.go, pkg/mcs/resource_manager/client/client_test.go
Issue Number: ref #4399 ref https://github.com/pingcap/tidb/issues/40876 
```commit-message
resource_manager/client: fix the infinite loop issue
```
Tests
- Unit test
Code changes
Side effects
- PR to update …
=> resource_manager/client: fix the infinite loop issue

pkg/mcs/resource_manager/client/config.go, pkg/mcs/resource_manager/client/model.go, tests/msc/resource_manager/resource_manager_test.go
Issue Number: ref #5851.
```commit-message
- Adjust the RU model config.
- Unify the SQL and KV CPU time RU cost.
```
Tests
- Unit test
```release-note
None.
```
=> resource_manager: adjust the RU model config

server/schedule/filter/filters.go
Issue Number: ref #5638
```commit-message
filter: fix panic caused by nil pointer
```
Tests
- No code
Code changes
- None
Side effects
- None
- None
```release-note
None
```
=> filter: fix panic caused by nil pointer

server/apiv2/handlers/keyspace.go, server/keyspace/keyspace.go, server/keyspace/keyspace_test.go
at tidb cloud, there are some components need to know load keyspace by id.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> keyspace: add load keyspace by id

cmd/pd-server/main.go, server/cluster/cluster_worker_test.go, server/schedulers/init.go, tests/dashboard/race_test.go, tests/dashboard/service_test.go, tests/server/server_test.go, tools/pd-simulator/main.go
Issue Number: Close #5936
```commit-message
```
Tests
- Unit test
`make pd-server && tiup playground nightly --tiflash 0 --pd 3 --kv 1 --db 1 --pd.binpath ./bin/pd-server`
```release-note
None.
```
=> *: fix scheduler init

pkg/tso/metrics.go, server/cluster/coordinator.go, server/handler.go, server/metrics.go, server/schedule/filter/filters.go, server/schedule/hbstream/metric.go, server/schedule/metrics.go, server/schedulers/balance_leader.go, server/schedulers/balance_region.go, server/schedulers/hot_region.go, server/schedulers/init.go, server/schedulers/metrics.go, server/server_test.go, server/statistics/buckets/bucket_stat_informer.go, server/statistics/store_collection.go, server/statistics/store_hot_peers_infos.go, server/testutil.go, tools/pd-simulator/simulator/task.go
1. replace `todo` with `TODO` in comments
2. replace `MockHandler` with `mockHandler`
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: use uniform case spellings

pd.code-workspace
```commit-message
Update `pd.code-workspace` to support all sub-workspaces.
```
Tests
- No code
```release-note
None.
```
=> misc: update pd.code-workspace

pkg/cgroup/cgroup_cpu_test.go, pkg/gctuner/finalizer_test.go, pkg/gctuner/memory_limit_tuner_test.go, pkg/gctuner/tuner_calc_test.go, pkg/gctuner/tuner_test.go
Signed-off-by: Sen Han <00hnes@gmail.com>
Issue Number: ref #5953
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> add enable_flaky_tests and skip some flaky tests in gctuner

pkg/mcs/resource_manager/server/resource_group.go
Issue Number: ref #5851.
```commit-message
Use construction func to init resource group token settings.
```
Tests
- Unit test
```release-note
None.
```
=> resource_manager: use construction func to init resource group token settings

cmd/pd-server/main.go
Previously, #5971 change the default value of `peer-urls` by accident. This PR fixes it.
```commit-message
```
Tests
- Unit test
```release-note
None
```
=> *: fix the default value of peer-urls

cmd/pd-server/main.go, pkg/mcs/tso/server/server.go, pkg/tso/config.go, pkg/utils/configutil/configutil.go, pkg/utils/configutil/configutil_test.go, pkg/versioninfo/versioninfo.go, server/util.go, tools/pd-ctl/pdctl/ctl.go, tools/pd-recover/main.go
Issue Number: Ref #5836 
```commit-message
Clean config, log initialization and refactor version info.
1. Refactor version info print and log applied to all service modes.
2. Clean config/log initialization in the CreateServerWrapper for PD and TSO
```
Tests
- Unit test
- No code
```release-note
None.
```
=> Clean config, log initialization and refactor version info

pkg/tso/config.go, pkg/utils/configutil/configutil.go, server/config/config.go, tools/pd-heartbeat-bench/config/config.go, tools/pd-simulator/simulator/config.go
This PR moves some config-related functions to the `configutil` package to reduce the duplicated implementation.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> config: refactor config functions

pkg/swaggerserver/empty_handler.go
fix typo
Tests
- No code
Code changes
Side effects
```release-note
None.
```
=> *: fix typo with swagger

pkg/mcs/resource_manager/server/manager.go
When there are too many resource groups, the metrics API can overload.
cleanup metrics of resource groups that does not update anymore.
now it uses constants, later we may want to introduce some config.
```commit-message
```
Tests
```release-note
None.
```
=> mcs: delete metrics that does not update

server/schedulers/balance_region.go
Issue Number: Ref https://github.com/tikv/pd/issues/4399
fix  balance_region log
```commit-message
fix log
```
```release-note
None.
```
=> schedulers: fix balance_region log

metrics/grafana/pd.json, server/metrics.go, server/schedule/operator/metrics.go, server/schedule/operator_controller.go, server/server.go
Issue Number: Close https://github.com/tikv/pd/issues/6043
```commit-message
*: add metrics when operator exceed store limit and the max cpu process
```
Tests
- Unit test
(default hide for noise reason.)
```release-note
None.
```
=> *: add metrics when operator exceed store limit and the max cpu process

pkg/basicserver/basic_server.go, pkg/mcs/resource_manager/server/apis/v1/api.go, pkg/mcs/resource_manager/server/manager.go, pkg/mcs/resource_manager/server/server.go, pkg/mcs/tso/server/server.go, pkg/utils/apiutil/apiutil.go, pkg/utils/apiutil/multiserviceapi/middleware.go, pkg/utils/apiutil/multiservicesapi/middleware.go, pkg/utils/apiutil/serverapi/middleware.go, server/api/metric.go, server/server.go, tests/mcs/resource_manager/resource_manager_test.go, tests/server/api/api_test.go
Issue Number: Close https://github.com/tikv/pd/issues/6051
```commit-message
resource-manager: supports redirect the HTTP request to primary server
```
Tests
- Unit test
before:
after:
```release-note
None.
```
=> resource-manager: supports redirect the http request to primary server

tests/client/global_config_test.go
Issue Number: Close #6013
```
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> test: fix unstable test TestClientWatchWithRevision

.github/workflows/check.yaml, pkg/mcs/resource_manager/server/apis/v1/api.go, server/apiv2/handlers/keyspace.go
Issue Number: Close https://github.com/tikv/pd/issues/6057
```commit-message
mcs: fix the resource manager cannot build with the swagger
```
Tests
- Unit test
can build.
```release-note
None.
```
=> mcs: fix cannot build with swagger

pkg/mcs/discovery/register.go, pkg/mcs/resource_manager/server/server.go, pkg/mcs/tso/server/server.go, pkg/mcs/tso/server/server_test.go, pkg/mcs/tso/server/testutil.go
This PR registers TSO server to etcd and fix a test.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: register TSO server to etcd

metrics/grafana/pd.json
Issue Number: Close #6095
```commit-message
```
Tests
- No code
master:
after:
Code changes
Side effects
```release-note
None.
```
=> remove tombstone monitor from the scheduler filter

pkg/mcs/tso/server/server.go, pkg/storage/endpoint/key_path.go, pkg/storage/endpoint/tso.go, pkg/storage/kv/etcd_kv.go, pkg/storage/storage_tso_test.go, pkg/tso/allocator_manager.go, pkg/tso/global_allocator.go, pkg/tso/local_allocator.go, pkg/tso/tso.go, server/server.go
The PR uses the TSO storage to replace `etcdutil` when loading and saving TSO.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> pkg: use tso storage

pkg/core/store.go, pkg/core/store_option.go, pkg/core/storelimit/limit.go, pkg/core/storelimit/limit_test.go, pkg/core/storelimit/sliding_window.go, pkg/core/storelimit/store_limit.go, server/cluster/cluster.go, server/config/persist_options.go, server/schedule/operator/influence.go, server/schedule/operator/operator_test.go, server/schedule/operator/step.go, server/schedule/operator_controller.go
Issue Number: Close #6104
```commit-message
1. using `SendSnapshot` to replace the send cost 
2 rate limit affect the `AddPeer`,`RemovePeer` and the sliding windows affects the `SendSnapshot`
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> pkg: add new store limit type `SendSnapshot`

server/config/persist_options.go
Issue Number: Close #6105.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> config: improve TTL log

pkg/mcs/tso/server/config.go, pkg/mcs/tso/server/server.go, tests/mcs/tso/server_test.go, tests/mcs/tso/testutil.go
Issue Number: ref #5836
```commit-message
```
Tests
- Unit test
- No code
```release-note
None.
```
=> fix listen addr of tso service

server/config/persist_options.go, server/schedule/checker/rule_checker_test.go, server/schedule/config/config.go, server/schedule/placement/rule_manager.go, server/schedule/placement/rule_manager_test.go
ref tikv/pd#5220
Issue Number: Close #5220 
```commit-message
rule_manager: generate default rules based on whether enable witness
```
Tests
- Manual test
- Setup cluster
Code changes
- None
Side effects
- None
- None
```release-note
None.
```
=> rule_manager: generate default rules based on whether enable witness

client/client.go, client/client_test.go, client/keyspace_client.go, client/meta_storage_client.go, client/pd_service_discovery.go, client/resource_manager_client.go, client/tso_client.go, client/tso_dispatcher.go, client/tso_mcs_discovery.go, client/tso_service_discovery.go, tests/client/Makefile, tests/client/client_test.go, tests/mcs/resource_manager/resource_manager_test.go
```commit-message
Further(final) refactor for PD/TSO-MCS Service Discovery and TSO Client.
```
Tests
- Unit test
```release-note
None.
```
=> Improve PD/TSO-MCS Service Discovery and TSO Client.

client/grpcutil/grpcutil.go, client/resource_manager_client.go
Issue Number: Close #6131 Ref #5851
```commit-message
need to check GetOrCreateGRPCConn error to avoid panic
```
Tests
- Unit test
- No code
```release-note
None.
```
=> resource_manager_client: fix client nil possible to fix panic 

pkg/mcs/resource_manager/server/server.go, tests/mcs/discovery/register_test.go
Issue Number: Close #6157
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: unify confusing etcd key

client/grpcutil/grpcutil.go
Improve grpcutil.GetOrCreateGRPCConn with CAS to prevent duplicate update and non-deterministic consequence
Issue Number: Ref #6159 
```commit-message
Improve grpcutil.GetOrCreateGRPCConn with CAS to prevent duplicate update and non-deterministic consequence
```
Tests
- Unit test
```release-note
None.
```
=> Improve grpcutil.GetOrCreateGRPCConn with CAS

pkg/mcs/resource_manager/server/server.go, pkg/mcs/tso/server/server.go, pkg/mcs/utils/constant.go, server/grpc_service.go, server/server.go, server/server_test.go, tests/cluster.go, tests/mcs/discovery/register_test.go, tests/mcs/tso/server_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/5836.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: move service name to utils/constant.go

.github/workflows/pd-tests.yaml, .github/workflows/tso-function-test.yaml
```commit-message
```
Tests
- No code
```release-note
None.
```
=> ci: add GitHub Actions workflows for release-7.x

pkg/tso/tso.go, tests/client/client_test.go
Issue Number: ref #6071 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: use revision for watch test

pkg/schedule/placement/label_constraint.go
Issue Number: Close #6238
```commit-message
Add a comment to emphasis the importance of "$" as a exclusive store label prefix
```
Tests
- No code
```release-note
None.
```
=> schedulers: Add a comment

client/pd_service_discovery.go
Issue Number: Close #6243.
```commit-message
```
Tests
- Manual test
By using tiup playground: `tiup playground v6.6.0 --db 1 --pd 3 --kv 4 --tiflash 0 --host 172.16.4.3` and replace the tidb binary with the fixed one.
```release-note
None.
```
=> client: fix compatibility problem of pd client

server/grpc_service.go
Issue Number: Close #6254
```commit-message
```
Tests
- Unit test
`~/pingcap/tiup/bin/tiup-playground v6.6.0  --pd.micro '[{"api":true, "amount":1},{"tso":true,"amount":1}]' --pd.binpath ~/pd/bin/pd-server --db.binpath ~/tidb-cse/bin/tidb-server --kv 3 --db 1 --tiflash 0 --db.port 14000 --host 172.16.4.3`
not related error log.
```release-note
None.
```
=> mcs: fix ctx in tso forward stream

pkg/tso/allocator_manager.go, pkg/tso/config.go
```commit-message
Unify the TSO `ServiceConfig` and `ConfigProvider` interfaces.
```
Tests
- Unit test
```release-note
None.
```
=> tso: unify the TSO ServiceConfig and ConfigProvider interfaces

pkg/tso/keyspace_group_manager_test.go
```commit-message
Optimize function signatures to reduce parameter passing.
```
Tests
- Unit test
```release-note
None.
```
=> tso: optimize function signatures to reduce parameter passing

pkg/election/lease.go, pkg/schedule/labeler/labeler.go, pkg/statistics/buckets/hot_bucket_cache.go, pkg/statistics/hot_cache.go, pkg/storage/endpoint/gc_key_space.go, pkg/storage/hot_region_storage.go, pkg/storage/leveldb_backend.go, pkg/tso/allocator_manager.go, pkg/tso/global_allocator.go, pkg/tso/keyspace_group_manager.go, pkg/tso/local_allocator.go, pkg/utils/metricutil/metricutil.go, pkg/utils/tsoutil/tso_dispatcher.go, server/cluster/coordinator.go, server/grpc_service.go
Issue Number: Close #6257
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: fix the missing log panic

pkg/tso/keyspace_group_manager.go
```commit-message
Put `finishSplitKeyspaceGroup` into the critical section.
```
Tests
- Unit test
```release-note
None.
```
=> tso: put finishSplitKeyspaceGroup into the critical section

tests/integrations/mcs/discovery/register_test.go
Issue Number: Close #6334.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestServerRegister` stable

pkg/mcs/resource_manager/server/apis/v1/api.go, pkg/mcs/tso/server/apis/v1/api.go, pkg/mcs/utils/util.go, tests/integrations/mcs/resource_manager/server_test.go, tests/integrations/mcs/tso/server_test.go
The root cause is https://github.com/prometheus/client_golang/issues/622
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix double compression of prom handler

client/client.go
Issue Number: Close #6361.
Fix the unexpected log output.
```commit-message
```
Tests
- Manual test
```release-note
None.
```
=> *: fix log output

pkg/tso/keyspace_group_manager.go, pkg/tso/keyspace_group_manager_test.go
```commit-message
Add retry mechanism for updating keyspace group.
```
Tests
- Unit test
```release-note
None.
```
=> tso: add retry mechanism for updating keyspace group

pkg/mcs/resource_manager/server/server.go, pkg/mcs/tso/server/server.go, pkg/utils/etcdutil/etcdutil_test.go
Issue Number: Ref #6124
revert etcd client without multi endpoint in pd-cse
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> etcdutil: revert etcd client without multi endpoint

pkg/schedule/operator_controller_test.go, pkg/utils/etcdutil/etcdutil_test.go, tests/integrations/tso/client_test.go, tests/server/tso/tso_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: fix failpoint disable

pkg/schedule/checker/replica_strategy.go
Issue Number: Close https://github.com/tikv/pd/issues/6424
```commit-message
checker: fix the incorrect metrics name
```
Tests
- Manual test 
```release-note
None.
```
=> checker: fix the incorrect metrics name

client/keyspace_client.go
Fix the channel leak problem.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> client: fix the leak of the keyspace watch channel

README.md
Issue Number: Close https://github.com/tikv/pd/issues/6499
```commit-message
* update the Go version from v1.19 to v1.20
```
Tests
- No code
```release-note
None.
```
=> README: update the Go version from v1.19 to v1.20

metrics/grafana/pd.json
Issue Number: Close #4399
```commit-message
metrics: update the mvcc db metrics of etcd
- distinguish between physical and logical
```
Tests
- Unit test
```release-note
None.
```
=> metrics: update the mvcc db metrics of etcd

pkg/utils/tsoutil/tso_dispatcher.go
Issue Number: Close #6517 
```commit-message
Remove unnecessary "create tso forwarding stream" on the common happy path
```
Tests
- No code
```release-note
None.
```
=> mcs, tso: remove unnecessary "create tso forwarding stream" log on the common happy path

pkg/mcs/tso/server/server.go
Issue Number: Close #6304
```commit-message
Rewrite TSO gPRC/HTTP server Close().
```
Tests
- Unit test
Reran TestMixedTSODeployment test cases 30 times, the issue wasn't reproed. Previously, it was reproed every 3 ~ 5 times.
-->
```release-note
None.
```
=> Fix tso server close stuck issue

client/resource_group/controller/config.go, client/resource_group/controller/controller.go, client/resource_group/controller/model.go, client/resource_group/controller/testutil.go, pkg/mcs/resourcemanager/server/config.go
Issue Number: Close https://github.com/tikv/pd/issues/6539
```commit-message
make consistent with the ru formula 
- replica number should consider for the request base
- add the batch request part
```
Tests
- Unit test
before:
after:
```release-note
None.
```
=> *: make consist with ru formula

pkg/utils/etcdutil/etcdutil.go
Introduced by https://github.com/tikv/pd/issues/6390
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: fix some log issues

pkg/keyspace/tso_keyspace_group.go, pkg/keyspace/tso_keyspace_group_test.go, pkg/keyspace/util.go
Issue Number: ref #6589.
```commit-message
Prohibit merging the default keyspace group.
```
Tests
- Unit test
```release-note
None.
```
=> keyspace: prohibit merging the default keyspace group

pkg/core/storelimit/store_limit.go, pkg/schedule/checker/checker_controller.go, pkg/schedule/operator/operator_controller.go, pkg/schedule/operator/status.go, server/config/config.go, server/config/persist_options.go, tools/pd-ctl/pdctl/command/operator.go
Issue Number: Ref #5892
```commit-message
fix some typos
```
```release-note
None.
```
=> typo: fix some typo

tests/cluster.go, tests/integrations/mcs/keyspace/tso_keyspace_group_test.go, tests/pdctl/keyspace/keyspace_group_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/6599
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: reduce unnecessary time.sleep in keyspace group

.github/workflows/pd-tests.yaml, Makefile, scripts/ci-subtask.sh, tests/integrations/client/Makefile, tests/integrations/mcs/Makefile, tests/integrations/tso/Makefile
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> ci: split integrations test to speed up

pkg/schedule/checker/replica_strategy.go, pkg/schedule/checker/rule_checker.go, pkg/schedule/checker/rule_checker_test.go
Issue Number: Close #6637
This PR is going to use the region store as the source instead of rule stores.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedule: fix location label in placement rule not work well with rule checker

pkg/utils/apiutil/serverapi/middleware.go, server/api/router.go, tests/server/api/api_test.go
Issue Number: Close #6598, close #6595.
The PR adds `X-Forwarded-For` into the HTTP header when the PD follower redirects the requests to the leader.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> api: support record the caller IP when forwarding

client/tso_client.go, pkg/keyspace/tso_keyspace_group.go
Since the finish is not triggered by the split API directly, we need to know when it is finished.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: add log for finishing split

go.mod, go.sum, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: ref #6415
```commit-message
```
Tests
before
after
```release-note
None.
```
=> dashboard: update version to show all instance cpu limit

tests/pdctl/keyspace/keyspace_group_test.go, tools/pd-ctl/pdctl/command/keyspace_group_command.go, tools/pd-ctl/pdctl/command/store_command.go
#6706 supports getting groups through the filter, we also need to support getting all groups in pd-ctl.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tools: support get all groups

Makefile, client/resource_group/controller/controller.go, client/resource_group/controller/limiter.go, pkg/cgroup/cgroup.go, pkg/core/rangetree/range_tree_test.go, pkg/core/store_test.go, pkg/schedule/checker/replica_checker_test.go, pkg/schedule/labeler/rules.go, pkg/schedule/operator/operator.go, pkg/schedule/operator/operator_controller.go, pkg/schedule/placement/fit_region_test.go, pkg/statistics/buckets/hot_bucket_task_test.go, server/config/store_config_test.go, tests/server/storage/hot_region_storage_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove full-width symbols

go.mod, go.sum, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: Ref #6415
- fix burstable expression
- add description for resource control sysbench
- not use root as default login user name
Tests
```release-note
None.
```
=> dashboard: update version to fix some bugs

client/Makefile, client/resource_group/controller/limiter_test.go, client/resource_group/controller/model_test.go, tests/integrations/tso/Makefile
Issue Number: Close #6781
When I check code for test [master/client/resource_group/controller/model_test.go#L41-L46](https://github.com/tikv/pd/blob/master/client/resource_group/controller/model_test.go?rgh-link-date=2023-07-10T07%3A31%3A07Z#L41-L46)
must fail, but was not tested.
Tests
- Unit test
- No code
```release-note
None.
```
=> client: client test need to be check

pkg/keyspace/keyspace.go
Issue Number: Close #6796
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> keyspace: fix data race

metrics/grafana/pd.json
Issue Number: Close #4350
```commit-message
1. devide Hot `Select event` into `Select read event` and `Select write event`
2. add new panel to show the `hot write bytes of the leader region`
```
Tests
Code changes
Side effects
```release-note
None.
```
=> metrics: modify hot grafana panel

tests/integrations/mcs/tso/keyspace_group_manager_test.go, tests/server/apiv2/handlers/testutil.go
Issue Number: Close #6795.
There might be a txn conflict error when loading the keyspace group and checking the split process.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: fix `TestGetTSOImmediately`

pkg/schedule/operator/metrics.go, pkg/schedule/operator/operator_controller.go
Issue Number: Close #6805
Unify the `operatorWaitCounter` and `operatorCounter`.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove unnecessary metrics

pkg/schedule/checker/priority_inspector.go, pkg/schedule/checker/priority_inspector_test.go
Issue Number: Close #5201.
Fix the logic of `Attempt` as the comment says.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedule: fix the attempt mechanism

pkg/schedule/splitter/region_splitter.go, pkg/schedule/splitter/region_splitter_test.go
Issue Number: Close #5535.
Skip the hot region check when splitting. 
cherry-pick https://github.com/tidbcloud/pd-cse/pull/90.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove hot region check (#90)

pkg/keyspace/tso_keyspace_group.go, pkg/mcs/scheduling/server/meta/config.go, pkg/schedule/config/config.go, pkg/storage/endpoint/key_path.go, pkg/tso/keyspace_group_manager.go, pkg/utils/etcdutil/etcdutil.go, pkg/utils/etcdutil/etcdutil_test.go, server/keyspace_service.go, server/server.go, tests/integrations/mcs/scheduling/meta_test.go
Issue Number: ref #5839.
```commit-message
- Implement the scheduling config watcher.
- Add the tests.
```
Tests
- Unit test
```release-note
None.
```
=> scheduling: implement the scheduling config watcher

codecov.yml
Issue Number: ref #6667.
```commit-message
Given that a significant portion of the PD code test is dependent on the integration tests,
which are essential for covering certain code scenarios, such as the testing of the `mcs` pkg
that specifically requires integration with an actual PD cluster, it becomes imperative to factor
these aspects into the codecov analysis.
This PR modifies the `codecov.yml` file to exclude solely the tool tests from the coverage analysis.
```
Tests
- Unit test
```release-note
None.
```
=> codecov: only ignore the tool tests

client/client.go, client/gc_client.go, pkg/replication/replication_mode.go, tests/integrations/client/gc_client_test.go, tests/integrations/client/global_config_test.go
Issue Number: Close #6894
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> client: add the missing forward ctx

pkg/utils/testutil/api_check.go, server/api/scheduler_test.go
Issue Number: Close https://github.com/tikv/pd/issues/6928
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> test: make `TestAPI` run again

metrics/grafana/pd.json, pkg/schedule/schedulers/balance_leader.go, pkg/schedule/schedulers/balance_region.go, pkg/schedule/schedulers/balance_test.go, pkg/schedule/schedulers/hot_region.go, pkg/schedule/schedulers/metrics.go, pkg/schedule/schedulers/scatter_range.go
Issue Number: Close  #6970
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> metrics: fix wrong metrics for balance region

server/core/region.go, tests/server/region_syncer/region_syncer_test.go
Issue Number: ref #6920
```commit-message
```
https://github.com/tikv/pd/pull/6948 add return which is cherry-pick from https://github.com/tikv/pd/pull/6911
But after https://github.com/tikv/pd/pull/5653 changed the logic for returning 
Tests
- Unit test
- No code
```release-note
None.
```
=> region: remove error return logic

tests/integrations/mcs/tso/keyspace_group_manager_test.go, tests/tso_cluster.go
Issue Number: Close #6991.
```commit-message
Improve the wait time of `WaitForPrimaryServing` to reduce the test failure rate.
```
Tests
- Unit test
```release-note
None.
```
=> tests: improve the wait time of WaitForPrimaryServing

pkg/mcs/scheduling/server/cluster.go, pkg/mcs/scheduling/server/server.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: init rule manager

pkg/tso/keyspace_group_manager.go, pkg/tso/metrics.go
Issue Number: ref  #7011.
```commit-message
Add some metrics for Keyspace Group operations.
```
Tests
- Unit test
```release-note
None.
```
=> tso: add some metrics for Keyspace Group operations

pkg/keyspace/tso_keyspace_group.go, server/cluster/cluster.go
Issue Number: Close #7001
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: avoid stuck goroutine when raftcluster failed to create

pkg/audit/audit_test.go, pkg/election/leadership_test.go, pkg/utils/etcdutil/etcdutil_test.go, server/api/version_test.go, tests/integrations/mcs/tso/server_test.go, tests/pdctl/config/config_test.go, tests/scheduling_cluster.go, tests/server/api/api_test.go, tests/testutil.go, tests/tso_cluster.go, tools/pd-backup/pdbackup/backup_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: unify the test logger

pkg/mcs/scheduling/server/server.go, pkg/schedule/coordinator.go, pkg/statistics/store_collection.go, pkg/statistics/store_collection_test.go, server/cluster/cluster.go, server/cluster/cluster_worker.go, server/handler.go, tests/integrations/mcs/scheduling/config_test.go
Issue Number: ref #5839, close #7041.
This PR disables the PD scheduling when enabling the scheduling service. It also registers the schedulers for scheduling service.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: disable PD scheduling when enabling scheduling service

tests/integrations/mcs/resourcemanager/resource_manager_test.go
Issue Number: ref #7144.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: skip TestWatchResourceGroup temporarily

pkg/balancer/round_robin.go, pkg/btree/btree_generic.go, pkg/btree/btree_generic_test.go, pkg/election/leadership.go, pkg/keyspace/tso_keyspace_group.go, pkg/mcs/resourcemanager/server/manager.go, pkg/mcs/resourcemanager/server/resource_group.go, pkg/memory/meminfo.go, pkg/ratelimit/limiter_test.go, pkg/schedule/schedulers/scheduler_controller.go, pkg/statistics/region_collection.go, pkg/tso/keyspace_group_manager.go, pkg/tso/keyspace_group_manager_test.go, pkg/utils/etcdutil/etcdutil.go, pkg/utils/etcdutil/etcdutil_test.go, pkg/utils/tempurl/tempurl.go, server/apiv2/handlers/tso_keyspace_group.go, server/grpc_service.go, server/server.go, tests/cluster.go, tests/integrations/client/global_config_test.go, tests/server/id/id_test.go, tests/server/tso/consistency_test.go
Replace sync.RWMutex/Mutex with syncutil which will be changed to deadlock one in tests.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: use syncutil lock

pkg/mcs/scheduling/server/cluster.go, pkg/statistics/store_collection.go, server/cluster/cluster.go
Issue Number: Close #7187.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove store statistics after store tombstone

server/util.go
Issue Number: Close https://github.com/tikv/pd/issues/7253
```commit-message
api: fix cannot dump trace with dashboard
```
Tests
- Unit test
can download:
and with curl:
```release-note
None.
```
=> api: fix cannot dump trace

pkg/schedule/schedulers/hot_region.go, pkg/schedule/schedulers/split_bucket.go, pkg/statistics/region_collection.go
Issue Number: Close #7261
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: check whether region is nil

pkg/core/region.go
Issue Number: Close #7273
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> core: fix datarace in RegionsInfo

metrics/grafana/pd.json, server/replication/metrics.go, server/replication/replication_mode.go
close tikv/pd#6975
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
=> dr-autosync: add metrics (#7110) (#7153)

pkg/mcs/resourcemanager/server/resource_group.go, pkg/mcs/resourcemanager/server/token_buckets.go
unify `requiredToken` , `neededTokens`, and `consumptionToken ` into `requiredToken`
```commit-message
```
Tests
- No code
Code changes
Side effects
```release-note
None.
```
=> resourcemanager: change param name

go.mod, go.sum, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: Close #7302
update dashboard version to revert https://github.com/pingcap/tidb-dashboard/pull/1583 and https://github.com/pingcap/tidb-dashboard/pull/1587
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
=> dashboard: update hotfix version

pkg/mcs/resourcemanager/server/apis/v1/api.go, pkg/mcs/scheduling/server/apis/v1/api.go, pkg/mcs/tso/server/apis/v1/api.go
Issue Number: Close #7290.
This PR moves redirector after root group init so that the metrics request won't be redirected to the primary.
```commit-message
```
Tests
- Manual test 
`tiup playground nightly --pd.mode ms --pd.api 1 --pd.scheduling 2 --kv 3 --tiflash 0 --host 10.2.8.101`
```release-note
None.
```
=> mcs: fix duplicated metrics

server/grpc_service.go
Issue Number: Close #7320
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: solve forward stream error

pkg/utils/grpcutil/grpcutil.go, server/gc_service.go, server/grpc_service.go
Issue Number: Close #7320
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: solve stream error when forward tso

pkg/election/leadership.go, pkg/utils/etcdutil/etcdutil.go
Issue Number: Close #7351
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> etcdutil, leadership: avoid redundant created watch channel

client/resource_group/controller/controller.go
Issue Number: close #7360.
```commit-message
Prevent `loadServerConfig` from panic.
```
Tests
- Unit test
```release-note
None.
```
=> resource_controller: prevent loadServerConfig from panic

pkg/member/member.go, tests/integrations/tso/client_test.go
Issue Number: Close #7381
```commit-message
```
Tests
- Unit test
- Manual test
```
for i in {1..100}
do
go test -timeout 120s -run ^TestMicroserviceTSOClient$ github.com/tikv/pd/tests/integrations/tso
go clean -testcache
done
```
```release-note
None.
```
=> tests: make TestUpdateAfterResetTSO stable

pkg/replication/replication_mode.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> dr: add more log when state change

tests/integrations/client/client_test.go, tests/integrations/mcs/resourcemanager/resource_manager_test.go, tests/integrations/mcs/tso/server_test.go, tests/integrations/tso/client_test.go
Issue Number: Close #7400
It is introduced by https://github.com/tikv/pd/pull/7301
For many times resign leader, we should skip this check.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make resign leader test more stable

tests/integrations/mcs/scheduling/server_test.go
Issue Number: Close #7237.
After the server starts, there will be a time window before starting schedulers.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make TestPrimaryChange stable

client/http/client.go, pkg/audit/audit_test.go, pkg/dashboard/adapter/redirector_test.go, pkg/utils/apiutil/apiutil.go, server/api/admin.go, server/api/admin_test.go, server/api/config.go, server/api/region_test.go, server/api/server_test.go, server/api/store_test.go, server/cluster/cluster.go, server/server_test.go, tests/integrations/mcs/keyspace/tso_keyspace_group_test.go, tests/integrations/mcs/resourcemanager/resource_manager_test.go, tests/integrations/mcs/tso/api_test.go, tests/server/api/api_test.go, tests/server/api/testutil.go, tests/server/apiv2/handlers/testutil.go, tests/server/member/member_test.go, tools/pd-api-bench/cases/cases.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: Use http.NoBody instead of nil in http.NewRequest calls

pkg/core/store_option.go, pkg/mcs/scheduling/server/cluster.go
Issue Number: Close #7445.
Previous PR #7396 removed the process of updating the last heartbeat ts for the scheduling server, which led to the store disconnection. This PR adds it back.
```commit-message
```
Tests
- Manual test
```release-note
None.
```
=> mcs: fix the last heartbeat is not updated

go.mod, go.sum, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: Close #7457
Update tidb-dashboard to v20231127.1 to introduce component upgrades for security reason
Dashboard release PR: https://github.com/pingcap/tidb-dashboard/pull/1620
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
=> dashboard: update version to v20231127.1

client/pd_service_discovery.go, client/tso_service_discovery.go, pkg/utils/grpcutil/grpcutil.go, server/config/persist_options.go
`serviceType` is unexported, so `DiscoverMicroservice` is improper  as  a method of interface
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update …
=> *: remove improper method in ServiceDiscovery

pkg/dashboard/adapter/manager.go, tests/pdctl/config/config_test.go
Issue Number: Close #7440. also see #7464
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make TestConfig stable

pkg/tso/keyspace_group_manager_test.go
Issue Number: Close #7429
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix unstable panic in tso test

pkg/schedule/schedulers/balance_leader.go, pkg/schedule/schedulers/balance_witness.go, pkg/schedule/schedulers/grant_hot_region.go, pkg/schedule/schedulers/grant_leader.go, pkg/schedule/schedulers/hot_region_config.go, pkg/schedule/schedulers/hot_region_test.go, pkg/schedule/schedulers/scatter_range.go, pkg/schedule/schedulers/shuffle_hot_region.go, pkg/schedule/schedulers/split_bucket.go
Issue Number: Close #7485
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedulers: fix config data race

pkg/core/region_tree.go, pkg/schedule/schedulers/evict_slow_trend_test.go, tests/integrations/mcs/resourcemanager/resource_manager_test.go, tests/integrations/mcs/tso/proxy_test.go, tests/registry/registry_test.go, tests/server/config/config_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make TestConfigPDServer stable

server/grpc_service.go, server/metrics.go, server/server.go
Add some metrics to better diagnose the forward error.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: add forward metrics

pkg/mcs/scheduling/server/config/config.go, pkg/utils/apiutil/serverapi/middleware.go, server/config/persist_options.go, tests/integrations/mcs/tso/api_test.go, tests/server/api/scheduler_test.go
Issue Number: Close #7512
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: add IsServiceIndependent check to fix redirect

Dockerfile
Issue Number: Close https://github.com/tikv/pd/issues/7521
```commit-message
ci: fix docker build with musl compatibility issue
```
Tests
- Unit test
```release-note
None.
```
=> ci: fix docker build sqlite3 and alpine 3.19 incompatibility 

client/go.mod, client/resource_group/controller/config.go, client/resource_group/controller/controller.go, client/resource_group/controller/limiter.go, client/resource_group/controller/limiter_test.go, client/resource_group/controller/metrics.go, pkg/mcs/resourcemanager/server/config.go, tests/pdctl/resourcemanager/resource_manager_command_test.go, tools/pd-ctl/pdctl/command/resource_manager_command.go, tools/pd-ctl/pdctl/ctl.go
Issue Number: Close https://github.com/tikv/pd/issues/7509
```commit-message
resource_control: improve trace logs, ctl and metrics
- add the ctl command to config resource cotnrol
- add metrics and a switch to enable trace log
```
Tests
- Unit test
```release-note
None.
```
=> resource_control: improve trace logs, ctl and metrics

.github/workflows/pd-tests.yaml
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
=> ci: fix CI for specific branch

server/grpc_service.go
Issue Number: Close #7528.
Revert part changes of #7014.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix panic of GetMinTS

pkg/mcs/scheduling/server/server.go
Issue Number: Close #7539.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix panic when getting the member which is not started

pkg/utils/apiutil/serverapi/middleware.go, tests/integrations/mcs/scheduling/api_test.go, tests/pdctl/scheduler/scheduler_test.go
Issue Number: Close #7533
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix unnecessary PDRedirectorHeader

server/api/store.go
```commit-message
```
Tests
- Manual test
```release-note
None.
```
=> api: fix the output of some APIs

pkg/mcs/resourcemanager/server/server.go
Issue Number: Close #7543.
Make the calling sequence is right.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix sequence of callback functions

Makefile, pd.code-workspace
Issue Number: ref #7298.
```commit-message
Add `test-real-cluster` command to the root Makefile.
```
Tests
- Unit test
```release-note
None.
```
=> Makefile: add test-real-cluster command to the root Makefile

client/http/client.go, client/http/client_test.go, tests/integrations/client/http_client_test.go, tests/integrations/mcs/members/member_test.go, tests/integrations/realtiup/util.go
```commit-message
When creating a client, it is required to pass in the `source` parameter to further distinguish the source of logs and requests.
```
Tests
- Unit test
```release-note
None.
```
=> client/http: require source mark when initializing the http client

Makefile
Issue Number: Close #7585
```commit-message
```
`make generate-errdoc` failed due to exist `.dashboard_build_temp`
```
$ make generate-errdoc
generating errors.toml...
./scripts/generate-errdoc.sh
Generate errors.toml failed: exit status 1, output:
_errdoc-generator/main.go:17:3: import path must be a string
make: *** [Makefile:196: generate-errdoc] Error 1
```
in `_errdoc-generator/main.go:17`
```
import (
...
pkg_mcs_tso_server "github.com/tikv/pd/pkg/mcs/tso/server"
.dashboard_build_temp_pkg_apiserver_debugapi_endpoint 
...
)
```
When executing `make dashboard-ui DASHBOARD=COMPILE` and losing some dependencies, `.dashboard_build_temp` is left behind.
Tests
```release-note
None.
```
=> makefile: make clean to remove dashboard temp

.github/workflows/pd-tests.yaml, server/versioninfo/fips.go
Issue Number: ref #7274
We will include fips on the tag to indicate version information
```commit-message
```
Tests
Code changes
Side effects
```release-note
None. …
```
=> versioninfo: remove fips suffix 

client/http/client.go, client/http/client_test.go
Issue Number: Close #7639
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> test: fix TestRedirectWithMetrics data race

server/api/region.go, tools/pd-ctl/tests/region/region_test.go
Issue Number: Close #7630.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> api: fix panic when region doesn't have a leader

pkg/mcs/resourcemanager/server/manager.go
The previous clean up logic uses incorrect number of labels, causing it to be ineffective.
Record `ruType` aside from resource group `name` in `comsumptionRecord`.
```commit-message
```
Tests
```release-note
None.
```
=> mcs: fix metrics cleanup

client/http/interface.go, client/http/request_info.go, tests/integrations/client/http_client_test.go
Issue Number: ref #7300
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> http: add GetVersion API

pkg/utils/apiutil/apiutil.go, pkg/utils/apiutil/serverapi/middleware.go, server/api/config.go, tests/integrations/mcs/scheduling/api_test.go, tests/integrations/mcs/tso/api_test.go, tools/pd-ctl/pdctl/command/config_command.go, tools/pd-ctl/pdctl/command/global.go, tools/pd-ctl/tests/config/config_test.go
Issue Number: Close #7690
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: add option to control redirect http request

tools/pd-heartbeat-bench/config/config.go
Issue Number: Ref #7703 
```commit-message
```
Tests
- Manual test 
```release-note
None.
```
=> tools: improve heartbeat bench cmd

pkg/keyspace/tso_keyspace_group.go, pkg/mcs/scheduling/server/config/watcher.go, pkg/mcs/scheduling/server/meta/watcher.go, pkg/mcs/scheduling/server/rule/watcher.go, pkg/tso/keyspace_group_manager.go, pkg/utils/etcdutil/etcdutil.go, pkg/utils/etcdutil/etcdutil_test.go, server/keyspace_service.go, server/server.go
Issue Number: Close #7689
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> etcdutil: fix load range option

tools/pd-api-bench/config/config.go
Issue Number: ref #7703
```commit-message
```
Tests
- Manual test
Code changes
Side effects
```release-note
None.
```
=> tools: add log file param for api bench

pkg/mcs/utils/util.go, pkg/utils/etcdutil/etcdutil.go, server/server.go
Issue Number: ref #7499.
```commit-message
Sort out the initialization functions of etcd client.
```
Tests
- Unit test
```release-note
None.
```
=> etcdutil, server: sort out the initialization functions of etcd client

server/grpc_service.go
Issue Number: Close #7719 
Cherry-pick of https://github.com/tidbcloud/pd-cse/pull/253.
When the interval between the first region heartbeat of new created region and bucket report is very short, there are chanced that the leader of region has not been persisted when handling the bucket report.
As the leader info is only used for metrics, it would be better to tolerate the leader info not found, and process the bucket report as well.
Otherwise, after return gRPC error, TiKV will unnecessarily re-establish the stream for report bucket, and some existing messages will be dropped.
```commit-message
server: tolerate no leader on handling report buckets.
```
Tests
- Integration test (by integration tests of CSE)
Code changes
- No.
Side effects
- No.
- Need to cherry-pick to the …
=> server: tolerate no leader on report bucket

pkg/member/member.go, pkg/utils/etcdutil/etcdutil.go, pkg/utils/etcdutil/etcdutil_test.go, pkg/utils/etcdutil/health_checker.go, pkg/utils/etcdutil/testutil.go, server/api/member.go, server/cluster/cluster.go, server/join/join.go, server/server.go, tests/server/join/join_test.go, tools/pd-ctl/tests/member/member_test.go
Issue Number: ref #7730, #7499.
```commit-message
Move the health checker into a separate file.
```
Tests
- Unit test
```release-note
None.
```
=> etcdutil: move health checker into a separate file

pkg/schedule/labeler/labeler.go, pkg/schedule/labeler/labeler_test.go
Issue Number: Close #7747
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> labeler: keep compatibility when meeting duplicate rules.

client/client.go, client/http/client.go, client/pd_service_discovery.go, tests/integrations/client/http_client_test.go
Issue Number: ref #7576
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> client: add sheme in pd http client

Makefile
Issue Number: ref #7758.
```commit-message
Build all necessary deps before the static check to make it not rely on the build command.
```
Tests
- Unit test
```release-note
None.
```
=> Makefile: build all necessary deps before the static check

tools/pd-heartbeat-bench/main.go
Issue Number: Ref #7703.
```commit-message
```
Tests
- Manual test
```release-note
None.
```
=> tools: fix store statistics

.golangci.yml, Makefile, pkg/core/storelimit/limit_test.go, pkg/utils/typeutil/clone_test.go, tests/integrations/mcs/resourcemanager/resource_manager_test.go
```commit-message
Adopt the latest golangci-lint version and check.
```
Tests
- Unit test
```release-note
None.
```
=> *: adopt the latest golangci-lint

tools/pd-api-bench/cases/controller.go
Issue Number: ref #7703
```commit-message
```
Tests
Code changes
Side effects
```release-note
None.
```
=> tools: support more concurrency for API bench

client/http/client.go, client/http/client_test.go, client/mock_pd_service_discovery.go, client/pd_service_discovery.go
```commit-message
Utilize a mock PD service discovery to prevent blocking of the HTTP request during testing.
```
Tests
- Unit test
```release-note
None.
```
=> client/http, tests: utilize a mock PD service discovery during testing

.github/workflows/pd-tests.yaml, .github/workflows/tso-function-test.yaml
Issue Number: Close #7933
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> ci: add GitHub Actions workflows for release-8.x

server/api/region_test.go
Issue Number: ref #7930
```commit-message
```
Tests
- Unit test
```
Before
<testcase classname="github.com/tikv/pd/server/api" name="TestRegionsWithKillRequest" time="12.599034"/>
After
go test -timeout 120s -run ^TestRegionsWithKillRequest$ github.com/tikv/pd/server/api
ok      github.com/tikv/pd/server/api   2.972s
```
```release-note
None.
```
=> tests/api: reduce TestRegionsWithKillRequest test time

server/server_test.go
```commit-message
which can use parallel test
```
Tests
- Unit test
```release-note
None.
```
=> tests/server: move `TestCheckClusterID` out of `leaderServerTestSuite`

metrics/grafana/pd.json
Issue Number: Close #7959
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> metrics: fix alloc id, current tso and patrol panel

pkg/utils/etcdutil/etcdutil_test.go, pkg/utils/testutil/testutil.go, server/api/region_test.go
Issue Number: ref #7930
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests/etcdutil: reduce `TestRandomKillEtcd` test time

pkg/mcs/resourcemanager/server/config.go
after #7042, we can remove this.
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects …
=> resource_control: remove unnecessary comment

tests/integrations/mcs/scheduling/api_test.go
Issue Number: Close #7954.
```
2024-03-20T07:59:25.9421434Z [2024/03/20 07:58:57.926 +00:00] [WARN] [cluster.go:1495] ["store has been Tombstone"] [store-id=6] [store-address=tikv6] [state=Offline] [physically-destroyed=false]
2024-03-20T07:59:25.9423334Z [2024/03/20 07:58:57.931 +00:00] [INFO] [cluster.go:2225] ["store limit removed"] [store-id=6]
```
store 6 becomes tombstone.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestStores` stable

tests/server/api/scheduler_test.go
Issue Number: Close #7810.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: fix `TestAPI`

tests/server/config/config_test.go
Issue Number: Close #7711.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestConfigAll` stable

tests/server/api/scheduler_test.go
Issue Number: Close #7702, close #6627.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestScheduleTestSuite` stable

pkg/schedule/operator/operator_controller.go, pkg/schedule/operator/operator_controller_test.go, pkg/schedule/operator/operator_queue.go, pkg/schedule/operator/waiting_operator.go
Issue Number:  Ref https://github.com/tikv/pd/issues/7897
```commit-message
pkg/schedule: optimize the lock usage of the operator controller
- use sync.Map for operators, which is friendly for check operators on the heartbeat hot path
- reduce the lock hold time by splitting the locks.
```
Tests
- Unit test
```release-note
None.
```
=> pkg/schedule: optimize the lock usage of operator controller

pkg/tso/keyspace_group_manager_test.go
test by `make ut`
```bash
--- FAIL: TestKeyspaceGroupManagerTestSuite (22.33s)
--- FAIL: TestKeyspaceGroupManagerTestSuite/TestPrimaryPriorityChange (12.89s)
testutil.go:67: 
Error Trace:    /data/nvme0n1/husharp/proj/pd/pkg/utils/testutil/testutil.go:67
/data/nvme0n1/husharp/proj/pd/pkg/tso/keyspace_group_manager_test.go:1205
/data/nvme0n1/husharp/proj/pd/pkg/tso/keyspace_group_manager_test.go:1132
Error:          Condition never satisfied
Test:           TestKeyspaceGroupManagerTestSuite/TestPrimaryPriorityChange
```
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests/tso: make TestPrimaryPriorityChange stable

server/cluster/cluster_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> cluster: make TestStoreOverloadedWithReplace stable

tests/server/tso/global_tso_test.go
Issue Number: Close #7017.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestLogicalOverflow` stable

pkg/schedule/checker/checker_controller.go
Issue Number: Ref #7963.
The previous cache size is too small when there is a large number of regions. Enlarge the cache size to speed up.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedule: enlarge waiting list cache size

server/api/admin_test.go, tests/integrations/tso/server_test.go
Issue Number: Close #6898.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestConcurrentlyReset` stable

tests/server/apiv2/handlers/testutil.go
Issue Number: Close #7380
Ensure the request can succeed even if the leader drops.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestSplitKeyspaceGroup` stable

client/resource_group/controller/controller.go
Export configuration for resource group client
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> resource_group: export DegradeModeWaitDuration

client/resource_group/controller/limiter.go
Issue Number: Close https://github.com/tikv/pd/issues/8159
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> controller: Reduce the frequency of printing logs

tests/server/api/api_test.go
because `checkStores` checks store state every 3 seconds
https://github.com/tikv/pd/blob/227860912dbf95c19c506335be2e6f8319ae28ba/server/cluster/cluster.go#L1796-L1804
when `GetTotalRegionCount` is not meet `InitClusterRegionThreshold`(100), will change store 4 to the serving state
https://github.com/tikv/pd/blob/6ecf23def91927788d6fb5103368c1755fe0dded/tests/server/api/api_test.go#L957-L963
and when changing store 4 to the serving state will make test unstable
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests/server/api: make `TestPreparingProgress` stable

pkg/storage/endpoint/key_path.go
Issue Number: Ref #7897.
```
$ benchstat old.txt new.txt
goos: linux
goarch: amd64
pkg: github.com/tikv/pd/pkg/storage/endpoint
cpu: Intel(R) Xeon(R) Gold 6240 CPU @ 2.60GHz
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
RegionPath-72   132.70n ± 2%   97.37n ± 4%  -26.62% (p=0.000 n=10)
│  old.txt   │              new.txt               │
│    B/op    │    B/op     vs base                │
RegionPath-72   48.00 ± 0%   39.00 ± 0%  -18.75% (p=0.000 n=10)
│  old.txt   │              new.txt               │
│ allocs/op  │ allocs/op   vs base                │
RegionPath-72   2.000 ± 0%   1.000 ± 0%  -50.00% (p=0.000 n=10)
```
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> pkg: improve region path

pkg/core/metrics.go, server/cluster/cluster_worker.go
Issue Number: Ref #7897
Before:
After:
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> core: use sync pool for tracer

pkg/core/region.go, pkg/core/region_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/7897
```commit-message
core/region: fix the sub tree may not consist of root tree
```
Tests
- Unit test
- No code
```release-note
None.
```
=> core/region: fix sub tree may not consist with root tree

metrics/grafana/pd.json
Issue Number: Ref https://github.com/tikv/pd/issues/7897
```commit-message
metrics: update grafana template to add heartbeat latency overview
```
Tests
- Unit test
```release-note
None.
```
=> metrics: update grafana template to add heartbeat latency overview

tests/integrations/realcluster/deploy.sh
Issue Number: Ref #7298
running with data race
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests/realcluster: using real pd with race

pkg/keyspace/tso_keyspace_group.go, server/apiv2/handlers/tso_keyspace_group.go, tests/integrations/mcs/keyspace/tso_keyspace_group_test.go
Issue Number: Close #8154
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: update node every restart

README.md
rely on https://github.com/tikv/pd/blob/3b051d727d02dae34d3a8b7f7b373165ef621e5f/go.mod#L3
```commit-message
update go version in readme
```
Tests
- No code
```release-note
None.
```
=> readme: update go version in readme

metrics/grafana/pd.json, pkg/statistics/metrics.go, pkg/statistics/store_collection.go, pkg/statistics/store_collection_test.go
Issue Number: Close #8337
before
after
```bash
$ ./pd-ctl store label 1 zone=c
Success! The store's label is updated.
$ ./pd-ctl store label 2 zone=b
Success! The store's label is updated.
$ ./pd-ctl store label 3 zone=c
Success! The store's label is updated.
$ ./pd-ctl config set replication.location-labels "zone"
Success!
```
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> statistics: extend store label with store id

pkg/encryption/master_key_test.go, pkg/storage/hot_region_storage_test.go, pkg/utils/grpcutil/grpcutil_test.go, pkg/utils/testutil/testutil.go, server/config/config_test.go, server/join/join.go, server/server_test.go, server/testutil.go, tests/config.go, tests/integrations/client/client_tls_test.go, tests/server/join/join_test.go, tools/pd-backup/pdbackup/backup_test.go, tools/pd-ctl/pdctl/command/global_test.go, tools/pd-ctl/tests/config/config_test.go, tools/pd-ctl/tests/health/health_test.go, tools/pd-ctl/tests/store/store_test.go, tools/pd-simulator/simulator/config/config.go, tools/pd-ut/coverProfile.go, tools/pd-ut/ut.go
Issue Number: Ref #8475
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: replace part of path with filepath

server/api/member_test.go, server/config/config.go
Issue Number: Close #8535
```commit-message
```
Tests
- Unit test
```release-note
config: disable EnableV2 of etcd
```
=> config: disable EnableV2 of etcd

server/util.go
Issue Number: Close #8553
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> api: remove duplicate `/debug/pprof/trace` register

tests/cluster.go, tests/integrations/mcs/scheduling/api_test.go
Issue Number: Close #7954.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove the previous joined pd

client/resource_group/controller/controller.go, pkg/keyspace/tso_keyspace_group.go, pkg/mcs/resourcemanager/server/manager.go, pkg/mcs/scheduling/server/server.go, pkg/schedule/coordinator.go, pkg/tso/allocator_manager.go, server/cluster/cluster.go, server/cluster/scheduling_controller.go, tools/pd-api-bench/cases/controller.go, tools/pd-heartbeat-bench/main.go
Issue Number: ref #7969
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: use reset for ticker

server/api/region_test.go
Issue Number: Close #8519.
The previous heartbeat is synchronized. Right now, it becomes asynchronized and the statistics may not be updated in time.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestRegionCheck` stable

tests/server/api/rule_test.go
Issue Number: Close #8408.
The rules may not be sorted. We can directly use the existing compare bundle function.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: make `TestLeaderAndVoter` stable

server/grpc_service.go, tests/server/server_test.go
Issue Number: ref #7167
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: add grpc rate limit tests

tools/pd-ctl/tests/scheduler/scheduler_test.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: make schedulerTestSuite stable

go.mod, go.sum, pkg/dashboard/adapter/config.go, scripts/dashboard-version, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: ref #4257 #8611
Update TiDB Dashboard to [v7.5.4-ec6d9999a](https://github.com/pingcap/tidb-dashboard/releases/tag/v7.5.4-ec6d9999a).
```release-note
None
```
=> chore(dashboard): update TiDB Dashboard to v7.5.4-ec6d9999a [release-7.5]

tests/integrations/client/cert_opt.sh
Issue Number: Ref #6910.
```commit-message
```
Tests
- No code
```release-note
None.
```
=> *: remove tidb security test files

client/client.go, client/pd_service_discovery.go, client/tso_service_discovery.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> client: reuse `initRetry` function

server/cluster/cluster.go
Issue Number: Close #8781
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> cluster: fix tso fallback when pd leader switch

go.mod, go.sum, pkg/dashboard/adapter/config.go, scripts/dashboard-version, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: ref #4257 #8611
Update TiDB Dashboard to [v7.1.6-afb197c94](https://github.com/pingcap/tidb-dashboard/releases/tag/v7.1.6-afb197c94).
```release-note
None
```
=> chore(dashboard): update TiDB Dashboard to v7.1.6-afb197c94 [release-7.1]

pkg/member/participant.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove unused code from participant.go

tests/integrations/mcs/scheduling/api_test.go
Issue Number: Close #8642
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: fix local id panic

README.md
Issue Number: ref #8802.
```commit-message
Remove the TSO consistency test status badge.
```
Tests
- No code
```release-note
None.
```
=> readme: remove the TSO consistency test status badge

server/cluster/cluster.go, tests/integrations/client/client_test.go
Issue Number: Close https://github.com/tikv/pd/issues/8836
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> cluster: fix tso fallback due raft cluster did not stop tso service

pkg/mock/mockserver/mockserver.go, pkg/syncer/client_test.go, tests/server/cluster/cluster_test.go
Issue Number: ref #8823.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: add test for syncer

pkg/cgroup/cgroup_cpu_test.go, pkg/core/region_test.go, pkg/mcs/resourcemanager/server/metrics_test.go, pkg/mcs/resourcemanager/server/token_buckets_test.go, pkg/tso/keyspace_group_manager_test.go, pkg/window/policy_test.go, tests/integrations/realcluster/cluster.go, tests/server/api/api_test.go, tools/pd-ctl/tests/scheduler/scheduler_test.go
Issue Number: ref #4322.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: fix lint issue

OWNERS
```commit-message
```
Tests
- Unit test
- No code
```release-note
None.
```
=> OWNERS: Sync OWNERS files from community membership

client/metrics/metrics.go
Issue Number: ref #8678.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> metrics: fix typo

client/errs/errno.go, client/pd_service_discovery.go
Issue Number: Close #9036
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> client: fix confusing error

pkg/schedule/splitter/region_splitter.go
Issue Number: Close #9093
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> schedule: adjust the log level

tests/integrations/client/client_test.go, tests/server/api/api_test.go, tests/testutil.go
Issue Number: Close #8693.
The reason is the same as the removing progress testing. As for panic, it is caused by the leader stepping down. So I add a check before put store, which might reduce the possibility of failure.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: fix `TestPreparingProgress`

client/client_test.go, tests/integrations/client/client_test.go, tests/integrations/mcs/tso/keyspace_group_manager_test.go, tests/integrations/realcluster/cluster_id_test.go, tests/integrations/realcluster/reboot_pd_test.go, tests/integrations/realcluster/scheduler_test.go, tests/server/api/api_test.go
Issue Number: ref #7969 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: close client after finishing tests

.github/workflows/check.yaml, .github/workflows/label.yaml, .github/workflows/pd-docker-image.yaml, .github/workflows/pd-tests.yaml, .github/workflows/tso-consistency-test.yaml, .github/workflows/tso-function-test.yaml, pkg/cache/ttl.go
Issue Number: Close #https://github.com/tikv/pd/issues/9047
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> cache: cherry-pick 9048 

client/client.go, client/metrics/metrics.go, tests/integrations/client/client_test.go
Issue Number: Close #9147
```commit-message
client: add GetLeaders method
```
Tests
```release-note
None.
```
=> client: add GetLeaders method

pkg/mcs/scheduling/server/rule/watcher.go
Issue Number: Close #9152
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: change log level of watcher in scheduling server

pkg/ratelimit/runner.go
Issue Number: Close https://github.com/tikv/pd/issues/9163
Ticker is stopped incorrectly.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> runner: move ticker initialization into goroutine

pkg/storage/endpoint/tso.go, pkg/storage/storage_tso_test.go, pkg/tso/keyspace_group_manager.go, pkg/tso/keyspace_group_manager_test.go, pkg/tso/tso.go, pkg/utils/tsoutil/tso_dispatcher.go, pkg/utils/tsoutil/tso_request.go, tests/server/tso/tso_test.go
Issue Number: close #8802.
```commit-message
Completely remove the legacy code related to the Local TSO.
```
Tests
- Unit test
```release-note
None.
```
=> tso: completely remove legacy code of Local TSO

pkg/tso/allocator.go, pkg/tso/keyspace_group_manager.go, server/server.go, tests/integrations/tso/client_test.go
Issue Number: close #9179.
```commit-message
Do not exit `allocatorUpdater` if the updating fails to prevent the TSO from stuck.
```
Tests
- Unit test
```release-note
None.
```
=> fix(tso): do not exit allocatorUpdater if the updating fails

cmd/pd-server/main.go, pkg/mcs/scheduling/server/apis/v1/api.go, pkg/schedule/schedulers/transfer_witness_leader_test.go, pkg/storage/storage.go, server/api/store_test.go, server/api/version_test.go, tests/integrations/client/gc_client_test.go, tests/server/cluster/cluster_test.go, tools/pd-ctl/pdctl/ctl.go
Issue Number: ref #4679
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> *: remove stale todos

.github/workflows/check.yaml, .github/workflows/label.yaml, .github/workflows/pd-docker-image.yaml, .github/workflows/pd-tests.yaml, .github/workflows/tso-consistency-test.yaml, .github/workflows/tso-function-test.yaml, server/server.go, server/tso/allocator_manager.go, server/tso/global_allocator.go, tests/client/client_test.go
Issue Number: Close #9051
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> pkg: fix tso is generated even if the member is not leader (#9056)

server/cluster/cluster.go
Issue Number: Close https://github.com/tikv/pd/issues/9154
```commit-message
syncer: set retained=true to syncRegionRunner
```
Tests
- Unit test
If the pending task exceeds 1 minute, the task will not fail.
```release-note
None.
```
=> syncer: set retained=true to syncRegionRunner

tests/server/api/health_test.go, tests/server/api/log_test.go, tests/server/api/member_test.go, tests/testutil.go
Issue Number: ref #7969 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: refactor the member/log/health api tests

tests/server/api/diagnostic_test.go, tests/server/api/server_test.go, tests/server/api/service_gc_safepoint_test.go, tests/server/api/service_middleware_test.go, tests/server/api/testutil.go
Issue Number: ref #7969.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: refactor gc/middleware/server/diag api tests

tests/server/api/etcd_api_test.go, tests/server/api/hot_status_test.go
Issue Number: ref #7969 
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: refactor hot/etcd api tests

server/api/store_test.go, tests/server/api/store_test.go
Issue Number: ref #7969.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: refactor store api tests

pkg/storage/endpoint/tso.go
Issue Number: ref #9157.
```commit-message
Change the timestamp save log level from Info to Debug to prevent excessive logging.
```
Tests
- Unit test
```release-note
None.
```
=> fix(storage): change timestamp save log level from Info to Debug

pkg/statistics/store_collection_test.go, pkg/statistics/store_hot_peers_infos.go
Issue Number: Close https://github.com/tikv/pd/issues/9270
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects …
=> hot_region: assign `historyLoads` to `LoadPred.Current`

server/cluster/cluster_test.go, tests/server/api/store_test.go
Issue Number: Close #9295
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: make TestStoreDelete and TestConcurrentStoreStats stable

pkg/keyspace/keyspace.go, pkg/keyspace/keyspace_test.go, server/apiv2/handlers/keyspace.go, tests/server/apiv2/handlers/keyspace_test.go
Issue Number: ref #9318
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> keyspace: allow `CreateKeyspaceByID` supporting name param

client/clients/tso/client.go, client/clients/tso/dispatcher.go, client/http/client.go, client/servicediscovery/service_discovery.go, pkg/syncer/client.go, pkg/utils/apiutil/apiutil.go, pkg/utils/etcdutil/etcdutil.go, pkg/utils/tsoutil/tso_dispatcher.go
Issue Number: Close #9370
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
=> log: degrade unless error log

client/http/types.go, pkg/mcs/utils/util.go, pkg/versioninfo/kerneltype/classic.go, pkg/versioninfo/kerneltype/doc.go, pkg/versioninfo/kerneltype/nextgen.go, pkg/versioninfo/versioninfo.go, server/api/status.go, tests/integrations/client/http_client_test.go, tests/integrations/mcs/scheduling/api_test.go, tests/integrations/mcs/tso/api_test.go, tests/server/api/status_test.go
Issue Number: ref #9350
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> api: support kernel type in status api

pkg/tso/tso.go
Issue Number: ref #8281.
```commit-message
Move the `jetLag` calculation before setting the physical gap gauge, ensuring more accurate monitoring data.
```
Tests
- Unit test
```release-note
None.
```
=> feat(tso): optimize jetlag metrics calculation sequence

pkg/mcs/resourcemanager/server/keyspace_manager.go, pkg/mcs/resourcemanager/server/keyspace_manager_test.go, pkg/mcs/resourcemanager/server/manager.go, pkg/mcs/resourcemanager/server/manager_test.go, pkg/mcs/resourcemanager/server/metrics.go
```commit-message
Using a global map during local integration tests may cause potential data races.
This PR replaces the global map with an embedded collection to prevent this issue.
```
Tests
- Unit test
```release-note
None.
```
=> metrics(resourcemanager): use an embedded metrics collection

client/metrics/metrics.go, client/resource_group/controller/controller.go, client/resource_group/controller/limiter.go, client/resource_group/controller/metrics/metrics.go
Issue Number: Close #9387 
```commit-message
```
Tests
- Unit test
Manually verify the resource group metrics have const labels set.
- No code
Code changes
Side effects
- Need to cherry-pick …
=> client: add const labels for resource group metrics

tests/server/api/store_test.go
Issue Number: Close #9362
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: fix `TestStoreDelete`

tools/pd-ctl/pdctl/command/label_command.go, tools/pd-ctl/pdctl/command/region_command.go
Issue Number: Close #9385
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
=> ctl: refactor by url values

pkg/schedule/schedulers/evict_slow_store.go, pkg/schedule/schedulers/metrics.go
Issue Number: Close #9391
```commit-message
```
Tests
- Unit test
- Manual test
```release-note
None.
```
=> metrics: record evict store status which is slow

client/client.go
Issue Number: ref #9458.
```commit-message
```
Tests
```release-note
None.
```
=> client: don't record metrics if no retry

pkg/schedule/schedulers/balance_range.go, pkg/schedule/schedulers/balance_range_test.go, pkg/utils/apiutil/apiutil.go, pkg/utils/keyutil/keyrange.go, server/api/scheduler.go, tests/integrations/client/client_test.go
Issue Number: Close #9473
```commit-message
1. Unified the way to decode the http key range from tidb 
2. Add move limit
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> scheduler: unified the decode function

go.mod, go.sum, server/cluster/cluster.go, server/cluster/cluster_test.go, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum, tools/pd-api-bench/go.mod, tools/pd-api-bench/go.sum
This is a manual cherry-pick of https://github.com/tikv/pd/pull/8991
Issue Number: Close https://github.com/tikv/pd/issues/9001, Ref https://github.com/tikv/tikv/issues/18107, Ref https://github.com/tikv/tikv/issues/18042
This PR mainly contains the cooperative works on mitigating the performance impacts when scaling.
```commit-message
In this PR, it returns the `NodeState` in `StoreHeartbeatResponse` to store nodes,
to notify the corresponsive store to handle it if necessary.
```
Tests
- Unit test
- No code
Code changes
- Has HTTP API interfaces changed (Don't forget to [add the declarative for the new API](https://github.com/tikv/pd/blob/master/docs/development.md#updating-api-documentat …
=> [CP-to-7.5] cluster: return NodeState in the response of StoreHeartbeat. (#8991)

client/http/types.go
Issue Number: ref #7300
TiDB does have these fields, see https://github.com/pingcap/tidb/blob/2c714c30f182da94f0fd61b4fdfda6f73a2e0d5d/pkg/store/pdtypes/api.go#L86-L87
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> client: add keys statistic back

go.mod, go.sum, server/cluster/cluster.go, server/cluster/cluster_test.go, tests/integrations/go.mod, tests/integrations/go.sum, tools/go.mod, tools/go.sum
This is a manual cherry-pick of https://github.com/tikv/pd/pull/8991
Issue Number: Close https://github.com/tikv/pd/issues/9001, Ref https://github.com/tikv/tikv/issues/18107, Ref https://github.com/tikv/tikv/issues/18042
This PR mainly contains the cooperative works on mitigating the performance impacts when scaling.
In this PR, it returns the NodeState in StoreHeartbeatResponse to store nodes,
to notify the corresponsive store to handle it if necessary.
```commit-message
In this PR, it returns the `NodeState` in `StoreHeartbeatResponse` to store nodes,
to notify the corresponsive store to handle it if necessary.
```
Tests
- Unit test
- No code
Code changes
- Has HTTP API interfaces …
=> [cp-to-8.5] cluster: return NodeState in the response of StoreHeartbeat. (#8991)

metrics/alertmanager/pd.rules.yml
Issue Number: ref #9548
```commit-message
```
Tests
- No code
```release-note
None.
```
=> *: remove a stale alert

go.mod, go.sum, pkg/utils/apiutil/serverapi/middleware.go, server/api/middleware.go, server/api/server.go, server/util.go, tests/integrations/go.mod, tests/integrations/go.sum, tools/go.mod, tools/go.sum
Issue Number: close #9556.
```commit-message
Update the third-party dependencies to address vulnerabilities.
```
Tests
- Unit test
```release-note
None.
```
=> deps(master): update to fix the vulnerabilities

tests/cluster.go, tests/server/api/admin_test.go, tests/server/cluster/cluster_test.go, tools/pd-ctl/tests/keyspace/keyspace_group_test.go
Issue Number: Close #9363 #9316
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> test: make TestSplitKeyspaceGroup and TestMergeKeyspaceGroup stable

.golangci.yml, go.mod, go.sum, pkg/response/region.go, pkg/response/region_easyjson.go, server/cluster/cluster.go, tests/integrations/go.mod, tests/integrations/go.sum, tests/server/api/region_test.go, tools/go.mod, tools/go.sum
Issue Number: Close #9557
```commit-message
```
Tests
- Unit test
Code changes
Side effects
```release-note
None.
```
=> api: fix some wrong metrics and add bucket version

pkg/mcs/tso/server/server.go, tests/integrations/mcs/tso/keyspace_group_manager_test.go, tests/integrations/mcs/tso/server_test.go, tests/integrations/tso/client_test.go, tests/tso_cluster.go
Issue Number: close #9501.
```commit-message
This PR requires specifying the keyspace group ID when checking the keyspace's primary server,
preventing duplicate keyspace IDs across multiple keyspace groups from disrupting the tests.
```
Tests
- Unit test
```release-note
None.
```
=> test: stablize the mcs TSO integration tests

pkg/keyspace/tso_keyspace_group.go, pkg/keyspace/tso_keyspace_group_test.go
Issue Number: Close #9579.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> mcs: fix primary parse

pkg/schedule/checker/rule_checker.go, pkg/schedule/checker/rule_checker_test.go
Issue Number: ref #9440.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> checker: skip store which does not meet the constraint

pkg/mcs/resourcemanager/server/grpc_service.go, pkg/mcs/resourcemanager/server/keyspace_manager.go, pkg/mcs/resourcemanager/server/keyspace_manager_test.go, pkg/mcs/resourcemanager/server/resource_group.go, pkg/mcs/resourcemanager/server/token_buckets.go, pkg/mcs/resourcemanager/server/token_buckets_test.go, tests/integrations/mcs/resourcemanager/api_test.go, tests/integrations/mcs/resourcemanager/resource_manager_test.go, tests/integrations/mcs/resourcemanager/service_limit_test.go
```commit-message
Add integration tests for the service limit.
```
Tests
- Unit test
```release-note
None.
```
=> test(resourcemanager): add service limit integration tests

pkg/mcs/resourcemanager/server/resource_group.go, pkg/mcs/resourcemanager/server/resource_group_test.go, pkg/mcs/resourcemanager/server/token_buckets.go, pkg/mcs/resourcemanager/server/token_buckets_test.go
Issue Number: ref #9455.
```commit-message
Add safeguard checks and warnings during token assignment to handle potential invalid token values.
```
Tests
- Unit test
```release-note
None.
```
=> fix(resourcemanager): add validation for token assignment anomaly

pkg/mcs/resourcemanager/server/resource_group.go, pkg/mcs/resourcemanager/server/token_buckets.go
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> resource group: rename some variables

server/cluster/cluster.go, tests/integrations/client/http_client_test.go
…nce test coverage for store labels and leader transfer
Issue Number: Close https://github.com/tikv/pd/issues/9602
```commit-message
```
Tests
- Unit test
```release-note
Fix the bug that placement rule may disappear after PD transfer leader
```
=> placement-rule: move placement rule initialization after LoadStores

pkg/storage/storage.go, server/apiv2/handlers/ready.go, tests/server/apiv2/handlers/ready_test.go
Issue Number: Close #9576
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> api: distinguish bootstrap state in ready api

pkg/core/store.go, pkg/core/store_test.go
Issue Number: Close #9640.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> core: fix tiflash engine label

pkg/storage/storage.go, server/apiv2/handlers/ready.go, tests/server/apiv2/handlers/ready_test.go
close tikv/pd#9576
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
=> api: distinguish bootstrap state in ready api (#9632)

pkg/utils/grpcutil/grpcutil_test.go
Issue Number: Close #9549, close #9428
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: fix `TestToServerTLSConfig` and `TestToClientTLSConfig`

go.mod, go.sum, tests/integrations/client/go.mod, tests/integrations/client/go.sum, tests/integrations/mcs/go.mod, tests/integrations/mcs/go.sum, tests/integrations/tso/go.mod, tests/integrations/tso/go.sum
Issue Number: ref #9556.
```commit-message
Update the third-party dependencies to address vulnerabilities.
```
Tests
- Unit test
```release-note
None.
```
=> deps(release-7.5): update to fix the vulnerabilities

pkg/mcs/resourcemanager/server/manager.go, pkg/mcs/resourcemanager/server/metrics.go, pkg/mcs/resourcemanager/server/service_limit.go, pkg/mcs/resourcemanager/server/service_limit_test.go
Issue Number: Close #9651
- Fix the bug that ru tokens is not limit when service limiter's available tokens is 0
- Add a gauge metrics for service limit
- Also track some extended metrics for the default resource group.
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
- PR to update [`pingcap/docs`](https://github.com/pingcap/docs)/[`pingcap/docs-cn`] …
=> resource_manager; fix the bug that ru tokens is not limit when available service limit is 0

errors.toml, pkg/core/store.go, pkg/core/store_option.go, pkg/errs/errno.go, server/cluster/cluster_test.go
Issue Number: Close https://github.com/tikv/pd/issues/9673
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> store: refactor leader transfer pause logic to use atomic operations

pkg/response/store.go, tools/pd-ctl/tests/scheduler/scheduler_test.go
Issue Number: Close #9682
```commit-message
```
Tests
- Unit test
- No code
Code changes
Side effects
```release-note
None.
```
=> api: show store pause status

metrics/alertmanager/pd.rules.yml, metrics/grafana/pd.json
Issue Number: Close #9686
```commit-message
```
Tests
new panel when enabled hide
Code changes
Side effects
```release-note
None.
```
=> metrics: add etcd storage alert

tools/pd-ctl/tests/scheduler/scheduler_test.go
If necessary, can continue to investigate based on the [logs](https://github.com/tikv/pd/issues/9667#issuecomment-3219210379). I think we can disable this test for now.
Issue Number: Close https://github.com/tikv/pd/issues/9667
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> test: disable TestSchedulerDiagnostic in ms

pkg/syncer/history_buffer.go, pkg/syncer/server.go
Issue Number: ref #9154
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> syncer: fix lock usage

pkg/schedule/schedulers/evict_slow_store.go, pkg/schedule/schedulers/evict_slow_store_test.go, tools/pd-ctl/pdctl/command/scheduler_command.go, tools/pd-ctl/tests/scheduler/scheduler_test.go
Issue Number: Ref https://github.com/tikv/pd/issues/9359, Close https://github.com/tikv/pd/issues/9703
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> slow-store: support changing config and add related test

metrics/grafana/pd.json, pkg/schedule/operator/metrics.go, pkg/schedule/operator/operator_controller.go, pkg/schedule/schedulers/balance_range.go, pkg/schedule/schedulers/balance_region.go, pkg/schedule/schedulers/hot_region_solver.go, pkg/schedule/schedulers/metrics.go, pkg/statistics/hot_cache.go, pkg/statistics/metrics.go, pkg/tso/allocator.go, pkg/tso/metrics.go, tests/integrations/tso/consistency_test.go, tests/integrations/tso/server_test.go, tests/server/cluster/cluster_test.go, tests/server/tso/tso_proxy_test.go, tests/server/tso/tso_test.go
Issue Number: ref #9357
This PR makes the following changes:
- Remove some unnecessary metrics
- Remove some useless monitors
- Remove dc field for TSO
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> metrics: clean up metrics

metrics/grafana/pd.json
Issue Number: ref #7730 
```commit-message
```
Tests
- Manual test
Before
After 
```release-note
None.
```
=> fix duplicated panel id

pkg/utils/etcdutil/testutil.go
Issue Number: ref #7969.
```commit-message
```
Tests
- Unit test
```release-note
None.
```
=> tests: support customizing log in tests

Makefile
Issue Number: ref #9350
```commit-message
```
Tests
- Manual test 
```
GOEXPERIMENT= CGO_ENABLED=1 go build  -gcflags '' -ldflags '-X "github.com/tikv/pd/pkg/versioninfo.PDReleaseVersion=v9.0.0-beta.2.pre-125-g0c8451256" -X "github.com/tikv/pd/pkg/versioninfo.PDBuildTS=2025-09-25 06:42:40" -X "github.com/tikv/pd/pkg/versioninfo.PDGitHash=0c8451256455522c9bc39b3d9215335b02d45b53" -X "github.com/tikv/pd/pkg/versioninfo.PDGitBranch=disable-dashboard-nextgen" -X "github.com/tikv/pd/pkg/versioninfo.PDEdition=Community" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.InternalVersion=9.0.0-e1f8338b" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.Standalone=No" -X "github.com/pingcap/tidb-dashboard/pkg/utils/version.PDVersion=v9.0.0-beta.2.pre-125-g0c8451256" -X …
```
=> *: disable dashboard by default in nextgen

go.mod, go.sum, pkg/mcs/scheduling/server/cluster.go, pkg/mcs/scheduling/server/grpc_service.go, pkg/mcs/scheduling/server/metrics.go, server/cluster/cluster.go, server/cluster/cluster_test.go, server/cluster/cluster_worker.go, server/forward.go, server/grpc_service.go, tests/cluster.go, tests/integrations/go.mod, tests/integrations/go.sum, tests/integrations/mcs/scheduling/server_test.go, tests/testutil.go, tools/go.mod, tools/go.sum
```commit-message
```
Tests
- Unit test
- Manual test
```release-note
None.
```
=> mcs: support bucket for scheduling service
