tikv/pd

- server/command.go
- server/conn.go
- server/id.go
- server/id_test.go
- server/leader.go
- server/server.go
- server/tso.go
- server/tso_test.go
- server/util.go
> support alloc id 

- Makefile
- server/config.go
- server/id.go
- server/leader.go
- server/server.go
- server/server_test.go
> *: add makefile and make check happy.

- protopb/errors.go
- server/cluster.go
- server/cluster_test.go
- server/command.go
- server/config.go
- server/conn.go
- server/id.go
- server/server.go
> *: support bootstrap cluster.

- server/cluster.go
- server/cluster_test.go
- server/command.go
- server/conn.go
- server/leader.go
- server/util.go
> server: support command get meta.

- server/cluster.go
- server/cluster_test.go
- server/command.go
- server/conn.go
> server: support put meta.

- server/conn.go
- server/rpc.go
- server/rpc_test.go
- server/tso_test.go
> extract RPC message codec.

- server/cluster.go
- server/cluster_test.go
- server/leader.go
- server/server.go
> server: cache nodes/stores when cluster starts.

- server/cluster.go
- server/cluster_test.go
- server/command.go
> server: get/put cluster meta

- server/cluster_worker_test.go
> simulate raft leader and transport. 

- server/cluster.go
- server/cluster_test.go
- server/cluster_worker.go
- server/cluster_worker_test.go
- server/config.go
+ support leader redirect if send a none leader peer.
+ retry send command if failed.
@ngaut @disksing
> *: support leader redirect, and command retry.

- pd-client/client.go
- pd-client/rpc_worker.go
- server/cluster_worker_test.go
- server/tso_test.go
- util/rpc.go
> *: fix compile error.

- server/cluster_test.go
- server/cluster_worker.go
- server/cluster_worker_test.go
> server: support region epoch.

- pd-client/client_test.go
- server/leader.go
- server/server_test.go
To fit newest etcd. 
@ngaut  @disksing
> *: update with newest etc.

- pd-client/client.go
- server/cluster_worker.go
- server/leader.go
- server/server_test.go
- server/tso_test.go
> server: tiny update and speed up test.

- server/cluster.go
- server/cluster_worker.go
- server/id.go
- server/leader.go
- server/tso.go
> server: use timeout context instead of TODO for txn.

- .gitignore
- Makefile
- pd-client/client.go
- pd-client/client_test.go
- pd-server/main.go
> tiny update

- server/cluster_worker.go
- server/cluster_worker_test.go
> server: fix compile error.

- server/cluster.go
- server/cluster_worker.go
- server/id.go
- server/leader.go
> server: use newest etcd.

- Dockerfile
- README.md
- start.sh
> support docker.

- server/cluster_worker.go
> server: check finished Ok first when job is retried.

- server/cluster_worker_test.go
@ngaut @qiuyesuifeng 
Fix for https://github.com/pingcap/kvproto/pull/24
>  server: update error.

- pd-client/rpc_worker.go
- server/cluster_worker.go
- server/command.go
> *: add tso requests check and tiny clean up.

- server/cluster.go
- server/cluster_worker.go
- server/util.go
> server: support split transaction retry.

- server/cluster_worker.go
- server/cluster_worker_test.go
- server/node_conn.go
> fix node conns test

- server/tso_test.go
> server: fix get timestamp test check.

- server/cluster_worker_test.go
- server/server_test.go
> server: use context.Background instead of context.TODO in test.

- server/cluster_test.go
- server/id_test.go
> server: tiny clean up.

- server/cluster_worker.go
- server/cluster_worker_test.go
> server: use msgpb instead.

- pd-client/client.go
> client: watch etcd with revision

- pd-server/main.go
- server/config.go
- server/leader.go
- server/server.go
- server/server_test.go
> *: introduce advertise addr.

- Dockerfile
- docker/start_pd.sh
> *: tiny update docker.

- server/cluster.go
- server/cluster_worker_test.go
- server/command.go
PTAL @siddontang @qiuyesuifeng
> cluster: Remove unnecessary leader check.

- run_cluster.sh
Try to fix #65 
@ngaut @qiuyesuifeng
> use user defined network

- server/cluster.go
- server/command.go
> server: use golang protobuf.

- server/leader.go
> server: fix etcd.

- pd-server/main.go
> pd-server: support pprof

- Dockerfile
> fix docker compile

- pd-client/client.go
If we start the cluster quickly at same time, tidb will crash because it can't get pd leader. 
We should retry to get it. 
@qiuyesuifeng @disksing
> pd-client: retry to get pd leader.

- cmd/pd-server/main.go
- server/cluster.go
- server/config.go
@ngaut @qiuyesuifeng @disksing
> *: add config and flag for max peer number.

- .travis.yml
@siddontang @tiancaiamao  PTAL
> travis: add sleep 1s to wait etcd startup.

- Makefile
- cmd/Godeps/Godeps.json
> *: add update kvproto in makefile.

- server/cluster_worker_test.go
> cluster_worker test: check id -> searchKey on etcd.

- cmd/pd-server/main.go
- pd-client/client.go
- pd-client/client_test.go
- pd-client/leader_change_test.go
- pd-client/rpc_worker.go
- server/cache.go
- server/cache_test.go
- server/cluster.go
- server/cluster_test.go
- server/cluster_worker.go
- server/cluster_worker_test.go
- server/command.go
- server/config.go
- server/conn.go
- server/errors.go
- server/id.go
- server/id_test.go
- server/leader.go
- server/server.go
- server/server_test.go
- server/store_conn.go
- server/store_conn_test.go
- server/tso.go
- server/tso_test.go
- server/util.go
@ngaut @qiuyesuifeng @disksing
> *: add license

- server/leader.go
This can only occur when we meet error with Etcd, and it is hard to write test now. 
I will do some abstraction and let test with etcd easily. 
@qiuyesuifeng @disksing
> server: resign leader if leader not changed.

- server/cluster.go
- server/id.go
- server/leader.go
- server/server.go
- server/tso.go
- server/util.go
> server: log slow etcd operations.

- server/balancer.go
- server/balancer_worker.go
- server/cluster_worker.go
- server/operator.go
> server: combine default balancer and others.

- server/util.go
> server: add more log.

- cmd/pd-server/main.go
- server/balancer.go
- server/balancer_test.go
- server/balancer_worker_test.go
- server/cluster.go
- server/config.go
> *: config capacity used ratio.

- server/balancer_worker.go
- server/cache.go
- server/cluster.go
> server: add balance metrics and slow log.

- server/balancer.go
- server/balancer_test.go
- server/balancer_worker.go
- server/balancer_worker_test.go
- server/cache.go
- server/cache_test.go
- server/cluster.go
- server/cluster_worker.go
- server/cluster_worker_test.go
- server/command.go
- server/conn.go
- server/errors.go
- server/expire_cache.go
- server/expire_cache_test.go
- server/leader.go
- server/operator.go
- server/server.go
- server/server_test.go
- server/tso_test.go
> Tiny clean up.

- server/cache.go
> server: update error return.

- cmd/pd-server/main.go
- server/cluster.go
- server/cluster_worker.go
- server/config.go
> *: cleanup.

- .travis.yml
@qiuyesuifeng @shenli @disksing
> travis: use etcd v3.

- .gitignore
- docker/etcd_dockerfile
> docker: upgrade etcd version to v3 in dockerfile

- _vendor/Godeps/Godeps.json
- _vendor/vendor/github.com/gorilla/websocket/.gitignore
- _vendor/vendor/github.com/gorilla/websocket/.travis.yml
- _vendor/vendor/github.com/gorilla/websocket/AUTHORS
- _vendor/vendor/github.com/gorilla/websocket/LICENSE
- _vendor/vendor/github.com/gorilla/websocket/README.md
- _vendor/vendor/github.com/gorilla/websocket/client.go
- _vendor/vendor/github.com/gorilla/websocket/conn.go
- _vendor/vendor/github.com/gorilla/websocket/conn_read.go
- _vendor/vendor/github.com/gorilla/websocket/conn_read_legacy.go
- _vendor/vendor/github.com/gorilla/websocket/doc.go
- _vendor/vendor/github.com/gorilla/websocket/json.go
- _vendor/vendor/github.com/gorilla/websocket/server.go
- _vendor/vendor/github.com/gorilla/websocket/util.go
> vendor: add missed godeps.

- pd-client/client.go
> client: using buffered channel for better concurrency

- pd-client/client.go
- pd-client/client_test.go
> client: update client GetRegion.

- Dockerfile
> change the web UI path, so it can be accessd in docker

- README.md
- cmd/pd-server/main.go
- conf/config.toml
- doc/clustering.md
- pd-client/client_test.go
- pd-client/leader_change_test.go
- server/cache_test.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/conn.go
- server/id_test.go
- server/server.go
- server/server_test.go
- server/tso_test.go
@ngaut @c4pt0r @qiuyesuifeng @shenli 
@queenypingcap  please check the doc.
> *: clean up flags.

- pd-client/client.go
- pd-client/client_test.go
- pd-client/leader_change_test.go
- server/cache_test.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/id_test.go
- server/server.go
- server/server_test.go
- server/tso_test.go
> *: remove root path flag

- server/config.go
> server: fix typo

- README.md
- cmd/pd-server/main.go
- conf/config.toml
- server/config.go
- server/server.go
@qiuyesuifeng @iamxy @shenli @huachaohuang
> *: re-use urls instead of host + port again.

- Makefile
- README.md
@siddontang @shenli @huachaohuang PTAL
> Makefile: add make dev option.

- Makefile
@qiuyesuifeng @shenli @disksing  @huachaohuang
> Makefile: use default

- Dockerfile
@qiuyesuifeng @siddontang @huachaohuang @iamxy PTAL
> Dockerfile: Update build

- server/join_test.go
- server/server.go
PTAL @siddontang @qiuyesuifeng
> server: tweak join_test

- _vendor/Godeps/Godeps.json
- _vendor/vendor/github.com/unrolled/render/buffer.go
- _vendor/vendor/github.com/unrolled/render/render.go
Fix data race
PTAL @siddontang @qiuyesuifeng @huachaohuang
> _vender: update render

- cmd/pd-server/main.go
- conf/config.toml
- pd-client/client_test.go
- pd-client/leader_change_test.go
- pd-client/rpc_worker.go
- server/api/router.go
- server/cache_test.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/conn.go
- server/id_test.go
- server/leader.go
- server/server.go
- server/server_test.go
- server/tso_test.go
- server/util.go
Remove addr and advertise-addr.
> Embed RPC port to etcd.

- cmd/pd-server/main.go
- conf/config.toml
- pd-client/client_test.go
- pd-client/leader_change_test.go
- pd-client/rpc_worker.go
- server/api/member_test.go
- server/api/router.go
- server/api/server.go
- server/cache_test.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/conn.go
- server/id_test.go
- server/leader.go
- server/server.go
- server/server_test.go
- server/tso_test.go
- server/util.go
> Embed API port to etcd

- Dockerfile
> docker: remove expose port in Dockerfile.

- conf/config.toml
- server/balancer.go
- server/cache.go
- server/server.go
> balancer: do some cleanup.

- pd-client/client.go
@siddontang  @disksing  @iamxy  PTAL
> pd-client: update pd connect timeout to 30s.

- server/api/member.go
- server/api/member_test.go
- server/api/router.go
- server/leader.go
#237
PTAL
@siddontang @huachaohuang @qiuyesuifeng 
example: 
```json
{
"addr": "http://:12379",
"pid": 9847
}
```
> server: add api leader

- server/config.go
> config: fix default data-dir.

- _vendor/Godeps/Godeps.json
- _vendor/vendor/github.com/ngaut/log/log.go
@qiuyesuifeng @huachaohuang @overvenus
> vendor: update log.

- _vendor/Godeps/Godeps.json
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/LICENSE
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/NOTICE
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/README.md
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/formatters.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/glog_formatter.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init_windows.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/journald_formatter.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/log_hijack.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/logmap.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go
- _vendor/Godeps/_workspace/src/github.com/coreos/pkg/capnslog/syslog_formatter.go
- cmd/pd-server/main.go
- server/config.go
- server/util.go
> *: add log-file flag

- cmd/pd-server/main.go
- server/util.go
> *: force redirect etcd log to stderr

- server/api/member_test.go
- server/api/redirector.go
- server/api/redirector_test.go
- server/api/server.go
- server/api/server_test.go
- server/api/util.go
- server/config.go
- server/conn.go
- server/conn_test.go
- server/join_test.go
- server/leader.go
- server/server_test.go
- server/util.go
Redirect API and RPC requests to leader.
> redirect request to leader.

- server/util.go
Resolved #282 
PTAL @shenli @huachaohuang @siddontang
> server: fix log rotation

- Makefile
- cmd/pd-server/main.go
- server/util.go
> *: add version infomation

- server/cache.go
- server/metrics.go
- random region duration
ref #193
> add some metrics

- Makefile
- pd-client/client_test.go
- pd-client/leader_change_test.go
- server/api/member_test.go
- server/api/server_test.go
- server/cache_test.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/id_test.go
- server/join_test.go
- server/server_test.go
- server/tso_test.go
> *: clean up unix socket

- Makefile
> Makefile: make clean leaves gracefully

- server/server_test.go
Travis-CI can be very slow sometimes, etcd takes more than 10s to sync wal.
> test: increase mustWaitLeader timeout.

- conf/config.toml
- server/config.go
- server/leader.go
- server/server_test.go
- server/tso.go
- server/tso_test.go
> server: save next tso

- server/cluster.go
- server/cluster_test.go
> server: check duplicated store address

- Makefile
Make build easier.
PTAL @huachaohuang @siddontang @qiuyesuifeng
> Makefile: update Makefile

- Makefile
> Makefile: fix illegal option

- server/config.go
- server/join.go
- server/join_test.go
> server: remove join self

- server/server_test.go
Seems there are some problems with our updated etcd, try to fix CI first and investigate it later.
> fix server test.

- Makefile
- pd-client/metrics.go
- pd-client/rpc_worker.go
- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
- server/conn.go
- server/metrics.go
- server/util.go
> add some metrics.

- server/cluster.go
- server/cluster_test.go
> fix closed channel.

- pd-client/leader_change_test.go
- server/conn.go
- server/server_test.go
PTAL @huachaohuang @siddontang @qiuyesuifeng 
Address comment https://github.com/pingcap/pd/pull/311/commits/33e5784113e8024de0da602c5dedf234a02b4a9d#diff-d5666a18e51cbff4c4f482faa6f9f449R191
> *: use built-in etcdclt in tests

- server/balancer_worker.go
- server/cluster.go
- server/metrics.go
Add some metrics to answer these questions:
- How many difference kind of balance operators?
- How many regions in the cluster?
- How many difference state of stores?
- How much data in the cluster?
- How much capacity in the cluster?
- How's the capacity balance in the cluster?
- How's the leader balance in the cluster?
> *: add some cluster metrics

- server/cluster.go
> server/cluster: fix some metrics

- server/balancer.go
- server/balancer_worker.go
1. I never use these logs, even for debug;
2. We have metrics and APIs to retrieve the information.
Reference Issue: #333
> server/balancer: cleanup some logs

- README.md
Add the test coverage icon. 
@qiuyesuifeng @huachaohuang @overvenus
> doc: add test coverage icon.

- .travis.yml
- Makefile
Ref: #345 
Runs coverage in travis with go1.7 only.
> Add coveralls using matrix

- server/util.go
PTAL @siddontang @queenypingcap
> util: remove "the"

- Makefile
- _vendor/vendor/github.com/google/btree/btree.go
- glide.lock
- glide.yaml
> vendor: update google/btree

- server/util.go
`PrintPDInfo()` prints `Welcome to Placement Driver(PD).`.
PTAL @huachaohuang  @siddontang @queenypingcap
> util: Welcome to Placement Driver(PD)

- server/cache.go
- server/cache_test.go
- server/store.go
Add storesInfo and move stores management from clusterInfo to storesInfo.
Base on https://github.com/pingcap/pd/pull/365.
> server/cache: add storesInfo

- conf/config.toml
- pd-client/client_test.go
- pd-client/leader_change_test.go
- server/api/balancer_test.go
- server/cache_test.go
- server/cluster.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/conn.go
- server/conn_test.go
- server/id_test.go
- server/server.go
- server/server_test.go
- server/tso_test.go
- server/util.go
> Revert "server/config: use random cluster id for new cluster"

- conf/config.toml
- pd-client/client_test.go
- pd-client/leader_change_test.go
- server/api/balancer_test.go
- server/cache_test.go
- server/cluster.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/conn.go
- server/conn_test.go
- server/id_test.go
- server/server.go
- server/server_test.go
- server/tso_test.go
- server/util.go
> [DNM] Revert "Revert "server/config: use random cluster id for new cluster""

- server/balancer.go
- server/balancer_test.go
- server/cache.go
- server/cluster.go
> server/cache: hide id allocator

- conf/config.toml
- server/balancer_test.go
- server/balancer_worker_test.go
- server/config.go
- server/filter.go
Check applying snaphost count of a store to avoid heavy io load.
> server/balance: check applying snapshot count

- server/balancer.go
- server/filter.go
Tiny cleanup and remove useless args.
> server/filter: cleanup filter

- server/config.go
Now the heartbeat is 1s and election timeout is 6s. ( 5 * heartbeat > election in etcd )
But we must know that if the PD is down, we will begin the election after 6s later. Is it too long?
Or maybe we can use 500ms and 3s instead? 
@ngaut @qiuyesuifeng @huachaohuang @overvenus
> server: use large heartbeat and election

- server/config.go
> server/config.go: replace "v" with "version"

- cmd/pd-server/main.go
> cmd: exit with 2 if server start failed

- server/util.go
close #408 
cc coreos/etcd#6067
> server: wait longer for etcd initialization

- README.md
- circle.yml
@siddontang @huachaohuang  PTAL
Please add pingcap/pd on https://circleci.com
> ci: Add circleci.yml

- pd-client/rpc_worker.go
TiDB can not start some times if it starts at the same time with PD,
because PD may need some time before serving requests.
> pd-client: add some retries when initializing cluster id

- server/api/store.go
- server/api/store_test.go
PATL @huachaohuang @siddontang 
close #419
> server/api: get stores API supports state argument 

- conf/config.toml
- server/cluster.go
- server/config.go
Don't adjust config when changed dynamically.
> server/config: adjust default leader config

- README.md
> README: adjust CI badges

- pd-client/rpc_worker.go
We should not reuse the same connection when it is in error.
> pd-client: reconnect if get cluster id error

- server/join.go
- server/join_test.go
- server/server.go
- server/server_test.go
- server/util.go
PTAL @huachaohuang @siddontang 
Close #435
> server: update advertise peer urls from etcd

- cmd/pd-ctl/main.go
- pdctl/README.md
- pdctl/command/config_command.go
- pdctl/command/exit_command.go
- pdctl/command/global.go
- pdctl/command/region_command.go
- pdctl/command/store_command.go
- pdctl/ctl.go
PTAL @huachaohuang @siddontang @overvenus
> pdctl: add region and store command

- server/cluster_worker_test.go
- server/coordinator.go
- server/coordinator_test.go
Region cache seems not useful any more.
> server/coordinator: remove region cache

- cmd/pd-server/main.go
- pd-client/leader_change_test.go
- server/api/server_test.go
- server/join_test.go
- server/server.go
> server: closer Server when an error occurs

- cmd/pd-server/main.go
- conf/config.toml
- server/api/config.go
- server/balancer_test.go
- server/cluster.go
- server/cluster_worker_test.go
- server/config.go
- server/replication.go
Do some simple cleanup and move replication related configs to replication section.
> server: cleanup some configs and add replication section

- server/config.go
PTAL @andelf @siddontang @huachaohuang 
```sh
neil:pd/ (v*) $ bin/pd-server --v     
Git Commit Hash: 020eaad1f31f9938df4d7e60adb7224ebc5a7306
UTC Build Time:  2017-01-07 06:37:54
neil:pd/ (v*) $ bin/pd-server -v                          
Git Commit Hash: 020eaad1f31f9938df4d7e60adb7224ebc5a7306
UTC Build Time:  2017-01-07 06:37:54
neil:pd/ (v*) $ bin/pd-server -version      
Git Commit Hash: 020eaad1f31f9938df4d7e60adb7224ebc5a7306
UTC Build Time:  2017-01-07 06:37:54
neil:pd/ (v*) $ bin/pd-server --version               
Git Commit Hash: 020eaad1f31f9938df4d7e60adb7224ebc5a7306
UTC Build Time:  2017-01-07 06:37:54
neil:pd/ (v*) $ bin/pd-server -v -version                    
Git Commit Hash: 020eaad1f31f9938df4d7e60adb7224ebc5a7306
UTC Build Time:  2017-01-07 06:37:54
neil:pd/ (v*) $ …
```
> server/config.go: add flag v for version info

- server/config.go
PTAL @andelf @huachaohuang @siddontang
> server/config.go: change flag v to V

- pdctl/command/global.go
- pdctl/command/region_command.go
- pdctl/ctl.go
PTAL @huachaohuang @siddontang @overvenus
> pdctl: get region with key

- Makefile
Address comment https://github.com/pingcap/pd/pull/469#issuecomment-274400548 .
> Makefile: ignore folder cmd and pdctl

- pkg/etcdutil/etcdutil.go
- pkg/etcdutil/etcdutil_test.go
- pkg/testutil/testutil.go
- server/api/member.go
- server/config.go
- server/join.go
- server/join_test.go
- server/server.go
- server/server_test.go
- server/util.go
This PR moves some etcd helper functions to package etcdutil and speeds up tests.
> *: move some etcd helper functions to package etcdutil

- _vendor/vendor/github.com/ngaut/systimemon/LICENSE
- _vendor/vendor/github.com/ngaut/systimemon/systime_mon.go
- glide.lock
- glide.yaml
- server/metrics.go
- server/server.go
> server: add time monitor and a corresponding metric

- server/coordinator_test.go
We need to separate the balance tests and replica tests so that they will not
screw up each other occasionally.
> server/coordinator: fix some tests

- server/api/scheduler.go
- server/balancer.go
- server/cache.go
- server/cache_test.go
- server/coordinator.go
- server/coordinator_test.go
- server/filter.go
- server/handler.go
- server/scheduler.go
- server/selector.go
- server/store.go
Add "evict-leader-scheduler" to transfer leader out of some stores.
We need to mark those stores as blocked, otherwise the balance-leader-scheduler
will be disturbed.
> server: add evict-leader-scheduler

- server/api/home.go
- server/api/label.go
- server/api/label_test.go
- server/api/router.go
for https://github.com/pingcap/pd/issues/505
PTAL @siddontang @andelf @huachaohuang
> server/api: add label api

- pdctl/command/config_command.go
- pdctl/command/global.go
- pdctl/command/member_command.go
- pdctl/command/region_command.go
- pdctl/command/store_command.go
PTAL @huachaohuang @siddontang @overvenus
> pdctl: extract api request

- cmd/pd-ctl/main.go
PTAL @siddontang @huachaohuang @overvenus
> pdctl: fix pipeline input

- pdctl/command/label_command.go
- pdctl/ctl.go
close https://github.com/pingcap/pd/issues/505
PTAL   @huachaohuang @siddontang @overvenus
> pdctl: add label command

- server/api/scheduler.go
- server/handler.go
- server/scheduler.go
Add a scheduler to random add/remove region peers, for test.
> server: add shuffle-region-scheduler

- pdctl/command/ping_command.go
- pdctl/ctl.go
close https://github.com/pingcap/pd/issues/524
> pdctl: add ping

- pkg/metricutil/metricutil.go
- pkg/metricutil/metricutil_test.go
This fixes #516 .
Also adds some more test cases.
> pkg/metricutil: fix #516 bad GetCmdLabel() implementation 

- Makefile
disable cgo when build release binary
PTAL @disksing @siddontang
> disable cgo

- pdctl/command/tso_command.go
- pdctl/ctl.go
> pdctl: add tso command

- _vendor/vendor/vendor
- server/config.go
- server/replication.go
> server: fix data race

- pd-client/client.go
- pd-client/client_test.go
- pd-client/rpc_worker.go
> pd-client: get region by id

- server/config.go
- server/replication.go
> server: fix data race for atomic load

- server/cache.go
- server/cache_test.go
- server/cluster.go
- server/command.go
> *: add logs and minor changes.

- Makefile
- server/cache.go
- server/operator.go
- server/region.go
- server/region_test.go
- server/util.go
close https://github.com/pingcap/pd/issues/546
PTAL @siddontang @disksing
> server: pretty region log

- server/config.go
PTAL @siddontang @overvenus @disksing
> server: adjust default leader schedule limit

- server/balancer_test.go
- server/cache.go
- server/cache_test.go
- server/cluster.go
- server/cluster_worker_test.go
- server/filter.go
- server/store.go
Fix #563 
Using `new(StoreStatus)` causes the inner filed unset.
> server: fix panic after delete store.

- server/cache.go
- server/cache_test.go
The old way relies on the randomness of map iteration, which is not guaranteed always works correctly.
cc @siddontang @nolouch @overvenus
> cache: random pick region from cache.

- pd-client/leader_change_test.go
- server/cluster.go
- server/leader.go
- server/tso.go
> tso: fix possible stale ts when leader changes twice.

- server/cluster.go
> server: add offline log

- pd-client/leader_change_test.go
- pkg/typeutil/string_slice.go
- pkg/typeutil/string_slice_test.go
- server/api/config.go
- server/api/config_test.go
- server/api/router.go
- server/cluster.go
- server/config.go
> server/api: omit empty field

- server/cache.go
- server/cache_test.go
> cache: clean up pending peers.

- server/balancer_test.go
- server/filter.go
- server/store.go
Fix #587
/cc @andelf @nolouch @zhangjinpeng1987
> server: tikv reports usedSize.

- cmd/pd-tso-bench/main.go
> pd-tso-bench: remove unused flag

- cmd/pd-tso-bench/main.go
- pd-client/client.go
- server/leader.go
> *: goroutines use individual context

- pd-client/client.go
In tso bench, we found that the request done chan allocation costs much time, it is better to use a pool to reduce the GC pressure. 
@coocood @disksing @nolouch
> pd-client: use sync pool for tso request

- server/id.go
- server/server.go
- server/tso.go
> server: add tso, cluster id, alloc id logs

- server/api/server.go
> server.go: fix errors package path

- Makefile
> remove needless building label.

- pdctl/command/global.go
- pdctl/command/hot_command.go
- pdctl/ctl.go
PTAL @disksing @siddontang @andelf
> pdctl: add hotspot command

- server/api/store.go
- server/api/store_test.go
- server/store.go
quickly reflect store down in store API.
PTAL @siddontang @disksing
> server/api: show store down 

- server/server.go
Should dial etcd with advertised address.
cc @siddontang @andelf @nolouch
> server: fix dial addr bug.

- pdctl/command/cluster_command.go
- pdctl/ctl.go
> pdctl: add cluster command

- server/balancer.go
- server/cluster.go
- server/coordinator.go
- server/metrics.go
> balance: add some metrics

- Makefile
> makefile: Enable -race with WITH_RACE=1

- pd-client/client_test.go
- server/api/server_test.go
- server/cluster_worker_test.go
- server/config.go
- server/grpc_service.go
Do the hack in tests, not on the server.
> test: update heartbeat tests.

- server/cluster_worker.go
- server/cluster_worker_test.go
left and right are swapped on tikv.
cc @nolouch @siddontang @overvenus
> fix wrong split history.

- server/balancer.go
- server/balancer_test.go
- server/scheduler.go
Cherrypick of #671 on rc3. /cc @nolouch  @siddontang @overvenus
> balance: avoid remove leader peer.

- pkg/logutil/log.go
- pkg/logutil/log_test.go
- server/coordinator.go
cc @andelf @nolouch @overvenus
> *: update logs.

- server/metrics.go
- server/tso.go
> tso: add metrics.

- circle.yml
ref: https://github.com/pingcap/tidb/pull/3850
> ci: update circleci to v2

- server/cluster_worker_test.go
- server/coordinator_test.go
- server/kv.go
Fix https://github.com/pingcap/tidb/issues/3668
cc @huachaohuang @nolouch @siddontang
> server cache: decrease load limit to 10,000.

- server/join.go
simple move logic to outer loop
> enhance pd join function

- pdctl/README.md
- pdctl/command/cluster_command.go
- pdctl/command/config_command.go
- pdctl/command/hot_command.go
- pdctl/command/label_command.go
- pdctl/command/member_command.go
- pdctl/command/region_command.go
- pdctl/command/store_command.go
- pdctl/command/tso_command.go
- server/api/member.go
- server/api/member_test.go
- server/api/router.go
related issue: https://github.com/pingcap/pd/issues/694
> api: support delete member by id.

- Jenkinsfile
> jenkins: update Jenkinsfile to use rc4 branch for CI

- Jenkinsfile
> jenkins:update Jenkinsfile to use rc3 branch for CI

- server/balancer.go
- server/metrics.go
- server/scheduler.go
For letting us know why a cluster is not well balanced.
> balancer: add metrics.

- server/balancer.go
- server/metrics.go
- server/scheduler.go
> scheduler: add metrics.

- Makefile
- cmd/pd-ctl/main.go
- server/util.go
also, add -V support for pd-ctl.
> *: add git branch name in tidb_version and starting log.

- pdctl/command/member_command.go
- server/api/member.go
- server/api/member_test.go
- server/api/router.go
- server/cluster_worker_test.go
- server/leader.go
- server/server.go
HTTP API:
```
$ curl -X POST http://127.0.0.1:2379/pd/api/v1/leader/resign
$ curl -X POST http://127.0.0.1:2379/pd/api/v1/leader/transfer/pd2
```
pd-ctl:
```
> member leader resign
> member leader transfer pd2
```
> support resign leader.

- cmd/pd-server/main.go
- pd-client/client_test.go
- pd-client/leader_change_test.go
- server/api/server_test.go
- server/cluster_test.go
- server/cluster_worker_test.go
- server/config.go
- server/id_test.go
- server/join_test.go
- server/leader.go
- server/leader_test.go
- server/server.go
- server/server_test.go
- server/testutil.go
- server/tso_test.go
Change 3 phase startup process `create/new, runEtcd, runServer` to 2 phase `create, run`.
> server: reorganize server start up.

- server/cache.go
- server/core/store.go
- server/leader.go
- server/util.go
should use time.Since instead of time.Now().Sub
> should use time.Since instead of time.Now().Sub

- server/namespace/classifer.go
PTAL @LiangShang @ming-relax @nolouch
> namespace: add Classifier interface.

- server/schedule/operator.go
- server/schedule/operator_test.go
PTAL @siddontang @disksing @huachaohuang
> schedule/operator: fix operator timeout

- server/cluster.go
cherry pick https://github.com/pingcap/pd/pull/758
> server: fix a bug that may set not empty store to tombstone state.

- server/cache.go
- server/coordinator.go
we need higher flow rate for read, the noise is more likely to occur.
> *: tune up the read min flow rate

- pd-client/client.go
- pd-client/leader_change_test.go
Fix https://github.com/pingcap/pd/issues/494
> client: update client urls.

- server/grpc_service.go
- server/heartbeat_streams.go
- server/metrics.go
1. Record store id.
2. Increase counter after receive message.
> *: adjust region heartbeat metrics.

- conf/config.toml
- server/cluster.go
- server/config.go
- server/coordinator.go
- server/coordinator_test.go
- server/handler.go
- server/kv.go
- server/leader.go
- server/schedule/scheduler.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_leader.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_leader.go
- server/schedulers/shuffle_region.go
- server/server_test.go
This is the recommitment for #769, and fix compatible problem
> sccheduler, server: persist scheudler list to etcd

- server/table_namespace_classifier.go
- server/table_namespace_classifier_test.go
Move the region to the corresponding namespace even if it contains infinite edge.
> namespaceClassfier classifies region containing infinite edge

- pdctl/command/operator.go
- server/api/history_test.go
- server/api/label_test.go
- server/api/operator.go
- server/api/operator_test.go
- server/api/region_test.go
- server/api/server_test.go
- server/api/store_ns_test.go
- server/api/store_test.go
- server/cluster_test.go
- server/cluster_worker.go
- server/grpc_service.go
- server/handler.go
> api, pdctl: support add/remove region peer.

- server/api/operator_test.go
- server/api/scheduler.go
- server/api/scheduler_test.go
- server/api/util.go
- server/handler.go
let we can dynamic add/remove it.
> api/scheduler: add region and hot region schedule api

- server/api/store.go
- server/cache.go
- server/cache_test.go
- server/cluster.go
- server/coordinator_test.go
- server/core/region.go
- server/core/store.go
- server/grpc_service.go
- server/metrics.go
- server/schedule/replica_test.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/mockcluster.go
- server/schedulers/test_util.go
- server/store_statistics.go
use Mb as unit, add RegionSize and LeaderSize in StoreInfo
> core: record store approximate size 

- server/cache.go
- server/etcd_kv.go
> server: save region to cache even when save kv failed. 

- server/coordinator.go
Above is a snapshot from one of our clusters
> coordinator: clear hot store related gauges when store is not hot any more

- pd-client/client.go
Trace `GetTSAsync` and other APIs...
@disksing @huachaohuang @nolouch
> pd-client: support opentracing for pd client

- server/coordinator.go
> coordinator: clear hot region related gauges when region is not hot any more.

- Makefile
- server/util.go
ref https://github.com/pingcap/tidb/pull/4947
> Makefile: use git describe to assign PDReleaseVersion

- server/api/store.go
- server/cluster_worker_test.go
- server/coordinator.go
- server/namespace_test.go
- server/schedule/replica_test.go
use prealloc checked code, then change to pre-make space. @disksing @huachaohuang PTAL
> prealloc premake space.

- server/api/operator_test.go
- server/api/scheduler.go
- server/api/scheduler_test.go
- server/api/util.go
- server/handler.go
> api: support add region and hot region scheduler.

- server/cluster.go
- server/coordinator.go
- server/coordinator_test.go
- server/grpc_service.go
- server/heartbeat_streams.go
- server/operator_test.go
- server/server.go
> *: fix heartbeat related issues.

- server/api/redirector.go
- server/config.go
- server/join.go
- server/server.go
> server: support tls for join

- server/balancer_test.go
- server/cluster.go
- server/coordinator.go
- server/coordinator_test.go
- server/schedulers/utils.go
https://github.com/pingcap/pd/pull/869
https://github.com/pingcap/pd/pull/874
https://github.com/pingcap/pd/pull/889
> cherry-pick some bug fixes from master.

- server/schedulers/hot_region.go
> scheduler: fix hot region scheduler select store problem.

- pkg/faketikv/cases/cases.go
- pkg/faketikv/cases/region_split.go
- pkg/faketikv/cluster.go
- pkg/faketikv/drive.go
- pkg/faketikv/node.go
> simulator: support region split.

- server/balancer_test.go
- server/cache.go
cherry-pick https://github.com/pingcap/pd/pull/930
> server: reduce the heartbeat lock overhead. (#930)

- server/config.go
- server/core/store.go
- server/store_statistics.go
we can use the unhealthy state of alarm. and turn defaultMaxStoreDownTime to 30 minute.
> server: adjust the status of the store

- server/schedulers/balance_test.go
- server/schedulers/hot_region.go
- server/schedulers/mockcluster.go
> schedulers: fix hot region scheduler adds peers on down stores

- server/balancer_test.go
- server/schedulers/hot_region.go
> schedulers: fix hot region scheduler adds peers on down stores (#958)

- server/coordinator.go
- server/coordinator_test.go
> server: check regions in background goroutine.

- server/cache.go
- server/coordinator.go
- server/coordinator_test.go
- server/core/region.go
- server/core/region_tree.go
- server/schedule/scheduler.go
cherry pick #963. Also the `ScanRegions` utils are cloned.
>  server: check regions in background goroutine.

- server/balancer_test.go
- server/cache_test.go
- server/coordinator_test.go
- server/core/kv_test.go
- server/core/region.go
- server/core/region_tree.go
* remove overlaps from regions
> server: fix stale regions info with overlaps that should be removed (#880)

- server/schedule/filters.go
- server/schedulers/balance_test.go
fix https://github.com/pingcap/pd/issues/974
> schdule: exclude offline store in filter source

- server/schedule/replica_checker.go
- server/schedulers/balance_region.go
- server/schedulers/balance_test.go
- server/schedulers/mockcluster.go
- server/schedulers/test_util.go
checker will add to tikv that have too many pending regions.
> scheduler: fix checker add peer to tikv that have too many pending regions

- server/config.go
- server/coordinator.go
- server/coordinator_test.go
- server/option.go
more compatibility, we can add a new scheduler that needs to enable by default
> server: let scheduler option backward compatibility

- server/schedulers/balance_region.go
Normally region score won't change rapidly.
> balance: region balance do not need to clear taint cache.

- server/config_test.go
- server/coordinator_test.go
- server/option.go
- server/server.go
PTAL @disksing @Connor1996 @siddontang
> merge master to 2.0 to release rc5

- server/coordinator.go
- server/coordinator_test.go
- server/schedulers/test_util.go
check learner even though learner is disabled to fit for the case where disable learner but there are still some learners waiting to be promoted.
> server: check learner regardless of whether learner enabled or not

- pdctl/command/scheduler.go
- server/api/scheduler.go
- server/handler.go
- server/schedule/basic_cluster.go
- server/schedule/mockcluster.go
- server/schedule/operator.go
- server/schedule/operator_kind.go
- server/schedule/operator_test.go
- server/schedule/range_cluster.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/balance_test.go
- server/schedulers/scatter_range.go
cherry-pick scatter range scheduler.
> Cherry-pick scatter range scheduler

- server/cache.go
- server/core/kv.go
- server/core/kv_test.go
- server/etcd_kv.go
> server: fix load region failure due to packet size too large. (#1064)

- pkg/faketikv/node.go
fix some mistake spell in simulator fake node source file, may be help for you
> fix some mistake spell in simulator fake node source file

- cmd/pd-recover/main.go
> pd-recover: delete max replicas

- server/cache.go
- server/config.go
- server/coordinator.go
- server/metrics.go
- server/option.go
> *: let patrol region tick interval configurable

- server/metrics.go
- server/schedule/filters.go
- server/schedule/metrics.go
> schedule: add metrics for the filter

- pkg/faketikv/cases/cases.go
- pkg/faketikv/cases/event_inner.go
- pkg/faketikv/cases/hot_read.go
- pkg/faketikv/cases/hot_write.go
- pkg/faketikv/cases/region_split.go
- pkg/faketikv/drive.go
- pkg/faketikv/event.go
- pkg/faketikv/task.go
Abstract some function into events. will add a complex case with dynamic change in next pr.
> simulator: add event mechanism

- CHANGELOG.md
- server/join_test.go
> CHANGELOG: update changelog for 2.0.3

- CHANGELOG.md
> CHANGELOG: update changelog for 2.0.3 (#1098)

- pkg/integration_test/member_test.go
The test occasionally fails on our CI.
After reproduced on my machine, the reason is that `DeleteMember` is not idempotent operation, which means if the first `DeleteMember` query times out while the node has been successfully removed, the following retry commands will return 404 not found.
Now we can judge the number of remaining nodes to check if the delete operation is completed.
`go test -check.f="TestMemberDelete"` for 200 times.
> integration: make TestMemberDelete more stable

- server/schedulers/balance_test.go
Fix TestStorageThreshold()
- make dev
- go run -check.f="TestStorageThreshold" for 200 times
Introduced by #1123
Resolve #1130
> schedulers: fix TestStorageThreshold

- pd-client/client.go
Insert some context check logic in the background goroutine process, and exit as early as possible when the client is found to be closed.
It will also eliminate some error messages when close pd client.
- make dev
- test the code snippet from #1134
Fix #1134
> pdclient: exit all goroutines as soon as possible when pd client is closed

- server/schedule/replica_checker.go
- server/schedulers/balance_test.go
cherry-pick #1123 , with #1132 which fixes the test case
unit test
#1123 
#1132
> schedule: fix store out of space due to moving replica

- cmd/simulator/main.go
- pkg/faketikv/cluster.go
- pkg/faketikv/conn.go
- pkg/faketikv/drive.go
- pkg/faketikv/event.go
- pkg/faketikv/node.go
- pkg/faketikv/raft.go
- pkg/faketikv/task.go
Abstruct `RaftInfo` from `ClusterInfo`
- N/A
> simulator: refactor ClusterInfo

- server/schedule/hot_cache.go
This PR fixes the `hot_write` and `hot_read` cases. The current if statement might lead to `value` to be nil when the region exists in `writeFlow`.
- Manual test
> schedule: fix hot write and read cases

- pkg/faketikv/cases/add_nodes.go
- pkg/faketikv/drive.go
- pkg/faketikv/raft.go
- pkg/faketikv/task.go
- server/core/region.go
- server/testutil.go
This PR supports raft learner in faketikv.
- New feature (non-breaking change which adds functionality)
- Manual tests
> simulator: support raft learner

- pkg/faketikv/cases/cases.go
- pkg/faketikv/cases/region_merge.go
- pkg/faketikv/task.go
- server/testutil.go
This PR is going to make simulator support `region-merge` operation.
- New feature (non-breaking change which adds functionality)
- Manual tests
> simulator: support region merge

- server/api/store.go
- server/config.go
- server/server.go
- server/util.go
- server/util_test.go
check the legality of the label. some careless user use `pdctl`  like:
```
pdctl >> config set location-labels host;
``` 
and it will bet set successfully. 
- Improvement (non-breaking change which is an improvement to an existing feature)\
unit test
> server/api: check the legality of the label

- Makefile
- cmd/simulator/main.go
- pkg/faketikv/cases/cases.go
This PR is going to run all cases of simulator when excuting `make simulator`.
- Manual tests
> simulator: run all cases of the simulator in Makefile

- cmd/pd-ctl/main.go
> pd-ctl: add an http prefix for address

- cmd/simulator/main.go
- pkg/faketikv/client.go
- pkg/faketikv/node.go
This PR is going to let simulator work with a real PD server.
- Manual teststed PR or issue link (optional)
> simulator: make simulator work with a real pd

- .travis.yml
- Makefile
- circle.yml
- docs/development.md
Just added some development docs.
> retool: install automatically and document

- pkg/faketikv/event.go
- pkg/faketikv/node.go
- pkg/faketikv/raft.go
- pkg/faketikv/task.go
This PR takes the store size into consideration in the simulator. 
- Manual tests
> simulator: take the store size into consideration

- Gopkg.lock
- Gopkg.toml
- Makefile
- hack/retool-install.sh
- server/tso.go
- server/tso_test.go
- tools.json
- vendor/github.com/etcd-io/gofail/runtime/failpoint.go
- vendor/github.com/etcd-io/gofail/runtime/http.go
- vendor/github.com/etcd-io/gofail/runtime/runtime.go
- vendor/github.com/etcd-io/gofail/runtime/terms.go
This PR uses [gofail](https://github.com/etcd-io/gofail) to test system time fallback.
- Unit test
#1173.
> server: use gofail to test time fallback

- server/core/store.go
This PR uses two variables to simplify the logic of score function.
N/A
> server: use variables to simplify the score function's logic

- pkg/faketikv/cases/add_nodes_dynamic.go
- pkg/faketikv/cases/balance_leader.go
- pkg/faketikv/cases/cases.go
- pkg/faketikv/cases/event_inner.go
- pkg/faketikv/cases/hot_read.go
- pkg/faketikv/cases/hot_write.go
- pkg/faketikv/cases/region_merge.go
- pkg/faketikv/drive.go
- pkg/faketikv/event.go
This PR adds a case to dynamically add nodes in the simulator and does slightly cleanup.
- Manual tests
> simulator: add nodes dynamically in the simulator

- pkg/faketikv/cases/cases.go
- pkg/faketikv/cases/delete_nodes.go
- pkg/faketikv/cases/event_inner.go
- pkg/faketikv/drive.go
- pkg/faketikv/event.go
- pkg/faketikv/raft.go
- pkg/faketikv/task.go
- server/testutil.go
This PR adds a case which dynamically deletes nodes in the simulator.
- Manual tests
> simulator: delete nodes randomly

- CHANGELOG.md
Add changelog for v2.0.1-rc1
None
None
None
None
None
> release v2.1.0-rc1

- .travis.yml
- README.md
- circle.yml
- pkg/faketikv/client.go
- pkg/faketikv/node.go
- server/cluster.go
Using go1.11
- Improvement (non-breaking change which is an improvement to an existing feature)\
make dev
> *: migrate to go1.11

- .github/pull_request_template.md
This PR refines the pull request template, guide the PR author to write better pull request description.
No code changes.
https://github.com/pingcap/tidb/pull/7332
> *: make pull request template more concise

- server/api/diagnose.go
- server/api/region_test.go
- server/cluster_info_test.go
- server/cluster_test.go
- server/core/kv.go
- server/core/kv_base.go
- server/leader.go
- server/schedule/hot_cache.go
- table/codec_test.go
- table/namespace_classifier_test.go
There are some unnecessary conversions in some files.
This PR removes these unnecessary conversions.
Tests 
- Unit test
> *: remove some unnecessary conversions

- pd-client/client.go
- server/api/member.go
- server/cache/lru.go
- server/cache/two_queue.go
- server/cluster.go
- server/cluster_test.go
- server/heartbeat_stream_test.go
- server/id_test.go
- server/schedulers/hot_region.go
- server/server_test.go
- server/tso_test.go
Fix the lint warnings reported by `make check`.
Fix #1171
- Fix code as suggested.
- Suppress revive in the places that have reason to violate the rules.
Tests 
- Unit test
> *: fix lint tool warnings

- CHANGELOG.md
> CHANGLOG: update changelog for v2.1.0-rc2

- cmd/simulator/main.go
- conf/simconfig.toml
- pkg/faketikv/cases/add_nodes.go
- pkg/faketikv/cases/add_nodes_dynamic.go
- pkg/faketikv/cases/balance_leader.go
- pkg/faketikv/cases/cases.go
- pkg/faketikv/cases/delete_nodes.go
- pkg/faketikv/cases/hot_read.go
- pkg/faketikv/cases/hot_write.go
- pkg/faketikv/cases/makeup_down_replica.go
- pkg/faketikv/cases/region_merge.go
- pkg/faketikv/cases/region_split.go
- pkg/faketikv/config.go
- pkg/faketikv/conn.go
- pkg/faketikv/drive.go
- pkg/faketikv/event.go
- pkg/faketikv/node.go
- pkg/faketikv/raft.go
The current simulator has some parameters hard-coded. It is not friendly enough.
This PR is going to make some parameters of the simulator configurable and also renames some variables to make it more clear.
Tests 
- Manual test
> simulator: make some parameters configurable

- tools/pd-simulator/README.md
When resolving the conflicts, I forgot to update the documentation of the PD simulator. 
This PR fixes the documentation of the PD simulator.
Tests 
- No code
> *: fix the documentation of simulator

- pkg/logutil/log.go
ref:  https://github.com/pingcap/tidb-docker-compose/pull/39
use a unified logger.
redirect the logger of the moudle `raft` and `grpc`.
Tests 
- Manual test
> util/log: unified logger

- server/store_statistics.go
cherry-pick #1261 
This PR is going to reset these metrics after the status of a store becomes tombstone.
Tests 
- Manual test
> server: fix store metrics (#1261)

- Gopkg.lock
- Gopkg.toml
- vendor/google.golang.org/grpc/rpc_util.go
- vendor/google.golang.org/grpc/transport/http2_server.go
- vendor/google.golang.org/grpc/transport/http_util.go
- vendor/google.golang.org/grpc/transport/transport.go
cherry-pick #1265 
This PR bumps the version fo grpc to 1.12.2 in order to fix the data race problem.
Tests 
- No code
> *: bump grpc to 1.12.2 (#1265)

- server/cluster.go
cherry-pick #1280
If the store is up, the upStoreCount should add one and continue the next loop.
Tests 
- Manual test
> *: fix a bug in checkStore (#1280)

- pkg/integration_test/version_upgrade_test.go
- server/cluster.go
- server/cluster_info.go
- server/grpc_service.go
- server/leader.go
- server/region_syncer/client.go
- server/region_syncer/server.go
- server/server.go
extract the region syncer to a package.
Tests 
- Unit test
> *: adjust region syncer code structure

- CHANGELOG.md
Add changelog of v2.1.0-rc.3 and v2.1.0-rc.4.
Tests 
- No code
> *: release v2.1.0-rc.4

- server/api/region_test.go
- tools/pd-ctl/main.go
- tools/pd-ctl/pdctl/command/region_command.go
Cherry-pick bugfixes from master branch for next release.
Cherry-pick PRs:
https://github.com/pingcap/pd/pull/1298
https://github.com/pingcap/pd/pull/1299
https://github.com/pingcap/pd/pull/1308
Tests 
- Unit test
> pdctl: cherry pick bugfixes

- server/api/region.go
- server/api/region_test.go
* server/api: fix region check API interface
Cherry-pick bugfixes from master branch for next release.
pick: https://github.com/pingcap/pd/pull/1311
> server/api: fix the issue about `regions/check` API  (#1311)

- tools.json
It seems upstream repo has rebased the branch recently, which breaks our `make check`.
Change to a valid revision.
Tests 
- Unit test
> test: fix megacheck commit revision

- pkg/integration_test/cluster.go
- pkg/integration_test/join_test.go
- pkg/integration_test/leader_watch_test.go
- server/join.go
- server/leader.go
- server/tso_test.go
- server/util.go
fix join problem and leader watcher.
cherry pick.
Tests 
- Unit test
> server: cherry pick some fixes 

- server/api/operator_test.go
- server/handler.go
Fix https://github.com/pingcap/pd/issues/1318
return errors when store is tombstone.
Tests 
- Unit test
> server/api: check store state before creating operators

- .travis.yml
- circle.yml
- cmd/pd-ctl/main.go
- pd-client/client.go
- pdctl/command/region_command.go
- pkg/faketikv/client.go
- pkg/faketikv/node.go
- server/api/region.go
- server/api/region_test.go
- server/cluster.go
- server/join.go
- server/server.go
Cherry-pick bug fixes to release-2.0 branch, including #1267 #1279 #1298 #1299 #1308 #1311 
- cherry-pick commits
- fix build/test problems
Tests 
- Unit test
> Cherry pick bug fixes to release-2.0

- CHANGELOG.md
Prepare for releasing v2.0.9
Add changelog for v2.0.9
Tests 
- No code
> add changelog for v2.0.9

- server/schedule/operator.go
- server/schedulers/balance_test.go
> [Cherry-pick] schedule: change merge match peers strategy (#1339)

- server/cluster.go
- server/cluster_test.go
* server: fix the issue about RaftCluster cannot be stopped
cherry-pick #1370 
fix the deadlock
Tests 
- Unit test
> server: Fix the issue about RaftCluster cannot be stopped (#1370)

- CHANGELOG.md
Add change log for v2.1.1
Tests 
- No code
> Release v2.1.1

- pkg/integration_test/pdctl_test.go
The test included in this PR is a part of #1328.
This PR adds some tests for `config` subcommand.
Tests 
- Unit test
> pdctl: add tests for config subcommand

- server/api/operator_test.go
- server/api/region_test.go
- server/api/stats_test.go
- server/cluster_info.go
- server/cluster_info_test.go
- server/cluster_test.go
- server/core/region.go
- server/core/region_option.go
- server/core/region_tree.go
> [Cherry-pick] server: check overlaps for new region (#1377)

- server/schedule/operator_controller.go
- server/schedule/range_cluster.go
- server/schedule/region_scatterer.go
- server/schedule/replica_checker.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/base_scheduler.go
- server/schedulers/hot_region.go
- server/schedulers/label.go
- server/schedulers/random_merge.go
- server/schedulers/scatter_range.go
add comments for `scheduler` and `schedulers`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/pd/1390)
> scheduler,schedulers: add some comments

- pkg/logutil/log.go
- pkg/logutil/log_test.go
- server/api/hot_status.go
- server/api/hot_status_test.go
- server/schedulers/scheduler_test.go
- tests/cluster.go
- tests/cmd/pdctl_test.go
This PR adds more tests to improve the code coverage.
Tests 
- Unit test
> *: add more coverage tests 

- .travis.yml
- Makefile
- README.md
- tools.json
There are a lot of issues which are not resolved in `Coveralls`. Another coverage test `Codecov` is much better than it.
The PR switches our coverage test from `Coveralls` to `Codecov`.
Tests 
- No code
> *: switch coverage test to Codecov 

- CHANGELOG.md
> release: update CHANGELOG.md for v3.0.0-beta

- CHANGELOG.md
update CHANGLOG.md to release v2.1.3
> update CHANGLOG.md to release v2.1.3

- server/config.go
- server/config_test.go
Signed-off-by: dongxu <huang@pingcap.com>
> config: Add pushgateway address parameter

- tools/pd-simulator/simulator/raft.go
some word spelled not correctly.
make a spelling correction.
> make a spelling correction

- server/cluster.go
Currently, we cannot add a low space store into the cluster which is not reasonable.
This PR allows adding a low space store and let the user solve the low space problem.
Tests 
- Unit test
> server: fix adding a low space store

- .travis.yml
- Dockerfile
- README.md
- circle.yml
- go.mod
`go 1.12` has been released.
This PR upgrades `go` to `1.12`.
Tests 
- Unit test
> *: Upgrade go to 1.12

- CHANGELOG.md
> Bump to v3.0.0-beta.1

- tools/pd-ctl/README.md
Signed-off-by: Keyi Xie <xiekeyi98@gmail.com>
Fix misspell.
Make the misspell correct.
Tests 
- No code
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/pd/1499)
> tools/pd-ctl: fix misspell in README.md

- CHANGELOG.md
> add CHANGELOG for 2.1.8

- pkg/etcdutil/etcdutil.go
- pkg/etcdutil/etcdutil_test.go
- server/etcd_kv.go
- server/server.go
- server/util.go
etcdutil: move kvGet to the uitl package
Signed-off-by: c4pt0r <i@huangdx.net>
> etcdutil: move kvGet to the util package

- server/cluster.go
- server/coordinator.go
- server/leader.go
- server/region_syncer/server.go
Do the same thing with #1511, but #1511 was closed by accident.
See #1511
Tests 
- Unit test
> *: improve some logs

- CHANGELOG.md
> update CHANGLOG for 2.1.9

- server/store_statistics.go
Add the metrics of the flow statistics of the store. 
Add metrics.
Tests 
- Manual test
> statistic: add the statistic of flow

- CHANGELOG.md
> update CHANGELOG for v2.1.11

- server/api/stats_test.go
- server/api/trend.go
- server/cluster.go
- server/cluster_info.go
- server/cluster_info_test.go
- server/coordinator.go
- server/core/region.go
- server/core/store.go
- server/handler.go
- server/mock/cluster.go
- server/namespace_cluster.go
- server/schedule/scheduler.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_hot_region.go
- server/statistics/hot_cache.go
- server/statistics/region.go
- server/statistics/store.go
- server/statistics/util.go
- server/statistics/util_test.go
- server/store_statistics.go
- server/store_statistics_test.go
- tests/pdctl/hot/hot_test.go
Part of modularizing PD. 
This PR splits statistics from `core` package.
Tests 
- Unit test
> *: split statistics from core package

- server/cluster_info.go
- server/coordinator_test.go
- server/core/store.go
- server/core/store_option.go
- server/schedule/basic_cluster.go
- server/schedule/operator_controller.go
- server/schedule/scheduler.go
cherry-pick #1586.
Tests 
- Unit test
> schedule: fix store maybe always overloaded (#1586)

- CHANGELOG.md
> bump to v3.0.0-rc.3

- server/config.go
pick #1598 
Tests 
- Unit test
- Manual test
> config: fix cannot set `two-way-merge` via pdctl (#1598)

- server/checker/learner_checker.go
- server/checker/merge_checker.go
- server/checker/merge_checker_test.go
- server/checker/metrics.go
- server/checker/namespace_checker.go
- server/checker/replica_checker.go
- server/coordinator.go
- server/namespace_test.go
- server/schedule/metrics.go
- server/schedule/operator.go
- server/schedulers/balance_region.go
- server/schedulers/balance_test.go
Part of modularizing PD.
This PR moves out checker from `schedule` package to `checker` package.
Tests 
- Unit test
> server: separate checker from schedule package

- tools/pd-ctl/pdctl/command/global.go
[#1597](https://github.com/pingcap/pd/issues/1597)
Tests 
- Unit test
> pdctl: print success response

- conf/config.toml
- pkg/mock/mockoption/mockoption.go
- server/api/api.raml
- server/api/store.go
- server/checker/merge_checker.go
- server/checker/merge_checker_test.go
- server/cluster_info.go
- server/config.go
- server/config_test.go
- server/option.go
- server/schedule/opts.go
- server/schedulers/balance_test.go
- server/schedulers/random_merge.go
- tools/pd-ctl/README.md
After #1598, the cluster cannot be upgraded successfully due to JSON parsing.
This PR fixes this problem by replacing the original parameter with a new one.
Tests 
- Unit test
Code changes
> *: fix upgrade problem caused by two way merge 

- conf/config.toml
- pkg/mock/mockoption/mockoption.go
- server/api/api.raml
- server/api/store.go
- server/cluster_info.go
- server/config.go
- server/config_test.go
- server/option.go
- server/schedule/merge_checker.go
- server/schedule/merge_checker_test.go
- server/schedule/opts.go
- server/schedulers/balance_test.go
- server/schedulers/random_merge.go
- tools/pd-ctl/README.md
cherry-pick #1602.
Tests 
- Unit test
> fix upgrade problem caused by two way merge (#1602)

- CHANGELOG.md
Release 3.0!
Update CHANGELOG.
- No code
> *: bump to 3.0.0

- server/config.go
- server/config_test.go
> config: warn undefined config item (#1577)

- server/schedulers/balance_region.go
Add log message for every branch so we can know why a store is skipped.
Add more log messages
Tests 
> scheduler: log all divergent routines when filtering the target store

- CHANGELOG.md
add changelog for v2.1.14
update changelog.md
Tests 
- No code
> changelog: add v2.1.14 changelog

- CHANGELOG.md
- server/schedule/waiting_operator.go
- server/schedule/waiting_operator_test.go
cherry-pick #1633.
Tests 
- Unit test
> schedule: fix merge related operators in waiting operators (#1633)

- CHANGELOG.md
> Bump version to 3.0.1

- CHANGELOG.md
Signed-off-by: youjiali1995 <zlwgx1023@gmail.com>
> *: bump to v2.1.15

- server/schedule/range_cluster.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/metrics.go
- server/schedulers/scatter_range.go
cherry-pick #1642.
Tests 
- Manual test
> schedule: fix scatter range (#1642)

- server/api/operator_test.go
- server/handler.go
Now the `merge region` via `pd-ctl` not work.  
Fix the logic.
Tests 
- Unit test
> *: fix add merge region api

- CHANGELOG.md
This PR bumps version to 3.0.2.
> *: Bump version to 3.0.2

- pkg/mock/mockcluster/mockcluster.go
- server/core/region.go
- server/core/region_option.go
- server/schedulers/balance_test.go
- server/schedulers/scheduler_test.go
- server/statistics/hot_cache.go
Fix region flow calculation for branch [new-hotspot-scheduler]
Tests 
- Unit test
> statistics: fix region flow calculation [new-hotspot-scheduler]

- go.mod
- go.sum
- server/coordinator.go
- server/schedulers/hot_region.go
- server/schedulers/utils.go
- server/schedulers/utils_test.go
- server/statistics/store.go
- server/statistics/store_collection.go
Add collecting threads information and calculating store scores for branch [new-hotspot-scheduler]
Tests 
- Unit test
> statistics, schedulers: add collecting threads information and calculating store scores [new-hotspot-scheduler]

- cmd/pd-server/main.go
- server/config.go
- server/util.go
Signed-off-by: cwen0 <cwenyin0@gmail.com>
cherry-pick https://github.com/pingcap/pd/pull/1695
> add config-check flag for pd-server (#1695)

- CHANGELOG.md
> bump version to v3.0.3

- Makefile
Signed-off-by: nolouch <nolouch@gmaile.com>
```
❯ make failpoint-enable
retool: downloading github.com/mgechev/revive
retool: setting version for github.com/mgechev/revive
retool: fatal err: execution error on "git checkout 7773f47324c2bf1c8f7a5500aff2b6c01d3ed73b": chdir /Users/nolouch/csn/program/go/src/github.com/pingcap/pd/.retools/src/github.com/mgechev/revive: no such file or directory
make: *** [failpoint-enable] Error 1
```
setup firstly.
Tests 
```
❯ make failpoint-enable
retool: downloading github.com/mgechev/revive
retool: setting version for github.com/mgechev/revive
retool: downloading github.com/dnephin/govet
retool: setting version for github.com/dnephin/govet
retool: downloading github.com/pingcap/failpoint/failpoint-ctl …
```
> Makefile: fix failpoint enable

- tests/pdctl/cluster/cluster_test.go
- tools/pd-ctl/pdctl/ctl.go
cherry-pick #1729.
Tests 
- Unit test
> tools: fix TLS in pd control (#1729)

- go.mod
- go.sum
> [new-hotspot-scheduler] update the kvproto dependency

- go.mod
- go.sum
> [new-hotspot-scheduler] update kvproto dependency

- tools/pd-ctl/main.go
- tools/pd-ctl/pdctl/command/operator.go
- tools/pd-ctl/pdctl/command/scheduler.go
cherry-pick #1765 #1763 
Tests 
- Unit test
> pd-ctl: fix output (#1765) (#1763) (cherry pick to release-2.1)

- tests/pdctl/cluster/cluster_test.go
- tests/pdctl/helper.go
- tests/pdctl/operator/operator_test.go
- tests/pdctl/region/region_test.go
- tests/pdctl/scheduler/scheduler_test.go
- tools/pd-ctl/main.go
- tools/pd-ctl/pdctl/command/global.go
- tools/pd-ctl/pdctl/command/operator.go
- tools/pd-ctl/pdctl/command/scheduler.go
cherry-pick #1765 #1763 
Tests 
- Unit test
> pd-ctl: fix output  (#1765) (#1763) (cherry pick to release-3.0)

- CHANGELOG.md
> update CHANGELOG  for v3.0.4

- server/server.go
For https://github.com/pingcap/pd/issues/1797. 
improve the fail point.
Tests 
- Unit test
> test: enlarge the sleep time for the failpoint `memberNil`

- server/cluster.go
- server/cluster_info.go
- server/coordinator.go
- server/coordinator_test.go
- server/statistics/hot_cache.go
- server/statistics/region_collection.go
- server/statistics/region_collection_test.go
- server/statistics/store_collection.go
cherry-pick #1753 and #1790
See the corresponding PR descriptions.
Tests 
- Unit test
> *: cherry pick some improvements to release 3.0

- server/cluster.go
- server/cluster_info.go
- server/coordinator.go
- server/coordinator_test.go
- server/statistics/hot_cache.go
- server/statistics/region_collection.go
- server/statistics/region_collection_test.go
- server/statistics/store_collection.go
cherry-pick #1753 and #1790
See the corresponding PR descriptions.
Tests 
- Unit test
> *: cherry pick some improvements to release 3.1

- server/coordinator_test.go
Currently, the store limit related tests are not very stable.
This PR changes some test configurations to make them more stable.
Tests 
- Unit test
> *: make tests more stable

- pkg/mock/mockoption/mockoption.go
- server/cluster.go
- server/config/config.go
- server/config/option.go
- server/schedule/opt/opts.go
Add an option to turn on/off placement rules feature.
Add configuration and make sure it is always disabled before the full feature get merged.
> config: add option to enable placement rules

- server/api/hot_status.go
- server/cluster.go
- server/handler.go
- server/statistics/store.go
- server/statistics/store_collection.go
- tests/pdctl/hot/hot_test.go
Some functions are forgot to change in PR  #1801 . This PR fixes them. The API doc is not changed because RAML do not support map.
Tests 
- Unit test
Code changes
> statistics: use float rate

- server/api/store.go
- server/core/store.go
- server/schedule/filter/filters.go
- server/schedule/region_scatterer.go
replace `GetIsBusy` with `IsBusy`
Tests 
- Unit test
> * : refactor "IsBusy"

- server/core/storage.go
Support load/save rules to persistent storage.
Define path and add methods.
Code changes
> core: add rules load/save

- conf/config.toml
- server/config/config.go
- server/schedule/checker/merge_checker.go
- tools/pd-ctl/README.md
The documentation is outdated.
This PR updates the documentation and fixes some comments
Tests 
- No code
> *: update the documentation to the latest version

- server/api/admin.go
- server/api/admin_test.go
- server/api/etcd_api_test.go
- server/api/util.go
use more accurate HTTP status code for reset ts
Tests 
- Unit test
> api: use more accurate http status code for reset ts

- server/api/admin.go
- server/api/admin_test.go
- server/api/etcd_api_test.go
- server/api/util.go
pick #1878 
Tests 
- Unit test
> api: use more accurate http status code for reset ts (#1878)

- server/core/region.go
- server/core/region_tree_test.go
Fix #1885 
decrease size and keys in `remove`.
Tests 
- Unit test
> core: fix wrong region size

- client/client.go
Signed-off-by: luancheng <luancheng@pingcap.com>
current pdTimeout(3s) is too small for backup & restore Scenario
so need set timeout outside 
add timeout argument in scanRegions function
Tests 
- Unit test
- No code
Code changes
Side effects
> client: add timeout for scanRegions

- server/server_test.go
- server/tso.go
- server/tso_test.go
pick  #1930 
Tests 
- Unit test
> server/tso: fix the panic issue when getTS in the follower (#1930)

- server/server_test.go
The test in `testServerSuite` will do some work and check assertions in another goroutine. If the asserts fails, the main goroutine will be blocked.
Use `defer` and some check to make sure the main goroutine won't blocked.
Tests 
- No code
> test: fix test blocking in testServerSuite

- go.sum
- pkg/mock/mockcluster/mockcluster.go
- server/cluster_test.go
- server/schedule/operator_controller_test.go
- server/schedule/placement/rule_manager.go
- server/schedule/range_cluster.go
- server/schedule/selector/selector.go
- server/statistics/region_collection_test.go
- server/statistics/store_collection_test.go
- tests/cluster.go
- tests/config.go
- tools/pd-simulator/simulator/cases/delete_nodes.go
To reduce runtime.growslice by preallocation slice .
Prealloc the slice.
Tests 
- Unit test
PS: See the benchmark in: https://github.com/pingcap/tidb/pull/9946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pingcap/pd/1950)
> *: reduce runtime.growslice by preallocation

- Makefile
- pkg/grpcutil/grpcutil.go
- server/api/region_test.go
- server/api/status_test.go
- server/cluster_test.go
- server/coordinator_test.go
- server/heartbeat_stream_test.go
- server/kv/etcd_kv.go
- server/member/lease.go
- server/region_syncer/client.go
- server/region_syncer/history_buffer_test.go
- server/schedule/operator_controller.go
- server/schedule/range_cluster.go
- server/schedulers/balance_leader.go
- server/schedulers/scatter_range.go
- tests/pdctl/config/config_test.go
- tests/pdctl/region/region_test.go
- tests/server/api_test.go
- tools/pd-analysis/analysis/parse_log_test.go
- tools/pd-ctl/pdctl/command/config_command.go
- tools/pd-ctl/pdctl/command/tso_command.go
- tools/pd-simulator/simulator/cases/delete_nodes.go
- tools/pd-simulator/simulator/cases/import_data.go
- tools/regions-dump/main.go
Just remove some unused code.
This PR also enables `unconvert` check.
Tests 
- Unit test
> *: remove some unused code

- tools/pd-ctl/pdctl/command/global.go
- tools/pd-ctl/pdctl/command/operator.go
unknow the result meaning.
improve the output.
Tests 
> pdctl: improve the output of faild commands

- .github/pull_request_template.md
It is easy to forget to update API document.
Add to check list.
- No code
> *: update PR template

- .travis.yml
- server/server.go
- server/tso.go
- server/tso_test.go
pick #1972 
cherry-pick
Tests 
- Unit test
> *: fix the race issue in ResetTS (#1972)

- server/api/region.go
- server/api/region_test.go
- server/api/router.go
- server/core/region.go
cherry-pick #1970 to release-2.1
Optimize `convertToAPIRegions` and `h.rd.JSON`
Tests 
- Unit test
> Improve the performance of the HTTP API for getting all regions (#1970)

- client/client.go
- client/client_test.go
Cherry-pick #1993
add `NewClientWithContext`
Tests 
- Unit test
> client: support create with context

- tools/pd-ctl/README.md
remove the unused item incorrect-ns 
remove the unused item incorrect-ns
Tests 
- No code
> remove the unused item incorrect-ns

- .gitignore
- .gitmodules
- Makefile
- cmd/pd-server/main.go
- go.mod
- go.sum
- pkg/ui/dist/dist.go
- pkg/ui/ui.go
- scripts/build-ui.sh
- scripts/retool-install.sh
- server/server.go
- tools.json
support build PD binary with UI.
```
PD_WEB=1 make
```
browse [localhotst:2379/web](http://localhotst:2379/web) to see the ui.
add scripts.
Tests 
> *: add web UI

- server/statistics/topn_test.go
Sometimes CI will fail due to the `TestTTL` of `TopN`.
Reduce the times of `Put`.
Tests 
- No code
> test: TopN: reduce Put times in TestTTL

- server/config_manager/config_manager.go
- server/config_manager/config_manager_test.go
- server/core/storage.go
Part of #1977.
This PR adds a config manager to manage all components' config.
Tests 
- Unit test
> *: add config manager

- server/api/region.go
- server/api/region_test.go
- server/cluster_info.go
- server/cluster_info_test.go
- server/core/region.go
- server/core/region_option.go
- server/metrics.go
Signed-off-by: hundundm <hundundm@gmail.com>
cherry-pick #1759 #1741 and part of #1641 
Tests 
- Unit test
> cluster: update the region cache when flow changed (#1759) (#1741) (#1641)

- go.mod
- go.sum
Update the `sysutil` dependence to the latest version.
Edit go.mod
Tests 
- No code
> go.mod: update the sysutil dependence

- server/config/config.go
Dashboard is disabled by default.
> dashboard: dashboard is disabled by default

- server/api/config.go
- server/api/log.go
- server/config/config.go
- server/grpc_service.go
- server/server.go
cherry-pick #2124 
Tests 
- Unit test
> rename EnableConfigManager to EnableDynamicConfig (#2124)

- go.mod
- go.sum
- pkg/dashboard/apiserver/apiserver.go
- pkg/dashboard/uiserver/uiserver.go
- tests/cluster.go
- tests/dashboard/service_test.go
Add a test that Dashboard is accessible.
Tests 
- Unit test
> dashboard: add test

- go.mod
- go.sum
> dashboard: update version

- go.mod
- go.sum
- pkg/dashboard/apiserver/apiserver.go
Update Dashboard to v0302
Update Dashboard to v0302
Tests 
> dashboard: update to v0302

- tools/pd-ctl/main.go
- tools/pd-ctl/pdctl/ctl.go
UCP #1832 
Tests 
Code changes
Side effects
> remove package pflag in pd-ctl

- server/schedule/filter/filters.go
cacheFilter is not used any more.
remoe it.
> filter: remove cacheFilter

- go.mod
- go.sum
- pkg/dashboard/apiserver/apiserver.go
Update Dashboard to v0305
Update Dashboard to v0305
Tests 
> dashboard: update to v0305

- go.mod
- go.sum
Update Dashboard to v0306
Update Dashboard to v0306
* Updated visuals for Key Visualizer
* Add parralell in compare and add max_diff table
* Add progess and comparsion for diagnosis report
Tests 
> dashboard: update to v0306

- pkg/dashboard/keyvisual/input/core.go
`RaftCluster` only runs in the leader,  change to `BasicCuster`
let follower can get region information.
Tests 
checked all keyvisuals are work well.
> dashboard: make keyvisual works in follower

- server/cluster/cluster_worker.go
- server/schedule/operator/create_operator.go
- server/schedule/operator/kind.go
- server/schedule/placement/rule.go
- server/schedule/placement/rule_manager.go
add some logs
- add log when placement rule is updated or removed
- add log when handled askSplit request
- add split policy and split keys to operator's desc
Tests 
- Manual test
- update placement rules
- split regions
- Need to cherry-pick to release-3.1
> placement, schedule: add some logs for placement rule and operator

- go.mod
- go.sum
- pkg/dashboard/apiserver/apiserver.go
Signed-off-by: niedhui <niedhui@gmail.com>
Add TLS support for the dashboard.  I'll update go.sum after https://github.com/pingcap-incubator/tidb-dashboard/pull/195 is accepted 
Tests 
Install client certificates for browser, then access https://127.0.0.1:2379 using the browser
> dashboard: tls support

- pkg/grpcutil/grpcutil.go
- server/config/config.go
support allowed Common Name(CN)
add filed `allowed CN`
Tests 
- Manual test
> *: support allowed Common Name(CN)

- server/region_syncer/client.go
Fixes #2231.
This PR adds a lock when establishing syncer client.
Tests 
- Unit test
> syncer: fix race problem in syncer

- server/schedule/filter/filters.go
- server/schedulers/hot_region.go
- server/schedulers/scheduler_test.go
UCP #2176
UCP #2176
add specialUse label 'reserved'
Tests 
- Unit test
Code changes
Side effects
> add specialUse reserved

- go.mod
- go.sum
This PR bump TiDB Dashboard UI version to 0320.
> dashboard: update to 0320

- pkg/btree/btree.go
- pkg/cache/two_queue.go
- pkg/mock/mockhbstream/mockhbstream.go
- revive.toml
- server/cluster/cluster.go
- server/config/config.go
- server/schedule/operator/builder.go
This check is usually unnecessary
Disable it.
Tests
- No code
> makefile: disable flag-parameter check

- .github/pull_request_template.md
Refine the template for pull request. And a chapter for release note
- the template of pull request is changed.
- when creating a new pull request, we will use the new template
Tests 
- No code
> .github/*: refine templates for  pull request

- server/config/config.go
- server/config/config_test.go
Fix: https://github.com/pingcap/pd/issues/2269
Add config structure and adjust function.
Tests 
- Unit test
> config: add replicate-mode configuration

- go.mod
- go.sum
- pkg/dashboard/redirector.go
- tests/dashboard/service_test.go
* Update Dashboard to v0327
* POST requests cannot be redirected correctly
* Update Dashboard to v0327
* Use 307 instead of 302 in `Redirector`
Tests 
- Manual test
> dashboard: update to 0327 and refine redirector

- server/config_manager/config_manager.go
- server/config_manager/config_manager_test.go
After a component is registered, if there are some new configs when we upgrading, it cannot be registered anymore. When we updating these configs, it will print out "cannot find the config item".
This PR fixes it by trying to update config item for each `Create` operation.
Fix the problem that cannot add new config item in upgrading when enabling dynamic config
Tests 
- Unit test
> config: fix cannot add new config item

- pkg/dashboard/manager.go
#2323 
Check the length of ClientUrls of all members. If it is 0, it is considered that members are not ready.
Tests 
- Manual test
> dashboard: check ClientUrls length

- server/cluster/cluster.go
- server/core/region.go
- server/core/region_option.go
- server/replicate/replicate.go
- server/replicate/replicate_test.go
Fix #2273
- save region replicate status to cache
- calculate recover progress based on region status (a simple approach, need improve, see: https://github.com/pingcap/pd/issues/2327)
- update test
Tests 
- Unit test
Code changes
> replicate: implement recover progress

- server/schedulers/hot_region.go
Fix https://github.com/pingcap/pd/issues/2352
push counters to a temp slice, then push to the operator later.
Tests 
- (no test because I'm not sure how to reproduce, but the problem is obvious...)
> schedulers: fix hot region scheduler panic

- server/api/member.go
Signed-off-by: mapleFU <1506118561@qq.com>
previous pr introduce a git hash logic, but got error data: https://github.com/pingcap/pd/pull/2361
This pr fix that
Change the Get interface and logic.
Provide correct `git_hash` in the latest version
Tests 
- No code
Code changes
Side effects
> Api: [BUGFIX] Bugfix error logic in pd api.

- server/schedulers/hot_region_config.go
increase the default tolerance. 
turn to `1.05`.
No need.
Tests 
> *: turn the default tolerance for hotregion

- tests/pdctl/scheduler/scheduler_test.go
Fix the ci failed case.
no need
Tests 
- Unit test
Side effects
> tests: fix scheduler test in pdctl

- .travis.yml
- Makefile
- go.mod
- go.sum
- tools.go
We used `go-deadlock` in the test but did not add it as a dependency on `go.mod`.
Add it as a dependency on `go.mod`.
Tests 
> go-tools: add go-deadlock dep

- server/schedulers/hot_region.go
cherry-pick #2353
push counters to a temp slice, then push to the operator later.
Tests 
- (no test because I'm not sure how to reproduce, but the problem is obvious...)
> schedulers: fix hot region scheduler panic (#2353)

- pkg/apiutil/serverapi/middleware.go
- tests/cluster.go
#2368 introduced some duplicated error checks.
This PR fixes it by removing these duplicated error checks
Fix the duplicated error check in API
Tests 
- Unit test
> api: fix the duplicated check

- Dockerfile
- Makefile
- tools/pd-recover/main.go
cherry-pick #2406.
This PR does three things:
- change make target to compile pd-recover together
- add pd-recover to the docker image
- add -V parameter to show the version of pd-recover
Tests 
- Manual test
- Fix the issue that pd-recover is not included in the docker image
> *: add pd-recover to Dockerfile (#2406)

- metrics/grafana/pd.json
cherry-pick #2405.
This PR fixes it by adjust the Grafana template. After this PR, the PD dashboard looks like:
Tests 
- No code
- Fix the issue that the monitors of TSO and id allocation are missing
> metrics: fix the tso and id monitor (#2405)

- go.mod
- go.sum
dashboard: update to 0514
dashboard: update to 0514
Tests 
> dashboard: update to 0514

- tests/client/client_test.go
Fix https://github.com/pingcap/pd/issues/2434
fix the unstabel test.
Tests 
- Unit test
Release note
- No
> fix unstable test TestGetRegionByID

- go.mod
- go.sum
Update tidb-dashboard to 05-18, for PR https://github.com/pingcap-incubator/tidb-dashboard/pull/502
Tests 
- No code
Side effects
- No
- Fix panic when generated SQL diagnosis report in dashboard.
> update go.mod for tidb-dashboard

- conf/config.toml
- pkg/dashboard/uiserver/embedded_assets_rewriter.go
This PR adds default config to `config.toml` for Dashboard, as well as supply missing license headers.
- No code
(no change)
> Add TiDB Dashboard configurations

- pkg/dashboard/adapter/manager.go
dashboard: generate Context every time the manager starts
dashboard: generate Context every time the manager starts
Tests 
- Unit test
> dashboard: generate Context every time the manager starts

- .github/pull_request_template.md
> Fix grammar mistake

- metrics/grafana/pd.json
fix the duplicate panel
change to `keys`.
Tests 
> metrics: remove duplicate grafana panel

- server/schedule/placement/fit.go
Fix https://github.com/pingcap/pd/issues/2478
check the length.
Tests
- fix the panic issue after deleting the rule
> schedule: fix panic issue after delete the rule

- server/schedule/filter/filters.go
BlackListFilter is not used any more.
Remove it.
Tests
- no test
> filter: remove BlackListFilter

- client/client.go
- tools/pd-tso-bench/main.go
https://github.com/pingcap/pd/issues/1847
Avoided slice re-allocation and copying cost
changed from histogram to summary for distribution information
Tests 
Code changes
- No functionality change, improvement in performance
- For benchmark, added Prometheus code to print metrics data at the end of a run
Side effects
- In case of many clients created within single Tidb instance can lead to slightly higher memory consumption
> Addressing latency issue for pd-clients

- conf/config.toml
- go.mod
- go.sum
- pkg/dashboard/adapter/config.go
- pkg/dashboard/dashboard.go
- pkg/dashboard/keyvisual/keyvisual.go
- server/config/config.go
dashboard: update to 0619
dashboard: update to 0619
Tests
Code changes
> dashboard: update to 0619

- plugin/scheduler_example/evict_leader.go
- server/schedule/selector/candidates.go
- server/schedule/selector/candidates_test.go
- server/schedule/selector/comparer.go
- server/schedule/selector/selector.go
- server/schedulers/adjacent_region.go
- server/schedulers/evict_leader.go
- server/schedulers/label.go
- server/schedulers/random_merge.go
- server/schedulers/shuffle_leader.go
- server/schedulers/shuffle_region.go
make the store selection process more elegant (and potentially more correct)
- add StoreCandidates
- replace RandomSelector
- add tests
- (replicaSelector is not replaced yet bacause it is more complex, do it later)
Tests
- Unit test
> selector: introduce StoreCandidates and replace RandomSelector

- server/schedule/filter/filters.go
- server/schedule/filter/filters_test.go
- server/schedule/region_scatterer.go
- server/schedulers/adjacent_region.go
- server/schedulers/balance_region.go
- server/schedulers/hot_region.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_region.go
there are many places check `IsPlacementRuleEnabled` and then create a filter.
add `NewPlacementSafeguard` to return a safeguard filter based on the placement rule is enabled or not.
Tests
- Unit test
> filters: add NewPlacementSafeguard

- server/api/rule_test.go
improve the coverage for `rule.go` by covering the error handling.
ref https://github.com/pingcap/pd/issues/2287
> test: improve coverage for rule.go 

- server/schedulers/balance_region.go
Take advantages of the `StoreCandidates`. Make code more elegant.
NOTE: CI will fail due to https://github.com/pingcap/pd/issues/2601, but it is ready for review.
Tests
- Unit test
> schedulers: use StoreCandidates in balance_region_scheduler

- plugin/scheduler_example/evict_leader.go
- server/cluster/cluster.go
- server/cluster/cluster_test.go
- server/core/basic_cluster.go
- server/core/errors.go
- server/core/store.go
- server/core/store_option.go
- server/schedule/filter/filters.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_leader.go
The term `block` is ambiguous.
Some renames.
Tests
- Unit test
Side effects
- Have API error message change.
> *: rename store block to pauseLeaderTransfer

- server/api/admin.go
- server/api/admin_test.go
- server/api/component.go
- server/api/config.go
- server/api/log.go
- server/api/member.go
- server/api/operator.go
- server/api/plugin.go
- server/api/rule.go
- server/api/scheduler.go
- server/api/store.go
Issue #2227  
Replace all HTTP API POST/DELETE method‘s output with more specified messages.
Tests
- Unit test
Code changes
> api: improve the output of HTTP API POST method

- tools/pd-ctl/README.md
The note of `key-type` still is confused.
Tests
> Update key type note

- server/schedulers/hot_region.go
- server/schedulers/hot_test.go
Expectation filter store did not take effect
Tests
- Unit test
> schedulers: fix hot region scheduler

- server/config/config.go
- server/config/config_test.go
- server/config/persist_options.go
Fix config backward compatibility problem.
cherry-pick #2612 
Tests
- Unit test
> config: fix configuration reload (#2612)

- server/schedule/checker/learner_checker_test.go
no test cover learnerChecker.
add some test
Tests
- Unit test
> checker: add learner checker test

- server/config/config.go
- server/schedule/checker/replica_checker.go
- server/schedule/checker/replica_strategy.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker/rule_checker_test.go
- server/schedule/placement/rule.go
Close #2528 #2418 
Same with #2662
Tests
- Unit test
Code changes
- Has `rule_checker` change
- Has `replica_strategy` change
- PR #2662 
Add `isolation_level` for Placement Rule.
> rule_checker, replica_strategy: add isolation_level for Placement Rule

- server/schedule/placement/rule_manager.go
Methods call `Batch` to reduce duplicated code.
Tests
- Unit test
> placement: rule_manager refactor

- go.mod
- go.sum
Bump Dashboard to v2020.08.07.1
Tests
> dashboard: bump v2020.08.07.1

- pkg/autoscaling/handler.go
- tests/autoscaling/autoscaling_test.go
Related to #2621. After #2673, there are still some problems which are existed operator or TiDB cloud implementation.
This PR updates the API to make it easier.
Tests
- Unit test
Code changes
> autoscaling: update auto scaling API

- pkg/errs/errs.go
- server/core/storage.go
- server/schedule/placement/rule_manager.go
- server/schedule/placement/rule_manager_test.go
Support RuleGroup level Index and Override properties.
Tracking issue: https://github.com/pingcap/pd/issues/2721
- kv storage L/S methods
- update ruleManager
- add unit test
Tests
- Unit test
Code changes
> placement, kv: support RuleGroup configuration

- server/schedule/placement/rule_manager_test.go
No test cover RemoveRuleByIDPrefix
add test
Tests
- Unit test
> placement: add deleteByIDPrefix test

- server/api/rule.go
- server/api/rule_test.go
- server/cluster/cluster.go
- server/cluster/coordinator.go
refactor to make it simpler
Tests
- Unit test
> cluster, api: cleanup suspect range

- server/schedule/placement/rule.go
- server/schedule/placement/rule_list.go
- server/schedule/placement/rule_manager.go
- server/schedule/placement/rule_test.go
Add some comments for some complex function and add unit test for the `buildRuleList` function
Tests
- Unit test
> placement: Add some detail comment and unit test

- server/schedulers/scheduler_test.go
github.com/tikv/pd/server/schedulers couldn't run unit test, see [detail](https://travis-ci.org/github/tikv/pd/builds/718882002) because of lacking testing.T
Tests
- Unit test
> test: add testing.T in schedulers 

- Makefile
Reinforce `make clean` command.
`make clean` now will clean more building files.
Tests
- No code
Code changes
- Has `Makefile` change.
- PR #2781 
No release note.
> Makefile: update clean command

- server/api/router.go
- server/api/rule.go
- tests/pdctl/config/config_test.go
- tools/pd-ctl/pdctl/command/config_command.go
Tracking issue: https://github.com/pingcap/pd/issues/2721
- add API support
- add pd-ctl support
- add test
Tests
- Unit test
Code changes
- Support configuring Index and Override properties for rule groups
> placement: add api and pd-ctl support for rule group configuration

- server/election/lease.go
Add some logs about lease state.
> election: add some logs

- server/statistics/store_collection.go
#2737 introduce nil when hot statistic
fix it
Tests
- Unit test
> statistic: fix nil in collect metrics

- server/cluster/cluster.go
- server/statistics/hot_cache.go
- server/statistics/hot_peer_cache.go
remove unnecessary param
Tests
- Unit test
> scheduler: remove unnecessary param

- server/statistics/store.go
statistics: reformat code in hot statistics
Tests
- Unit test
> statistics: reformat code in hot statistics

- server/election/leadership.go
- server/tso/global_allocator.go
- server/tso/tso.go
Signed-off-by: JaySon-Huang <tshent@qq.com>
Fix several typos.
Fix several typos.
Tests
- No code
Code changes
- N/A
Side effects
- N/A
> *: Fix several typos

- server/tso/global_allocator.go
After refactoring `tso` pkg, the `leadership` won't have data race problems any more. So there's no need to use `atomic.Value`. Considering the readability, this pr changes it back to a normal struct field.
Remove the use of `atomic.Value` from Global TSO Allocator.
Tests
- Unit test
* Remove the use of `atomic.Value` from Global TSO Allocator.
> tso: remove the use of atomic.Value

- metrics/grafana/pd.json
add store pick
Tests
- Unit test
> metrics: add store pick in hot peer schedule direction metrics

- pkg/errs/errno.go
- server/cluster/coordinator.go
- server/server.go
fix #2823 
check ctx when loading schedule config
Tests
- Unit test
> fix ci failed in api package

- plugin/scheduler_example/evict_leader.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_leader.go
- server/schedulers/scatter_range.go
we should call `.Error` to convert `error` to `string`, otherwise we will get an empty result.
Tests
- Unit test
> fix empty http response in scheduler

- metrics/grafana/pd.json
- server/schedule/placement/config.go
- server/schedule/placement/config_test.go
- server/schedule/placement/rule_manager.go
Fix https://github.com/tikv/pd/issues/2862
- Before commit a patch, call `trim()`
- In `trim()` check if new item is the same with old
- add tests
Tests
- Unit test
Side effects
> placement: trim patch

- pkg/autoscaling/handler.go
- pkg/errs/errno.go
- pkg/etcdutil/etcdutil.go
- server/api/middleware.go
- server/cluster/cluster.go
- server/cluster/coordinator.go
- server/core/storage.go
- server/handler.go
- server/kv/etcd_kv.go
- server/schedule/plugin_interface.go
- server/schedule/scheduler.go
- server/server.go
To solve #2704
Tests
- Unit test
> *: refine error log in cluster pkg

- client/client.go
- tests/client/client_test.go
Support scatter client in client which is also an compatibility change. ref https://github.com/tikv/pd/pull/2849
Tests
- Unit test
Code changes
> client: support scatter group

- cmd/pd-server/main.go
- server/member/member.go
- server/region_syncer/client.go
- server/tso/allocator_manager.go
Related to #2704.
This PR fixes some logs which are not consistent by mistake.
Tests
- Unit test
> *: minor fix for log refinement

- conf/config.toml
- go.mod
- go.sum
- pkg/dashboard/adapter/config.go
- server/config/config.go
* dashboard: update to v2020.09.08.1
* dashboard: add `enable-experimental` config
Tests
- Unit test
Code changes
* dashboard: update to v2020.09.08.1
* dashboard: add `enable-experimental` config
> dashboard: update to v2020.09.08.1 and add enable-experimental config

- CONTRIBUTING.md
- docs/development-workflow.md
Add some guidelines about DCO and how to find a task.
Tests
- No code
> *: update contributing

- server/schedule/operator/builder.go
- server/schedule/operator/builder_test.go
- server/schedule/operator/create_operator.go
- server/schedule/operator_controller_test.go
- server/schedulers/grant_leader.go
- server/schedulers/hot_test.go
- server/schedulers/scheduler_test.go
* operator: refactor the builder to prepare to support the joint consensus
Tests
- Unit test
> operator: refactor the builder to prepare to support the joint consensus

- server/schedule/operator/builder.go
- server/schedule/operator/builder_test.go
- server/schedule/operator/create_operator.go
- server/schedule/operator/create_operator_test.go
- server/schedule/operator_controller_test.go
- server/schedulers/hot_test.go
- server/schedulers/scheduler_test.go
* operator: implement joint consensus builder
Tests
- Unit test
> operator: implement joint consensus builder

- pkg/typeutil/convension.go
- server/schedule/operator/builder.go
- server/schedule/operator/builder_test.go
- server/schedule/operator/create_operator.go
In this PR, address comments to the previous PR #2938  #2944 
* unite `hasAbilityLeader` and `allowLeader`
* use `allowDemote + useJointConsensus` instead of `useJointConsensus`
* consider `promote learner + demote voter` as a step, and add test for it
* rename `Empty` to `IsEmpty`
* rename `b2i` to `BoolToInt`
* unite `newBuilderWithBasicCheck` and `NewBuilder`
Tests
- Unit test
> operator: optimize builder code for the previous PRs

- server/schedule/operator/builder.go
- server/schedule/operator/builder_test.go
* schedule: unify the naming style of builder
> schedule: unify the naming style of builder

- server/api/router.go
schedulerConfigHandler use path from other pkg rather than a string directly, this PR will unify.
Tests
- Unit test
> misc: unify route path

- server/core/region.go
- server/core/region_tree.go
we usually check nil when we directly use `leader[storeID]` , but we did not in some function.
I think we should add it to avoid forgetting it although they are used in test now.
Tests
- Unit test
> add nil check in GetLeader and GetFollower

- server/api/router.go
- server/api/scheduler.go
api: fix miss err in `redirectSchedulerDelete` 
Tests
- Unit test
-  fix miss err in `redirectSchedulerDelete`
> api: fix miss err in `redirectSchedulerDelete` 

- server/cluster/coordinator.go
metrics: fix error hot statistic metrics
Tests
- Unit test
- fix error hot statistic metrics
> metrics: fix error hot statistic metrics

- server/tso/global_allocator.go
- server/tso/local_allocator.go
- server/tso/tso.go
Part of #2984 and #2759. Prepare for the next step of implementing the global TSO generation algorithm.
Extract a public method for the normal (or old) way of TSO generation. 
Tests
- Unit test
> tso: add basic TSO generation logic for the local allocator

- .travis.yml
No need coverage for release branches.
Tests
- No code
> ci: remove coverage

- go.mod
- go.sum
* dashboard: update to v2020.09.21.1
Tests
- Unit test
* dashboard: update to v2020.09.21.1
> dashboard: update to v2020.09.21.1

- server/schedule/operator/operator.go
- server/schedule/operator_controller.go
- server/schedulers/balance_leader.go
- server/schedulers/balance_region.go
- server/schedulers/balance_test.go
- server/schedulers/utils.go
When we check the log about create and finish operator, we don't know info about it. Especially, leader score and region score.
Tests
- Unit test
- add additional info for operator
> operator: add additional info for operator

- pkg/autoscaling/calculation.go
- pkg/autoscaling/calculation_test.go
- tests/autoscaling/autoscaling_test.go
This label is previously added by operator and we can add it in PD now.
This PR adds `hotRegion` label for auto scaling stores.
Tests
- Unit test
> autoscaling: add hotRegion label for auto scaling stores

- server/election/leadership.go
> leadership: fix typo

- client/client.go
- client/metrics.go
Signed-off-by: jyz0309 <45495947@qq.com>
In PR #2890 that cherry-pick PR #2830 to `release-4.0`, in order to unify the naming style, we changed the function name from `GetMemberInfo ` to `GetAllMembers`. This PR is to cherry-pick this part to the `master`.
> client: rename GetMemberInfo to GetAllMembers

- tools/pd-tso-bench/README.md
- tools/pd-tso-bench/main.go
Resolve #3024.
* Add more statistics info for the benchmark.
* Support more flags to customize the benchmark settings.
Tests
> tools: enhance the pd-tso-bench

- server/api/region.go
- server/api/router.go
- server/handler.go
- tests/pdctl/region/region_test.go
- tools/pd-ctl/pdctl/command/region_command.go
Support check learner-peer API.
This PR also refactor the tests of region in pd-ctl.
Tests
- Unit test
> api: add check learner-peer API

- server/api/region.go
- server/handler.go
Use a flag to reduce some unnecessary functions.
Just as the above says.
Tests
- Unit test
> api: reduce duplicated functions

- server/api/region.go
- server/api/region_test.go
- server/api/router.go
- server/api/util.go
- server/handler.go
ref https://github.com/tikv/pd/issues/2965 
Add a http api for scattering regions
Tests
- Unit test
> api: Add scatter regions http api

- server/tso/allocator_manager.go
- server/tso/global_allocator.go
> tso: fix some bad smelling in allocator

- tools/pd-simulator/main.go
- tools/pd-simulator/simulator/config.go
close #3101 
- Use meta parsed from `simConfig.toml` to adjust config in pd server which is created by simulator.
Tests
Code changes
- Use meta parsed from toml to adjust simulator config.
- Fix bug of simulator config.
> Simulator: fix simulator config is not read correctly from file

- server/config/config.go
fix bad spelling.
fix the bad spelling.
> config: fix bad spelling

- tools/pd-simulator/simulator/cases/import_data.go
Signed-off-by: ZenoTan <zenotan1998@gmail.com>
In bench bot, if simulator runs indefinitely, it will block other bench. So it is necessary to guarantee simulator case will stop.
In import-data case, after import, we wait for another period for it to stop. After that, we force it.
Tests
- Manual test
> simulator: Force stop condition for pd bench

- pkg/autoscaling/prometheus.go
- pkg/btree/btree_test.go
- pkg/encryption/master_key_test.go
- pkg/errs/errno.go
- pkg/logutil/log.go
- pkg/testutil/testutil.go
- server/api/rule_test.go
- server/config/config.go
- server/core/region.go
- server/grpc_service.go
- server/schedule/operator/status.go
- server/util.go
- tests/pdbackup/backup_test.go
- tests/pdctl/config/config_test.go
- tests/server/cluster/cluster_test.go
- tools/pd-backup/pdbackup/backup.go
- tools/pd-heartbeat-bench/main.go
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
remove redundant parentheses
remove redundant parentheses
Tests
- No code
Code changes
None
Side effects
None
None
> *: clean up code

- tools/pd-tso-bench/README.md
- tools/pd-tso-bench/main.go
Support to request the Local TSO from a specific DC.
* Fix a typo.
* Add a new flag to specify the `dc-location` for `GetLocalTSO`.
Tests
> tools: support to request the Local TSO from a specific DC

- go.mod
- go.sum
Try to resolve #3159. Related PR: pingcap/log#12.
Use the concurrently safe log to prevent the data race.
Tests
- Unit test
> log: use the concurrently safe log to prevent the data race

- client/client.go
```
goroutine 270 [chan send, 2175 minutes]:
github.com/tikv/pd/client.(*client).tsLoop(0xc00070ede0)
/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20200921100508-9ee41c4144f3/client/client.go:263 +0xda7
created by github.com/tikv/pd/client.NewClientWithContext
/home/jenkins/agent/workspace/tidb_v4.0.7/go/pkg/mod/github.com/tikv/pd@v1.1.0-beta.0.20200921100508-9ee41c4144f3/client/client.go:178 +0x351
```
When the client timeout, the context will be canceled. And then `checkStreamTimeout` will return. But if at the same time the stream return with non-nil value. The `createdCh` will block.
This PR fixes this problem by not allowing the checkStreamTimeout to return in advance.
Tests
- Unit test
- Fix the block channel introduced by checkStreamTimeout
> client: fix the block channel introduced by checkStreamTimeout

- pkg/movingaverage/avg_over_time.go
- pkg/movingaverage/avg_over_time_test.go
- pkg/movingaverage/median_filter.go
- pkg/movingaverage/median_filter_test.go
- pkg/movingaverage/moving_average.go
- pkg/movingaverage/time_median.go
- server/cluster/cluster_stat.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
- server/statistics/region.go
- server/statistics/store.go
move `moving average` to new pkg, only move without modify.
The first step of #3180
Tests
- Unit test
> move `moving average` to new pkg

- client/client.go
A bug found from pingcap/tidb#20980. There is a certain chance that when a TSO request is received, the corresponding DC's `tsDeadline` is not ready.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/61998/pipeline/49/
Manually check the `tsDeadline` when it's not ready.
Tests
- Unit test
> client: fix the nil interface conversion bug

- client/client.go
- server/election/leadership.go
- server/schedule/operator_controller.go
- server/schedulers/hot_region.go
- server/server.go
- server/tso/global_allocator.go
The canceled operator will be added two times on the counter.
This PR fixes this problem and fixes several log format problems.
Tests
- Unit test
> misc: fix metrics and several log format problem

- server/schedule/filter/filters.go
Close #3195.
This PR fixes the filter source/target metrics.
Tests
- Manual test
> metrics: fix the filter metrics

- client/client.go
Close #3207.
Tests
- Mannual test
> client: fix the bug that may cause the tso process to freeze

- go.mod
- go.sum
Update TiDB Dashboard 
Update the TiDB Dashboard vendor to v2020.10.21.1
Tests
- dashboard: update to v2020.11.26.1
> Update TiDB Dashboard to v2020.11.26.1

- server/schedulers/utils.go
- server/statistics/hot_cache.go
- server/statistics/hot_peer.go
- server/statistics/hot_peer_cache.go
It's a part of #3201
Tests
- Unit test
> scheduler: add better hot region output for pd-ctl

- client/client.go
add detailed comment and revise cancel in `tsLoop`.
> client: add detailed comment  and revise cancel

- server/schedulers/hot_region.go
- server/schedulers/utils.go
tiny refactor, no logic changes.
Tests
- Unit test
> hot scheduler: move expect load out of storeLoad

- go.mod
- go.sum
As the title said.
This is for below issues:
* https://github.com/pingcap/sysutil/pull/24
* https://github.com/pingcap/sysutil/pull/25
* https://github.com/pingcap/sysutil/pull/22
Tests 
- No code
Side effects
- N/A
- N/A
> *: update go.mod for sysutil

- server/schedule/checker/merge_checker.go
- server/schedule/checker/merge_checker_test.go
Closes https://github.com/tikv/pd/issues/3229
This PR adds a check before doing the merge operation.
Tests
- Unit test
> checker: check the target region size before doing merge operation

- server/schedule/checker_controller.go
- server/schedulers/hot_region.go
scheduler: add comment for write leader in hot region scheduler
Tests
- Unit test
> scheduler: add comment for write leader in hot region scheduler

- server/encryptionkm/key_manager.go
- server/schedule/placement/rule_manager.go
To solve https://github.com/tikv/pd/issues/3279
Tests
- Unit test
> crt:Function literal can be simplified

- tools/pd-analysis/analysis/transfer_counter.go
- tools/pd-analysis/main.go
To solve #3281
Tests
- Unit test
> fix file permissions 

- pkg/encryption/kms.go
- plugin/scheduler_example/evict_leader.go
- server/core/region_test.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_leader.go
- server/schedulers/hot_test.go
Close #3275.
This PR combines several append into one
Tests
- Unit test
> *: reduce unnecessary append

- tools/pd-ctl/pdctl/command/scheduler.go
There is a typo in scheduler command.
This PR fixes it.
Tests
- No code
> tools: fix a typo in scheduler command

- server/grpc_service.go
Sometimes we wanna know why there is an error from region heartbeat metrics. But we don't know the exact reason for the region heartbeat error.
This PR distinguishes the error kind for the metrics of region heartbeat.
Tests
- Unit test
> metrics: improve the region heartbeat metrics

- server/cluster/coordinator_test.go
`TestStoreOverloaded` may fail in a slow environment.
Check elapsed time.
Tests
- Unit test
> cluster: fix TestStoreOverloaded

- server/schedule/placement/rule_list.go
Closes https://github.com/tikv/pd/issues/3265
Add an extra check for `getRulesForApplyRegion`.
Tests
- Manual test
> placement: fix panic when changing the default rule

- server/id/id.go
* `AllocatorImpl.Alloc` and `AllocatorImpl.Generate` may conflict when executed concurrently.
* id: lock the `Generate` function
Tests
> id: lock the Generate function

- go.mod
- go.sum
Update to TiDB Dashboard v2021.01.04.1 to fix the bug that Statement is not working in TiDB 5.0 branch.
Update to TiDB Dashboard v2021.01.04.1
Tests
- Unit test
> dashboard: Update to TiDB Dashboard v2021.01.04.1

- server/statistics/store_collection.go
There are some intermediate variables of v2 region score formula that are not exposed in grafana.
Add the missing metrics.
> statistics: add score formula v2 related metrics

- pkg/mock/mockid/mockid.go
- server/cluster/cluster.go
- server/id/id.go
- server/server.go
- tests/cluster.go
make code more readable.
Tests
- Unit test
> *: make the id allocator more readable 

- plugin/scheduler_example/evict_leader.go
- server/schedule/checker/merge_checker.go
- server/schedule/checker/replica_checker.go
- server/schedule/checker/rule_checker.go
- server/schedule/checker_controller.go
- server/schedulers/balance_leader.go
- server/schedulers/evict_leader.go
- server/schedulers/grant_leader.go
- server/schedulers/hot_region.go
- server/schedulers/label.go
- server/schedulers/random_merge.go
- server/schedulers/shuffle_hot_region.go
- server/schedulers/shuffle_leader.go
close https://github.com/tikv/pd/issues/3350
Add metrics to record operator creating failed due to limit configuration.
> scheduler: add operatorLimitCounter metrics for each scheduler

- metrics/grafana/pd.json
Many users(come from DBaaS、operator、tiup) monitor multiple TiDB clusters in one Grafana, this PR make Grafana dashboards support multiple clusters and not affect single cluster usage. Cluster variable is hidden by default.
- add a tidb_cluster label in all expr
- add cluster variable in Grafana templating
How it Works:
load it to your Grafana :))
Single Cluster:
No change
Multiple Cluster:
Construct a label that can uniquely identify the cluster. in tidb_operator, you can use {namespace}-{cluster_name} as your {tidb_cluster} variable.
add this configuration to your prometheus config
```
relabel_configs:
- source_labels:
- namespace
- name
separator: "-"
target_label: tidb_cluster
```
Tests
- No code
Code changes
- Has HTTP API interfaces change (Don't forget to …
> metrics: grafana dashboards support multiple cluster

- pkg/testutil/testutil.go
- server/tso/allocator_manager.go
- tests/client/client_test.go
- tests/cluster.go
- tests/server/tso/allocator_test.go
- tests/server/tso/global_tso_test.go
- tests/server/tso/local_tso_test.go
- tests/server/tso/manager_test.go
* Refine the allocator setup methods.
* Refine and speed up the tests.
Tests
- Unit test
> tso: refine the allocator setup method and tests

- server/region_syncer/client.go
- server/region_syncer/server.go
close https://github.com/tikv/pd/issues/3399
Tests
- Unit test
> syncer: fix region syncer data race

- Makefile
Signed-off-by: AnubhavUjjawal <anubhavujjawal@gmail.com>
Issue #2138 #2136 reference difficulties faced when our `docker build`
is broken. 
The commit attempts to mitigate the difficulties by adding a
sanity test in `make check` command. `make check` command is run in the
github workflow as well, so we would be able to locate any issues caused
due to a broken `docker build` quickly.
Tests
- Unit test
No release note
> build: add tests for building docker image

- conf/config.toml
- server/api/tso_test.go
- server/config/config.go
- server/grpc_service.go
- server/handler.go
- server/server.go
- server/tso/allocator_manager.go
- tests/client/client_test.go
- tests/cluster.go
- tests/server/member/member_test.go
- tests/server/tso/allocator_test.go
- tests/server/tso/global_tso_test.go
- tests/server/tso/local_tso_test.go
- tests/server/tso/manager_test.go
Close #3414.
* Introduce `Labels` configuration.
* Make TSO use labels to configure.
Tests
- Unit test
- pingcap/tidb#19212
- pingcap/tidb#22639
> config, tso: add labels configuration to update TSO configuration

- go.mod
- go.sum
- server/api/member.go
- server/api/member_test.go
- server/tso/allocator_manager.go
add dclocation in member response
ref https://github.com/pingcap/kvproto/pull/721
Tests
- Unit test
> api: add dclocation in member response

- go.mod
- go.sum
Signed-off-by: Max-Cheng <aaron9shire@gmail.com>
https://github.com/pingcap/tidb-dashboard/issues/812
What's Changed:`go.mod`
- PR to update `pingcap/sysutil`
Tests 
- Unit test
- Support display cpu-arch
> *:update github.com/pingcap/sysutil

- client/client.go
- pkg/errs/errno.go
- server/tso/global_allocator.go
- server/tso/local_allocator.go
- server/tso/tso.go
- tests/client/client_test.go
Revise the codes of TSO generation.
* Check leadership before generating TSO.
Tests
- Unit test
> tso: revise the TSO generation

- go.mod
- go.sum
issue: https://github.com/tikv/pd/issues/3438
This PR was  go.mod change
Tests
Unit test
No release-note
> fix sum check error

- metrics/grafana/pd.json
- server/metrics.go
the accuracy of the heartbeat histogram is not suitable.
Tests
> server/metrics: improve the accuracy of heartbeat histogram

- client/base_client.go
- client/client.go
- client/client_test.go
- tests/client/client_test.go
Due to `client.tsoDispatcher` is updated with the `baseClient.allocators`, sometimes they are not consistent because the updating is out of sync. This PR fixes this problem.
* Update `client.tsoDispatcher` more reasonably.
* Add GC for the unused TSO allocator and dispatcher.
* Add some logs.
Tests
- Unit test
> client: optimize the mechanism of creating TSO dispatcher

- server/api/router.go
Sometimes the trace may be important for debugging.
This PR adds more profile API.
Tests
- Unit test
> api: support more profile API

- server/tso/allocator_manager.go
Signed-off-by: Zheming Li <nkdudu@126.com>
cancel context when delete allocator manager to stop background loop.
Tests
- No code
Release note
> tso: cancel context when delete allocator manager
